### ISSUE TITLE
Key repeat not working

### ISSUE THREAD

**Issue by kyranjamie** [tekezo/Karabiner#157]
MacBook Pro running ML.
Tested on both laptop and external keyboard.

Since installing KR4MB holding down a key does not repeat the letter.  The key repeat settings have been left as default. 

Event viewer shows that repeat is working fine, but this isn't the case in any other application.

Known issue, bug or user error?

Edit: may well be ML issue, rather than KR4MB.

**Comment by iSynth** [comment]
Why it closed?
When I hold any letter key a letter char not repeat. Repeat work with any other keys but not with letters keys.

**Comment by tekezo** [comment]
See this article.
http://www.tekrevue.com/tip/how-to-disable-the-character-accent-menu-in-os-x-mountain-lion/

**Comment by iSynth** [comment]
Thanks for quick reply! Now it works!
