### ISSUE TITLE
Spanish "cedilla" key (ç and Ç chars)

### ISSUE THREAD

**Issue by joaquinmartinezgc** [tekezo/Karabiner#224]
Hi! first of all, thanks for this awesome code.

As you should know, most of coding languages are designed for US layout, so developer of other countries use to code slower due to ugly mappings. For example, backslash is alt+º, braces and brackets "{", "}", "[" ,"]" are alt+ "´", "ç" , "`" ,  and "+", and so on... 

Here is a full layout sample: http://km.support.apple.com/library/APPLE/APPLECARE_ALLGEOS/HT2841/Spanish%202.gif

In spanish (french and portuguese as well) layout there's a key known as Cedilla, his symbol is ç or Ç, ( /s/ sound) (more about this character here http://en.wikipedia.org/wiki/%C3%87) 

Most of spaniards doesn't use that key, because is mainly used in portuguese and catalonian. In my case, it is close to useless.

So it would be great to map it for a common command, for example ":" wich in spanish layout is shift+dot(.)

These are my suggestions:

ç => ":"
Ç (shift+ç) => backslash()

Thanks in advance.

**Comment by julianmojico** [comment]
For OSx latests versions (High Sierra, Mojave and Catalina), use latest Karabiner (different version and repo).

You will also get **Karabiner Event Viewer** In this installation.
You can use Karabiner Event Viewer to **debug special characters keycodes**, and it also allows you to **add new rules** to Karabiner mapping.

More info:
https://karabiner-elements.pqrs.org/docs/manual/operation/eventviewer/
