### ISSUE TITLE
Caps Lock to ctrl + esc timeout

### ISSUE THREAD

**Issue by jonmorehouse** [tekezo/Karabiner#226]
I'm using PcKeyboard hack to map my capslock key to key 80 (system preferences is mapped to no-action. With KeyRemap4MacBook I've selected the F19 to esc and ctrl.

The command works fine, but it seems that escape doesn't register fast enough. I often times hit escape and another key and it registers as a ctrl holding event. I've set the key overlaid modifier timeout to 150ms and delay until repeat to 100ms. I can't seem to reduce these timeouts any lower without completely losing functionality.

Has anyone else had this issue / found a solution?

**Comment by lencioni** [comment]
Thanks! I was having the same problem and I think this helped. For anyone following along looking for clear instructions, I believe these are the steps I took:

1. In Keyboard preferences pane under "Modifier Keys", set Caps Lock to "No Action".
2. In Seil, check "Change the caps lock key" and set the value to `80`.
3. In Karabiner, under "Misc" open private.xml
4. Paste the following into private.xml: https://github.com/tekezo/Files/blob/master/KeyRemap4MacBook/private.f19_escape_control_v2/private.xml
5. In Karabiner, under "Change Key" click "Reload XML".
6. Check "F19 to Escape and Control v2"

**Comment by lencioni** [comment]
Hmm, on further experimentation, this seems to have a different problem for me--it does not kick in the control key quickly enough. Is there perhaps a way to have the control/escape behavior be immediately responsive for this key?

**Comment by tekezo** [comment]
If you are using external keyboard, you should choose your keyboard at step 1.

**Comment by lencioni** [comment]
Thanks, that's a great point. But unfortunately it does not resolve my problem.

**Comment by tekezo** [comment]
Please confirm whether your caps lock key sends the f19 key event properly when you disable Karabiner setting.
If the f19 key is sent well, confirm "Key Repeat tab > Advanced Configurations > Key Overlaid Modifier > Initial Modifier Wait" in Karabiner Preferences. It should be 0.

**Comment by lencioni** [comment]
I have confirmed that caps lock sends f19 key event by using Karabiner's EventViewer. I have also confirmed that the initial modifier wait is set to 0. I tried playing around with some of the other values in the key repeat tab but wasn't able to make it work. Let me know if you have anything more to try!

**Comment by tekezo** [comment]
The control key event is not sent even in EventViewer?
I guess you are releasing the caps lock key before you release other keys.

(Read the setting description.)
https://github.com/tekezo/Files/blob/master/KeyRemap4MacBook/private.f19_escape_control_v2/private.xml#L11-L14

If you don't want this behavior, remove this line.
https://github.com/tekezo/Files/blob/master/KeyRemap4MacBook/private.f19_escape_control_v2/private.xml#L25

**Comment by lencioni** [comment]
Thanks so much for your help so far. I think you might be right that I am performing the following motion:

1. Press caps lock
2. Press other key
3. Release caps lock
4. Release other key

However, if I remove that line, then it never seems to send escape even when I only hit caps lock. Is there a setting that I can use so the above motion sends Control and a press+release of caps lock sends Escape?

**Comment by tekezo** [comment]
`__KeyOverlaidModifier__` has timeout.
If you press and hold the caps lock key over timeout, the escape key event will not be sent.

Please restore the default values in Key Repeat tab and confirm the caps lock behavior.

**Comment by lencioni** [comment]
All of the values in the Key Repeat tab are at their defaults, but it still has the same behavior of only sending Control and never sending Escape with that line removed.

**Comment by tekezo** [comment]
If so, I guess this issue is your hardware issue.
Please confirm your raw device events by debug mode.
https://pqrs.org/osx/karabiner/document.html.en#debugmode

**Comment by lencioni** [comment]
I reverted back to the non-Seil configuration and ran the debug mode. Here's what I get with my external keyboard for a single caps lock press and release:

```
Aug 30 08:33:38 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80040001, key 0x003b, kbdType  40, repeat = 0
Aug 30 08:33:38 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00040001, key 0x003b, kbdType  40, repeat = 0
Aug 30 08:33:38 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x003b, kbdType  40, repeat = 0
Aug 30 08:33:38 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003b, kbdType  40, repeat = 0
Aug 30 08:33:38 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 10, flags 0x00000000, key 0x0035, kbdType  40, repeat = 0
Aug 30 08:33:38 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 11, flags 0x00000000, key 0x0035, kbdType  40, repeat = 0
```

And here's the same key on my laptop's internal keyboard:

```
Aug 30 08:35:58 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80040001, key 0x003b, kbdType  43, repeat = 0
Aug 30 08:35:58 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00040001, key 0x003b, kbdType  43, repeat = 0
Aug 30 08:35:58 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x003b, kbdType  43, repeat = 0
Aug 30 08:35:58 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003b, kbdType  43, repeat = 0
Aug 30 08:35:58 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 10, flags 0x00000000, key 0x0035, kbdType  43, repeat = 0
Aug 30 08:35:58 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 11, flags 0x00000000, key 0x0035, kbdType  43, repeat = 0
```

And with the Seil configuration, here's what I get for a single caps lock press on my external keyboard:

```
Aug 30 08:40:00 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80040001, key 0x003b, kbdType  40, repeat = 0
Aug 30 08:40:00 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00040001, key 0x003b, kbdType  40, repeat = 0
Aug 30 08:40:00 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x003b, kbdType  40, repeat = 0
Aug 30 08:40:00 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003b, kbdType  40, repeat = 0
```

and internal keyboard:

```
Aug 30 08:40:48 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80040001, key 0x003b, kbdType  43, repeat = 0
Aug 30 08:40:48 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00040001, key 0x003b, kbdType  43, repeat = 0
Aug 30 08:40:48 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x003b, kbdType  43, repeat = 0
Aug 30 08:40:48 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003b, kbdType  43, repeat = 0
```

**Comment by tekezo** [comment]
The first result are sending the escape key event as expected.
What's your Seil configuration?

**Comment by lencioni** [comment]
Ah, not sure why but my Seil configuration was a bit messed up. I changed it back to map caps lock to 80, and now this is what I get:

```
Aug 30 20:21:08 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 10, flags 0x80000000, key 0x0050, kbdType  40, repeat = 0
Aug 30 20:21:08 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00040001, key 0x003b, kbdType  40, repeat = 0
Aug 30 20:21:08 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 11, flags 0x80000000, key 0x0050, kbdType  40, repeat = 0
Aug 30 20:21:08 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003b, kbdType  40, repeat = 0
Aug 30 20:21:08 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 10, flags 0x00000000, key 0x0035, kbdType  40, repeat = 0
Aug 30 20:21:08 joe kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 11, flags 0x00000000, key 0x0035, kbdType  40, repeat = 0
```

And actually, things seem to be working better now. Thanks for your help with this. I'll post back if I come across any other problems.
