### ISSUE TITLE
Add the ability to set Timeout and Initial Modifier Wait per-binding

### ISSUE THREAD

**Issue by philc** [tekezo/Karabiner#229]
I use key overlaid modifiers with the shift keys (shift while held, and left/right parenthesis when used alone). I also use Enter as an overlaid modifier.

I have "Initial Modifier Wait" set to 0ms, so that I can chord these modifiers immediately when pressed.

However, now I'd like to use spacebar as a modifier (fn when held; space when pressed alone). The problem with spacebar is that you type it commonly with regular characters, and so it requires careful timing to be used as a modifier. I don't care about space bar repeating, and I'm willing to have to hold it for 500ms before it becomes activated as a modifier, so that it never activates as a modifier in the normal course of typing.

What I want is a Initial Modifier Wait of 500ms for my spacebar modifier binding, but an Initial Modifier Wait of 0ms for my Shift and Enter modifier bindings.

As far as I know I can't do this with the current Karabiner. It would be great if the Initial Modifier Wait setting could be overridden on a per-binding basis in private.xml.

Note that I've tried using this with the spacebar modifier and it's not as good as using Initial Modifier Wait.

```
  <elapsedtimesincelastpressed_greaterthan>
    Millisecond::RawValue::500
  </elapsedtimesincelastpressed_greaterthan>
```

**Comment by orand** [comment]
Even better, can you modify the  [TouchCursor XML](https://github.com/tekezo/Karabiner/blob/7338e2c6280f136b1b637b2426b07bb2a796064f/src/core/server/Resources/include/checkbox/touchcursor.xml) to include these changes?  Too often the TouchCursor setting triggers a binding when it shouldn't.  I would make the change, but it's not clear to me whether I should use `__BlockUntilKeyUp__`, `__HoldingKeyToKey__`, or `__KeyDownUpToKey__`.

**Comment by tekezo** [comment]
@orand
I've improved TouchCursor by using __BlockUntilKeyUp__ at the latest beta version (10.6.29).

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by orand** [comment]
Excellent! Thank you!

**Comment by lastobelus** [comment]
@philc I've had pretty good results eliminating the lag in touch typing but using space key as modifier by using the following:
```xml
      <block>
        <elapsedtimesincelastreleased_greaterthan>Millisecond::RawValue::60</elapsedtimesincelastreleased_greaterthan>
        <autogen>
              __HoldingKeyToKey__
              KeyCode::SPACE,

              @begin
              KeyCode::SPACE
              @end

              @begin
              KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_dvorak_homerow_mode
              @end

              ThresholdMillisecond::RawValue::25,
            </autogen>
          </block>
      <block>
```

I still occasionally notice the lag when space is the first character I'm typing in a burst of touch typing, but I can live with that. It also means I can use spacebar with auto repeat, as long as I've typed something else first, even another space.

You can tune the values to your typing speed and how fast you want to be able to trigger the overlay mode. It's a tradeoff -- the elapsed time eliminates the keyup lag for the range of times in your normal typing, which means you have to make a slight mental pause to go into overlay mode.

**Comment by lastobelus** [comment]
You can see my whole private.xml [here](lastobelus/karabiner-settings).

**Comment by djjcast** [comment]
@lastobelus Here's another alternative similar to yours:
* No stuttering during normal typing.
* 'Initial Modifier Wait' set to 0 works as expected and without any issues.
* Space repeats on hold after 'Delay Until Repeat' milliseconds.
```xml
<?xml version="1.0"?>
<root>
  <modifierdef>SPACEFN</modifierdef>

  <item>
    <name>SpaceFN layout</name>
    <appendix>Space+hjkl to Left/Down/Up/Right</appendix>
    <identifier>private.spacefn</identifier>

    <block>
      <elapsedtimesincelastpressed_lessthan>Millisecond::RawValue::201</elapsedtimesincelastpressed_lessthan>
      <autogen>
        __KeyToKey__
        KeyCode::SPACE,
        KeyCode::SPACE
      </autogen>
    </block>
    <block>
      <elapsedtimesincelastpressed_greaterthan>Millisecond::RawValue::200</elapsedtimesincelastpressed_greaterthan>
      <autogen>
        __KeyOverlaidModifierWithRepeat__
        KeyCode::SPACE,
        KeyCode::VK_MODIFIER_SPACEFN, ModifierFlag::SPACEFN,
        KeyCode::SPACE
      </autogen>
    </block>

    <autogen>
      __KeyToKey__
      KeyCode::H, ModifierFlag::SPACEFN,
      KeyCode::CURSOR_LEFT
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::J, ModifierFlag::SPACEFN,
      KeyCode::CURSOR_DOWN
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::K, ModifierFlag::SPACEFN,
      KeyCode::CURSOR_UP
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::L, ModifierFlag::SPACEFN,
      KeyCode::CURSOR_RIGHT
    </autogen>
  </item>
</root>
