### ISSUE TITLE
Latest version causes crashes in LibreOffice

### ISSUE THREAD

**Issue by jinnko** [tekezo/Karabiner#243]
Since upgrading to Karabiner from KeyRemap4Macbook LibreOffice has been consistently crashing.  Have tried both the stable and latest of LibreOffice, while using the latest Karabiner 10.0.5 release.  After removing Karabiner LibreOffice no longer crashes, therefore I submit the bug report here.

The only key I have mapped with Karabiner is § becomes forward delete.

The crash report can be seen at http://pastebin.com/s8v1s872.

**Comment by Nashatyrev** [comment]
Hi, 
I'm now working on this problem from the JDK side.
Noticed that in the dump supplied there are no java references. So possibly the problem might be on any side: the similar bugs in both JDK and LibreOffice, the Karabiner bug or the Apple bug. 
Regards,
Anton.

**Comment by tekezo** [comment]
Thanks!

There are crash logs which contain jvm:
https://groups.google.com/forum/#!msg/osx-karabiner/Ma0Bt2I2D-k/WiajWwueUQkJ
https://youtrack.jetbrains.com/issue/IDEA-127574
https://code.google.com/p/android/issues/detail?id=73736

I hope these help you.

**Comment by Nashatyrev** [comment]
Thanks for response.
It turned out that the JDK definitely has a problem and need to be fixed. Thus the LibreOffice likely has its own bug.
