### ISSUE TITLE
Vim Bindings for Normal Mode Doesn't Recognize Dvorak Layout

### ISSUE THREAD

**Issue by elderling** [tekezo/Karabiner#254]
Ubiquitous Vim Key Bindings for Normal Mode don't map properly when Dvorak layout is used. The key bindings always correspond to QWERTY layout. I first tried with the OS Dvorak layout. When that didn't work i switched to OS keyboard setting to U.S. (QWERTY) layout and enabled "Use Dvorak Keyboard Layout (QWERTY to Dvorak)" in Karabiner. In either case, normal Dvorak text entry works as expected but the The Vim Key Bindings still map to QWERTY layout in Normal Mode. 
The only other remapping I have enabled is "Change Fn Key"->"Fn+letter to Control+letter Fn+Escape..."
OS X Version 10.9.4

**Comment by harob** [comment]
I also have this same issue; I would love to use ubiquitous-vim with dvorak. Do you happen to know of any existing vim key binding config for dvorak? Or a good way to get started on setting on up?

Thanks!
