### ISSUE TITLE
Remapping Control_L + Left mouse button?

### ISSUE THREAD

**Issue by Dygerati** [tekezo/Karabiner#262]
I'm trying to remap ctrl+left mouse to ctrl+left command for multiclick in Sublime Text. 

  ```
<item>
    <name>Multiclick for Sublime</name>
    <appendix>Change Mouse Left + Control to Mouse Left + Command</appendix>
    <identifier>private.multiclick_sublime</identifier>
    <only>SUBLIME</only>
    <autogen>__KeyToKey__ 
    	PointingButton::LEFT, VK_CONTROL,
    	PointingButton::LEFT, VK_COMMAND
    </autogen>
  </item>
```

Parses, but doesn't seem to do much. Any thoughts?

**Comment by ajeba99** [comment]
Yep, that worked and it works because Windows (inside VMWare Fusion) handles it CTRL Clicking just fine; barring you have your CTRL and ALT set up properly.  Thanks Tekezo.
