### ISSUE TITLE
Switching to Chinese input via 'vkchangeinptusourcedef' occasionally requires reselection of text field

### ISSUE THREAD

**Issue by simichaels** [tekezo/Karabiner#279]
I've recently set up bindings so that I can use shortcuts to switch between U.S. Extended and Simplified/Traditional Chinese inputs. Occasionally, if I use this to switch from U.S. Extended to Chinese (I can see that this switch actually happens because the input icon in the statusbar changes) and begin typing, the character selection window never appears and it seems as if I'm just typing with U.S. Extended. If I deselect the text field in which my cursor is, then reselect it, the input works as it should. Switching input sources via Mac's default hotkeys doesn't seem to cause this problem, and when it does occur via Karabiner, it seems to do so only some of the time; I can't determine much of a pattern. It seems as if it's more likely to happen on the first time I switch from U.S. Extended to Chinese input after selecting a text field, but even then it works sometimes.

The relevant section of my private.xml is below:

     <vkchangeinptusourcedef>
        <name>KeyCode::VK_CHANGE_INPUTSOURCE_CHINESE_TRADITIONAL</name>
        <inputsourceid_equal>com.apple.keylayout.TCIM.Pinyin</inputsourceid_equal>
    </vkchangeinptusourcedef>
    <vkchangeinptusourcedef>
        <name>KeyCode::VK_CHANGE_INPUTSOURCE_CHINESE_SIMPLIFIED</name>
        <inputsourceid_equal>com.apple.keylayout.SCIM.ITABC</inputsourceid_equal>
    </vkchangeinptusourcedef>
    <vkchangeinputsourcedef>
        <name>KeyCode::VK_CHANGE_INPUTSOURCE_US_EXTENDED</name>
        <inputsourceid_equal>com.apple.keylayout.USExtended</inputsourceid_equal>
    </vkchangeinputsourcedef>

    <item>
        <name>US + Chinese input shortcuts</name>
        <appendix>Hyper + comma = Traditional</appendix>
        <appendix>Hyper + period = Simplified</appendix>
        <appendix>Hyper + slash = US Extended</appendix>
        <identifier>private.us_chinese_input</identifier>
        <autogen>__KeyToKey__ KeyCode::COMMA, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L, KeyCode::VK_CHANGE_INPUTSOURCE_CHINESE_TRADITIONAL</autogen>
        <autogen>__KeyToKey__ KeyCode::DOT, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L, KeyCode::VK_CHANGE_INPUTSOURCE_CHINESE_SIMPLIFIED</autogen>
        <autogen>__KeyToKey__ KeyCode::SLASH, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L, KeyCode::VK_CHANGE_INPUTSOURCE_US_EXTENDED</autogen>
    </item>

**Comment by ylorn** [comment]
@tekezo I was wondering if there is a **KeyCode**, something like `VK_CHANGE_INPUTSOURCE_NEXT` or `VK_CHANGE_INPUTSOURCE_PREVIOUS`, which can directly change the current input source to the **next** one or the **previous** one? Or the simulation of **⌘ + Space** and **⌘ + ⌥ + Space** is the only workaround?

**Comment by tekezo** [comment]
@ylorn 
> Or the simulation of ⌘ + Space and ⌘ + ⌥ + Space is the only workaround?

Yes. It's the only reliable way.
If you want to assign command-option-space to other function, please change the shortcut to other key such as f19.
![150201-0001](https://cloud.githubusercontent.com/assets/659178/5992097/3cb4c634-aa5b-11e4-90e9-1d2e1317520b.png)
