### ISSUE TITLE
CapsLock remap works only for internal keyboard

### ISSUE THREAD

**Issue by khinsen** [tekezo/Karabiner#289]
I use Karabiner on my MacBook Retina (OSX 10.9) for various remappings, among which CapsLock to Control (via Seil). With the internal keyboard, everything works fine.

When I use an external USB keyboard (standard Apple model), CapsLock has no function at all, neither its original function nor the remapped Control function. All other remappings work fine.

**Comment by sypl** [comment]
For me, this doesn't work on an IBM Model M. I have tried all combinations, but assigning a modifier to the caps lock (in my case command), whilst it does fires off cmd + key, thereafter it immediately fires off a FlagsChanged event, even if I'm still holding down caps. So if I'm cmd-tabbing, it will fire off once to move to the next tab, then act as if I've release cmd. Is it just that the driver in the keyboard does't support this type of reassignment?

**Comment by tekezo** [comment]
Did you do "No Action" configuration for external keyboard?
You should choose IBM Model M at "No Action" configuration.
https://pqrs.org/osx/karabiner/seil.html.en#noaction

**Comment by sypl** [comment]
I currently: 
* In OSX keyboard settings:
  * set 'No action' for the Model M caps lock
* In Seil
  * enable 'Change the caps lock key' flag and set it to 55

In event viewer it will release the cmd (caps lock key) once I have keyed cmd+anykey. If I hold down or spam anykey it will not release, but as soon as I stop it will release the cmd again. Appears to be something to do with a key timeout. I had some some timing parameters, but I reset those, to no effect.

My guess is it's just the keyboard. If I use it on OSX with the caps set to cmd via keyboard settings and turn off seil and karabiner I still get the same effect.

**Comment by sypl** [comment]
Or it may be the adapter I'm using. The Model M is PS2 so I have to attach the PS2-USB adapter to use it.

**Comment by tekezo** [comment]
@sypl
Thank you for reply.

> My guess is it's just the keyboard. If I use it on OSX with the caps set to cmd via keyboard settings and turn off seil and karabiner I still get the same effect.

I also think your guess is right.
It's known that some PS2-USB adapter causes problem such as dropping some keys.

**Comment by sypl** [comment]
It was the adapter. Got a new one and it works perfectly now. False alarm, sorry.
