### ISSUE TITLE
Stuck key when using external keyboard

### ISSUE THREAD

**Issue by ernestorocha** [tekezo/Karabiner#303]
First of all, thanks a lot for this app! It's amazing!

I know I'm asking too much, but I'd like your help to find this problem:

Since most of the time I'm in "clamshell mode", I'm using an external keyboard (Microsoft Arc) and sometimes the shift key gets "stuck", once happened to command a long time ago. The only way to fix it is restarting Karabiner. Never happened using the built-in keyboard as far as I remember.

Do you have any idea what can be ? Sometimes It happens like 3 times in 10 minutes and sometimes it takes hours or days. How can I track down the cause of the error ?

EDIT:

Forgot to mention, I'm on latest karabiner beta and latest Yosemite, but this bug first appearance was months ago.

**Comment by fidele007** [comment]
Hi, can I know how the workaround was done? I have the same problem where remapping anything to another key with a command modifier gets the command key stuck until I press it again, and this is on my laptop keyboard and not an external one.
