### ISSUE TITLE
Multimedia Home does not register

### ISSUE THREAD

**Issue by redolent** [tekezo/Karabiner#307]
VK_BROWSER_HOME may not be supported. I tried to map the key on an external keyboard.
http://www.kbdedit.com/manual/low_level_vk_list.html

As another developer, how can I help?

**Comment by auralarch** [comment]
I have this great little [multimedia PC keyboard] (http://www.v7-world.com/v7_us/products/connect/keyboard-mice/keyboard/slim-multimedia-keyboard-491410.html) which I love- after physically rearranging a number of the keys & using ControllerMate to functionally manifest those changes (as well as add many other customizations & functions).  But there are a number things which I am simply unable to do with ControllerMate...

My **goal** is to **repurpose** some of the **multimedia keys** designed to perform functions or launch apps in the Windows environment **as new custom modifier keys** in OS X.  However, I've encountered some obstacles. Creating new modifier keys is not possible with ControllerMate unfortunately.  And apparently (as you state above) Karabiner does support some/many/all (?) of the multimedia keys on PC keyboards.

First, is there a list of which keys (and/or keyboards) which are supported by Karabiner, or is there any way for me to determine if any (and which) multimedia keys on my keyboard are supported by Karabiner?  And if not, do you have any immediate ideas on how I might use ControllerMate to send some signal (key code, Applescript, anything) to Karabiner that I could then use to trigger my custom modifers?  There must be a way to do this somehow.  Any thoughts, comments, ideas or pointers will be greatly appreciated!

*This is __brilliant__ BTW!  I just adore this software...  I only just discovered it this afternoon and I've been mesmerized, amazed & delighted by its scope, power & flexibility/extensibility!!!  I had all but given up on my dreams of having additional modifier keys (which I think should be part of every keyboard already anyway!).*
*I apologize if I should've created a new issue- I often see folks being scolded for starting new threads or creating new issues when something similar (or the same) already existed, conversely I see people being chastised for supposedly hijacking threads when their issue seems to legitimately fit there...*

Thank you **SO** much for you time & consideration!

**Comment by charles-esterbrook** [comment]
I'm no Karabiner expert, but I'd like to point out that when you launch Karabiner and click the "Misc & Uninstall" tab, there is a "Launch EventViewer" button which you can use to see what happens when you press various keys. I've used it before and found it quite useful.

And let me say that I love Karabiner too and really appreciate it. I use it to make my Caps Lock a "Hyper" modifier key, giving me access to touch typing cursor movement and other functions that work across all apps.

Btw there is a donation page here:
https://pqrs.org/osx/karabiner/donation.html.en

**Comment by auralarch** [comment]
Ah- thank you sir for your informative response!  Excellent- very helpful!  I had not yet even installed Karabiner when I posed my query.
