### ISSUE TITLE
Is it possible to change the input source automatically by application?

### ISSUE THREAD

**Issue by nanernunes** [tekezo/Karabiner#308]

**Comment by puttin** [comment]
here is a script to change input source:
```
#!/usr/bin/env xcrun --sdk macosx swift

import Carbon

// print(Process.arguments)
precondition(Process.arguments.count == 2)

let inputSourceID = Process.arguments[1]
// print(inputSourceID)

let inputSourceIDKey = kTISPropertyInputSourceID
let inputSourcePropertiesDict = [inputSourceIDKey as String: inputSourceID]

// print("all inputMode:",  TISCreateInputSourceList(nil, false).takeUnretainedValue())

// weird system bug? https://github.com/noraesae/kawa/issues/3
let inputSourceList_nsarray = TISCreateInputSourceList(inputSourcePropertiesDict as CFDictionary, false).takeRetainedValue() as NSArray
let inputSourceList = inputSourceList_nsarray as! [TISInputSource]
// print(inputSourceList)
precondition(inputSourceList.count != 0)
let inputSource = inputSourceList[0]

TISSelectInputSource(inputSource)

```

maybe hammerspoon will help?

**Comment by tekezo** [comment]
@puttin Please use hammerspoon to fire the script.

Recommendation:
OS X has a bug that TISSelectInputSource will fail to switch CJKV input sources.
You should select the previous input source and send "Select next source in Input menu" shortcut (control-option-space or command-option-space)
https://github.com/tekezo/Karabiner/blob/version_10.15.0/src/core/server/Resources/vkchangeinputsourcedef.xml#L210-L236

**Comment by puttin** [comment]
@tekezo good to know the bug

here is the final working script gist:
https://gist.github.com/puttin/89bef9ec55646c470a83
