### ISSUE TITLE
please actually save settings in private.xml

### ISSUE THREAD

**Issue by kakulukia** [tekezo/Karabiner#314]
.. so that they can be easily transferred to other macs or even saved in a dotfiles repo 

Karabiner already has a private.xml, but the settings are not mirrored in there. :/
Making that private.xml available under ~/.karabiner/private.xml instead of the current directory would make distribution easier ..

**Comment by bammoo** [comment]
So, it's just a checkbox list, not the status of on or off. That seems not convenient for users.

**Comment by CestDiego** [comment]
I would like to suggest this is reopened, Why not sync the settings in the private.xml? I want to use `<deviceonly>` to have some modifications to only be on my external keyboard and not on the internal (like remapping the ESC key to some other character in my external keyboard) It's the same problem as this person has : https://groups.google.com/forum/#!msg/osx-karabiner/GTIjVp5jpLY/4citUnCwqRgJ

It would be of great help to know where is all this information stored.

**Comment by tekezo** [comment]
@CestDiego You should sync private.xml together.
The `<include>` tag is useful for syncing private.xml:
https://pqrs.org/osx/karabiner/xml.html.en#dropbox

**Comment by CestDiego** [comment]
@tekezo I didn't mean to sync it between computers, but to sync the changes made with the private.xml

**Comment by tekezo** [comment]
@CestDiego  The `export` command result includes the private.xml settings.
What's mean of your `sync`?
You meant "why is the setting in private.xml not enabled automatically"?

**Comment by CestDiego** [comment]
@tekezo I meant the changes made in the karabiner app, why arent they reflected in the private.xml file, or in case the private.xml is only for custom things, why aren't the settings set with the app in a normal xml file instead of a plist?

**Comment by tekezo** [comment]
I understood your intention.

The plist is the most easiest way to save configuration in OS X.
(We can use the rubust save/load methods with plist, and it's also integrated with Cocoa Key-Value Coding.)

That's why we use plist to save the configuration.
Of course, we can implement self data store. But there is not enough merit.
