### ISSUE TITLE
How to lock screen?

### ISSUE THREAD

**Issue by yisibl** [tekezo/Karabiner#323]
In MacBook Air used: 

```
Cmd + Option + Power
```

I want  mapping to `Ctrl + L`

**Comment by tekezo** [comment]
How about this private.xml?
https://github.com/tekezo/Files/blob/master/Karabiner/private.control_l_to_lock_screen/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by DXist** [comment]
I modified this snippet to lock laptop screen on `Ctrl+Cmd+L`:
```xml
?xml version="1.0"?>
<root>
	<item>
		<name>Lock screen by control-command-L</name>
		<identifier>private.control_command_l_to_lock_screen</identifier>

		<autogen>
			__KeyToKey__
			KeyCode::L, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL | ModifierFlag::COMMAND_L,
			ConsumerKeyCode::POWER, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L,
		</autogen>
	</item>
</root>
```
But locking works unstable. Sometimes it is required to press `Ctrl+Cmd+L` two or three times to lock the screen. It could be related to sleep mode - today I wasn't able to lock the screen from the first press after the laptop had been woken up. After that locking works like a charm.

**Comment by tekezo** [comment]
@DXist 
I cannot reproduce your issue.
I doubt that you pressed another key after you press ctrl+cmd+L.
The sleep will be canceled if another key is pressed immediately after you press ctrl+cmd+L.

**Comment by DXist** [comment]
I press ctrl+cmd, and then L. Can it be contact bounce? Physical or on scan code level?

**Comment by tekezo** [comment]
Your operation is correct.

Usually, the key bouncing is not matter for screen lock.
(Another input events are required to cancel sleep.
For example, you press `k` key together or mouse click.)

Another cause might be, sleep is prevented by other apps.
If you can reproduce this issue easily, please confirm this issue in a clear environment such as Guest User.

**Comment by DXist** [comment]
I hadn't been able to reproduce the issue under Guest user session yet. I reproduced it under my main user on home machine. I use Skype and Spectacle on daily basis.

**Comment by tekezo** [comment]
Thank you for confirmation.
It's very likely that some apps prevent sleep.

I believe Skype is not cause.
I don't use Spectacle, so I don't know well about it.

Some apps which do some heavy task (eg. media encoding) might prevent sleep to continue their task.
Are you using such apps?

**Comment by DXist** [comment]
No, I don't use such apps. I will inform you if I find something.

**Comment by gstn-caruso** [comment]
Does anyone know how to do this with the new syntax?
