### ISSUE TITLE
Brightness Up + Down Don't work In Yosemite

### ISSUE THREAD

**Issue by RichardD012** [tekezo/Karabiner#324]
Currently using a Das Keyboard 4 in Yosemite with Karabiner 10.5.0.  I can't seem to get the F1 & F2 (or any key for that matter) to map to Brightness Up and Down. 

What's interesting is, out of the box, Scroll Lock and Pause/Break map to Brightness Up/Down respectively.  When using the EventViewer, these keypresses don't show any events out of the box.  

However, if I map Pause/Break to eject or power, the mapping seems to be correct.  They still don't show in the Event Viewer though.

**Comment by RichardD012** [comment]
After finding your debug documentation I realized why the brightness up/down didn't show up in the EventViewer.  Debugging I found that the hex codes were 0x006b and 0x0071.  A simple mapping in private.xml worked.

For anyone who may have this exact issue, here's the following.

```
<?xml version="1.0"?>
<root>
  <list>

    <item>
      <name>Remap Brightness Keys</name>
      <appendix>Darker, Brighter</appendix>
      <identifier>remap.brightnesskeys</identifier>
      <autogen>--KeyToKey-- KeyCode::F1, KeyCode::RawValue::0x006b</autogen>
      <autogen>--KeyToKey-- KeyCode::F2, KeyCode::RawValue::0x0071</autogen>
    </item>

  </list>
</root>
```

**Comment by FrankWu100** [comment]
@RichardD012 thx!! it's work for me!!

**Comment by ralfonso** [comment]
Just a followup, this XML (with the ```ModifierFlag```) works better for me since it allows me to use my remapped ```Fn``` key to get actual F1 and F2 events. Thanks for the original XML!

```
<?xml version="1.0"?>
<root>
  <list>
    <item>
      <name>Remap Brightness Keys</name>
      <appendix>Darker, Brighter</appendix>
      <identifier>remap.brightnesskeys</identifier>
      <autogen>--KeyToKey-- KeyCode::F1, ModifierFlag::NONE, KeyCode::RawValue::0x006b</autogen>
      <autogen>--KeyToKey-- KeyCode::F2, ModifierFlag::NONE, KeyCode::RawValue::0x0071</autogen>
    </item>
  </list>
</root>
```
