### ISSUE TITLE
⌘T no longer mapped to "Add to Sidebar"

### ISSUE THREAD

**Issue by rhpt** [tekezo/Karabiner#325]
In Yosemite (not sure about Mavericks), Command+T is mapped to "New Tab". Karabiner has it as "Add to Sidebar".

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at v10.5.8.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

Diff:
https://github.com/tekezo/Karabiner/commit/fb7e2f65c8e2480f2107437036c18821319a9ce4
