### ISSUE TITLE
I can not remap the right fn to option key (alt)

### ISSUE THREAD

**Issue by poc7667** [tekezo/Karabiner#326]
I can not remap the right fn to option key (alt)

I tried to use `private.xml` to remap the keyboard 
But it didn't work for me

![](https://i.imgur.com/vbJoTMP.png)

![](https://i.imgur.com/nYw8re4.png)

	  <devicevendordef>
	    <vendorname>FILCO_Keyboard_VendorID</vendorname>
	    <vendorid>0x04d9</vendorid>
	  </devicevendordef>
	  <deviceproductdef>
	    <productname>FILCO_Keyboard_ProductID</productname>
	    <productid>0x1818</productid>
	  </deviceproductdef>
	 
	  <item>
	    <name>FILCO</name>
	    <appendix>Swap RIGHT FN to OPTION </appendix>
	    <identifier>private.for_FILCO_Keyboard</identifier>
	    <block>
	      <device_only>
	        DeviceVendor::FILCO_Keyboard_VendorID,
	        DeviceProduct::FILCO_Keyboard_ProductID
	      </device_only>
	      
	      <autogen>__KeyToKey__ KeyCode::CONTROL_L, KeyCode::OPTION_R</autogen>
	      <autogen>__KeyToKey__ KeyCode::OPTION_R, KeyCode::CONTROL_L</autogen>
	      
	      
	      
	      
	    </block>
	  </item>

**Comment by tekezo** [comment]
Unfortunately, you have to modify hardware in order to change filco's fn key behavior by software.
#320 might help you.

**Comment by tekezo** [comment]
If you want to change right option key to fn key, you should use this autogen:

```xml
    <autogen>__KeyToKey__ KeyCode::OPTION_R, KeyCode::FN</autogen>
```

And enable "Fn+F1 to ..." in prepared settings.
https://pqrs.org/osx/karabiner/faq.html.en#fn
