### ISSUE TITLE
how to catch button6 & 7 on mouse ?

### ISSUE THREAD

**Issue by zhfish** [tekezo/Karabiner#329]
my mouse is m545 ( http://www.logitech.com/product/wireless-mouse-m545 )
it can set button4 & 5 all right
but it can't catch button 6&7 in event view

**Comment by tekezo** [comment]
It seems to have 5 buttons.
Where's the location of the button 6 and 7?
Is it Tilt wheel?

**Comment by zhfish** [comment]
Tilt wheel is button 4&5
button 6&7 is mouse left side buttons

**Comment by tekezo** [comment]
Tilt wheel will be interpreted as scroll wheel in OS X.
Do you want to use tilt wheel as other function?

**Comment by zhfish** [comment]
button 6&7 is mouse left side buttons ...
no Tilt wheel

Tilt wheel 's setting is well in OSX

**Comment by tekezo** [comment]
If you cannot catch these button events, Logitech Control Center might change these buttons.
Please confirm Logitech Control Center preferences or uninstall it by LCC Uninstaller.

**Comment by zhfish** [comment]
e.. i don't install Logitech Control Center For Mac never.

in windows ,Logitech Control Center can catch these events

**Comment by tekezo** [comment]
Hmm, did you already change buttons via Karabiner?
Could you show me your enabled settings?
(screen shot of Karabiner Preferences with "show enabled only" checkbox.)

**Comment by zhfish** [comment]
yeah, Karabiner is nice, i use button4 & 5 (tilt wheel) via Karabiner
![qq20150114-1](https://cloud.githubusercontent.com/assets/287033/5733123/09b9c7ce-9bd9-11e4-95d3-6d320f5af871.png)

**Comment by tekezo** [comment]
Hmm, if so, Karabiner might not support button 6 and button 7.
Please confirm USB Overdrive.
www.usboverdrive.com/

**Comment by zhsso** [comment]
I use m545 too
and I remap 6&7 to pageup and pagedown

```xml
 <item>
      <name>Mouse Side to Page Up and Down</name>
      <identifier>private.mouse_side_to_page_up_down</identifier>
     <autogen>
       __SimultaneousKeyPresses__ KeyCode::COMMAND_L, KeyCode::D, KeyCode::PAGEDOWN,
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::COMMAND_L, KeyCode::PAGEUP,
    </autogen>
 </item>
```xml

karabiner is an awesome tool!

**Comment by giaosudau** [comment]
@zhsso It works but when I press Command L it's page up too.
How to fix that?

**Comment by tekezo** [comment]
@giaosudau Use device_only filter.
https://pqrs.org/osx/karabiner/xml.html.en#devicedef

**Comment by giaosudau** [comment]
@tekezo Thanks It works :+1:

**Comment by zhfish** [comment]
It works, thanks
