### ISSUE TITLE
Feature request: text formating shortcuts for PC users

### ISSUE THREAD

**Issue by steph643** [tekezo/Karabiner#330]
It would be great if PC users could use the following shortcuts in word processors and browsers:
* Ctrl+b = bold
* Ctrl+i = italic
* Ctrl+u = underline

**Comment by tekezo** [comment]
I guess these feature do not have generic shortcut key.
It's easier to make your own settings for word processors by private.xml at first.
https://pqrs.org/osx/karabiner/xml.html.en#appdef

(Please share to me if you have made useful settings. I'll add them into prepared settings.)

**Comment by steph643** [comment]
Control/Command+b/i/u are common to all applications I know that involve rich text edition. However,  maybe it is dangerous to permanently map Control+b/i/u to Command+b/i/u.
I will use the following settings in the coming months and post here if I find a problem:
```
  <item>
    <name>Use PC Style Italic/Bold/Underline</name>
    <appendix>(Control+i/b/u to Command+i/b/u)</appendix>
    <appendix>{{ PC_STYLE_BINDINGS_IGNORE_APPS_DESCRIPTION }}</appendix>
    <identifier>private.pc_style_italic_bold_underline</identifier>
    <not>{{ PC_STYLE_BINDINGS_IGNORE_APPS }}</not>
    {{ PC_STYLE_BINDINGS_IGNORE_EXTRA }}
    <autogen>__KeyToKey__ KeyCode::U, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL, KeyCode::U, ModifierFlag::COMMAND_L</autogen>
    <autogen>__KeyToKey__ KeyCode::B, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL, KeyCode::B, ModifierFlag::COMMAND_L</autogen>
    <autogen>__KeyToKey__ KeyCode::I, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL, KeyCode::I, ModifierFlag::COMMAND_L</autogen>
  </item>
```
