### ISSUE TITLE
PointingDevice -> Button to Button -> Control+LeftClick to LeftClick not working

### ISSUE THREAD

**Issue by weeman1337** [tekezo/Karabiner#332]
As the title says PointingDevice -> Button to Button -> Control+LeftClick to LeftClick is not working. When I enable the option, Control+LeftClick behavior doesn't change to LeftClick. Instead it keeps Control+LeftClick. I'm using Karabiner on Yosemite with an external PC mouse.

**Comment by tekezo** [comment]
Did you enable other settings which changes button?
Please show me your enabled settings (Karabiner Preferences with "show enabled only".)

**Comment by weeman1337** [comment]
For testing purposes I disabled all other settings and it's still not working. I also tried to disable all other accessibility helpers.

**Comment by tekezo** [comment]
Please control+leftclick in EventViewer > Mouse Area.
Show me the result.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by weeman1337** [comment]
Here it is:
eventType:keyMod          code:0x3b       name:Control_L       flags:Ctrl                               misc:KeyCode::CONTROL_L	characters:    
eventType:mouseDown       code:0x0        name:left            flags:Ctrl                               misc:{771, 125} 1
eventType:mouseUp         code:0x0        name:left            flags:Ctrl                               misc:{771, 125} 1
eventType:keyMod          code:0x3b       name:Control_L       flags:                                   misc:KeyCode::CONTROL_L	characters:

**Comment by tekezo** [comment]
Thank you!
Is the result same even if you enabled "Control+LeftClick to LeftClick"?

If so, please tell me your mouse information.

If you are using Microsoft mice, please uninstall IntelliPoint because Karabiner does not work with IntelliPoint.

**Comment by weeman1337** [comment]
eventType:keyMod          code:0x3b       name:Control_L       flags:Ctrl                               misc:KeyCode::CONTROL_L	characters:    
eventType:mouseDown       code:0x0        name:left            flags:Ctrl                               misc:{741, 114} 1
eventType:mouseUp         code:0x0        name:left            flags:Ctrl                               misc:{741, 114} 1
eventType:keyMod          code:0x3b       name:Control_L       flags:                                   misc:KeyCode::CONTROL_L	characters:    

eventType:keyMod          code:0x3b       name:Control_L       flags:Ctrl                               misc:KeyCode::CONTROL_L	characters:    
eventType:mouseDown       code:0x0        name:left            flags:Ctrl                               misc:{770, 119} 1
eventType:mouseUp         code:0x0        name:left            flags:Ctrl                               misc:{770, 119} 1
eventType:keyMod          code:0x3b       name:Control_L       flags:                                   misc:KeyCode::CONTROL_L	characters:    

One event is with enabled the other with disable option. Looks the same except the position (?).

The mouse is a Logitech M500. I don't use any special Logitech mouse software.

**Comment by tekezo** [comment]
Hmm, it's strange.
The expected result (on my machine) is like this:

```xml
eventType:keyMod          code:0x3b       name:Control_L       flags:Ctrl                               misc:KeyCode::CONTROL_L	characters:
eventType:keyMod          code:0x3b       name:Control_L       flags:                                   misc:KeyCode::CONTROL_L	characters:
eventType:mouseDown       code:0x0        name:left            flags:                                   misc:{780.67578125, 98} 1
eventType:mouseDragged    code:0x0        name:left            flags:                                   misc:{780.67578125, 99} 1
eventType:mouseDragged    code:0x0        name:left            flags:                                   misc:{780.67578125, 100} 1
eventType:mouseUp         code:0x0        name:left            flags:                                   misc:{780.67578125, 100} 0
eventType:keyMod          code:0x3b       name:Control_L       flags:Ctrl                               misc:KeyCode::CONTROL_L	characters:
eventType:keyMod          code:0x3b       name:Control_L       flags:                                   misc:KeyCode::CONTROL_L	characters:
```

But your result keeps control+left.

Karabiner might be failed to detect your mouse.
Is your mouse shown in EventViewer > Devices?

**Comment by weeman1337** [comment]
Here is the device information of the mouse:

Consumer
    USB Laser Mouse (Logitech)

    DeviceVendor::RawValue::0x046d,
    DeviceProduct::RawValue::0xc069,

    DeviceLocation::RawValue::0x14200000,

**Comment by tekezo** [comment]
The Consumer type is belong to keyboard.
So, your mouse is not detected in Karabiner.

Another driver might be conflict with Karabiner.
Are you using extra mouse drivers such as SmoothMouse?

**Comment by weeman1337** [comment]
Yes I'm using SmoothMouse. If this is the problem, is there a way to get it working together?

**Comment by tekezo** [comment]
Unfortunately, there is not a way to work them together.

**Comment by weeman1337** [comment]
Hmm... Is it possible to define a custom (private.xml)rule that does "Control+LeftClick to LeftClick" in this case? Controls doesn't seem to be the problem, but how to match the left click?

**Comment by tekezo** [comment]
System will be crash when you use Karabiner and SmoothMouse together for pointing device.
So, Karabiner disables pointing device modification automatically if SmoothMouse is installed.

If you want to change Control+LeftClick to LeftClick in Karabiner, uninstall SmoothMouse is an only way.

**Comment by weeman1337** [comment]
Hmm Smooth Mouse is unfortunately a must have.. So I think I won't use this modifier. All other things are working fine. Karabiner is a cool software!
