### ISSUE TITLE
Can I set a custom status when I tap a key？

### ISSUE THREAD

**Issue by Helly1024** [tekezo/Karabiner#333]
Such as capslock. When we tap capslock key the status is on and tap it again it will be off.
Some hotkey are enabled while the status is on and disabled when the status is off.

**Comment by tekezo** [comment]
Yes.
Plesae tell me your desired hotkey.

**Comment by Helly1024** [comment]
<item>
        <name>F19 to F19</name>
        <appendix>(F19 to Hyper (ctrl+shift+cmd+opt) + F19 Only, send escape)</appendix>
        <identifier>private.f192f19_escape</identifier>
        <autogen>
            --KeyOverlaidModifier--
            KeyCode::F19,
            KeyCode::COMMAND_L,
            ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,
            KeyCode::ESCAPE
        </autogen>
    </item>
    <item>
        <name>Hyper K to Down</name>
        <appendix>(Hyper-K to Down arrow)</appendix>
        <identifier>private.hyper-k-down</identifier>
        <autogen>
            --KeyToKey--
            KeyCode::K,
            ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,
            KeyCode::CURSOR_DOWN
        </autogen>
    </item>



I want to set F19 as capslock.Then I can use K to CURSOR_DOWN when status is on and enable use K to CURSOR_DOWN when status is off.

**Comment by tekezo** [comment]
```xml
<?xml version="1.0"?>
<root>

  <modifierdef>HYPER</modifierdef>

  <item>
    <name>Example</name>
    <identifier>private.example</identifier>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::F19,
      KeyCode::VK_MODIFIER_HYPER,
      KeyCode::VK_LOCK_HYPER,
    </autogen>

    <autogen>__KeyToKey__ KeyCode::K, ModifierFlag::HYPER, KeyCode::CURSOR_DOWN</autogen>
  </item>

</root>
```

**Comment by Helly1024** [comment]
Thanks for your help! My hotkey working happily now.
