### ISSUE TITLE
Add 'Application Key to Command_R+Space' mapping

### ISSUE THREAD

**Issue by DXist** [tekezo/Karabiner#334]
In iTerm I remapped Command_L to Option_L to have consistent PC-like behavior for readline (`Alt-b / Alt-f`) and tmux keybindings.

And I mapped CapsLock to an Application Key to switch layout using this modifier. Now I can't switch keyboard layout in iTerm because there is no Command_L in my iTerm setup. I would like to use right Command key and have `Application Key to Command_R + Space` mapping.

**Comment by tekezo** [comment]
Please use new setting which will be added by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.application_to_command_space/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml
