### ISSUE TITLE
Double-tap hold

### ISSUE THREAD

**Issue by chendo** [tekezo/Karabiner#335]
Is it possible to have a double tap hold modifier?

i.e.

* tap Shift
* hold Shift quickly afterwards
* Converts to custom modifier down

`__DoublePressModifier__` only fires after I release the second tap unfortunately.

**Comment by tekezo** [comment]
lastpressedphysicalkey_only and elapsedtimesincelastpressed_lessthan filters allow you to do it.
(last pressed physical key only, elapsed times since last pressed less than)

```xml
    <block>
      <lastpressedphysicalkey_only>KeyCode::SHIFT_L</lastpressedphysicalkey_only>
      <elapsedtimesincelastpressed_lessthan>Millisecond::RawValue::1000</elapsedtimesincelastpressed_lessthan>
      <autogen>
        __KeyToKey__
        KeyCode::SHIFT_L,
        KeyCode::COMMAND_L,
      </autogen>
    </block>
```

**Comment by chendo** [comment]
Fantastic, thanks! Love your work!
