### ISSUE TITLE
Is it possible to assign both DoubleKeyModifier and KeyOverlaidModifier to one key?

### ISSUE THREAD

**Issue by jumjamjohn** [tekezo/Karabiner#336]
Is it possible to assign both DoubleKeyModifier and KeyOverlaidModifier to one key simultaneously?
For instance, when you press Shift_Left twice, you get Return, while when you hold Shift_L, it works as Control_Left.
Thank you.

**Comment by tekezo** [comment]
Basically, Karabiner does not allow to combine plural autogens into one key.

But, how about this private.xml?
https://github.com/tekezo/Files/blob/master/Karabiner/private.shift_to_return_holding_control/private.xml

**Comment by jumjamjohn** [comment]
It works! Thank you so much.

**Comment by tekezo** [comment]
Now we can use Option::KEYTOKEY_DELAYED_ACTION for this purpose.

https://github.com/tekezo/Karabiner/blob/version_10.9.0/src/core/server/Resources/include/checkbox/samples.xml#L934-L967
