### ISSUE TITLE
Karabiner causes screencast-o-matic (SOM) to crash

### ISSUE THREAD

**Issue by patkujawa-wf** [tekezo/Karabiner#337]
It took a long time working with the http://www.screencast-o-matic.com/ team to track down the cause of the app (versions 1 and 2) crashing on my macbook pro. In the end, it turned out that disabling Karabiner (fully, via Security & Privacy) fixed the crashes.
![image](https://cloud.githubusercontent.com/assets/6391742/6087582/87ff609c-ae0a-11e4-8b17-80e3a74f4cdb.png)

I find Karabiner really useful, but SOM is essential for my work. I wish I could have both :)

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at v10.6.5.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by patkujawa-wf** [comment]
Thank you so much! It appears to be working for me :)

**Comment by tekezo** [comment]
Thank you for confirmation!
