### ISSUE TITLE
it's slow to response while at Chinses WUBI input method

### ISSUE THREAD

**Issue by babyking** [tekezo/Karabiner#338]
In 10.6.4, I find it's slow to echo text while at Chinese WUBI input mode, but It's ok while at English input method or quit karabiner!

**Comment by tekezo** [comment]
I cannot reproduce this issue on my machine.
Is this issue happen even if you logged in as Guest user? (== clean environment)

If so, could you describe how to reproduce?

1. Karabiner Settings that you are enabled.
2. The way to reproduce show echo in WUBI input mode. (Note: I don't know WUBI input source well.)
