### ISSUE TITLE
Is it possible to map a non-multi-touch pointing device to multi-touch gestures?

### ISSUE THREAD

**Issue by Peeja** [tekezo/Karabiner#341]
I have a trackball. I used to have a Magic Mouse, and I miss being able to switch spaces easily with a three-fingered swipe. I'd really like to be able to enter a mode (maybe by holding a key or a mouse button) and turn trackball movement into three-fingered swiping.

Is that possible somehow? I haven't found a setting that does anything like that, but so much in Karabiner is hard to discover. :)

**Comment by tekezo** [comment]
If you are using Logitech M570t, I recommend this setting.

![150213-0001](https://cloud.githubusercontent.com/assets/659178/6171143/6c457fd2-b31c-11e4-9e6b-00f6fa0bc9a3.png)

If not, we should write own setting like that.
What's key you want to use as mode key?

**Comment by Peeja** [comment]
I'm using a Kensington Slimblade. I'm not sure what would be best for the mode key—probably either a modifier or a mouse button.

**Comment by tekezo** [comment]
How about new setting that will be added by this private.xml?
https://github.com/tekezo/Files/blob/master/Karabiner/private.slimblade/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

Note:
This setting changes trackball to control-arrow keys.
Therefore, you should not disable these Mission Control's shortcuts.

**Comment by Peeja** [comment]
Aha! I didn't know about `PointingRelative::*`.

Wow, that feels really nice. Thanks! Karabiner really is the best.
