### ISSUE TITLE
Remap key unless part of certain combinations (pass-through)

### ISSUE THREAD

**Issue by airdrummingfool** [tekezo/Karabiner#346]
Hello,
I've been trying to figure out how to ignore a key remap command if that key is used in certain combinations. For example, I've remapped `left control` to `left command`, but I want to ignore that remap if `left control` is used in combination with `tilde`.

Looking through the source, I found a couple places where certain keys are passed-through (e.g. https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/apps/terminal.xml), but all of those refer to a snippet that refers to a `wrap_keys.xml` that refers to a host of other xml files. Is there an easier way, or should I duplicate that setup if I want to pass-through certain key combinations?

If that complicated setup is required for pass-through, then this is a feature request to have some kind of simple key-exclusion functionality in the remap definitions :)
Thanks!

**Comment by tekezo** [comment]
Changing control-a, control-b, .., control-z to command-* using wrap_keys/*.xml is one of clear way.

Another way, we can restore command-tilde to control-tilde like this:

```xml
    <autogen>
      __KeyToKey__
      KeyCode::BACKQUOTE, ModifierFlag::COMMAND_L,
      KeyCode::BACKQUOTE, ModifierFlag::CONTROL_L,
    </autogen>
```

But it changes both physical command-tilde and physical control-tilde.
So, we mark physical command key by using virtual modifier.

```xml
  <modifierdef>PHYSICAL_CONTROL_L</modifierdef>

  <item>
    <name>Example</name>
    <identifier>private.example</identifier>
    <autogen>
      __KeyToKey__
      KeyCode::CONTROL_L,
      KeyCode::COMMAND_L, ModifierFlag::PHYSICAL_CONTROL_L,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::BACKQUOTE, ModifierFlag::COMMAND_L | ModifierFlag::PHYSICAL_CONTROL_L,
      KeyCode::BACKQUOTE, ModifierFlag::CONTROL_L,
    </autogen>
  </item>
```
