### ISSUE TITLE
Command_L to Control_L (only in Terminal) interfering with `⌘␣` Spotlight invocation

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tekezo/Karabiner#347]
I'd like to see the **“Command_L to Control_L (only in *)”** settings special-case `⌘␣`, such that it's still passed to the system to invoke Spotlight.

Pending this being implemented, is there an easy way to special-case or exclude particular key-combinations from that functionality, when it is enabled?

**Comment by tekezo** [comment]
Please use new setting that will be added by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.left_command_to_left_control_terminal/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by ELLIOTTCABLE** [comment]
@tekezo I've improved upon this somewhat:

https://gist.github.com/ELLIOTTCABLE/e353793e628467ff45c1

Unfortunately, I'm running into the following issue: with ⌘␣ and ⌘⇧␣ remapped, I still can't cycle in *both* directions through the app-switcher; after ⌘␣'ing, as soon as I hit ⇧, the app-switcher closes before I can hit ␣ again to move *backwards* through the switcher.

Here's what EventViewer has to say about it:

```
eventType:keyMod          code:0x0        name:                flags:                                   misc:KeyCode::A	characters:    
eventType:keyMod          code:0x3b       name:Control_L       flags:Ctrl                               misc:KeyCode::CONTROL_L	characters:    
eventType:keyMod          code:0x38       name:Shift_L         flags:Shift Ctrl                         misc:KeyCode::SHIFT_L	characters:    
eventType:keyMod          code:0x3b       name:Control_L       flags:Shift                              misc:KeyCode::CONTROL_L	characters:    
eventType:keyMod          code:0x37       name:Command_L       flags:Shift Cmd                          misc:KeyCode::COMMAND_L	characters:    
```

**Comment by tekezo** [comment]
You can solve it by changing shift keys to lazy shift keys.
Please enable following prepared settings:
* Shift_L to Lazy_Shift_L
* Shift_R to Lazy_Shift_R
