### ISSUE TITLE
Command + Control + F not working for fullscreen.

### ISSUE THREAD

**Issue by endrebak** [tekezo/Karabiner#348]
I want to open the fullscreen mode in a software called slicereader.

It seems to be fussy about how to open the fullscreen mode; first you have to press down `Command`, then you need to press `Control`, then you need to press F. If you press the keys in any other sequence, the bell is rung and it does not work.

I'm guessing this is why this key-command is not working:

```KeyCode::F | ModifierFlag::COMMAND_L, | ModifierFlag::CONTROL_L```

I know it is possible to press keys in sequence with the ```__{ ... }__``` syntax, but is there a way to press modifier keys in a certain sequence while holding them in?

What I want to do is first press command and hold it, then control and hold it, then f.

**Comment by tekezo** [comment]
> If you press the keys in any other sequence, the bell is rung and it does not work.
I cannot reproduce this issue.

Anyway, you can specify modifier order by using sticky modifier.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::A,

      KeyCode::VK_STICKY_COMMAND_L,
      KeyCode::VK_STICKY_CONTROL_L,
      KeyCode::A,
      Option::NOREPEAT,
    </autogen>
```

**Comment by endrebak** [comment]
Thanks a bunch!
