### ISSUE TITLE
PC style Ctrl+Shift+(Left or Right Arrow) to highlight words 

### ISSUE THREAD

**Issue by theflashback** [tekezo/Karabiner#349]
Folks,

can you guys make Ctrl+Shift+LeftArrow and Ctrl+Shift+RightArrow to highlight the entire word like on PC?

Thanks!

Serge

**Comment by tekezo** [comment]
Please use this setting.
![150223-0015](https://cloud.githubusercontent.com/assets/659178/6325944/eda90c8a-bb8f-11e4-9e66-ccdc50659ae8.png)

**Comment by theflashback** [comment]
It is flaky - sometimes it works sometimes it does not.

________________________________

**Comment by theflashback** [comment]
It only works when you hold the Shift key first and then the Ctrl. Otherwise it does not. Any assistance with that?

Thanks!

Serge

________________________________

**Comment by tekezo** [comment]
I guess other settings are conflicting.
Please show me your enabled settings.
(Screen shot of Preferences with "show enabled only")

**Comment by theflashback** [comment]
Fumihiko,

here is what I found:

if you press Shift + Ctrl + Left/Right Arrows OSX starts selecting words. But if you press Ctrl+Shift+Left/Right arrows it does not work. OSX always expects you to press Shift first to start selecting words. Is there anyway we can make it work so that word selection works regardless of whether Shift is pressed first or after the Ctrl key is already down?

Thanks,

Serge

________________________________

**Comment by tekezo** [comment]
Ctrl+Shift+Left/Right arrows works well on my machine.
Please show me your enabled settings.

**Comment by theflashback** [comment]
Fumihiko,

Attached is what I disabled and now it seems to work fine.

Can you send me two more entries for my private XML that will workaround XCode 6.3?

When the block of code is selected, hitting TAB should move the selected block to the right and Shift+Tab to the left? In XCode they do it via Command+[ and Command+[ which is totally cumbersome 😂😂😂.

Cheers!!

Serge

[image1.PNG]

Thanks!

Serge



On Feb 25, 2015, at 18:44, Takayama Fumihiko <notifications@github.com<mailto:notifications@github.com>> wrote:


Ctrl+Shift+Left/Right arrows works well on my machine.
Please show me your enabled settings.

**Comment by tekezo** [comment]
It's not a good way that perform such a context dependent behavior by using Karabiner.
Because Xcode does not provides a way to observe internal state to external apps (eg.  Karabiner).

You should confirm Xcode Preferences > Key Bind.
![150227-0001](https://cloud.githubusercontent.com/assets/659178/6409236/ea96016c-bea3-11e4-8165-1ee6b60a06b4.png)

**Comment by theflashback** [comment]
Yeah, I tried that, but it does not observe the presence of the shift key -- I will keep trying - just remapped the Command+L to F6 in Google chrome to focus the address bar - I am getting up to speed 👍👍👍

Thank you for all your hard work! After 25 years of blind typing on my PC I could not type anything in OS X because everything was mapped differently.

Hugs!

Serge



On Feb 27, 2015, at 00:15, Takayama Fumihiko <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not a good way that perform such a context dependent behavior by using Karabiner.
Because Xcode does not provides a way to observe internal state to external apps (eg. Karabiner).

You should confirm Xcode Preferences > Key Bind.
[150227-0001]<https://cloud.githubusercontent.com/assets/659178/6409236/ea96016c-bea3-11e4-8165-1ee6b60a06b4.png>
