### ISSUE TITLE
PrntScn to print the entire screen / Alt + PrntScn to print the selected block

### ISSUE THREAD

**Issue by theflashback** [tekezo/Karabiner#350]
Can we implement this PC style commands too?

Thanks!

Serge

**Comment by tekezo** [comment]
Please use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.pc_style_printscreen/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by theflashback** [comment]
Awesome! This works OK!

________________________________
