### ISSUE TITLE
Move or enable modifier keys on new 'layer'

### ISSUE THREAD

**Issue by sypl** [tekezo/Karabiner#352]
I don't think Karabiner has the concept of layers, but this is what I'm trying to achieve:
- set command_r to custom modifier, call it 'special'
- holding special turns J into shift_r, K into command_r

Doing this with a single modifier is easy enough, i.e. special + J = shift + J = capital J. However trying special + J + K gives me either capital K (because I pressed J before K, therefore triggering shift+K) or command+J (vice versa).

Is there a way I can have J and K always behave as shift and command, and never as J and K, whenever I'm holding down 'special'?

**Comment by tekezo** [comment]
There are two ways to do it.
https://github.com/tekezo/Files/blob/master/Karabiner/private.command_r_special/private.xml

**Comment by sypl** [comment]
That's fantastic. Thanks!
