### ISSUE TITLE
Can't remap the backquote key.

### ISSUE THREAD

**Issue by politicus** [tekezo/Karabiner#353]
Succeded in remapping the Return key. So, Karabiner is working. And apparently I know how to remap keys. But I had no luck in remapping the ` key (backquote key) to another key (Delete/Forward Delete).

Karabiner version: 10.6.0
Input source: French

From the EventViewer
Language Code: fr
Input Source ID: com.apple.keylayout.French
Input Mode ID: ---

**Comment by tekezo** [comment]
Please confirm KeyCode of your ` key by EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

I guess ` key in fr is KeyCode::BACKSLASH.
If so, "Backslash(\) to Delete" changes your ` key.

**Comment by politicus** [comment]
Working like a charm. Thank you.
