### ISSUE TITLE
dota_osx unable to be seen in EventViewer/Defined in private.xml

### ISSUE THREAD

**Issue by micks-ketches** [tekezo/Karabiner#355]
dota_osx (Dota 2)seems to have no bundle id to tie it to and thus no way for me to have any app specific definitions, here is a bit of infodump:

`Analysis of sampling dota_osx (pid 30087) every 1 millisecond
Process:         dota_osx [30087]
Path:            /Users/mickerus/Library/Application Support/Steam/steamapps/common/dota 2 beta/dota_osx
Load Address:    0x1f000
Identifier:      dota_osx
Version:         ???
Code Type:       X86
Parent Process:  bash [30084]`
I did a bit of digging, but was unable to make Karabiner detect that specific application, Keep in mind it is run using OpenGL and Terminal/bash seems to be it's parent process (I've tried com.apple.Terminal without success)

`<equal>dota_osx</equal>` will not work nor will any other ID combinations I've tried.

**Comment by tekezo** [comment]
Unfortunately, there is no way to handle programs that do not have app forms.

**Comment by tekezo** [comment]
Please make a wrapper for dota_osx by AutoMator.
(Create an app that launch dota_osx.)

Wine has similar program and Wineskin makes a wrapper app.

**Comment by micks-ketches** [comment]
steam_osx usually launches dota, would that cause any with the wrapper?

**Comment by tekezo** [comment]
I don't know well about steam.
How about making a wrapper for steam_osx?

**Comment by kaansoral** [comment]
It doesn't help much, but have you tried handing the Steam app itself?
(I guess it might not be what you want, if you're trying to handle multiple games)

**Comment by micks-ketches** [comment]
unfortunately dota does not belong in the steam hiearchy for some reason, it's a really weird interaction. If i define it for steam_osx then it will work only if I tab from steam directly into dota.

**Comment by NekR** [comment]
Not sure if it's still actual for you, but this works for me:

```xml
<appdef>
  <appname>DOTA</appname>
  <equal>com.dota2</equal>
</appdef>
```

/cc @gxgani

**Comment by gxgani** [comment]
@NekR cool, thanks.
