### ISSUE TITLE
Key press not registered by the Event Viewer?

### ISSUE THREAD

**Issue by Goles** [tekezo/Karabiner#357]
Hello,

My keyboard does have a 'Fn' key at the right of the right Control key. When activating Karabiner debug, I'm getting the following output when pressing + releasing the key:

```
Mar 10 09:42:04 Goles kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x00ff, kbdType  40, repeat = 0
Mar 10 09:42:04 Goles kernel[0]: org.pqrs.Karabiner --Debug-- An unknown modifier is pressed (KeyCode:0xff, Flags:0x80000000). Ignore it.
Mar 10 09:42:04 Goles kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x00ff, kbdType  40, repeat = 0
Mar 10 09:42:04 Goles kernel[0]: org.pqrs.Karabiner --Debug-- An unknown modifier is pressed (KeyCode:0xff, Flags:0x80000000). Ignore it.
```

However when I run the EventViewer nothing is going on on that Key press.. Any ideas of what could be going on here?

**Comment by tekezo** [comment]
Your key (KeyCode:0xff) is ignored by Karabiner.

That key sends same key event at both key up and key down.
Therefore, we cannot use that key to normal usage because we cannot detect physical key up.

**Comment by Goles** [comment]
@tekezo That's strange, I have another MacBook that I use with this keyboard and I didn't notice this problem. Do you think there's something I can do about it?

**Comment by tekezo** [comment]
I guess it is caused by the third vendor keyboard driver or your keyboard is broken.

**Comment by Goles** [comment]
@tekezo I'm going to debug this issue in the MacBook were this keyboard is working properly. Is there a way to actually pick the driver myself? Haven't installed anything so I guess OS X did it for me when it tried to recognize this keyboard model.

**Comment by tekezo** [comment]
I don't know well.
Does your fn key work properly in Safe Mode?
If not, you should check your MacBook in Genius Bar.

Mac OS X: Starting up in Safe Mode
http://support.apple.com/kb/ht1455

**Comment by Goles** [comment]
Maybe I didn't explain myself correctly,

This is an external non-apple keyboard, not my MacBook's keyboard.

Does that change things?
Cheers!

**Comment by tekezo** [comment]
I see.
Unfortunately, Karabiner does not support the fn key in non-apple keyboards.
