### ISSUE TITLE
Remap Alt to Command for microsoft keyboard 

### ISSUE THREAD

**Issue by morenoh149** [tekezo/Karabiner#358]
Is it possible? I looked over the code list here https://github.com/tekezo/Karabiner/blob/version_10.6.0/src/bridge/generator/keycode/data/KeyCode.data
I there anyway to remap the alt key to command and the windows key to alt/option. I'm a mac user trying to use a Microsoft keyboard. http://www.amazon.com/Microsoft-Natural-Ergonomic-Keyboard-4000/dp/B000A6PPOK/ref=sr_1_1?ie=UTF8&qid=1426065091&sr=8-1&keywords=microsoft+keyboard+4000

thank you

**Comment by morenoh149** [comment]
Ah eventviewer reports the keys as `Command_L` `Option_L` & `Option_R`. I'll try these codes instead.

**Comment by morenoh149** [comment]
Ah even better the options I needed are already available as checkboxes. Excellent software!

**Comment by tekezo** [comment]
You can confirm KeyCode by EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by Leoaraujo79** [comment]
![image](https://cloud.githubusercontent.com/assets/3285978/9248241/670b300c-41ba-11e5-8ffa-c357497da3ed.png)


Hi Just in case someone find this post looking for settings.

This is how I set my Microsoft keyboard - German layout to use with my Mac Mini.

Hope it helps someone out there.

**Comment by NicolasVanhecke** [comment]
@Leoaraujo79 
Could you show the custom items you have written in the xml? I am trying to do the same (use mechanical keyboard from windows on mac osx). If it is possible, only activate this on external keyboards?

**Comment by Leoaraujo79** [comment]
@NicolasVanhecke 

Sorry, I am not using this setup anymore...

**Comment by NicolasVanhecke** [comment]
@Leoaraujo79 

Ah man, that sucks. 
Did you find another tool, or a better way to remap  keys on macOSX? I am quiet fond of my mechanical and would like to code with it on mac.

**Comment by Leoaraujo79** [comment]
@NicolasVanhecke

I end up getting used to the keyboard without additional software.
