### ISSUE TITLE
Photoshop Click/Drag

### ISSUE THREAD

**Issue by UnionDesign** [tekezo/Karabiner#359]
Software works great but in Photoshop I'm constantly experiencing a click and hold/drag behaviour when I'm only performing simple single clicks. It appears to happen randomly but with regularity. If I click back and forth between two layers for instance this will always happen but not with a predicable pattern (could happen after 1 single click or 15... but it always happens eventually). This is with the latest Mac OS X and the lastest Creative Cloud version.

**Comment by tekezo** [comment]
There is possibility of a hardware issue that your mice button is bouncing.
Please enable "General > Don't remap any pointing devices" and confirm your issue still happen.

**Comment by UnionDesign** [comment]
I'm certain that wasn't the case. But I've since switched to a mouse that doesn't require Karabiner anymore.
