### ISSUE TITLE
Is it possible to map every scroll wheel click?

### ISSUE THREAD

**Issue by Peeja** [tekezo/Karabiner#361]
I'd like to have my scroll wheel move me between my tabs in Chrome when I hold the left mouse button. So far, I have

```xml
<autogen>
  __KeyOverlaidModifier__
  PointingButton::LEFT,
  KeyCode::VK_MODIFIER_BUTTON4,
  PointingButton::LEFT,
</autogen>

<group>
  <only>Google Chrome</only>
  <autogen>__ScrollWheelToKey__ ScrollWheel::UP,   ModifierFlag::BUTTON4, KeyCode::BRACKET_LEFT,  ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L</autogen>
  <autogen>__ScrollWheelToKey__ ScrollWheel::DOWN, ModifierFlag::BUTTON4, KeyCode::BRACKET_RIGHT, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L</autogen>
</group>
```

This works, but it doesn't trigger multiple times if I scroll quickly. It looks like Karabiner limits how often it fires a `ScrollWheelToKey` to work with continuous-scrolling mice. My trackball has a discrete scroll wheel, so I'd rather have it always trigger. Is there a way to get `ScrollWheelToKey` for each scroll event and bypass the interval check?

**Comment by tekezo** [comment]
Please adjust "Karabiner Preferences > Key Repeat tab > Advanced Configuration > ScrollWheel to Key > Key Repeat Wait" setting.

**Comment by Peeja** [comment]
You really have thought of everything, haven't you? Thanks so much!
