### ISSUE TITLE
Question: How to Remap Option+Letter keys?

### ISSUE THREAD

**Issue by kylebrandt** [tekezo/Karabiner#362]
For example I would like to turn option+d into a [. When doing this I still end up with a rounded d (∂).

I have tried:

```
	<item>
		<name>option+d to {</name>
		<identifier>remap.optd_to_curly</identifier>
		<autogen>
			__KeyToKey__ 
			KeyCode::D, 
			ModifierFlag::OPTION_L | ModifierFlag::OPTION_R,
			KeyCode::BRACKET_LEFT,
		</autogen>
	</item>
```

EventView output:

![image](https://cloud.githubusercontent.com/assets/1692624/6710070/90462b5a-cd54-11e4-8979-78cacb6680c3.png)

**Comment by kylebrandt** [comment]
Managed to figure it out I think:
```
		<autogen>
			__KeyToKey__ 
			KeyCode::D, VK_OPTION | ModifierFlag::NONE,
			KeyCode::BRACKET_LEFT,
		</autogen>
```

However I still don't understand what was wrong with my other one, or how this one works. I just adapted https://pqrs.org/osx/karabiner/faq.html.en#unicode-hex-input and got lucky....

**Comment by tekezo** [comment]
`ModifierFlag::OPTION_L | ModifierFlag::OPTION_R` means "if both the left option key and the right option key are pressed".

--------------------

The second

```xml
        <autogen>
            __KeyToKey__ 
            KeyCode::D, VK_OPTION | ModifierFlag::NONE,
            KeyCode::BRACKET_LEFT,
        </autogen>
```
will be expanded two autogens:

```
        <autogen>
            __KeyToKey__ 
            KeyCode::D, ModifierFlag::OPTION_L | ModifierFlag::NONE,
            KeyCode::BRACKET_LEFT,
        </autogen>
        <autogen>
            __KeyToKey__ 
            KeyCode::D, ModifierFlag::OPTION_R | ModifierFlag::NONE,
            KeyCode::BRACKET_LEFT,
        </autogen>
```

**Comment by kylebrandt** [comment]
Thanks for explaining. I even read about the pipe in the documentation but inserted it to mean "or" in my head :-P
