### ISSUE TITLE
Home / End Keys doesn't work properly on Photoshop

### ISSUE THREAD

**Issue by atilkan** [tekezo/Karabiner#363]
As title says. It puts 'a' or 'e' instead. Just like hitting ctrl + e / a.  
Instead Ctrl+e/a, Home and End keys should work like Cmd+right / left arrow. 
I guess this is cause of Mac OS doesn't have a standard keyboard layout globally. Every program does what it pleased.

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at the latest beta version (v10.6.27).

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by atilkan** [comment]
I red in mail but forgot to say thanks.
