### ISSUE TITLE
Remap events to IPC calls?

### ISSUE THREAD

**Issue by cmsj** [tekezo/Karabiner#364]
Hi

I'm a maintainer of Hammerspoon (http://www.hammerspoon.org) an OS X automation app driven by Lua. One of our core features is being able to bind a hotkey to a Lua function, allowing the user to automate very many things with a quick keypress.

Something I'm finding is that I want to go beyond the abilities of Carbon to register hotkeys with the OS (e.g. I'd like to be able to behave differently if COMMAND_L or COMMAND_R are pressed with different hotkeys, but obviously this is not available in Carbon). Currently I work around this by using Karabiner to remap the various combinations to keys that aren't on my keyboard (such as F13-F19 and KEYMAP_0-KEYMAP9), but I am starting to run out of spare keycodes!

So, I was wondering how you would feel about extending Karabiner to be able to deliver events to another process, perhaps something like:

    <autogen>
      --KeyToHammerspoon--
      KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_R | ModifierFlag::OPTION_R
      Hammerspoon::MySpecialCursorEvent
    </autogen>

which would be delivered via some IPC mechanism to the Hammerspoon process, for it to decide how to handle "MySpecialCursorEvent". Or perhaps something like:

    <autogen>
      --KeyToHammerspoon--
      KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_R | ModifierFlag::OPTION_R
    </autogen>

which would send a more complex event to Hammerspoon, telling it the combination of keys that were pressed. I would tend to favour the former, since it would involve less repetition of the structure of the event.

(If suitably abstracted, it's entirely possible that this mechanism would want to be adopted by many other OS X automation apps besides Hammerspoon)

**Comment by tekezo** [comment]
Karabiner allows you to run shell commands by shortcuts.
https://pqrs.org/osx/karabiner/xml.html.en#vkopenurldef

Can Hammerspoon do something from command line?

**Comment by cmsj** [comment]
Yeah, it can. I started to work up a patch for Karabiner to talk to our CFMessagePort, but I think a URL handler might make the most sense here.

Thanks for the response, and thanks for karabiner!

**Comment by cmsj** [comment]
(For the sake of future web searches, this is now implemented in Hammerspoon 0.9.27 with the addition of the hs.urlevent extension. An example of integration with Karabiner is given, at http://www.hammerspoon.org/go/#karabinerurl )
