### ISSUE TITLE
Swap Backslash and Pipe

### ISSUE THREAD

**Issue by gharlan** [tekezo/Karabiner#365]
On a german keyboard I want to swap `#` and `'` (single quote). I think the key is the backslash key on the US layout.

**Comment by tekezo** [comment]
Please use new setting that will be added by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.german_swap_hash_and_quote/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by sypl** [comment]
That works but causes large lag when activated. Is it just me?

**Comment by tekezo** [comment]
No lag on my machine.
What's events are delayed, key events or mouse?

**Comment by sypl** [comment]
It freezes up both the keyboard and mouse. Seems like some sort of infinite loop going on.

**Comment by tekezo** [comment]
If you are using Gaming Mouse, Karabiner might bring some lag.
Please try "General > Don't remap any pointing devices".

**Comment by sypl** [comment]
No, no mouse at all, just trackpad. I thought it may be because I have a lot of remappings already so I tried again with another clean config, but still get the lag. I'll maybe try it on a friend's laptop next.

**Comment by tekezo** [comment]
If you changed values in Key Repeat tab, some values make lag.
Please confirm "Simultaneous Key Presses > Delay Threshold *".
