### ISSUE TITLE
Problems with some combinations of keys (for example ALT + t)

### ISSUE THREAD

**Issue by wondernet** [tekezo/Karabiner#368]
I have Yosemite and Karabinier is version 10.6.0. In previous versions I didn't have this problem.
I have this problem with remote in windows machines where I use combinations of ALT + other keys. Some of this combinations still work, but not all of them.

**Comment by tekezo** [comment]
What settings you are using?
(Please show me Karabiner Preferences with "show enabled only" checkbox.)

**Comment by wondernet** [comment]
![screen shot 2015-03-25 at 21 17 11](https://cloud.githubusercontent.com/assets/1641599/6833288/839aab16-d334-11e4-8738-5605f83b2027.png)

**Comment by tekezo** [comment]
Hmm, I cannot reproduce your issue.

Microsoft says "Fix for issues with Alt key shortcuts" in the latest release.
https://itunes.apple.com/en/app/microsoft-remote-desktop/id715768417?mt=12

Is your issue solved by new Remote Desktop?
If not, could you confirm whether your issue happen without Karabiner?

**Comment by wondernet** [comment]
I is fixed with that update to Remote Desktop.
