### ISSUE TITLE
Strange behaviour PC Style Home/End #2 In Browser 

### ISSUE THREAD

**Issue by hiphapis** [tekezo/Karabiner#369]
Textarea in browser
when i press `HOME`, then move to back page
yes, i known reason is bind `Commend+Left`

how to resolve this problem?

**Comment by tekezo** [comment]
The command+left shortcut works fine in this github textarea on my machine (Safari, Chrome).
Did you change shortcuts of browser?

Does "PC Style Home/End" solve your issue?

**Comment by hiphapis** [comment]
Oops Sorry.
yes textarea does work. problem is just in browser
i expect scroll to top when i press `HOME` but do move to back page

**Comment by tekezo** [comment]
Unfortunately, there is not a way in Karabiner.

You might do it by this sequence:

1. Ignore browers in PC Style settings by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.PC_STYLE_BINDINGS_IGNORE_APPS/private.xml

2. Change key bindings in browser.

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by hiphapis** [comment]
ah.. :cry: 
yes. i known private.xml and already i did try it.
but i'm failed. so i written this issue.
Thanks @tekezo
