### ISSUE TITLE
KeyCode::J doesn't work when remapping modifier keys

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#372]
Karabiner.version 10.6.0

I'm trying to map `SEMICOLON` to `EXTRA6`, and then, while `EXTRA6` is active, `F` is going to be `COMMAND_L`. My end game is to be able to use `J K I L` as arrow keys while staying on the home row. 

The problem is: `J` will not fire any events while `F` is pressed no matter what, and it seems that `J` is the only key for which this problem happens. Here is a config and a pasteboard of the events.

Reproduced with these minimal settings. No other autogens activated.
```xml
<autogen>
	__KeyOverlaidModifier__ KeyCode::SEMICOLON, KeyCode::VK_MODIFIER_EXTRA6, KeyCode::SEMICOLON
</autogen>

<autogen>
	__KeyToKey__ KeyCode::F, ModifierFlag::EXTRA6, KeyCode::COMMAND_L, ModifierFlag::EXTRA6
</autogen>

```

Pasteboard of the events *** annotated *** where relevant:
```
*** SEMICOLON key down ***
eventType:keyDown         code:0x26       name:j               flags:                                   misc:KeyCode::J	characters:j   
eventType:keyUp           code:0x26       name:j               flags:                                   misc:KeyCode::J	characters:j   
eventType:keyDown         code:0x28       name:k               flags:                                   misc:KeyCode::K	characters:k   
eventType:keyUp           code:0x28       name:k               flags:                                   misc:KeyCode::K	characters:k   
eventType:keyDown         code:0x22       name:i               flags:                                   misc:KeyCode::I	characters:i   
eventType:keyUp           code:0x22       name:i               flags:                                   misc:KeyCode::I	characters:i   
eventType:keyDown         code:0x25       name:l               flags:                                   misc:KeyCode::L	characters:l   
eventType:keyUp           code:0x25       name:l               flags:                                   misc:KeyCode::L	characters:l   

*** F key down ***
eventType:keyMod          code:0x37       name:Command_L       flags:Cmd                                misc:KeyCode::COMMAND_L	characters:    
*** J key down ***
*** J key up ***
*** no trace of J ***
eventType:keyDown         code:0x28       name:k               flags:Cmd                                misc:KeyCode::K	characters:k   
eventType:keyDown         code:0x22       name:i               flags:Cmd                                misc:KeyCode::I	characters:i   
eventType:keyDown         code:0x25       name:l               flags:Cmd                                misc:KeyCode::L	characters:l   
*** F key up ***
eventType:keyMod          code:0x37       name:Command_L       flags:                                   misc:KeyCode::COMMAND_L	characters:    

*** SEMICOLON key up ***
```
Interestingly, when pressing `COMMAND_L` instead of `F`, `J` works as expected.

Edit 1:
If `SEMICOLON` is released while `F` is still down, `J` works as expected, which probably means `J` doesn't like playing with multiple mapped modifiers.

Edit 2:
Just tried Karabiner in debug mode. With `SEMICOLON` and `A` down, `J` shows **no** events in Console.

**Comment by tekezo** [comment]
It's hardware limitation "2 key rollover".
https://pqrs.org/osx/karabiner/faq.html.en#rollover

**Comment by nkgm** [comment]
Thanks for shedding light on this. Suspected it might be hardware related but couldn't find any other key combinations. I've since found the same problem for `BRACKET_LEFT + I + T`, `SLASH + M + N` etc. Funny how Apple use "2 key rollover" to reduce cost, yet their keyboards cost more than most.
