### ISSUE TITLE
Shift + Home & Shift + End

### ISSUE THREAD

**Issue by udayms** [tekezo/Karabiner#375]
Hi,

The Home and End keys working PC style on a MAC is my most used feature of Karabiner. However, I find that Shift+home and Shift+end doesnt seem to work and I use these extensively while coding in editors like phpstorm, sublimetext etc. How can I get those working?

.Uday

**Comment by tekezo** [comment]
Does your issue happen in the latest beta version? (v10.6.39)

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by madshn** [comment]
i have the most up-to-date version as of today (just installed) and have the same issue as described here..

**Comment by adergaard** [comment]
For me too, in part

Testing it in this textarea here in Github it actually works fine i.e. Shift+Home and Shift+End goes to start/end of line and selects the text underneath it.

However, in SublimeText that I use for coding, only Shift + End works as expected. Shift + Home doesn't.

I know this sounds weird but I can only describe what is happening.
