### ISSUE TITLE
"Initial Modifier Wait" setting is not honoured by KeyOverlaidModifierWithRepeat

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#380]
More specifically, it appears to be ignored for values less that ~500ms.

**Comment by tekezo** [comment]
You should set greater value than "Delay Until Repeat".

**Comment by nkgm** [comment]
Tried setting all values to 0, 10 etc but the initial timeout is not affected. For example:
```xml
<autogen>__KeyOverlaidModifierWithRepeat__ KeyCode::C, KeyCode::SHIFT_L, KeyCode::SPACE</autogen>
```
I was hoping setting "Initial Modifier Wait" to 0 would speed up the transition from `SHIFT_L` to `SPACE` (when no other keys as pressed), but it only seems to be affected for values above ~500ms.

**Comment by tekezo** [comment]
You should change value as:

* Initial Modifier Wait: default value
* Timeout: default value
* Delay Until Repeat: 100
