### ISSUE TITLE
KEYTOKEY_DELAYED_ACTION works for the first key only

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#381]
```xml
<!-- this will work -->
<autogen>
  __KeyToKey__
  KeyCode::F,
  KeyCode::VK_NONE,

  Option::KEYTOKEY_DELAYED_ACTION,
  KeyCode::F,

  Option::KEYTOKEY_DELAYED_ACTION_CANCELED_BY, KeyCode::J
</autogen>

<!-- this WON'T work -->	
<autogen>
  __KeyToKey__
  KeyCode::F,
  KeyCode::VK_NONE,

  Option::KEYTOKEY_DELAYED_ACTION,
  KeyCode::F,

  Option::KEYTOKEY_DELAYED_ACTION_CANCELED_BY, KeyCode::K
</autogen>
	
<!-- this WON'T work -->	
<autogen>
  __KeyToKey__
  KeyCode::F,
  KeyCode::VK_NONE,

  Option::KEYTOKEY_DELAYED_ACTION,
  KeyCode::F,

  Option::KEYTOKEY_DELAYED_ACTION_CANCELED_BY, KeyCode::L
</autogen>

<!-- this WON'T work -->		
<autogen>
  __KeyToKey__
  KeyCode::F,
  KeyCode::VK_NONE,

  Option::KEYTOKEY_DELAYED_ACTION,
  KeyCode::F,

  Option::KEYTOKEY_DELAYED_ACTION_CANCELED_BY, KeyCode::I
</autogen>
```

**Comment by tekezo** [comment]
They work fine on my machine.

Karabiner applies only the first matched <autogen>.
If you are putting them into one `<item>`, Karabiner use the first <autogen>.
https://pqrs.org/osx/karabiner/xml.html.en#order

**Comment by nkgm** [comment]
Just assumed that logically it should be possible to distinguish between the 4 depending on which key the action was cancelled with, but I see why it currently doesn't. Even if I put each one in a separate item, the result should be the same though shouldn't it?

**Comment by tekezo** [comment]
If you want to use multiple canceled_by, put them into one autogen.

https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/samples.xml#L897-L933

**Comment by nkgm** [comment]
Can't believe I missed that considering the time I've spent looking at examples. Works a treat. Thanks!

**Comment by tekezo** [comment]
The example has been added just yesterday. Thank you for feedback!
