### ISSUE TITLE
PC Style Home/End and PgUp/PgDown does not work in muCommander

### ISSUE THREAD

**Issue by theflashback** [tekezo/Karabiner#383]
Folks,

enabling this works fine but makes muCommander completely unusable. Can you create a private.xml for my to bypass this feature in muCommander? Ideally, we need to have an exception list of app.

Let me know.

Serge

**Comment by tekezo** [comment]
Please use new setting that will be added by this private.xml.
https://github.com/tekezo/Files/blob/master/Karabiner/private.pc_style_mucommander/private.xml

**Comment by theflashback** [comment]
Hi!

Thanks for your quick reply. For some reason it does not work. I imported the xml, reloaded it and then even restarted the app. It still does not work. Unchecking home/end/pgup/pgdown in the PC user settings works in muCommander but then in all other apps lose this functionality! Please help! This is very crucial :-) !!

Thank you!!



On Apr 17, 2015, at 01:34, Takayama Fumihiko <notifications@github.com<mailto:notifications@github.com>> wrote:


Please use new setting that will be added by this private.xml.
https://github.com/tekezo/Files/blob/master/Karabiner/private.pc_style_mucommander/private.xml

**Comment by tekezo** [comment]
You have to enable the new setting. Did you enable that?

If you did, a bundle identifier of muCommander might be changed and we have to support it.
Could you tell me the bundle identifier of muCommander?
You can confirm it by EventViewer.
https://pqrs.org/osx/karabiner/xml.html.en#appdef
