### ISSUE TITLE
Remapping priority (Colemak)

### ISSUE THREAD

**Issue by aymericbeaumet** [tekezo/Karabiner#384]
**System**: Darwin macbookpro 14.1.0 Darwin Kernel Version 14.1.0
**Karabiner**: 10.6.39

---

- I enabled the Colemak layout
- I enabled some Emacs mappings

The expected behaviour is that the Colemak layout is applied first, followed by the Emacs mappings.

It appears that the Qwerty mappings always takes precedence. It brokes the Emacs mappings where the position overlaps between the Qwerty and the Colemak layouts, for example:
- Qwerty `^E` == Colemak `^F` (go to the end of line instead of jumping a single character)
- Qwerty `^K` == Colemak `^E` (delete to the end of line instead of jumping to the end of the line)
- ...

Is there a way to specify the order in which the mapping should be interpreted?

**Comment by aymericbeaumet** [comment]
I was able to do what I wanted by defining custom mappings which uses the Qwerty physical position of the Colemak letters.

For example, `E` needs to be used in order to map `^F`:

```xml
  <item>
    <identifier>remap.control_f</identifier>
    <name>^F</name>
    <autogen>__KeyToKey__ KeyCode::E, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL, KeyCode::CURSOR_RIGHT</autogen>
  </item>
```

**Comment by tekezo** [comment]
Thank you for resolving issue by yourself.
Your private.xml is the only way to use Colemak and Emacs mappings.

**Comment by aymericbeaumet** [comment]
Ok, solved then.

Keep going the great work!
