### ISSUE TITLE
Recursive mapping

### ISSUE THREAD

**Issue by aymericbeaumet** [tekezo/Karabiner#385]
**System**: Darwin macbookpro 14.1.0 Darwin Kernel Version 14.1.0
**Karabiner**: 10.6.39

---

- I remapped the options keys to the control keys.
- I also added the following mapping:

```xml
  <item>
    <identifier>remap.controls_to_brackets</identifier>
    <name>Controls to brackets</name>
    <autogen>
      __KeyOverlaidModifier__ KeyCode::CONTROL_L, ModifierFlag::CONTROL_L | ModifierFlag::NONE,
        KeyCode::CONTROL_L,
        KeyCode::BRACKET_LEFT,
    </autogen>
    <autogen>
      __KeyOverlaidModifier__ KeyCode::CONTROL_R, ModifierFlag::CONTROL_R | ModifierFlag::NONE,
        KeyCode::CONTROL_R,
        KeyCode::BRACKET_RIGHT,
    </autogen>
  </item>
```

The expected behavior is that a physical stroke on one of the option keys should emulate a control stroke, which itself should generate either a `[` or a `]`.

The control keys are properly emulated, but the brackets are not generated. So I suppose the mappings are not recursively triggered?

**Comment by aymericbeaumet** [comment]
A temporary solution is to directly map the option keys to the control/bracket keys:

```xml
  <item>
    <identifier>remap.options_to_control_brackets</identifier>
    <name>Options to control/brackets</name>
    <autogen>
      __KeyOverlaidModifier__ KeyCode::OPTION_L, ModifierFlag::OPTION_L | ModifierFlag::NONE,
        KeyCode::CONTROL_L,
        KeyCode::BRACKET_LEFT,
    </autogen>
    <autogen>
      __KeyOverlaidModifier__ KeyCode::OPTION_R, ModifierFlag::OPTION_R | ModifierFlag::NONE,
        KeyCode::CONTROL_R,
        KeyCode::BRACKET_RIGHT,
    </autogen>
  </item>
```

**Comment by tekezo** [comment]
Karabiner does not support recursive mapping.
You should change option key directly.

**Comment by aymericbeaumet** [comment]
Alright, thanks! Will keep my temporary skein then.
