### ISSUE TITLE
[Feature Request] VK_LOCK_MY_MODIFIER_INCREMENT and VK_LOCK_MY_MODIFIER_DECREMENT

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#386]
I found this in the examples but I don't think it's related:
https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/samples/virtual_keycodes/vk_lock.xml#L148

Example use case in **NOTE** section [here](https://github.com/tekezo/Karabiner/issues/382#issuecomment-94286502).

**Comment by tekezo** [comment]
These are unnecessary for that purpose.
