### ISSUE TITLE
For japanese keyboard EISUU with df xcvb to 567890 return some error in Dvorak 

### ISSUE THREAD

**Issue by ForrestAlfred** [tekezo/Karabiner#388]
![2015-04-25 6 09 57](https://cloud.githubusercontent.com/assets/8122371/7332561/461a1a5a-eb77-11e4-9f78-881f431e35c9.png)
EISUU with                       w      e      r
                                         s  

works OK:                        !        "      # 
                                        $ 
 But with                                   d       f       
                                                 x       c       v      b
gets wrong :                            Q      W 
                                                A      S       Z       X 
I'm confuzzed.

**Comment by tekezo** [comment]
#389
