### ISSUE TITLE
For japanese keyboard EISUU with DF-XCVB to 56-7890 return some error in Dvorak 

### ISSUE THREAD

**Issue by ForrestAlfred** [tekezo/Karabiner#389]
![2015-04-25 6 09 57](https://cloud.githubusercontent.com/assets/8122371/7332561/461a1a5a-eb77-11e4-9f78-881f431e35c9.png)
![2015-04-25 6 58 47](https://cloud.githubusercontent.com/assets/8122371/7332663/2dbf7094-eb7d-11e4-8b1b-a636c2a006cf.png)

I'm totally confuzzed. Could you help me?

**Comment by ForrestAlfred** [comment]
![2015-04-25 7 05 16](https://cloud.githubusercontent.com/assets/8122371/7332701/7dfdb06e-eb7f-11e4-9997-d84c9f35395f.png)
![2015-04-25 7 15 11](https://cloud.githubusercontent.com/assets/8122371/7332702/7e756226-eb7f-11e4-9f85-9e4620e98aef.png)

**Comment by ForrestAlfred** [comment]
By add it manually. it works.

**Comment by ForrestAlfred** [comment]
![2015-04-25 8 21 18](https://cloud.githubusercontent.com/assets/8122371/7332857/e7c3cd7c-eb88-11e4-9691-a4f329eb8021.png)
I found the conflict.But how it conflict?

**Comment by tekezo** [comment]
Do you enable other settings?

Karabiner applies only the first matched <autogen>.
So, if you change these keys by other settings, the setting might not work.
https://pqrs.org/osx/karabiner/xml.html.en#order

**Comment by ForrestAlfred** [comment]
THKs

**Comment by ForrestAlfred** [comment]
I does use Workman layout now.
