### ISSUE TITLE
Configuring Logitech Windows Keyboard

### ISSUE THREAD

**Issue by moazam1** [tekezo/Karabiner#391]
Thanks for making a great utility.

I am using logitech k750 windows keyboard http://www.logitech.com/en-gb/product/k750-keyboard UK layout.

Some of the keys are not mapped correctly i.e. @ key displays " and vice versa. F1, f2, etc are also not working. I am wondering if you have xml file that can change this keyboard layout?

**Comment by tekezo** [comment]
Does "Change Keyboard Type in System Preferences > Keyboard" correct your keys?

![screen shot 2015-04-27 at 6 35 29 pm](https://cloud.githubusercontent.com/assets/659178/7345055/575b093c-ed0c-11e4-9b9b-13f6372110ca.png)

Enable "Change F1..F19 Keys ... > Change F1..F19 Key > F1..F12 to Functional Keys..." in Karabiner for f1,f2 keys.

**Comment by moazam1** [comment]
@tekezo Thanks for the reply. Mac is not recognizing keyboard. I have set it to European keyboard. I can't seem to find my keyboard layout in system preferences.

![screen capture 2](https://cloud.githubusercontent.com/assets/5168122/7348045/f6bc3a54-ece5-11e4-91fa-c5f009bd567f.png)

I have changed f1, f2, etc keys but they are still not working. I am just hearing a dumb sound when I press those keys.
![screen shot 2015-04-27 at 1 57 43 pm](https://cloud.githubusercontent.com/assets/5168122/7348059/196d4c14-ece6-11e4-8c47-d31b3686c0aa.png)

Thanks for your help.

**Comment by tekezo** [comment]
Are you using correct input source? (I guess you should use British PC input source.)

And what events are shown in EventViewer when you press f1 key?
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by moazam1** [comment]
My input source event viewer shows: com.apple.keylayout.British. 

And here is copy log from event viewer:

    eventType:keyDown         code:0x7a       name:F1              flags:Fn                                  misc:KeyCode::F1	characters:    
    eventType:keyUp           code:0x7a       name:F1              flags:Fn                                 misc:KeyCode::F1	characters:    
    eventType:keyDown         code:0x78       name:F2              flags:Fn                                 misc:KeyCode::F2	characters:    
    eventType:keyUp           code:0x78       name:F2              flags:Fn                                 misc:KeyCode::F2	characters:    
    eventType:keyDown         code:0x63       name:F3              flags:Fn                                 misc:KeyCode::F3	characters:    
    eventType:keyUp           code:0x63       name:F3              flags:Fn                                 misc:KeyCode::F3	characters:

**Comment by tekezo** [comment]
Thank you for information.

For F1,F2 keys, you enabled wrong settings.
Please enable "F1,F2 to Brightness Adjust". (You enabled reverse settings.)

For @,", do you want to input @ by shift-2?
If so, how about using U.S. input source?
