### ISSUE TITLE
Slow keyUp response when mapping to multiple keys with modifier

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#392]
Trying to mimick Sublime's superb `OPTION+UP/DOWN` movements. Example config:
```xml
<autogen>
	__KeyToKey__ KeyCode::CURSOR_DOWN, ModifierFlag::OPTION_L, 
	KeyCode::CURSOR_DOWN, 
	KeyCode::CURSOR_RIGHT, ModifierFlag::COMMAND_L,
</autogen>
```
Now, when key repeat sets in and I release the key, I always get a few more repeats. It works fine when I remove `ModifierFlag::COMMAND_L`.

**Comment by tekezo** [comment]
Karabiner add a wait around modifier key events for avoid key order confusion in apps such as virtual machine.
(You can adjust it in "KeyRepeat tab > Advanced Configurations > Generic > Wait before and after a modifier key event".)

Please decrease wait or move command-right arrow into after keyup.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::CURSOR_DOWN, ModifierFlag::OPTION_L, 
      KeyCode::CURSOR_DOWN,

      Option::KEYTOKEY_AFTER_KEYUP,
      KeyCode::CURSOR_RIGHT, ModifierFlag::COMMAND_L,
    </autogen>
```

**Comment by nkgm** [comment]
I've adjusted `Wait before and after a modifier key event` to `0ms` and it works great. Any setbacks in that?

**Comment by tekezo** [comment]
Almost all apps work fine with `0ms`.
That change might cause issue in some apps which read raw key events.
(eg: virtual machine, adobe apps.)
