### ISSUE TITLE
How to map SHIFT_R to CURSOR_UP while maintain shift function when press with other key?

### ISSUE THREAD

**Issue by puttin** [tekezo/Karabiner#395]
I have tried with multi `__KeyToKey__`, `__KeyOverlaidModifier__` and `__HoldingKeyToKey__` or `VK_MODIFIER_EXTRA1` but all not works as expected.

**Comment by tekezo** [comment]
How about this autogen?

```xml
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_R,
      KeyCode::SHIFT_R,
      KeyCode::CURSOR_UP,
    </autogen>
```

**Comment by puttin** [comment]
I have tried this autogen when I'm trying. 
It has some problems:
1. Press Shift_r will also produce a shift_r with an up.
2. Long press shift_r will not produce repeat up

**Comment by tekezo** [comment]
I see. Use this autogen:

```xml
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_R,
      KeyCode::VK_LAZY_SHIFT_R,
      KeyCode::CURSOR_UP,

      Option::KEYOVERLAIDMODIFIER_REPEAT
    </autogen>
```

**Comment by puttin** [comment]
Works like a charm. You are genius!

So here are another questions:

VK_LAZY_SHIFT_R and KEYOVERLAIDMODIFIER_REPEAT.

I will try to understand by myself.
Hope we can write some awesome wiki about these stuff.

**Comment by tekezo** [comment]
I see.
