### ISSUE TITLE
"Open private.xml" doesn't work

### ISSUE THREAD

**Issue by jmuheim** [tekezo/Karabiner#397]
Clicking on the button doesn't do anything anymore. Got the newest version.

For the time being: where can I find the `private.xml` file?

**Comment by tekezo** [comment]
`~/Library/Application Support/Karabiner/private.xml`

I cannot reproduce this issue.
Please tell me your environment information and show the system.log.
https://pqrs.org/osx/karabiner/contact.html.en
https://pqrs.org/osx/karabiner/faq.html.en
