### ISSUE TITLE
PC USER: Home/End keys on numeric keyboard (Microsoft)

### ISSUE THREAD

**Issue by theflashback** [tekezo/Karabiner#398]
Please make  HOME/END keys work as beginning of line/end of line on Microsoft keyboard (NUMERIC portion of the keyboard) when NUMLOCK is off

**Comment by tekezo** [comment]
Use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.keypadnumlock_pcstyle/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by theflashback** [comment]
This worked as a charm – but I now lost the Control+INSERT/Shift+INSERT functionality on the numpad as copy/paste …. Is there any way to bring it back?

Serge

**Comment by tekezo** [comment]
I see. I've updated private.xml. How about it?
https://github.com/tekezo/Files/blob/master/Karabiner/private.keypadnumlock_pcstyle/private.xml

**Comment by theflashback** [comment]
Works as a charm!

Love you guys!

Serge

________________________________
