### ISSUE TITLE
Scrolling with PgUp / PgDown using numeric keyboard does not move the cursor

### ISSUE THREAD

**Issue by theflashback** [tekezo/Karabiner#400]
When scrolling using PgUp/PgDown keys on numeric keyboard, the scrolling works fine but the cursor does not move. It needs to move to the new position accordingly.

Thanks!

**Comment by tekezo** [comment]
This is OS X behavior and it does not change from Karabiner.
However, most apps supports option-PgUp/PgDown to scroll with cursor.

#398 changes keypad pgup/pgdown to option-PgUp/PgDown.
