### ISSUE TITLE
Status messages as such CAPS/NUMLOCK modes on/off should disappear after a few seconds

### ISSUE THREAD

**Issue by theflashback** [tekezo/Karabiner#401]
Currently all status messages are on the screen at all times. They should really go away after X number of seconds as they take up real estate.

**Comment by theflashback** [comment]
Alternatevely, the status message can e displayed right next to Karabiner system icon.

**Comment by tekezo** [comment]
There is not such options, however how about the following configuration in "Status Message" tab in Preferences?

* Type: Edge of Screen
* Color: Blue
* Position: Top left (Actually, color bar will be shown in top edge.)

**Comment by weiweihuanghuang** [comment]
agree
