### ISSUE TITLE
__KeyOverlaidModifier__ + Mouse click

### ISSUE THREAD

**Issue by aymericbeaumet** [tekezo/Karabiner#402]
I remapped the left and right commands so that when pressed alone they respectively insert `{` and `}`.

```xml
    <item>
      <identifier>remap.modifiers.commands_to_commands_curly_braces</identifier>
      <name>Commands to commands / curly braces</name>
      <autogen>
        __KeyOverlaidModifier__ KeyCode::COMMAND_L, ModifierFlag::COMMAND_L | ModifierFlag::NONE,
        KeyCode::VK_LAZY_COMMAND_L,
        KeyCode::BRACKET_LEFT, ModifierFlag::SHIFT_L,
      </autogen>
      <autogen>
        __KeyOverlaidModifier__ KeyCode::COMMAND_R, ModifierFlag::COMMAND_R | ModifierFlag::NONE,
        KeyCode::VK_LAZY_COMMAND_R,
        KeyCode::BRACKET_RIGHT, ModifierFlag::SHIFT_R,
      </autogen>
    </item>
```

But now I am unable (unless I explicitly define a new `<autogen>`) to use `Cmd + Click`. I though Karabiner would handle mouse actions as keystrokes (e.g.: `Cmd + A` works), but it doesn't seem to.

How to support mouse events with this?

**Comment by aymericbeaumet** [comment]
![image](https://cloud.githubusercontent.com/assets/569243/7582526/cc730ad4-f88e-11e4-95c2-a1ca4c9486ba.png)

**Comment by tekezo** [comment]
I cannot reproduce this issue on my machine.
Could you show me your enabled settings?
(Screen shot of Preferences with "show enabled only" checkbox.)

**Comment by aymericbeaumet** [comment]
Just enabling this item doesn't reproduce the issue.

The problem was elsewhere...

![image](https://cloud.githubusercontent.com/assets/569243/7610128/bdc0f13a-f97a-11e4-8789-7bebc0b0f786.png)
