### ISSUE TITLE
The Karabiner cannot catch the Keyboard Event of a bluetooth keyboard

### ISSUE THREAD

**Issue by ylorn** [tekezo/Karabiner#403]
Here is the thing. I use my HHKB Professional 2 Type-S as my external keyboard. It usually requires a USB cable to connect to my mac, and it works great with Karabiner. Recently, I finally got tired of the cable, because it is extremely inconvenient to use for I have to connect it every time. So I bought an alt controller board from [hasu](https://geekhack.org/index.php?topic=71517.0). This controller board brings bluetooth compatibility to the HHKB, which is great because I can finally use my keyboard freely. 

But problems come with it too. When in bluetooth mode, it can not work with the Karabiner! 
Here is the details. To make it as simple as possible, I only enable two items in Karabiner as the image shown below:
![Karabiner Preference Screen Shot](http://cl.ly/aypA/Screen%20Shot%202015-05-14%20at%208.18.04%20PM.png)
What do these two items do is basically switch input source between English and Chinese by simulating Command + Space to select the previous input method when tapping (press and release quickly) the right Shift key, but the right shift key remains as the modifier key when you press (hold without releasing) it. Here is the detailed configuration of these two items: https://gist.github.com/ylorn/43b589daf6d621a7fc47

This configuration works fine with Apple Internal Keyboard and HHKB USB mode, but not with the HHKB Bluetooth mode. Let me show you the problem.

- First, the Apple Internal Keyboard. This is what it looks like in the Device tab of EventViewer:
![Apple Internal KeyBoard Device Tab Screen Shot](http://cl.ly/azON/download/Screen%20Shot%202015-05-14%20at%208.37.28%20PM.png)
This is what it looks like in the Main tab of EventViewer when I **tap** (press and release quickly) the *right shift* key:
![Apple Internal Keyboard Main Tab Screen Shot](http://cl.ly/ayuV/Screen%20Shot%202015-05-14%20at%208.41.38%20PM.png)
This is what debug mode responses when I **tap** (press and release quickly) the *right shift* key (to see if it can receive the keyboard event properly):
![Apple Internal Keyboard Debug Mode Response](http://cl.ly/azLn/Screen%20Shot%202015-05-14%20at%208.53.56%20PM.png)
To be specific, it is the following lines:
```
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80020004, key 0x003c, kbdType  43, repeat = 0
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00020004, key 0x003c, kbdType  43, repeat = 0
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x003c, kbdType  43, repeat = 0
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003c, kbdType  43, repeat = 0
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00100008, key 0x0037, kbdType  43, repeat = 0
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 10, flags 0x00100008, key 0x0031, kbdType  43, repeat = 0
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 11, flags 0x00100008, key 0x0031, kbdType  43, repeat = 0
May 14 20:53:18 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x0037, kbdType  43, repeat = 0
```

- Second, the HHKB KeyBoard with USB Mode (connect HHKB to the mac via an USB cable). This is what it looks like in the Device tab of EventViewer:
![HHKB KeyBoard USB Device Tab Screen Shot](http://cl.ly/axVl/Screen%20Shot%202015-05-12%20at%206.37.29%20PM.png)
This is what it looks like in the Main tab of EventViewer when I **tap** (press and release quickly) the *right shift* key:
![HHKB KeyBoard USB Main Tab Screen Shot](http://cl.ly/az3y/Screen%20Shot%202015-05-14%20at%209.03.30%20PM.png)
This is what debug mode responses when I **tap** (press and release quickly) the *right shift* key (to see if it can receive the keyboard event properly):
![HHKB KeyBoard USB Debug Mode Response](http://cl.ly/az2t/Screen%20Shot%202015-05-14%20at%209.04.54%20PM.png)
To be specific, it is the following lines:
```
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80020004, key 0x003c, kbdType  40, repeat = 0
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00020004, key 0x003c, kbdType  40, repeat = 0
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x003c, kbdType  40, repeat = 0
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003c, kbdType  40, repeat = 0
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00100008, key 0x0037, kbdType  40, repeat = 0
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 10, flags 0x00100008, key 0x0031, kbdType  40, repeat = 0
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 11, flags 0x00100008, key 0x0031, kbdType  40, repeat = 0
May 14 21:04:32 Troys-MacBook-Pro kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x0037, kbdType  40, repeat = 0
``` 

- Finally, the HHKB Keyboard with Bluetooth mode (connect HHKB to mac via Bluetooth). This is what it looks like in the Device tab of EventViewer:
![HHKB KeyBoard BT Device Tab Screen Shot](http://cl.ly/axIY/Screen%20Shot%202015-05-12%20at%206.37.50%20PM.png)
This is what it looks like in the Main tab of EventViewer when I **tap** (press and release quickly) the *right shift* key:
![HHKB KeyBoard BT Main Tab Screen Shot](http://cl.ly/azLM/Screen%20Shot%202015-05-14%20at%209.10.45%20PM.png)
This is what debug mode responses when I **tap** (press and release quickly) the *right shift* key (to see if it can receive the keyboard event properly):
![HHKB KeyBoard BT Debug Mode Response](http://cl.ly/azIS/Screen%20Shot%202015-05-14%20at%209.13.13%20PM.png)

**As you can see, from `May 14 21:12:09`, I have been keeping hitting the *right shit* key, but Karabiner has received nothing.**

Would you please help me to figure out what is wrong? I will be really appreciate if you can give me some hint to fix this, because I can't live without Karabiner!

Thanks!

ylorn

**Comment by tekezo** [comment]
Your bluetooth device's vendorId and productID is zero.
Karabiner ignores that keyboard device in order to avoid system crash from such invalid devices.
Please enable this setting.

![screen shot 2015-05-16 at 10 16 55 am](https://cloud.githubusercontent.com/assets/659178/7664132/18893aaa-fbb5-11e4-837f-532c1ce7f9cc.png)

**Comment by ylorn** [comment]
Thanks! This saves my day!
