### ISSUE TITLE
Use remapped ESC to toggle ubiquitous vi mode

### ISSUE THREAD

**Issue by HaoyangFeng** [tekezo/Karabiner#404]
Ubiquitous vi mode can be toggled using the Escape key.
However, with ```CONTROL_L to CONTROL_L (CONTROL_L only to send ESCAPE)``` enabled, hitting CONTROL_L by itself doesn't toggle ubiquitous vi mode.

**Comment by tekezo** [comment]
You should make new setting.
Please use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.ubiq_toggle_control/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml
