### ISSUE TITLE
Backslash(\) to Option_L + 3 (Hash #) has problems in Terminal with Option -> meta passthrough

### ISSUE THREAD

**Issue by johndrinkwater** [tekezo/Karabiner#406]
OSX's stock Terminal has a toggle for "Use option as meta key", I use this so I can stick with the same key config in tmux & irssi on my server between client systems.
With # remapped to a new key, it is impossible(?) to pass this character to the application running in ssh, as it only gets meta+3 sent to it.

I had a look at making a private.xml tweak for this, but I appear stumped on how I could output a custom unicode character? I see #91 brought it up before, but that is closed.
Other options in karabiner for "hashtag" are using shift - which outputs £, as this is a UK keyboard :)

**Comment by tekezo** [comment]
There is not a easy way to do it.
There are two workarounds.

# Use U.S. input source together.

Karabiner can change input source by shortcut.
So, change input source that is able to input # directory like U.S. input source.
This private.xml allows you to input # by backslash key in Terminal.

https://github.com/tekezo/Files/blob/master/Karabiner/private.british_backslash_to_hash/private.xml

# Make your own keylayout

You can input # by backslash key in British - PC input source.
You can also make your own keylayout based British input source.
Use Ukelele to make new keylayout.

Ukelele
http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele
