### ISSUE TITLE
Japanese keyboard, change * to ' 

### ISSUE THREAD

**Issue by Trinley** [tekezo/Karabiner#408]
The apostrophe is in a weird place. Could someone generate the text for a switch between 
: to '  ?

I want it to produce ' instead, which right now gets done by 
shift + 7

Thank you!!

Also, does anyone know how to make the ¥ button work as a second delete button? I press that accidentally all the time and I never use the ¥ symbol, it'd be great if pressing that key would make it delete instead.

**Comment by tekezo** [comment]
How about "Change Keyboard Layout > Set a keyboard type to ANSI on JIS and ISO keyboard" in prepared settings?

And about ¥, please use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.jis_yen_to_delete/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by Trinley** [comment]
You're a life saver! Thank you, now I don't have to look at my keyboard when I need to type a symbol, I just hit the keys using my muscle memory! There are some keys I don't use that often that I want to change back, but I'll putz around and tinker. I think it'd be helpful to know how to customize keys to suit my needs anyways. Thank you Tekezo! I appreciate you taking the time.
