### ISSUE TITLE
"mouse key -> scroll -> initial wait, repeat wait" don't affect horizontal scrolling

### ISSUE THREAD

**Issue by andreasgrimm** [tekezo/Karabiner#409]
when I'm scrolling left or right with my scroll wheel (tilting left/right and holding), there's this slight (feels like 500ms or so) delay after the first scroll action until the scrolling gets repeated. the above mentioned settings don't seem to affect this delay time.

are these settings meant to affect the horizontal scrolling behavior as well?

**Comment by tekezo** [comment]
That setting is effective only in mouse keys (mouse operation by keyboards) functions in Karabiner.

What settings you are using in Karabiner?

**Comment by andreasgrimm** [comment]
Ok, got it! My fault then, I guess I didn't realize what "mousekey" actually means. The feature I'm describing would then have to go under "Pointing Device" .. makes sense ;)

Currently I'm using (on a US Keyboard Layout)
- Reverse Vertial Scrolling
- Shift + Delete to Forward Delete (if no other modifiers pressed)
- Section to Backquote

btw: I'm also using "USB Overdrive" to completely get rid of the mouse pointer accerleration. In there you can remap Pointing Device buttons, but unfortunately regarding customizing you can't by far go as granular as with Karabiner ;)
