### ISSUE TITLE
Maximum Threshold For Shift Without Modifiers

### ISSUE THREAD

**Issue by codeanpeace** [tekezo/Karabiner#410]
How could I modify the below to set a maximum threshold for sending escape when shift is typed without other modifiers?
Shift + modifiers = uppercase modifier
Tapping shift quickly = escape
Holding shift for a while before releasing = ignore or some other command
Another way of putting it is to only send escape if shift's keyup is within x milliseconds of its keydown. Thanks!

```
    <item>
      <name>Shift_L to Shift_L</name>
      <appendix>(+ When you type shift_L only without other modifiers, send Escape)</appendix>
      <identifier>remap.shiftL2shiftL_escape</identifier>
      <autogen>__KeyOverlaidModifier__ KeyCode::SHIFT_L, ModifierFlag::SHIFT_L | ModifierFlag::NONE, KeyCode::SHIFT_L, KeyCode::ESCAPE</autogen>
    </item>
```

**Comment by tekezo** [comment]
Adjust this value in Key Repeat tab:

![screen shot 2015-05-25 at 12 13 19 pm](https://cloud.githubusercontent.com/assets/659178/7791217/7786f442-02d7-11e5-92d7-631842563818.png)

**Comment by codeanpeace** [comment]
Thanks!
