### ISSUE TITLE
Binding right shift to L_Command only works for certain shortcuts

### ISSUE THREAD

**Issue by andrewschreiber** [tekezo/Karabiner#411]
Using 10.6 on OSX 10.10

When enabling this bind, all rshift + letter shortcuts work as expected (cmd + letter).
However rshift+lshift commands do not work for the following letters:
q w e r t y u i o
All other rshift+lshift + letter shortcuts work as expected (cmd + lshift + letter).

**Comment by tekezo** [comment]
I cannot reproduce this issue.

Please show the result of EventViewer when you press rshift+lshift+e.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

And show me your enabled settings. (Preferences with "show enabled only" checkbox.)

**Comment by andrewschreiber** [comment]
Here is rshift +lshift + e

eventType:keyMod          code:0x37       name:Command_L       flags:Cmd                                misc:KeyCode::COMMAND_L	characters:    
eventType:keyMod          code:0x38       name:Shift_L         flags:Shift Cmd                          misc:KeyCode::SHIFT_L	characters:    
eventType:keyMod          code:0x38       name:Shift_L         flags:Cmd                                misc:KeyCode::SHIFT_L	characters:    
eventType:keyMod          code:0x37       name:Command_L       flags:                                   misc:KeyCode::COMMAND_L	characters:    

and here is a picture of my enabled settings
![screen shot 2015-05-27 at 11 10 45 am](https://cloud.githubusercontent.com/assets/1892071/7843819/3074c8d2-0461-11e5-8315-8b51b9067db5.png)

**Comment by tekezo** [comment]
Thank you for information.

I guess that it is a 2-key rollover problem. (hardware limitation)
https://pqrs.org/osx/karabiner/faq.html.en#rollover

Please confirm whether `shift+e` event is fired by `rshift+lshift+e` without Karabiner setting.
If there is no output when you pressed `e` key with `rshift+lshift`, it's a 2-key rollover problem.
You should use another key combination.

**Comment by andrewschreiber** [comment]
Ah, the 2-key rollover! What an unexpected limitation! That must be it, as I am using a wireless apple keyboard currently.

Thanks for the help. Closing issue.
