### ISSUE TITLE
Ignore all JetBrains apps for PC Style Home / End / PageUp / PageDown

### ISSUE THREAD

**Issue by rayshan** [tekezo/Karabiner#412]
JetBrains has many IDE apps that are quite popular, not just IntelliJ, PhpStorm, RubyMine defined [here](https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/snippets/pcstyle_homeend_ignore_apps.xml). Could you please ignore the prefix `com.jetbrains`? That should cover all of them. Thanks!

Reference: https://www.jetbrains.com/products.html

**Comment by tekezo** [comment]
Thank you for feedback.

I've added com.jetbrains to ignore apps.
https://github.com/tekezo/Karabiner/commit/fda65bda5dd47a740775cb940763f97f45b4ab12

There is a limitation that we have to list "IntelliJ, PhpStorm,... others" at the moment.
I'll improve these rules in the next release or next next release.

**Comment by rayshan** [comment]
I'm really sorry, after testing `.57` and thinking about it, I think my understanding of how `block` works was wrong. And I believe the original code may have the wrong behavior as well.

What users would expect: if "Use PC Style Home/End/PageUp/PageDown" is enabled, these keys still send their original keycode in all `com.jetbrains.` apps. For example: Home sends Control+A, but still sends Home when in WebStorm.

**Comment by tekezo** [comment]
I see.
I've updated behavior at v10.6.58.
Please confirm the latest beta version.

**Comment by rayshan** [comment]
Thanks, confirmed working for home / end (at least in JetBrains WebStorm).
