### ISSUE TITLE
Add POST_FROM_EVENTS_AS_RAW to KEYTOKEY_AFTER_KEYUP

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#413]
Take this config for example:

```xml
<autogen>
	__KeyToKey__
	KeyCode::G, ModifierFlag::CONTROL_R,
	KeyCode::G, ModifierFlag::CONTROL_R,
	Option::KEYTOKEY_BEFORE_KEYDOWN, KeyCode::VK_LOCK_NKGM_IDEA_GOTO_FORCE_ON, 
	Option::KEYTOKEY_AFTER_KEYUP, KeyCode::RETURN, KeyCode::VK_LOCK_NKGM_IDEA_GOTO_FORCE_OFF,
</autogen>
```
`CONTROL_down+G_down`(opens dialog) -> (do some typing) -> `G_up`(sends `RETURN` to dialog)

It's all fine so far, however if `ESCAPE` is pressed in the meantime:

`CONTROL_down+G_down`(opens dialog) -> `ESCAPE`(dialog closes) -> `G_up`(dialog is not there, so `RETURN` is sent to the editor)

If the proposed option was supported, instead of `KeyCode::RETURN` I could use `KeyCode::VK_MODIFIER_NKGM_IDEA_GOTO_RETURN` and decide whether to send `RETURN` in another mapping.

**Comment by tekezo** [comment]
I would like to avoid recursive remapping in order to prevent from infinity loop.

(`__SimultaneousKeyPresses__` is an exception.
However `__SimultaneousKeyPresses__` is always applied before `__KeyToKey__`.
Therefore, there is not possibility to loop.)

I consider adding modifier flag specification into Option::KEYTOKEY_AFTER_KEYUP such as:

```
Option::KEYTOKEY_AFTER_KEYUP, ModifierFlag::NKGM_IDEA_GOTO,
KeyCode::RETURN, KeyCode::VK_LOCK_NKGM_IDEA_GOTO_FORCE_OFF,
```

**Comment by nkgm** [comment]
Thanks for the reply. Bit confused though... How would that solve the problem?

**Comment by tekezo** [comment]
Please upgrade to v10.6.61 and use these autogens:

```xml
    <autogen>
      __KeyToKey__
      KeyCode::G, ModifierFlag::CONTROL_R,
      KeyCode::G, ModifierFlag::CONTROL_R,
      Option::KEYTOKEY_BEFORE_KEYDOWN, KeyCode::VK_LOCK_NKGM_IDEA_GOTO_FORCE_ON,

      Option::KEYTOKEY_AFTER_KEYUP, ModifierFlag::NKGM_IDEA_GOTO,
      KeyCode::RETURN, KeyCode::VK_LOCK_NKGM_IDEA_GOTO_FORCE_OFF,

      Option::NOREPEAT,
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::ESCAPE, ModifierFlag::NKGM_IDEA_GOTO,
      KeyCode::ESCAPE,
      KeyCode::VK_LOCK_NKGM_IDEA_GOTO_FORCE_OFF,
    </autogen>
```

**Comment by nkgm** [comment]
Works great as usual. Thanks a lot!
