### ISSUE TITLE
Feature Request: Disable certain rules when in textfields.

### ISSUE THREAD

**Issue by mcourteaux** [tekezo/Karabiner#414]
I searched through the samples and documentation, but I couldn't find it: create a rule that only applies if you are not in a textfield. For example: I created a rule that lets me navigate in PDF's when opened in Apple's Preview in a vim way. However, when I want to search the PDF for some text, I can't type hjkl anymore, since these are mapped to the arrow keys. So I want to add to the rule that it only applies when i'm not in a typing environment.

Is it implemented already? If not, is this technically possible to do so?

**Comment by tekezo** [comment]
Use `<uielementrole_not>AXTextField, AXTextArea</uielementrole_not>`.

An example:
https://github.com/tekezo/Karabiner/blob/version_10.6.0/src/core/server/Resources/include/checkbox/hjkl_arrow.xml#L17-L33

**Comment by mcourteaux** [comment]
Brilliant, it works! Thanks. An easier to find reference would be nice or a little note in the documentation with the link to this sample. :)
