### ISSUE TITLE
Support for force click on new trackpads?

### ISSUE THREAD

**Issue by deprecated** [tekezo/Karabiner#416]
Are there any plans for supporting force click (and pressure sensitivity in general) on the new track pads?  With the latest (10.6.0) stable version of Karabiner, when I try a force click in the Mouse Area of the EventViewer it just seems to register as a mouseDragged event. 

Will

**Comment by tekezo** [comment]
Karabiner does not support multi touch actions and I guess the force click is one of multi touch actions.
(Unfortunately, I don't have devices that support force click.)

I hope that BetterTouchTool will support the force click.

**Comment by deprecated** [comment]
Thanks for the clarification, and for the pointer to BetterTouchTool - it seems that it already supports force click: http://blog.boastr.net/bettertouchtool-with-force-touch-trackpads/

I remember trying out BetterTouchTool several years ago, and finding it to be a bit unstable, but hopefully it has improved in the meantime.
