### ISSUE TITLE
Doesn't work under 10.11-beta1 (kernel extension wont load)

### ISSUE THREAD

**Issue by dmilith** [tekezo/Karabiner#419]

**Comment by tekezo** [comment]
Karabiner works in OS X 10.11.

I guess this issue is about Seil.
I've released Seil 11.2.0 that works in OS X 10.11. Please use it.
https://pqrs.org/osx/karabiner/seil.html.en

**Comment by aciampo** [comment]
Same problem with Karabiner 10.6 in 10.11 Beta (15A244d).

**Comment by tekezo** [comment]
OS X 10.11 (15A244d) has another problem.
See #450
