### ISSUE TITLE
Window names not visible in Event Viewer.

### ISSUE THREAD

**Issue by trusktr** [tekezo/Karabiner#420]
The Event Viewer doesn't show any window names. I wanted to try a `<windowname_only>` rule, but don't know the window name. (I can see the window name in the window's title bar, so I can try that)

**Comment by tekezo** [comment]
You have to allow AXNotifer to use accessibility features.
Please confirm System Preferences > Security & Privacy > Privacy > Accessibility.
https://pqrs.org/osx/karabiner/document.html.en#axnotifier

**Comment by trusktr** [comment]
@tekezo Sweet. Thanks. I missed that. Are `<only>` and `<windowname_only>` AND or OR?

**Comment by tekezo** [comment]
All filters are AND.

**Comment by trusktr** [comment]
@tekezo How can we do an OR?

For example, any of the apps OR any window with name?

```
    <block>
      <only>TERMINAL,SCREEN_SHARING, VI, REMOTEDESKTOPCONNECTION, EMACS, X11, VNC</only>
        <!-- OR? -->
      <windowname_only>Neovim-e</windowname_only>
      ...
    </block>
```

**Comment by tekezo** [comment]
You should make multiple blocks.

```xml
    <block>
      <only>TERMINAL,SCREEN_SHARING, VI, REMOTEDESKTOPCONNECTION, EMACS, X11, VNC</only>
      ...
    </block>

    <block>
      <windowname_only>Neovim-e</windowname_only>
      ...
    </block>
```

You can use replacementdef to put same contents into multiple places.
https://pqrs.org/osx/karabiner/xml.html.en#replacementdef

Using CDATA is useful.
https://github.com/tekezo/Karabiner/blob/version_10.6.0/src/core/server/Resources/replacementdef.xml#L59-L66

**Comment by trusktr** [comment]
Awesome, thanks so much!!

Here's my capslock to control for [Neovim-e](https://github.com/coolwanglu/neovim-e):

```xml
<?xml version="1.0"?>
<root>
  <windownamedef>
    <name>NEOVIM_E</name>
    <regex>Neovim-e</regex>
  </windownamedef>
  <replacementdef>
    <replacementname>APP_TO_CTRL</replacementname>
    <replacementvalue>__KeyToKey__ KeyCode::PC_APPLICATION, KeyCode::CONTROL_L</replacementvalue>
  </replacementdef>
  <item>
    <name>Application Key to Command_L (custom).</name>
    <appendix>(+ Application Key to Control_L in Terminal, Screen Sharing, MacVim,</appendix>
    <appendix>RDC, Emacs, X11, VNC, Neovim-e)</appendix>
    <identifier>private.remap.pc_application2commandL_controlL</identifier>
    <block>
      <only>TERMINAL,SCREEN_SHARING, VI, REMOTEDESKTOPCONNECTION, EMACS, X11, VNC</only>
      <autogen>{{ APP_TO_CTRL }}</autogen>
    </block>
    <block>
      <windowname_only>NEOVIM_E</windowname_only>
      <autogen>{{ APP_TO_CTRL }}</autogen>
    </block>
    <autogen>__KeyToKey__ KeyCode::PC_APPLICATION, KeyCode::COMMAND_L</autogen>
  </item>
</root>
```

:smile:
