### ISSUE TITLE
External wireless mac keyboard "home row numbers overlay" not working

### ISSUE THREAD

**Issue by alex-cory** [tekezo/Karabiner#422]
Everything works that I've tested however when I use one of my favorite keyboard hacks `home row numbers overlay,` it doesn't work.  On the EventViewer, without holding space it doesn't register the home row except for `;` and when holding space it doesn't register the home row except for `;`

Below is the output from the event viewer when pressing all the homerow including `;` first, then holding space and pressing all the homerow.
```
eventType:keyDown         code:0x29       name:;               flags:                                   misc:KeyCode::SEMICOLON	characters:;   
eventType:keyUp           code:0x29       name:;               flags:                                   misc:KeyCode::SEMICOLON	characters:;   
eventType:keyDown         code:0x1d       name:0               flags:                                   misc:KeyCode::KEY_0	characters:0   
eventType:keyUp           code:0x1d       name:0               flags:                                   misc:KeyCode::KEY_0	characters:0
```

I did test this using a plug in mac external keyboard and it did work, so that is what I'm using for now.

**Comment by tekezo** [comment]
Are you pressing three keys at the same time?
(For example, space, g and shift key)
If so, it might be "two-key rollover" limitation of wireless keyboard.

If not, please show me enabled settings. (screen shot of Preferences with "show enabled only")
