### ISSUE TITLE
Feature Request:   enable sticky or doubletap FN key?

### ISSUE THREAD

**Issue by jubilatious1** [tekezo/Karabiner#424]
Hello Tekezo! Thank you for such a wonderful program!

Laptop keyboard, choosing System Preferences::Keyboard the box  "use F1, F2, etc. keys as standard keys" meaning FN key has to be pressed to enable actions "pictorially" represented on those keys (e.g. brightness, Mission Control, Launchpad, volume, etc.).

Is there anyway to add an option in Karabiner to make the FN key sticky? Or for doubletap FN to followed by F1 through F12... to signal the pictorial actions?

Thank you!

**Comment by tekezo** [comment]
Please upgrade Karabiner to the latest beta version (v10.6.69) and use these settings with "use F1,F2, etc. keys as standard keys".

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

Note:
There are some similar settings with "Fn+F1,F2 to ...".
Enable proper settings.

![screen shot 2015-06-19 at 4 09 09 pm](https://cloud.githubusercontent.com/assets/659178/8248764/a6f3c24e-169d-11e5-889c-c6c314b0c234.png)

**Comment by jubilatious1** [comment]
Thank you! Works perfectly. 

Now F1-12 keys are dual purpose, and I can use one hand in either case. Just single or double tap FN to activate pictorial functions!
