### ISSUE TITLE
Karabiner not remapping keypress from Applescript keyCode() event

### ISSUE THREAD

**Issue by NickChristensen** [tekezo/Karabiner#425]
I'm having trouble triggering a keycode (in my case, `⌃+F19`) from applescript, and having Karabiner remap it. If I physically press `⌃+F19`, I get the expected result. I cannot manage to trigger that from applescript in any way.

Applescript (using JavaScript):
```js
Application('System Events').keyCode(0x50, {using: 'command down'});
```

`private.xml`:
```xml
<?xml version="1.0"?>
<root>
	<item>
		<name>⌃+F19 > ▶❚❚</name>
		<identifier>custom_to_play</identifier>
		<autogen>__KeyToKey__
			KeyCode::F19,
			ModifierFlag::CONTROL_L,
			ConsumerKeyCode::MUSIC_PLAY
		</autogen>
		<autogen>__KeyToKey__
			KeyCode::F19,
			ModifierFlag::CONTROL_R,
			ConsumerKeyCode::MUSIC_PLAY
		</autogen>
	</item>
</root>
```

Things I've tried:
- Replacing `KeyCode::F19` with `KeyCode::RawValue::0x50`. Same result.
- Removing the `ModifierFlag` from the xml, and the `{using: 'command down'}` from the applescript. This also gives the same result, without the control key.
- Verified that I'm using the keyCode() method correctly by sending an F11, which is set to Show Desktop in my system preferences, and works fine.

Any ideas?

**Comment by tekezo** [comment]
Karabiner modifies key events only from physical devices.

Please upgrade Karabiner to the latest beta version and use `post-hid-event` utility.

You can post MUSIC_PLAY key event by this shell command:

```
/Applications/Karabiner.app/Contents/Library/utilities/bin/post-hid-event NX_KEYTYPE_PLAY
```

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by NickChristensen** [comment]
:tada: This is exactly what I was looking for, but even simpler! Thank you! :tada:
