### ISSUE TITLE
 ScrollWheelToKey when FlipScrollWheel has been set

### ISSUE THREAD

**Issue by FrankAtHome** [tekezo/Karabiner#426]
I'm inverting the scroll wheel directions on my mouse only (not touchpad!) using the FlipScrollWheel commands. 

However, enabling the flip scroll wheel function prevents my custom ScrollWheelToKey mappings from working. How can I use both at the same time?

here is a snippet from my private.xml :
```
<item>
    <name>Microsoft Sculpt Mouse - Flip scroll wheel directions</name>
    <identifier>microsoft_flipwheel</identifier>
    <device_only>DeviceVendor::Microsoft, DeviceProduct::SculptComfortMouse</device_only>
    <autogen>__FlipScrollWheel__
        Option::FLIPSCROLLWHEEL_VERTICAL,
        Option::FLIPSCROLLWHEEL_HORIZONTAL
    </autogen>
</item>  
<item>
    <name>Modifier with scrollwheel to cycle tabs</name>
    <identifier>modifiedscrollwheel</name>
    <device_only>DeviceVendor::Microsoft, DeviceProduct::SculptComfortMouse</device_only>
    <autogen>__ScrollWheelToKey__
        ScrollWheel::UP, ModifierFlag::FN | ModifierFlag::NONE,
        KeyCode::BRACKET_LEFT, ModifierFlag::SHIFT_L, ModifierFlag::COMMAND_L
    </autogen>
    <autogen>__ScrollWheelToKey__
        ScrollWheel::DOWN, ModifierFlag::FN | ModifierFlag::NONE,
        KeyCode::BRACKET_RIGHT, ModifierFlag::SHIFT_L, ModifierFlag::COMMAND_L
    </autogen>
  </item>
```

**Comment by tekezo** [comment]
Karabiner applies only the first matched <autogen>.
https://pqrs.org/osx/karabiner/xml.html.en#order

So, please swap items.

**Comment by FrankAtHome** [comment]
thanks, that fixes this issue. The Karabiner tool is awesome!

Another thing I noticed:
The modified scroll wheel behaviour (xml entries above) only works as long as I do not  move the mouse cursor while holding right-click. As soon as I move the mouse cursor even a tiny bit, the right-click menu comes up instead of the modified behaviour...

Would you be able to suggest a method of achieving tolerance to moving the cursor while holding the mouse button that acts as a modifier for the scroll-wheel ?
Ideally, the right-click menu should not appear at all after triggering any action for which the button acts as modifier (i.e. right-click scroll wheel action). 
Instead, the right-click menu should only appear when right-clicking and then releasing the button again, without having performed any action for which the button acts as modifier.

Is the behaviour described above possible to configure with karabiner?

**Comment by tekezo** [comment]
Thank you for feedback.
It seems a bug.
Please wait for a while.

**Comment by tekezo** [comment]
I've fixed the `__KeyOverlaidModifier__`  issue at the latest beta version. (v10.6.70)

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by FrankAtHome** [comment]
thanks, it's working for me now!

**Comment by FrankAtHome** [comment]
actually, I spoke too soon.
Using the following code now deactivates the 'normal' (os-built-in) left-click drag behaviour (e.g. drag window, etc.)
````
  <modifierdef>LEFTCLICK</modifierdef>
    <autogen>__KeyOverlaidModifier__
        PointingButton::LEFT, ModifierFlag::NONE,
        KeyCode::VK_MODIFIER_LEFTCLICK,
        PointingButton::LEFT,
    </autogen>
```
Is that expected behaviour? If yes, how can I get the custom modifier for left-click in addition to normal left mouse button behaviour?

**Comment by tekezo** [comment]
That is expected. Please use this autogen.

```xml
    <autogen>
      __KeyToKey__
      PointingButton::LEFT, ModifierFlag::NONE,
      PointingButton::LEFT, ModifierFlag::LEFTCLICK,
    </autogen>
```

**Comment by FrankAtHome** [comment]
Great! all my questions have been answered; Karabiner is truly a marvel!
