### ISSUE TITLE
Slash to backslash

### ISSUE THREAD

**Issue by mmakarious** [tekezo/Karabiner#427]
Hello, my question mark aka slash button is no longer working, and because of this I wanted to switch it with the backslash key. 

However, due to the fact that my slash key is not working, as I previously stated, it is proving to be quite tedious to try and add the keytokey code in the private.xml texts.

Any advice (question mark), :')

**Comment by tekezo** [comment]
Please use this private.xml.
https://github.com/tekezo/Files/blob/master/Karabiner/private.backslash_to_slash/private.xml
