### ISSUE TITLE
Sticky virtual modifier

### ISSUE THREAD

**Issue by sypl** [tekezo/Karabiner#429]
I use this setting to get a sticky shift [https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/commons/sticky_modifiers/SHIFT_L.xml], which is awesome. I also however have some other self-defined modifiers for getting to some characters. Let's call that modifier MOD. I've been trying to find some way to get MOD to behave in a sticky fashion but haven't been able to. Problem seems to be that MOD doesn't send a keycode by itself on tap. Is there any workaround for this?

**Comment by tekezo** [comment]
You can use sticky modifier by KeyCode::VK_STICKY_MOD.
https://pqrs.org/osx/karabiner/xml.html.en#modifier

**Comment by sypl** [comment]
Thanks for the reply. I see now, and got it working, but the behaviour seems to differ from the shift sticky. It's a one-time thing, which prevents me holding down MOD and typing several characters in that layer.

Basically, given I declare this modifier: `<modifierdef>SOMEMOD</modifierdef>`

I have to make a choice between these two functionalities:
`<autogen>
    __KeyToKey__
    KeyCode::COMMAND_L,
    KeyCode::VK_MODIFIER_SOMEMOD
</autogen>`

`<autogen>
    __KeyToKey__
    KeyCode::COMMAND_L,
    KeyCode::VK_STICKY_SOMEMOD
</autogen>`

First one acts like a held shift, the other acts as a one-time tap activation. Is there any way to combine the two?

**Comment by sypl** [comment]
Also tried this, which wasn't successful.

`<autogen>
        __KeyOverlaidModifier__
        KeyCode::VK_MODIFIER_CHARACTER,
        KeyCode::VK_MODIFIER_CHARACTER,
        KeyCode::VK_STICKY_CHARACTER_FORCE_ON,
        KeyCode::VK_STICKY_CHARACTER,
    </autogen>`

**Comment by tekezo** [comment]
You should use this autogen:

```xml
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::COMMAND_L,
      KeyCode::VK_MODIFIER_CHARACTER,
      KeyCode::VK_STICKY_ACTIVE_MODIFIERS_FORCE_ON,
      KeyCode::VK_STICKY_CHARACTER,
    </autogen>
```

**Comment by sypl** [comment]
Oh wow, that works perfectly. Thank you!

Is the "Key overlaid modifier > timeout" meant to release the sticky after a set time? That's not working for me.

**Comment by tekezo** [comment]
`__KeyOverlaidModifier__` does not send key events even if you press the target key alone when you press and hold the target key. The timeout set the threshold.

For example, if timeout is 1000ms, sticky modifier will not be sent when you press and hold the left command key while 1 second.
