### ISSUE TITLE
Compatibility with BetterTouchTool

### ISSUE THREAD

**Issue by InsomniacSoftware** [tekezo/Karabiner#430]
Along with Karabiner, I also am using [BetterTouchTool](http://www.boastr.de/) to customize my system.  I use BTT mostly for making finger taps on my Trackpad into actions (for example, a single finger tap at the top of the Trackpad will mute/unmute the system audio)

BTT can't do some actions I want :frowning: but Karabiner can :smile:.  However, Karabiner doesn't have the ability read the taps on a Trackpad :cry:. **[1]**

My idea was to configure BTT's action to do something simple, like send `F16` which doesn't exist on my keyboard, and have Karabiner react to the `F16` keypress but it is not able to do this.

I see the `F16` action in the Karabiner EventViewer but the main Karabiner app is not reacting to the BTT actions/output.  Is it possible to have Karabiner receive the BTT output/react on BTT's actions?

For testing, (using `p` instead of `F16` since I could test that key)
* In my private.xml file, I have `<autogen>__KeyToKey__ KeyCode::P, KeyCode::K</autogen>`
* I press the `p` key on my keyboard, I get the letter `k`, so Karabiner is working properly :+1:
* In BTT I have configured the Single Finger Tap Top Middle to send the `p` key.
* In any application, when I tap the top of the Trackpad, I get the letter `p` :thumbsdown:
* Even in Karabiner Settings app and the EventViewer, when I tap, I get the letter `p`. :thumbsdown:

eventType | code | name | flags | misc
--------- | ---- | ---- | ---- | ----
eventType:keyDown | code:0x23 | name:p | flags: | misc:KeyCode::P	characters:p
eventType:keyUp | code:0x23 | name:p | flags: | misc:KeyCode::P	characters:p

Thanks for looking into this

**[1]**: Have you thought about passing trackpad touch detection to the user?  If Karabiner did, I could probably get rid of BTT.  I see that the multi-touch extension does this (the live view in the Area section) but I don't see a way to access the info (position and number of touches).

**Comment by tekezo** [comment]
Karabiner modifies input events from only connected devices.
Therefore, you cannot change events from BTT by Karabiner.

What's action you want to do that BTT can't do?

**Comment by karas1999** [comment]
Hi tekezo, I have the save wish as InsomniacSoftware. Here is why I want this for your consideration. Basically I want to use Karabiner and BTT together to redefine the Drag in Macbook. You know there are two drag method now, 3 finger drag or double-tap drag, but they both have limitations. 3 finger gestures are so useful that I'd rather define these gestures for other features like change tabs in Safari than drag. The double-tap drag, if enabled, will cause a 0.3 second delay for the normal single tap, this is not acceptable for me. 
With Karabiner, I'm so glad that I can redefine the drag feature. I remapped the FN key to VK_MOUSEKEY_LOCK_BUTTON_LEFT, so I can press FN to start dragging and press again to release. But if I can remap this key to the track pad itself, that would be much more greater. I've tried map VK_MOUSEKEY_BUTTON_LEFT to VK_MOUSEKEY_LOCK_BUTTON_LEFT, I thought I could just "Click" the track pad to start dragging and "Click" again to release, but sadly it doesn't work. 

Hope that you can consider this.

**Comment by tekezo** [comment]
This private.xml adds a setting that changes click to click lock.
https://github.com/tekezo/Files/blob/master/Karabiner/private.trackpad_click_to_lock_click/private.xml

But, you have to double click to perform normal single click. Is it right?

**Comment by karas1999** [comment]
Hi tekezo,
Thank you very much for provide me such a good method. This is not exactly what I want because it will change the very important single click. But it let me know that I can use the pointing button to remap the trackpad. So what I did is remapped the RIGHT key, not the LEFT key, like this:
1. Use the BTT to set tip-tab right to RIGHT key instead of the normal two-finger tap. This is very simple to use. 
2. Use Karabiner to remap the POINTBUTTON::RIGHT to VK_MOUSEKEY_LOCK_BUTTON_LEFT and done. 
Now I can use two-finger tap to start dragging, and then two-finger tap again to release. And if I want to use the right click, just use tip-tap right. Because BTT don't work with karabiner, it won't be changed to the lock left key. 
I think this is almost the best solution I can found now. Good enough for me. 
What will be better is that if we can change the "Left Click" to drag lock, and keep "Left tap" as normal single click. You know Mac trackpad you can single "tap", and single "Click".These are two different gestures but in OS X are all used as normal single click. What a waste. But I couldn't find out the code number for "Left Tab" or "Left Click". If I use POINTBUTTON::LEFT, it just match both. 
Anyway, thank you very much for giving me such a good idea. It solved the most disappointing Macbook experience.

**Comment by InsomniacSoftware** [comment]
@tekezo very sorry for not replying.  For some reason I didn't get the notification of the followups.

I also reported this issue to the BTT developer with the following.  Unfortunately he hasn't responded, yet.
> I have configured Command+Single Finger Tap (Top Left, Top Middle, Top Right) functions to the predefined Keyboard Keys for Previous, Play/Pause, Next actions. This works fine with VLC but does not work with Apple's media apps like iTunes and QuickTime Player.  If I remove the Command key requirement so it is only a tap, it works properly. This is the same with any modifier key.

BTT doesn't send the proper media actions when combined with a modifier key.  I think it is not removing the modifier so the app receives it as Command+Play/Pause.
Karabiner does send proper media actions with a modifier pressed but it can't detect the location/area of a trackpad tap.

So this is why I was trying to get BTT to send `F16` when I did a TipTap+Command and have Karabiner react to the `F16` and send `ConsumerKeyCode::MUSIC_PLAY`.  Make sense?  This is similar to using Seil to remap `CAPSLOCK` to an F-key that Karabiner can then react upon.

As mentioned above, I see that your Multi-Touch extension is able to detect a touch, including the location of the finger.  Is it possible to get access to this info so we can create custom actions based on finger tap locations?

Thanks

**Comment by tekezo** [comment]
@InsomniacSoftware
I see.

Karabiner has a command line utility `post-hid-event`.
It allows you to send consumer key event from shell.

For example, execute this shell command sends ConsumerKeyCode::MUSIC_PLAY.
```
/Applications/Karabiner.app/Contents/Library/utilities/bin/post-hid-event NX_KEYTYPE_PLAY
```

I've added `--flag` option into `post-hid-event` at v10.6.94. (the latest beta version)
You can send command-play by this shell command.
```
/Applications/Karabiner.app/Contents/Library/utilities/bin/post-hid-event --flag command NX_KEYTYPE_PLAY
```

You can configure execute this shell command in BTT.


How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by InsomniacSoftware** [comment]
Tekezo, thank you for the reply. I learn something new about Karabiner all the time!

Unfortunately this option did not directly work, again due to the Command key being held as part of the trigger.  When the Apple application receives the Play/Pause event, it does not happen if I'm still pressing the Command key.  For example, I can configure BTT to trigger the shell script with just a Tap instead of Command+Tap and it works. Same as before when using BTT's internal Play/Pause function.  Also, if I run `post-hid-event --flag command NX_KEYTYPE_PLAY`, it does not work.  Obviously this issue is due to Apple's applications being more strict and is not an issue with Karabiner.

I assume that Karabiner doesn't have the ability to block the physical keyboard Command key from being detected when using `post-hid-event`? (similar to using the `ModifierFlag::NONE` option)  If it could do that, you could add a `--flag none` option to negate any modifiers being pressed when using the utility.

As a workaround, I've configured BTT to execute the command of `sleep .25; /Applications/Karabiner.app/Contents/Library/utilities/bin/post-hid-event NX_KEYTYPE_PLAY`.  This gives me a quarter of a second to release the command key before the PlayPause event is sent.  Unless you have a better method to accomplish this task, the workaround will have to do.

P.S. When the `post-hid-event` utility runs, it always triggers the System Alert sound at the end.  Would it be possible for you to remove that function, or allow the user to disable it with a `--noalert` argument flag? 

Thanks

**Comment by tekezo** [comment]
> P.S. When the post-hid-event utility runs, it always triggers the System Alert sound at the end.

I cannot reproduce this problem. Does this issue happen in Guest User?
I guess another app plays alert sound via NX_KEYTYPE_PLAY.

**Comment by InsomniacSoftware** [comment]
It happens with all of the NX_KEYTYPE_ arguments of `post-hid-event`, not just the PLAY argument.

Strange that it does not happen under the Guest user or a new test user so it is something with my account.  It does it when used within Karabiner, BTT or manually run from a Terminal prompt.

No idea what under my profile would be causing this.  Any suggestions on where to start troubleshooting?

**Comment by tekezo** [comment]
> Any suggestions on where to start troubleshooting?

The easiest way to find the cause is close all apps and open them one by one.
If the alert still happen even if you close all apps, confirm your System Preferences especially Accessibility.

**Comment by InsomniacSoftware** [comment]
So after quitting everything and disabling extensions, it stopped the alerts after quitting TotalFinder.  But after starting it up again and after a reboot, the alerts are no longer playing.  It must have been some kind of temporary issue but it is working fine now.  
Thanks
