### ISSUE TITLE
Can fn + [esdf] be remapped on filco minila?

### ISSUE THREAD

**Issue by endrebak** [tekezo/Karabiner#432]
I know the fn keys can't be remapped but I'm wondering whether fn + [esdf]  - which means arrow keys on the minila - can be remapped or whether they always have to mean arrow keys?

I'd like fn+a to mean f1, fn+s to mean F2 etc.

**Comment by tekezo** [comment]
Use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.arrows_to_f1/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by endrebak** [comment]
Thanks.
