### ISSUE TITLE
Shift-insert (why "except in Terminal")?

### ISSUE THREAD

**Issue by mrjcleaver** [tekezo/Karabiner#433]
Hi - just curious - is there a way to define the scope so Shift-insert works in Terminal?

![karabiner 2015-07-05 08-35-30](https://cloud.githubusercontent.com/assets/59202/8511651/e5bec528-22f0-11e5-9ead-960aac581c4c.png)

Thanks,
   M.

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.terminal_shift_insert_to_paste/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by mrjcleaver** [comment]
Awesome, seems to work a treat, thanks :)

I'd expect a lot of people to want this, just because if switching back and forth between Linux and Mac this helps with consistency.

Cheers, M.

**Comment by tekezo** [comment]
Thank you for confirmation.
I've also adjusted the prepared settings at the latest beta version. (v10.6.78)

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates
