### ISSUE TITLE
Use Sparkle's guided install to avoid installer GUI

### ISSUE THREAD

**Issue by pornel** [tekezo/Karabiner#434]
Since 1.10 Sparkle supports ["guided installation", which hides Installer's GUI](https://github.com/sparkle-project/Sparkle/wiki/Package-Updates).

You can opt-in to this by naming the update file "karabiner.sparkle_guided.pkg"

**Comment by tekezo** [comment]
Thank you for suggestion!
It's very cool.
Karabiner uses guided installation since v10.6.77.
