### ISSUE TITLE
Unknown symbol : ApplicationType::PHPSTORM

### ISSUE THREAD

**Issue by hancc** [tekezo/Karabiner#441]
WHY

**Comment by hancc** [comment]
https://pqrs.org/osx/karabiner/xml.html.en#appdef

**Comment by tekezo** [comment]
Yes, you should define new app by appdef.
Or use the latest beta and use <only>PhpStorm</only>.
https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/appdef.xml#L575-L578

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates
