### ISSUE TITLE
How can I make CAPSLOCK a modifier key instead of a toggle?

### ISSUE THREAD

**Issue by jamesalmeida** [tekezo/Karabiner#442]
I'm trying to make it so some keys are different when I hold the Capslock key but go back to normal when I let go of the Capslock key. Right now, it seems to only act as a toggle that I have to press again to turn it off. Is it possible to make Capslock not a toggle but only change keys when I'm holding it down and turn off when I let go?

**Comment by tekezo** [comment]
Please follow this procedure:

1. Install Seil: https://pqrs.org/osx/karabiner/seil.html.en
2. Change caps lock key code to 80 in Seil. (Do not forget "No Action" configuration.)
3. Enable new setting by this private.xml: https://github.com/tekezo/Files/blob/master/Karabiner/private.sync_capslock_keydownup/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by jamesalmeida** [comment]
Thanks!
