### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by ishmael1851** [tekezo/Karabiner#443]
Not sure if this is caused by Karabiner, but since others have reported kernel crashes, I thought I'd add this report.

*** Panic Report ***
panic(cpu 6 caller 0xffffff8009a17cc2): Kernel trap at 0xffffff80099cf5a6, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffffbf4bd157e8, CR3: 0x000000045299d03d, CR4: 0x00000000001626e0
RAX: 0xffffff7f80000000, RBX: 0xffffff80276f0640, RCX: 0xffffff7f80000028, RDX: 0x0000003fcbd157c0
RSP: 0xffffff81f432b340, RBP: 0xffffff81f432b370, RSI: 0x000000004463b68e, RDI: 0xffffff800e3cdb90
R8:  0x0000000000020000, R9:  0x0000000000001400, R10: 0xffffff8033161f00, R11: 0x0000000004730000
R12: 0xffffff800e3cdb90, R13: 0xffffff800d34b000, R14: 0x000000000001e000, R15: 0xffffff802ef2b0f0
RFL: 0x0000000000010206, RIP: 0xffffff80099cf5a6, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffffbf4bd157e8, Error code: 0x0000000000000000, Fault CPU: 0x6

Backtrace (CPU 6), Frame : Return Address
0xffffff81f432aff0 : 0xffffff800992bda1 
0xffffff81f432b070 : 0xffffff8009a17cc2 
0xffffff81f432b230 : 0xffffff8009a34b73 
0xffffff81f432b250 : 0xffffff80099cf5a6 
0xffffff81f432b370 : 0xffffff80099c4549 
0xffffff81f432b710 : 0xffffff80099936d3 
0xffffff81f432b770 : 0xffffff8009ee7881 
0xffffff81f432b890 : 0xffffff8009ee7b81 
0xffffff81f432b8c0 : 0xffffff7f8bd44571 
0xffffff81f432b8f0 : 0xffffff7f8bd9ebff 
0xffffff81f432b920 : 0xffffff7f8bd0d995 
0xffffff81f432b940 : 0xffffff7f8bd42fcc 
0xffffff81f432b960 : 0xffffff7f8bd26944 
0xffffff81f432b980 : 0xffffff7f8bd12360 
0xffffff81f432b9c0 : 0xffffff7f8bd1270d 
0xffffff81f432b9f0 : 0xffffff7f8bd12ac9 
0xffffff81f432ba20 : 0xffffff7f8bd202cc 
0xffffff81f432ba70 : 0xffffff7f8bd9d2f9 
0xffffff81f432baa0 : 0xffffff7f8bd10db2 
0xffffff81f432bb30 : 0xffffff8009f01192 
0xffffff81f432bb60 : 0xffffff8009f01d89 
0xffffff81f432bbc0 : 0xffffff8009eff503 
0xffffff81f432bd00 : 0xffffff80099e21e7 
0xffffff81f432be10 : 0xffffff800993000c 
0xffffff81f432be40 : 0xffffff80099149f3 
0xffffff81f432be90 : 0xffffff800992531d 
0xffffff81f432bf10 : 0xffffff8009a031ea 
0xffffff81f432bfb0 : 0xffffff8009a35396 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(156.16)[8DA5CE1F-2C00-3CE3-8BF1-1FC07BFCF4E7]@0xffffff7f8bd0c000->0xffffff7f8bd7afff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[D8F585E8-2EE9-3135-8E37-A034123FE45C]@0xffffff7f8a239000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[6F7F093D-DBEA-356A-9A08-D8EAC7F767DE]@0xffffff7f8ab95000
         com.apple.driver.AppleIntelHD4000Graphics(10.0.6)[0946CF20-EEED-3505-A261-A26EEFE25CF5]@0xffffff7f8bd89000->0xffffff7f8bde4fff
            dependency: com.apple.iokit.IOSurface(97.4)[A4AE35B7-0C17-38F2-AD0D-A4C4B40196FB]@0xffffff7f8aa1f000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[D8F585E8-2EE9-3135-8E37-A034123FE45C]@0xffffff7f8a239000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[6F7F093D-DBEA-356A-9A08-D8EAC7F767DE]@0xffffff7f8ab95000
            dependency: com.apple.iokit.IOAcceleratorFamily2(156.16)[8DA5CE1F-2C00-3CE3-8BF1-1FC07BFCF4E7]@0xffffff7f8bd0c000

BSD process name corresponding to current thread: WindowServer

Mac OS version:
14E46

Kernel version:
Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64
Kernel UUID: E3C26B2F-8B97-3F1D-B193-690F7E34F830
Kernel slide:     0x0000000009600000
Kernel text base: 0xffffff8009800000
__HIB  text base: 0xffffff8009700000
System model name: Macmini6,2 (Mac-F65AE981FFA204ED)

System uptime in nanoseconds: 13380304509105
last loaded kext at 11048540204016: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7f8c377000, size 20480)
last unloaded kext at 11117167432271: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7f8c377000, size 16384)
loaded kexts:
org.pqrs.driver.Karabiner	10.6.83
org.virtualbox.kext.VBoxNetAdp	4.3.30
org.virtualbox.kext.VBoxNetFlt	4.3.30
org.virtualbox.kext.VBoxUSB	4.3.30
org.virtualbox.kext.VBoxDrv	4.3.30
com.intel.kext.intelhaxm	1.1.1
com.your-file-system.filesystems.yfs	1.6.11
com.apple.filesystems.smbfs	3.0.1
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.AGPM	110.19.6
com.apple.driver.X86PlatformShim	1.0.0
com.apple.iokit.IOBluetoothSerialManager	4.3.5f8
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHDA	272.18.1
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleIntelHD4000Graphics	10.0.6
com.apple.driver.AppleMikeyDriver	272.18.1
com.apple.driver.AppleHV	1
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.5f8
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.AppleIntelFramebufferCapri	10.0.6
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AppleIRController	327.5
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleSDXC	1.6.5
com.apple.iokit.AppleBCM5701Ethernet	10.1.3
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	272.18.1
com.apple.kext.OSvKernDSPLib	1.15
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.5f8
com.apple.iokit.IOBluetoothFamily	4.3.5f8
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.AppleGraphicsDeviceControl	3.10.24
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.CoreStorage	471.30.1
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.iokit.IO80211Family	730.60
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOFireWireFamily	4.5.7
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	397
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: Macmini6,2, BootROM MM61.0106.B09, 4 processors, Intel Core i7, 2.3 GHz, 16 GB, SMC 2.8f0
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x435438473353313630424D2E4D3136464544
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x435438473353313630424D2E4D3136464544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x10E), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.5f8 15969, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500.11 GB
USB Device: USB Receiver
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: Hub
USB Device: Nexus 4
USB Device: Hub
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: Mac mini, Apple Inc., 23.4

**Comment by tekezo** [comment]
I think that it is related with GPU driver. (Karabiner is not related with this issue.)
If you found the way to reproduce this issue, please confirm whether this issue is happen without Karabiner.
