### ISSUE TITLE
Add elapsedtimesincelastreleased_lessthan filter

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#444]
Would such a filter be feasible, and would it be possible for it to also detect when virtual modifiers have been released?

**Comment by tekezo** [comment]
Could you describe your usage of elapsedtimesincelastreleased_lessthan?

**Comment by nkgm** [comment]
Let's say for example, that in a simultaneouskeypress mapping `F+H` = `NKGM+Option+Left`, so that holding down `F` maintains `NKGM+Option` and I can press `H` or `L` multiple times to move by word. With `elapsedtimesincelastreleased_lessthan` available for virtual modifiers, I could have a block:

```xml
<block>
  <lastpressedphysicalkey_only>KeyCode::VK_MODIFIER_NKGM</lastpressedphysicalkey_only>
  <elapsedtimesincelastreleased_lessthan>Millisecond::RawValue::230</elapsedtimesincelastreleased_lessthan>
  <autogen>
    __KeyToKey__ KeyCode::H, KeyCode::CURSOR_LEFT
  </autogen>
  <autogen>
    __KeyToKey__ KeyCode::L, KeyCode::CURSOR_LEFT
  </autogen>
</block>
```

In other words, being able to perform an extra action as an "after-effect". 

I understand this is a very specific example, but there can be other uses for such a feature. For another example:

```xml
<autogen>
	__HoldingKeyToKey__
		KeyCode::F7,

		@begin
		KeyCode::VK_NONE,

		Option::KEYTOKEY_DELAYED_ACTION,
		KeyCode::F7,

		Option::KEYTOKEY_DELAYED_ACTION_CANCELED_BY, KeyCode::F7,
		ConsumerKeyCode::MUSIC_PREV,
		KeyCode::VK_KEYTOKEY_DELAYED_ACTION_DROP_EVENT,
		@end

		@begin
		KeyCode::F7, 
		KeyCode::VK_OPEN_URL_SHELL_Spotify_seek_backward,
		DelayUntilRepeat::RawValue::200,
		KeyRepeat::RawValue::140,
		@end
</autogen>
```

Here, holding `F7` pressed, I'm seeking backward on the current song in Spotify. If I release `F7`, and decide I want to seek back some more, I have to press and keep it again for the seeking to start. If we had the `elapsedtimesincelastreleased_lessthan` filter, I could release `F7` and tap it again quickly to seek back in single steps.

**Comment by tekezo** [comment]
Thank you for information.
I see.
I'll add `elapsedtimesincelastreleased_lessthan` soon. Please wait.

**Comment by tekezo** [comment]
I've added the following filters at v10.7.5.
Please upgrade Karabiner to the latest beta.

* `<lastreleasedphysicalkey_only>`
* `<lastreleasedphysicalkey_not>`
* `<elapsedtimesincelastreleased_greaterthan>`
* `<elapsedtimesincelastreleased_lessthan>`

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by nkgm** [comment]
Does this work for virtual keys as well?

**Comment by tekezo** [comment]
These support physical keys only.
But the virtual keys are synchronized with physical keys.
Let me know if there are situation these filters not work well.

**Comment by nkgm** [comment]
But the problem with `SimultaneousKeyPresses` is that you press two or more keys, so you can't know which was last released, and also, you don't want the additional autogens triggering when those keys were released alone.

Here is an [example configuration](https://github.com/tekezo/Karabiner/issues/382#issuecomment-94677828), where it makes sense to check when the `NKGM` virtual modifier has been released.

**Comment by tekezo** [comment]
I see.
Your focus is `<lastreleasedphysicalkey_only>` and `<lastreleasedphysicalkey_not>`. Right?

**Comment by nkgm** [comment]
Yes it is `lastreleasedphysicalkey_only`, but I guess the "physical" part of the name would be inaccurate if you also implement it for virtual keys. Also, if say I release `DF` and with it `NKGM` is released too, which of those keys was "last" released? What if releasing those keys meant more than one virtual keys being released? Which one would take priority?

What I'm trying to say is, maybe there should be `releasedvirtualkey_only` and `elapsedtimesincereleased` filters (notice there is no "last"), but I realize this is a lot to ask, and tbh I'm not even sure if it's worth the effort.

**Comment by tekezo** [comment]
I've added `<lastsentevent_only>` at v10.8.4.
Please upgrade to the latest beta version.

Note:
The previous `__SimultaneousKeyPresses__` sends KeyCode::D or KeyCode::H after sending KeyCode::VK_MODIFIER_NKGM.
So you should send KeyCode::VK_MODIFIER_NKGM again in Option::KEYTOKEY_AFTER_KEYUP.

```xml
    <!-- D is SHIFT -->
    <autogen>
      __SimultaneousKeyPresses__
      __{ KeyCode::D, KeyCode::H, }__
      KeyCode::VK_MODIFIER_NKGM,
      Option::SIMULTANEOUSKEYPRESSES_POST_FROM_EVENTS_AS_RAW,

      Option::KEYTOKEY_AFTER_KEYUP, <!-- NEW -->
      KeyCode::VK_MODIFIER_NKGM, <!-- NEW -->
    </autogen>

    <block>
      <lastsentevent_only>KeyCode::VK_MODIFIER_NKGM</lastsentevent_only>
      <!-- Put your autogens -->
      <autogen>
        __KeyToKey__
        KeyCode::RETURN,
        KeyCode::MISSION_CONTROL,
      </autogen>
    </block>
```

**Comment by nkgm** [comment]
Thanks I'll try this today. Couple of questions:

1. What about "elapsedtime"?
2. Is `lastsentevent_only` a `lastpressedphysicalkey_only` for virtual keys?

**Comment by tekezo** [comment]
1. Use `<elapsedtimesincelastreleased_greaterthan>` and `<elapsedtimesincelastreleased_lessthan>`

2. `<lastsentevent_only>` is check the last event that Karabiner sent.
It's not same as `< lastpressedphysicalkey_only>` for virtual keys.
