### ISSUE TITLE
Can't get  --KeyOverlaidModifier-- to work

### ISSUE THREAD

**Issue by Januzz** [tekezo/Karabiner#445]
Using Seil and Karabiner, I'm trying to remap Caps Lock as suggested by, e.g., Brett Terpstra (http://brettterpstra.com/2012/12/08/a-useful-caps-lock-key/).

In my private.xml I added: 

``` 
<item>
        <name>Remap Caps Lock to Hyper</name>
        <appendix>Maps CapsLock hold to Control+Shift+Option+Command and CapsLock only to Escape.</appendix>
        <identifier>com.januz.caps_lock_to_hyper</identifier>
        <autogen>
            --KeyOverlaidModifier--
            KeyCode::F19,
            KeyCode::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,
            KeyCode::ESCAPE
        </autogen>
    </item>
```
But the hold part does not work. In EventViewer, when I hold the Caps Lock key, I get repeated Esc presses.

My key repeat settings are the following, are those responsible?

<img width="638" alt="screenshot 2015-07-28 10 55 39" src="https://cloud.githubusercontent.com/assets/1440498/8927366/36d86c06-3517-11e5-951b-0185cd89969e.png">

Thanks!

**Comment by tekezo** [comment]
At first, please confirm you did "No Action" configuration.
https://pqrs.org/osx/karabiner/seil.html.en#usage

**Comment by Januzz** [comment]
Yes, I did. For both the internal and my Bluetooth keyboard.

**Comment by tekezo** [comment]
OK. Your setting seems correct.
I doubt this is a hardware issue.

If you disable Karabiner setting, f19 key should be sent by the physical caps lock key.
(Seil changes the caps lock key to f19 key.)
Does the f19 key remapping work fine? You can confirm it by EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by Januzz** [comment]
I think so. My settings in Seil:

![screenshot 2015-07-28 17 23 23](https://cloud.githubusercontent.com/assets/1440498/8935560/a973d7e2-354d-11e5-9245-e59b608c43c8.png)

EventViewer (Karabiner off):

![screenshot 2015-07-28 17 23 45](https://cloud.githubusercontent.com/assets/1440498/8935568/b81359ee-354d-11e5-8903-deee278accf4.png)

EventViewer (Karabiner on):

![screenshot 2015-07-28 17 24 22](https://cloud.githubusercontent.com/assets/1440498/8935615/f6f0e762-354d-11e5-82f4-fbd19bf2b3a8.png)

**Comment by tekezo** [comment]
You should change the caps lock keycode to 80 in Seil.

**Comment by Januzz** [comment]
Argh, I thought that because I use a German keyboard I had to use 53 as listed under "known keycode".

Now it works. Thanks a lot!!
