### ISSUE TITLE
Disable inertia scrolling?

### ISSUE THREAD

**Issue by nathanhornby** [tekezo/Karabiner#446]
I can't find an option for this anywhere, and it doesn't seem to inherit the options from the trackpad accessibility settings (I've turned off inertia scrolling there) in OSX - is there a way to avoid it when using Karabiner? I'd rather have a 1:1 scroll when using my trackball.

These are the options I'm utilising:

![screen shot 2015-07-31 at 15 18 37](https://cloud.githubusercontent.com/assets/1975168/9009203/80be8c92-3797-11e5-923b-f231a7b1c5bd.png)

**Comment by tekezo** [comment]
Please search "Disable Momentum Scroll" and enable it.

**Comment by nathanhornby** [comment]
Ah, perfect, thank you @tekezo !
