### ISSUE TITLE
Can't use modifier with scrollwheel

### ISSUE THREAD

**Issue by dr-ewan** [tekezo/Karabiner#451]
I'm trying to change scroll up & scroll down to option scroll up and option scroll down. 

Using the following in private XML doesn't seem to work:
    <autogen>__ScrollWheelToKey__ ScrollWheel::UP,
          ModifierFlag::OPTION_L,ScrollWheel::UP</autogen>

Does this not work? Or am I missing something?

**Comment by tekezo** [comment]
Does this autogen satisfy your desire?

```xml
    <autogen>
      __ScrollWheelToScrollWheel__
      ModifierFlag::NONE,
      ModifierFlag::OPTION_L,
    </autogen>
```

**Comment by dr-ewan** [comment]
That's perfect. Thank you very much
