### ISSUE TITLE
Updating from 10.6.0 to 10.6.1+ causes unexpected call of secondary key function

### ISSUE THREAD

**Issue by kennonb** [tekezo/Karabiner#452]
This is a very odd issue, but hopefully I can explain this well enough. This doesn't happen in 10.6.0, but not sure if it's an issue specifically with Slack, or Karabiner. So here's the issue:

* I have CAPS LOCK remapped to be a modifier key if held down, and then ESC if simply pressed.
* In 10.6.0, this works as expected everywhere.
* When I update to anything after 10.6.0 (hard to pinpoint the exact release), certain text fields (like Slack's quick switch dialog) always treat the modifier key as ESC.

So I used to be able to initiate the Quick Switcher in Slack, hold CAPS LOCK + j to go down to a chat, and then press enter. Doing that in a later version of the software will just dismiss the Quick Switcher. But the stable release works fine.

I am using El Capitan (Beta 6), so that might be another issue. I'm going to try a fresh install (on a VM) later to see if that sorts anything out.

Can I provide any other details?

**Comment by tekezo** [comment]
We usually faced that behavior when we don't perform "No Action" configuration.
Please confirm your "No Action" state.
https://pqrs.org/osx/karabiner/seil.html.en#usage

**Comment by kennonb** [comment]
Thanks tekezo. That setting is disabled for all keyboards. 

I feel like it might be an issue with Slack in someway, because that's the only app that is behaving this way. I'll write them and see if anyone uses this type of config, and if they have seen any issues.

**Comment by tekezo** [comment]
Thank you for confirmation.

You can confirm key events in EventViewer:
https://pqrs.org/osx/karabiner/document.html.en#eventviewer
It helps you test whether Karabiner changes keys properly.

**Comment by kennonb** [comment]
Thanks. I've been away so haven't been abel to respond. I did check that, and that leads me to suspect that it's something with the way Slack is interpreting these keystrokes. It seems to show the same regardless of the version I'm on. So I'm closing this. Thanks for the help.
