### ISSUE TITLE
KeyOverlaidModifier doesn't work for some key codes

### ISSUE THREAD

**Issue by lowski** [tekezo/Karabiner#453]
Hi,
I love this app. Thanks to it I was able to program all buttons on my Logitech M560 mouse. Thanks!

I have one issue though: I'm able to remap forward button in my mouse to behave differently when hold / tap, like this:

```xml
            <autogen>
                --KeyOverlaidModifier--
                KeyCode::COMMAND_R,
                KeyCode::CURSOR_RIGHT, ModifierFlag::CONTROL_L,
                KeyCode::CURSOR_RIGHT, ModifierFlag::COMMAND_L
            </autogen>
```

When I try to use the same syntax for back button:

```xml
            <autogen>
                --KeyOverlaidModifier--
                KeyCode::D, ModifierFlag::COMMAND_L,
                KeyCode::CURSOR_LEFT, ModifierFlag::CONTROL_L,
                KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L
            </autogen>
```

It only works for tap but not for hold.

Am I doing something wrong? I tried to look for `KeyOverlaidModifier` parameter in docs but couldn't found anything :(.

**Comment by tekezo** [comment]
How about this autogen?

```xml
            <autogen>
                --KeyOverlaidModifier--
                KeyCode::COMMAND_R,
                KeyCode::COMMAND_R,
                KeyCode::CURSOR_RIGHT, ModifierFlag::COMMAND_R
            </autogen>
```

**Comment by lowski** [comment]
@tekezo the problem is with second auto-gen - the one that uses `KeyCode::D`.

**Comment by tekezo** [comment]
If you want to the following behavior, use this autogen.
* Send control-left when you tap command-d.
* Send command-left when you hold command-d.

EventViewer is useful for confirm the result.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

```xml
    <autogen>
      __HoldingKeyToKey__
      KeyCode::D, ModifierFlag::COMMAND_L,

      <!-- hold -->
      @begin
      KeyCode::CURSOR_LEFT, ModifierFlag::CONTROL_L,
      @end

      <!-- tap -->
      @begin
      KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L
      @end
    </autogen>
```

**Comment by lowski** [comment]
@tekezo unfortunately the last snippet doesn't work for me. It always execute the shortcut in the `<!-- hold -->` section (`KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L`) no matter whether I hold or tap a button. Maybe I have something wrong in `Key Repeat` settings?


![screenshot 2015-08-14 17 16 38](https://cloud.githubusercontent.com/assets/1379988/9277116/56672d52-42a8-11e5-8819-1e9c61b6346e.png)
![screenshot 2015-08-14 17 16 48](https://cloud.githubusercontent.com/assets/1379988/9277117/566b2010-42a8-11e5-80a2-0dbfb3302a38.png)

**Comment by tekezo** [comment]
Sorry, I mistook the hold and tap comment.
The correct comment is:
*  for the first @begin @end
*  for the second @begin @end

So, your mouse always sends the tap event.

I guess your M560 sends key down and up events at the same time when you press the mouse button.
(And it does not send any events when you release the button.)
If so, Karabiner always treat the M560 button is tapping.

You can confirm your mouse button behavior by this autogen:
```xml
    <autogen>
      __KeyToKey__
      KeyCode::D, ModifierFlag::COMMAND_L,
      KeyCode::SPACE,
    </autogen>
```
If key down and key up events are sent when you pressed the button, and any events are not sent when you release the button in EventViewer, your button sends key down and up events at the same time.

If you are installed Logitech Control Center, their driver might change your buttons implicitly.
(eg. it might change the normal button event to command-d event.)
Uninstalling LCC might change the behavior.

**Comment by lowski** [comment]
Thanks for your help @tekezo !

I haven't install Logitech Control Center or anything like that.

You are right, my mouse sends key down and key up events immediately after one another (without waiting for release) for side back button. It actually really strange because side forward button work as expected :). I guess there is no way to overcome this. Anyway thanks to Karabiner I was able to make my mouse usable on OS X - by default it doesn't support it very well.
