### ISSUE TITLE
Launcher Mode v2 not work

### ISSUE THREAD

**Issue by LeoHe09** [tekezo/Karabiner#455]
10.7.0 version before I can properly use private.xml, now it can only use the default values, custom invalid.

- OS X version: OS X 10.10.4
- Karabiner version: Karabiner 10.7.0
- Your Mac hardware: MacBook Air
- Your keyboard hardware: NO

**Comment by tekezo** [comment]
Sorry for inconvenience.

If you are using ModifierFlag::NONE in custom, please remove it.

(Launcher Mode v2 uses own modifier flag since v10.7.0,
so custom settings which use ModifierFlag::NONE will be ignored.)

private.xml example:
https://pqrs.org/osx/karabiner/gallery.html.en#launcher-mode-v2

**Comment by LeoHe09** [comment]
It has been normal use, thanks.
