### ISSUE TITLE
Ctrl Home/End does not work in 10.7.0

### ISSUE THREAD

**Issue by jgregor** [tekezo/Karabiner#456]
I have PC Style Home/End #2 enabled.
And also Command <-> Control switch, for PC keyboard usage.

From 10.7.0 Ctrl Home/End does not go to the beginning/end of document, just to beginning/end of line, ignoring the Ctrl key.

**Comment by tekezo** [comment]
PC Style Home/End #2 works in TextEdit on my machine with these settings.
Does this issue happen in specific apps?

<img width="641" alt="screen shot 2015-08-11 at 7 28 12 pm" src="https://cloud.githubusercontent.com/assets/659178/9195619/275c3df4-405f-11e5-94c8-0ff6dc48ccd1.png">

**Comment by jgregor** [comment]
Textedit also works in my machine. It is about the Eclipse IDE editor, I will investigate further.
Thank you!

**Comment by jgregor** [comment]
I got back to 10.6.0, and added eclipse appdef: org.eclipse.platform.ide. Now I see Eclipse in the "Use PC Style Home/End #2" setting, as in the screenshot. I remapped ctrl+A/E in Eclipse and it fits my needs. As it is working now as I want I will not upgrade to 10.7.0.
![karabiner-2](https://cloud.githubusercontent.com/assets/3947308/9217683/1100a0f6-40cb-11e5-97a3-2530d631f745.png)

**Comment by tekezo** [comment]
Thank you for information!

I've fixed this issue at v10.7.1.
Please upgrade Karabiner to the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates
