### ISSUE TITLE
Disable option + key from entering special characters?

### ISSUE THREAD

**Issue by jetrii** [tekezo/Karabiner#457]
I used to have a custom keyboard profile on Mavericks that remove special character input (such as Option + E) to use them as IDE shortcuts. Unfortunately, it looks like Yosemite ignores the settings. Is there a way to configure Karabiner to do nothing when I type Option + <letter> so I can use them as IDE shortcuts?

**Comment by tekezo** [comment]
You can change option-e to another key combination such as command-control-e by this private.xml.
Then assign command-control-e to your favorite function in IDE.
Does your IDE provide key bind function?
https://github.com/tekezo/Files/blob/master/Karabiner/private.option_e_to_command_control_e/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml
