### ISSUE TITLE
Feature request: provide some API or CLI tool to change profiles from scripts

### ISSUE THREAD

**Issue by netvl** [tekezo/Karabiner#458]
I often use my Mac with a USB keyboard but I also frequently detach it and go somewhere without keyboard. I therefore have two profiles. It would be great if it was possible to switch these profiles automatically when I attach or detach USB plug for the keyboard.

There are several applications for Mac which can detect USB devices plugging/unplugging, but I can't do much with them because Karabiner does not support switching profiles anyhow except from the GUI menu. I came up with a script in AppleScript which opens the menu and toggles the profile for me, but it often fails to work for unknown reason (and recently stopped to work at all, presumably due to an antivirus program).

So it would be great if Karabiner provided some kind of CLI tool or some other programmable API which would allow to switch profiles in response to some other program's request. Something like

    karabinerctl set-profile "With keyboard"

**Comment by tekezo** [comment]
Use command line interface and `select_by_name`.
https://pqrs.org/osx/karabiner/document.html.en#commandlineinterface

**Comment by netvl** [comment]
Wow, there is a command line interface! Thank you very much! Don't know how I missed it in the docs...
