### ISSUE TITLE
No input source on Arabic? 

### ISSUE THREAD

**Issue by YOnoda** [tekezo/Karabiner#459]
It seems that there does not exist Arabic inputsource coding. I'm not sure why it has been left out... Maybe is there any peculiar reason that prevents it from being implemented in Karabiner?

**Comment by tekezo** [comment]
There is not a peculiar reason.
Karabiner extends input source support by requests.
This is the first request for Arabic.

I've added basic input source definition at v10.7.3.
https://github.com/tekezo/Karabiner/commit/f9d13b95313448fc73cc625fd4387c492044a04c

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by YOnoda** [comment]
Ah, I appreciate it. Thank you for the addition.
