### ISSUE TITLE
 get message Unknown symbol:  ApplicationType::iTerm  when add ignore app 

### ISSUE THREAD

**Issue by Awesomez** [tekezo/Karabiner#460]
Hi i want to add iterm to ignore list like this:

    <replacementdef>
      <replacementname>PC_STYLE_BINDINGS_IGNORE_APPS</replacementname>
      <replacementvalue>
        VIRTUALMACHINE,
        REMOTEDESKTOPCONNECTION,
        VNC,
        TEAMVIEWER,
        EMACS,
        TERMINAL,
        X11,
        VI,
	iTerm,
      </replacementvalue>
    </replacementdef>

but i get error msg below:
----------------------------------------
Unknown symbol:
ApplicationType::iTerm
----------------------------------------

please help me , thank you !

**Comment by tekezo** [comment]
You should define `iTerm` by `<appdef>` before you use it.
https://pqrs.org/osx/karabiner/xml.html.en#appdef

But iTerm is already in `TERMINAL`.
You don't need to add iTerm as a separated item.
Remove `iterm` from replacementvalue.
https://github.com/tekezo/Karabiner/blob/version_10.7.0/src/core/server/Resources/appdef.xml#L29-L35

**Comment by Awesomez** [comment]
Yes  I appreciate it. Thank you very much.

**Comment by yifanchen** [comment]
I want to add iTerm2 to the ignore list as well. 
```
<?xml version="1.0"?>
<root>
  <appdef>
    <appname>TERMINAL</appname>
    <equal>com.apple.Terminal</equal>
  </appdef>
  <replacementdef>
  <replacementname>MY_IGNORE_APPS</replacementname>
  <replacementvalue>TERMINAL</replacementvalue>
  </replacementdef>
</root>
```
I have the above code in the `private.xml` setting, however I don't see my setting in Key Change tab after I reload it. Any idea what's going on?

**Comment by tekezo** [comment]
#591
