### ISSUE TITLE
multi-touch extension stops working

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#461]
I've started using thumbsense as of recent, and I love it, but unfortunately the multi-touch extension stops responding after a short time (no sleep involved), which means thumbsense gets stuck and I have to quit Karabiner to be able to type `SDF` etc again. When the problem happens, I launch the `Karabiner_multitouchextension` app, and in the `Area` tab I can see the red dot stuck and not responding to movement on the trackpad. Restarting Karabiner helps, but the problem comes back short after.

**Comment by tekezo** [comment]
I think it's an issue of `Karabiner_multitouchextension`.
`Karabiner_multitouchextension` uses non public API in order to get multi touch devices state.

Is this issue solved by restarting `Karabiner_multitouchextension`?
If so, are there any logs related with multitouchextension in system.log?

**Comment by nkgm** [comment]
This time it happened after a wakeup. Thumbsense would remain active even when not touching the trackpad. 

I opened `Karabiner_multitouchextension` and unchecked "Activate setting while 1 finger on multi-touch device", but thumbsense was still stuck, so I also had to restart Karabiner to get my normal keyboard behavior back.

> Is this issue solved by restarting Karabiner_multitouchextension?

I thought `Karabiner_multitouchextension` is just a GUI. Normally I have to restart Karabiner for thumbsense to come back to normal. Sometimes restarting has no effect on thumbsense (remains stuck), so I have to disable thumbsense in `Karabiner_multitouchextension` and  restart Karabiner.

```
8/18/15 6:10:55.513 PM Karabiner[15401]: observer_NSWorkspaceScreensDidWakeNotification
8/18/15 6:11:03.124 PM Karabiner[15401]: observer_NSWorkspaceDidWakeNotification
8/18/15 6:11:03.124 PM Karabiner_multitouchextension[36633]: observer_NSWorkspaceDidWakeNotification
8/18/15 6:11:07.235 PM Karabiner_multitouchextension[79556]: Invalid color System, labelColor (warning given only once)
8/18/15 6:11:07.289 PM Karabiner_multitouchextension[79556]: Session state has been changed. (active)
8/18/15 6:11:07.289 PM Karabiner_multitouchextension[79556]: registerIONotification
8/18/15 6:14:44.433 PM Karabiner_multitouchextension[79556]: observer_NSConnectionDidDieNotification is called
8/18/15 6:14:45.518 PM Karabiner_AXNotifier[15410]: connection went invalid while waiting for a reply because a mach port died
8/18/15 6:14:45.519 PM Karabiner_AXNotifier[15410]: NSDistantObject (0x7f9c4a33edb0) is invalid (no connection)
8/18/15 6:14:45.521 PM Karabiner_AXNotifier[15410]: observer_NSConnectionDidDieNotification is called
8/18/15 6:14:47.181 PM Karabiner[79732]: Invalid color System, labelColor (warning given only once)
8/18/15 6:14:49.596 PM Karabiner[79732]: checkForUpdates https://pqrs.org/osx/karabiner/files/appcast.xml
8/18/15 6:14:49.703 PM Karabiner[79732]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
8/18/15 6:14:49.703 PM Karabiner[79732]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
8/18/15 6:14:49.703 PM Karabiner[79732]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
8/18/15 6:14:49.722 PM Karabiner[79732]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
8/18/15 6:14:49.722 PM Karabiner[79732]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
8/18/15 6:14:49.728 PM Karabiner_multitouchextension[79741]: Invalid color System, labelColor (warning given only once)
8/18/15 6:14:49.732 PM Karabiner[79732]: Session state has been changed. (active)
8/18/15 6:14:49.743 PM Karabiner[79732]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
8/18/15 6:14:49.772 PM Karabiner[79732]: observer_IONotification
8/18/15 6:14:49.772 PM Karabiner[79732]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
8/18/15 6:14:49.000 PM kernel[0]: org.pqrs.Karabiner --Info-- RemapClass::allocation_count_ 423999/2097152 (memory usage: 20% of 8192KB)
8/18/15 6:14:50.017 PM Karabiner_multitouchextension[79741]: Session state has been changed. (active)
8/18/15 6:14:50.017 PM Karabiner_multitouchextension[79741]: registerIONotification
8/18/15 6:14:52.216 PM Karabiner[79732]: Bartender: Loaded BartenderHelperNinety
```

**Comment by tekezo** [comment]
Thank you for information.

Could you increase "Wait for relaunch" value in Advanced tab?

<img width="522" alt="screen shot 2015-08-19 at 12 31 22 pm" src="https://cloud.githubusercontent.com/assets/659178/9348208/3dc91aac-466e-11e5-997b-07aacb1883b3.png">

`Karabiner_multitouchextension` is not just GUI.
Karabiner cannot observe touch events, so multitouchextension observes these events by using non public API and switches Karabiner settings.

If the red dot stuck is always shown even if you restart multitouch extension, I guess it's a hardware issue.
If so, do not using 1 finger setting. Use 2 fingers settings instead.

**Comment by nkgm** [comment]
Thanks, I'll try that and report back.

> If the red dot stuck is always shown even if you restart multitouch extension, I guess it's a hardware issue. If so, do not using 1 finger setting. Use 2 fingers settings instead.

But how do I restart *just* the multitouch extension? Normally it's closed and I only launch it from Karabiner->Preferences->Misc & Uninstall->"Launch multitouch extension" whenever I need to make a change in my multitouch preferences, and then close it again. 

My trackpad works the entire time, even when the red dot is stuck. Hence, I can't see how this is a hardware problem. I'm also a user of BetterTouchTool, which I believe makes use of that same non-public API, and I haven't experienced any similar issues. Is there perhaps an option for more verbose logging I can activate?

**Comment by tekezo** [comment]
> But how do I restart just the multitouch extension? 
Quit Karabiner_multitouchextension from Activity Monitor, then launch multitouchextension.
(Registering multitouchextension into Dock is useful.)

thumbsense should be disable both at quitting multitouchextension and after restarted multitouchextension.
(I understand this issue as thumbsense is still enabled at quitting and after restarted.)

**Comment by tekezo** [comment]
I've succeed to reproduce this issue!
I'll fix soon. Please wait.

**Comment by tekezo** [comment]
I've fixed this issue at v10.7.10.
Please upgrade Karabiner to the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by nkgm** [comment]
Wow that was quick! Incidentally, I just woke my mac from sleep and thumbsense was stuck again.
Downloading beta now.

What was causing it?

**Comment by tekezo** [comment]
The cause is that OS X calls multi touch API with invalid argument if any fingers are touched at launch.

multi-touch extension remembers the last device (in API arguments) in order to ignore another touch devices while any fingers are touched the last device.
(For example, you have Trackpad and Magic Mouse, Magic Mouse will be ignored while your fingers touch Trackpad.)

multi-touch extension remembers device in the invalid argument and ignores following valid devices.
So, it causes stuck.

Commit: https://github.com/tekezo/Karabiner/commit/fe7484a6fedce8dee54dcbc60c28d9569fb84c96

**Comment by nkgm** [comment]
Thank you so much, I really appreciate your hard work. 
Closing for now - will reopen if issue persists.
