### ISSUE TITLE
How to ignore this remapping if a modifier is being held down?

### ISSUE THREAD

**Issue by iiiGerardoiii** [tekezo/Karabiner#463]
Hi!
I want to make the `Option_L` key work as `Delete` if:
* The key was tapped alone (when no other modifier was being held down)

And work as `Option_L` if:
* The key was tapped while other modifier was being held down.
* The key was held down for longer than 0.2 seconds

Here's what I've done:
* `<autogen>__KeyOverlaidModifier__ KeyCode::OPTION_L, KeyCode::OPTION_L, KeyCode::DELETE</autogen>`
* Change the Key Overlaid Modifier Timeout to 200ms

Everything works great except when I press and hold a modifier (`Shift` for example) and then tap `Option_L` while I keep holding `Shift`, `Delete` comes up.

Is there a way to make this `<autogen>` get ignored if there's another modifier key being pressed?

**Comment by tekezo** [comment]
Please use this autogen:
```xml
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::OPTION_L, ModifierFlag::OPTION_L | ModifierFlag::NONE,
      KeyCode::OPTION_L,
      KeyCode::DELETE,
    </autogen>
```

**Comment by iiiGerardoiii** [comment]
Nice! works just as I wanted, thanks for your help Mr. Tekezo!
