### ISSUE TITLE
Karabiner doesn't work for eclipse from 10.7.0

### ISSUE THREAD

**Issue by cnxobo** [tekezo/Karabiner#464]
OS X 10.10.5
eclipse 4.3 Kelper
Karabiner works well at v10.6.0.
It doesn't work from v10.7.0 to v10.7.4.
This issues only happens in eclipse.
Other apps works fine.

**Comment by tekezo** [comment]
Please describe your expected behavior and the actual result.

For example:
Using "Use PC Style Home/End #2":
Expected: cursor will be moved to the beginning of line by Home key.
Actual: cursor will be moved to the top of document by Home key.

**Comment by cnxobo** [comment]
Using Emacs Mode.
When press ^F, Expected cursor will be moved to left one character
Actual nothing happened.

^bnfd all noting happened
![image](https://cloud.githubusercontent.com/assets/3774948/9349468/11392472-4679-11e5-898d-1210eb627285.png)

**Comment by tekezo** [comment]
Thank you for information.
I've fixed this issue at v10.7.7.
Please upgrade Karabiner to the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by cnxobo** [comment]
:+1: It works, thank you.
I love Karabiner :)
