### ISSUE TITLE
Remap Fn+Fx keys when Fn is already remapped

### ISSUE THREAD

**Issue by DennisSchiefer** [tekezo/Karabiner#465]
I am currently trying to replace my `CapsLock` key with the `Fn` key. On my way to that goal I have stumbled upon some issues that might be misunderstandings on my part how Karabiner + Seil works. I'll iterate my findings so far and my remaining issues in the following:

- I disabled `CapsLock` in the System Preferences
- I used Seil to remap `CapsLock` to `F19`
- I used Karabiner to remap `F19` to `Fn`

This mapping works for e.g. obtain the `Fn+Delete` behavior when pressing `CapLock+Delete` now, but none of the `Fn+F1..12` combinations work.

It is my understanding that Seil works on a lower level than Karabiner. So, by changing `CapsLock` to `F19` there, Karabiner only ever sees `F19` when I press the `CapsLock` button. Therefore, I then tried to remap `F19+F1..12` to `Fn+F1..F12`, which Karabiner apparently cannot do (there can only be one `FromKey`, right?). Next, I was hoping that I could use Karabiner to build a chain of substitutions, i.e. first mapping `F19` to `Fn` and then using this new mapping for further remappings - which also seems not to be the possible (right?).

So my final question would be, how can I change `CapsLock` to behave as `Fn` in every situation?

(Note, I also set reverse `Fn` behavior for the top row - if this changes things)

EDIT:
I have now found the option to use `__SimultaneousKeyPresses__`, which somewhat helps. I can remap `F19+F1` to `BRIGHTNESS_DOWN` and so on. The only issue with this is that `F19` (aka `Fn`) does not really work as a modifier key - I have to press both buttons at the same time. I can't press and hold `F19` and then press `F1` to get the desired mapping.

**Comment by tekezo** [comment]
Do you already read this article?
https://pqrs.org/osx/karabiner/faq.html.en#fn

**Comment by DennisSchiefer** [comment]
Thank you, I actually didnn't. I was only aware of the Manual page for Karabiner - not that there are a couple of more explanation pages.

You're FAQ helped me to configure what I wanted. Thank you.
