### ISSUE TITLE
switch displays in multi-head configuration

### ISSUE THREAD

**Issue by aculich** [tekezo/Karabiner#466]
**Feature request:** When using multiple monitors it would be handy to bind keys to switch the focus to a window of the other display, optionally zooming the mouse pointer along with the focus.

A simple app called [CatchMouse](http://macappstore.org/catchmouse/) demonstrates the functionality.

**Comment by tekezo** [comment]
You can do it with new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.warp_cursor/private.xml

**Comment by aculich** [comment]
Thanks, that does exactly what I need!
