### ISSUE TITLE
Device_only seems to work only in "autogen" item block

### ISSUE THREAD

**Issue by Sartoric** [tekezo/Karabiner#469]
I have a main ITEM block in order to group several mapping ITEMS for a logitech mouse. 
Device_only option doesn't works if I try to set it for the main ITEM block (in fact custom mapping works also from keyboard).

Maybe it's not an issue and it's a "by default" behaviour, so I'm just asking.

**Comment by tekezo** [comment]
Yes.
You have to put `<device_only>` into `<item>`.

If you want disable all settings in a specific device, please consider using `__PassThrough__` + `<device_only>`.
https://github.com/tekezo/Karabiner/blob/version_10.8.0/src/core/server/Resources/include/checkbox/ignore_apps_and_devices.xml#L32-L51

**Comment by Sartoric** [comment]
Ok, Thanks for the tip.
Just to clarify, what I was trying to do is something like this 

<item>
    <device_only></device_only>
    <only></only>
    <name></name>
        <item>
            <name></name>
            <identifier></identifier>
            <autogen></autogen>
        </item>
        <item>
            <name></name>
            <identifier></identifier>
            <autogen></autogen>
        </item>
</item>        

Just to "simplify" my private.xml .. you know ... I'm an old style developer ;-)

**Comment by tekezo** [comment]
I see.
You have to put `<only>` into the leaf `<item>`s.

```xml
<item>
    <name></name>
    <item>
        <name></name>
        <identifier></identifier>
        <device_only></device_only>
        <only></only>
        <autogen></autogen>
    </item>
    <item>
        <name></name>
        <identifier></identifier>
        <device_only></device_only>
        <only></only>
        <autogen></autogen>
    </item>
</item>
```
