### ISSUE TITLE
Suggestion: Make Numpad Hack Default to Off

### ISSUE THREAD

**Issue by nicolasartman** [tekezo/Karabiner#470]
I just spent some time wondering why my fn+kmlo...etc. combinations were resulting in numbers, only to find that the default key behavior was changed and the option in karabiner was to _disable_ the change rather than enable it. Even if it's on by default, I think it would be much clearer to have the option be _enable NumPad hack_, so users would get the default system behavior with nothing checked.

Thank you for your consideration!

**Comment by tekezo** [comment]
Thank you for suggestion.
I've received the same suggestion before.
I'll remove numpad hack from the Implicit behavior.

**Comment by tekezo** [comment]
The fn keypad has been removed from Implicit behavior at v10.8.3.
You can confirm in the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by nicolasartman** [comment]
Thank you!

**Comment by ppixu** [comment]
I can't find the numpad hack anymore. Has it been removed completely?

**Comment by tekezo** [comment]
The fn keypad has been removed from implicit behavior since v10.9.0. 
Please enable "Use old style fn keypad" manually if needed.

Version History: 
https://pqrs.org/osx/karabiner/history.html.en#history ﻿
Show less

**Comment by ppixu** [comment]
Oh there it was. Maybe mention 'keypad hack' in the description to make it searchable if that's what it was called before?

**Comment by ppixu** [comment]
It was the only reason I installed karabiner back in the day :)
