### ISSUE TITLE
FN to Anything doesn't work

### ISSUE THREAD

**Issue by fmp777** [tekezo/Karabiner#471]
Seems Karabiner doesn't register the FN key at all.  The EventViewer doesn't show any key press when FN is used.

Not sure if it matters, but this is a Logitech K811 keyboard.

**Comment by tekezo** [comment]
Unfortunately, Karabiner does not support the fn key in logitech keyboards.
The fn does not send any key events to OS.
I guess it is closed into the keyboard hardware.
