### ISSUE TITLE
In EventViewer, pressing LeftOption+RightArrow on Early 2015 MacBook Pro shows Fn involved

### ISSUE THREAD

**Issue by IshmaelYavitz** [tekezo/Karabiner#472]
I don't know if this is expected behavior or not.

Using the integrated keyboard, pressing and holding left option, pressing and releasing right arrow, and then releasing left option shows the following events:

    eventType:keyMod          code:0x3a       name:Option_L        flags:Opt                                misc:KeyCode::OPTION_L	characters:    
    eventType:keyDown         code:0x7c       name:Right           flags:Opt NumPad Fn                      misc:KeyCode::CURSOR_RIGHT	characters:    
    eventType:keyUp           code:0x7c       name:Right           flags:Opt Fn                             misc:KeyCode::CURSOR_RIGHT	characters:    
    eventType:keyMod          code:0x3a       name:Option_L        flags:                                   misc:KeyCode::OPTION_L	characters:    

The `keyDown` and `keyUp` events show the `Fn` flags.

Karabiner 10.8.0
OS X 10.10.5 (Yosemite)
Early 2015 13" MacBook Pro with 3.1 GHz processor, 512 GB SSD, 16 GB RAM

**Comment by tekezo** [comment]
It's OS X behavior.
OS X appends fn flag to arrow keys automatically.
Please ignore it.

**Comment by IshmaelYavitz** [comment]
Ah, okay.  Thanks for your fast response.
