### ISSUE TITLE
Upgrade wiped out custom mods in ~/Library/Application Support/Karabiner/private.xml

### ISSUE THREAD

**Issue by mikemakuch** [tekezo/Karabiner#473]
I upgraded recently and lost my mods in private.xml. I would expect upgrade to not do that. Thanks.

**Comment by tekezo** [comment]
Karabiner does not do that.
Is your private.xml not a regular file such as link or in network filesystem?

**Comment by mikemakuch** [comment]
It's a regular file. I believe it did do that because after I upgraded I 
lost my custom mods in private.xml. I don't know how else it might have 
happened. What was in there was contents of samples.xml.

Thanks
Mike

**Comment by tekezo** [comment]
Karabiner will create private.xml by the following contents if private.xml does not exist at launch.
```xml
<?xml version="1.0"?>
<root>
</root>
```

If your private.xml is same as above, I guess your private.xml have been lost by disk error or other errors and Karabiner recreated it at launch.

Please consider making an external xml file and include it in private.xml.
https://pqrs.org/osx/karabiner/xml.html.en#dropbox

If your private.xml is not above, like samples.xml,
https://github.com/tekezo/Karabiner/blob/version_10.8.0/src/core/server/Resources/include/checkbox/samples.xml
I guess Time Machine or other backup softwares reverted your changes.
Please confirm your system.

**Comment by mikemakuch** [comment]
I have a backup system and I was able to retrieve my private.xml from 
backup without a problem. As soon as I upgraded Karabiner I lost my 
custom functionality and began investigating. As soon as I restored my 
private.xml from backup and did a reload xml, I regained my custom 
functionality.

I just wanted to share this info I thought you'd appreciate it.

Thanks

Mike

**Comment by tekezo** [comment]
Thank you for information.
I'm glad that you backed up your private.xml and restore it properly.
If you faced same error again, let me know the contents of private.xml that has been reset.

And I recommend you to verify your disk by Disk Utility.
(If your private.xml has been vanished by disk error, you should replace the disk.)
http://support.apple.com/kb/PH5864
