### ISSUE TITLE
Swapping CTRL and FN keys

### ISSUE THREAD

**Issue by edwardjiang7** [tekezo/Karabiner#474]
I have switched both of them and I have tried everything but it does not work. I'm running Yosemite. Does it not work on Yosemite?

**Comment by tekezo** [comment]
Please read this section:
https://pqrs.org/osx/karabiner/faq.html.en#fn

**Comment by edwardjiang7** [comment]
Yes, I have my FN and my F1... keys swapped. For example. for F11, I just press F11. For the volume down, I press FN + F11. How do I have to change it so that I can swap FN and CTRL?

**Comment by tekezo** [comment]
Try these settings.
https://pqrs.org/osx/karabiner/img/fnfunc.png

**Comment by edwardjiang7** [comment]
Hello, that does not work either. Any other ideas please?

**Comment by tekezo** [comment]
Please tell me your information:
https://pqrs.org/osx/karabiner/contact.html.en

And tell me the "Use all F1, F2, etc. keys as standard function keys." setting is enabled or not.
http://support.apple.com/kb/ht3399

**Comment by edwardjiang7** [comment]
Yes, I am using all the F keys as the standard function keys. It is enabled.

**Comment by tekezo** [comment]
What's your environment?
https://pqrs.org/osx/karabiner/contact.html.en

**Comment by edwardjiang7** [comment]
OS X version: Yosemite 10.10.5
Karabiner version: Karabiner 10.8.0
Your Mac hardware: MacBook Pro
Your keyboard hardware: Not sure, default Macbook Pro (Late 2013 model)

**Comment by tekezo** [comment]
These setting works well on my machine.

<img width="645" alt="screen shot 2015-09-07 at 11 51 57 am" src="https://cloud.githubusercontent.com/assets/659178/9708485/72f745e4-5557-11e5-9356-ed64de5dcd13.png">

If you can use Terminal, you can enable these settings by this commands.
Enable them by terminal and disable other settings you previous enabled from GUI.

```sh
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.controlL2fn 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn2controlL 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f1 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f3_lion 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f5 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f7 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f10 1
```

**Comment by edwardjiang7** [comment]
Hey, I tried everything and it doesn't work. I also switched my command key and my control key from the beginning in the keyboard settings.

**Comment by tekezo** [comment]
Please reset your keyboard settings and change everything in Karabiner.

**Comment by edwardjiang7** [comment]
I reset everything and activated Karabiner only and it still did not work.

**Comment by tekezo** [comment]
Is your issue still "the physical control key + f11 does not work as volume down"?
Please confirm your physical control key will be fn key in EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

And show me your enabled settings. (Show me a screen shot of Karabiner Preferences with "show enabled only".)

**Comment by edwardjiang7** [comment]
I think we are having a misunderstanding haha.

Right now, the Command + C = copy
Command + V = paste

Here is what I need:

fn + C = copy
fn + V = paste

**Comment by tekezo** [comment]
Do you want to use fn as command key?
Please enable "Change Fn key > Fn to Command_L".

**Comment by edwardjiang7** [comment]
I tried that before but it did not work but I will try that again tomorrow.

**Comment by edwardjiang7** [comment]
I have tried that as well and that does not work.

**Comment by edwardjiang7** [comment]
I updated the post above.

**Comment by tekezo** [comment]
Please enable "Change Command_L Key > Command_L to Fn" together.

**Comment by edwardjiang7** [comment]
What do you mean by that?

**Comment by tekezo** [comment]
You have to enable these settings.

Could you show me your all enabled settings?
(Show me a screen shot of Karabiner Preferences with "show enabled only".)

<img width="637" alt="screen shot 2015-09-09 at 1 46 08 pm" src="https://cloud.githubusercontent.com/assets/659178/9753557/554f1dca-56f9-11e5-82b4-8310cce06983.png">

**Comment by edwardjiang7** [comment]
<img width="693" alt="screen shot 2015-09-09 at 8 52 53 am" src="https://cloud.githubusercontent.com/assets/11775993/9763675/7a2e1fac-56d0-11e5-8c4d-409968e82bf8.png">

That's what I currently have.

**Comment by tekezo** [comment]
Thank you for information.
The 2 settings changes the physical fn key and the left command key.
You can confirm they are swapped in EventViewer.

For the physical left command key (changed to the fn key) + function key,
you should enable these function key related settings.
https://github.com/tekezo/Karabiner/issues/474#issuecomment-138167594

Please execute these command in Terminal or enable these settings in GUI.
```sh
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f1 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f3_lion 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f5 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f7 1
/Applications/Karabiner.app/Contents/Library/bin/karabiner set remap.fn_fkeys_to_consumer_f10 1
```

**Comment by edwardjiang7** [comment]
Oh wow. I must say you are a lifesaver! It finally works.

I tried this around a month ago and I gave up but came back to this because I thought that this was the only program that was the most successful even though I failed at it. With your help, it's working now. Thank you so much!

**Comment by adancygier** [comment]
If you use an external keyboard along with the built in mac keyboard, I would advise setting fn to Control_L and setting another key that you don't use often that has a duplicate to fn, for instance I set Option_R to fn.

**Comment by ohoroyoi** [comment]
@tekezo still happen. and the directory is different with your command.
