### ISSUE TITLE
Providing symmetric control keys on the short Apple keyboard

### ISSUE THREAD

**Issue by pajatopmr** [tekezo/Karabiner#476]
I map CapsLock to F13 (using Seil) and select "no action" for CapsLock (using the Keyboard system preferences tool).  Then I brute force change return.xml with Karabiner to add the following snippet:

```
<item>
  <name>F13 to Control_L</name>
  <appendix>(+ When you type F13 only, send F13)</appendix>
  <identifier>remap.f132controlL_f13</identifier>
  <autogen>__KeyOverlaidModifier__ KeyCode::F13, KeyCode::CONTROL_L, KeyCode::F13</autogen>
</item>
```

This gives me the ability to 1) have symmetric Control keys with CapsLock and Return, and 2) map the F13 key to a Menu key in Emacs when it is typed alone.

Is it possible to simplify this kludgy process within Karabiner alone?  If someone were to suggest a clean way to achieve this, I will be glad to test it and generate a PR.

**Comment by tekezo** [comment]
It's a best way to achieve your desire.

Another way, the modifier key configuration of system preferences will be applied before Karabiner.
So, change the caps lock key to the control key (or other modifiers) and change control key in Karabiner.

**Comment by pajatopmr** [comment]
That's what I was doing before I hit upon the notion to apply the Karabiner return key modification idea that makes it a return key when typed alone but a control key when typed with another key to a key (F13) mapped onto capslock by Seil.

What's the best way of adding a mapping in Karabiner to apply this technique to any function key?  I suspect that is the best I'll be able to do from Karabiner.  Would that be to post a private.xml file?

**Comment by tekezo** [comment]
> What's the best way of adding a mapping in Karabiner to apply this technique to any function key?

Writing such autogen for all function keys is the most simple way.

If your autogen is too complex and you want to reduce duplicated code,
you can reduce the duplicated code by using `<include>` and `<replacementdef>`.
https://pqrs.org/osx/karabiner/xml.html.en#include-with-replacementdef
But I think output private.xml by scripting language is more easier way in that case.
