### ISSUE TITLE
CTRL + CMD + <arrow keys> = strange behavior

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#477]
I noticed something strange was going on when trying to map `CTRL+CMD+LEFT/RIGHT` in *IntelliJ IDEA*. For some reason IDEA registered `CTRL+CMD+RIGHT`=`OPTION+TAB` and `CTRL+CMD+LEFT`=`OPTION+SHIFT+TAB`.

Trying the same with *AppCode* registers the **correct keystrokes**, which is beyond me, baring in mind it's from the same company and essentially the same core as IDEA.

The same happens when I quit Karabiner and BTT.

Finally trying the same in EventViewer registers nothing. This is what I see in EventViewer when I `CTRL+CMD+RIGHT`:

```
eventType:keyMod          code:0x37       name:Command_L       flags:Cmd                                misc:KeyCode::COMMAND_L	characters:    
eventType:keyMod          code:0x3b       name:Control_L       flags:Ctrl Cmd                           misc:KeyCode::CONTROL_L	characters:    
eventType:keyMod          code:0x37       name:Command_L       flags:Ctrl                               misc:KeyCode::COMMAND_L	characters:    
eventType:keyMod          code:0x3b       name:Control_L       flags:                                   misc:KeyCode::CONTROL_L	characters:    
```

When I activate Karabiner.debug I can still see this when I press `RIGHT` while holding down `CTRL+CMD`:

```
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- UpdateEventFlagsCallback [ caught]: flags 0x00340009
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 10, flags 0x80340009, key 0x007c, kbdType  44, repeat = 0
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- UpdateEventFlagsCallback [sending]: flags 0x00340009
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 10, flags 0x00340009, key 0x007c, kbdType  44, repeat = 0
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 11, flags 0x80340009, key 0x007c, kbdType  44, repeat = 0
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- UpdateEventFlagsCallback [ caught]: flags 0x00140009
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 11, flags 0x00340009, key 0x007c, kbdType  44, repeat = 0
9/14/15 1:01:50.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- UpdateEventFlagsCallback [sending]: flags 0x00140009
9/14/15 1:01:51.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80040001, key 0x0037, kbdType  44, repeat = 0
9/14/15 1:01:51.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [ caught]: eventType 12, flags 0x80000000, key 0x003b, kbdType  44, repeat = 0
9/14/15 1:01:51.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00040001, key 0x0037, kbdType  44, repeat = 0
9/14/15 1:01:51.000 AM kernel[0]: org.pqrs.Karabiner --Debug-- KeyboardEventCallback [sending]: eventType 12, flags 0x00000000, key 0x003b, kbdType  44, repeat = 0
```

Also tried with empty `private.xml` but same result.

What am I missing?

**Comment by tekezo** [comment]
The command-control-arrow keys do not call [NSResponder  keyDown].
So, EventViewer cannot show these events.
It's an OS X limitation.

**Comment by nkgm** [comment]
Ok so I understand this is not a Karabiner bug.
But how does AppCode detect these correctly? Should I avoid them altogether, or is there a workaround?

**Comment by tekezo** [comment]
It depends input event handling in each apps.
If AppCode does not recognize command-control-arrow keys, you should change these key combinations to other combinations by Karabiner.

**Comment by nkgm** [comment]
`AppCode` is the **only program** that recognizes them **correctly** like I said in my original question. `IntelliJ IDEA` recognizes `CTRL+CMD+RIGHT` as `OPTION+TAB` which I thought was **very weird**.  Anyway I respect your time so I'll research this on my own. I was wondering if you could point me to any further information with regards to the following:

> The command-control-arrow keys do not call [NSResponder keyDown].
> So, EventViewer cannot show these events.

**Comment by tekezo** [comment]
I got it.

To receive these events, we should override [NSApplication sendEvent].
https://github.com/tekezo/Karabiner/blob/master/src/util/EventViewer/Classes/EventViewerApplication.m#L8-L12

I changed EventViewer at v10.9.9.
EventViewer also shows command-control-arrow keys.

**Comment by nkgm** [comment]
Great work as usual. Thanks!
