### ISSUE TITLE
right click to lock button left doesn't work

### ISSUE THREAD

**Issue by anoda9** [tekezo/Karabiner#478]
I'm trying to assign right click to hold left click (drag), but it's not working. Mac OSX 10.10.5, Karabiner 10.9.

`<item>
	<name>right click to drag</name>
	<identifier>private.right_click_to_drag</identifier>
	<autogen>__KeyToKey__ KeyCode::VK_MOUSEKEY_BUTTON_RIGHT, KeyCode::VK_MOUSEKEY_LOCK_BUTTON_LEFT</autogen>
</item>`

What am I doing wrong?

**Comment by tekezo** [comment]
Please use `PointingButton::RIGHT` to the target key.

```xml
  <item>
    <name>right click to drag</name>
    <identifier>private.right_click_to_drag</identifier>
    <autogen>__KeyToKey__ PointingButton::RIGHT, KeyCode::VK_MOUSEKEY_LOCK_BUTTON_LEFT</autogen>
  </item>
```

**Comment by anoda9** [comment]
Thanks!
