### ISSUE TITLE
Status of the Wacom Tablet Side buttons, no event

### ISSUE THREAD

**Issue by NNois** [tekezo/Karabiner#479]
I can't emulate the side button of my Wacom Intuos5 tablet with Karabiner.

This would be very very useful...
I don't see anything on the event viewer when I press one of the Wacom button, but i see when i "mouse up or down".
Does seeing nothing in the event viewer means this would never be possible ?

Many people use the tablet as a "pointing device" while leaving the left hand on the physical keyboard.
Providing the ability to perform various app related shortcut, but we need to tap too on the Wacom physical buttons... if we could map those button to some keyboard shortcut with karabiner this would be so much better !
This is a request pending from 2010 to Wacom and they don't give a shit of their users...

**Comment by tekezo** [comment]
Unfortunately, Karabiner does not support tablet devices.
And there is not a plan to support them I don't have these devices for now.

I found other project TabletMagic. How about it?
https://github.com/thinkyhead/TabletMagic
