### ISSUE TITLE
Xcode 7 has a new simulator app position

### ISSUE THREAD

**Issue by puttin** [tekezo/Karabiner#480]
`/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app` instead of `/Applications/Xcode.app/Contents/Applications/iOS Simulator.app`

which causes file `/src/core/server/Resources/vkopenurldef.xml`'s `VK_OPEN_URL_APP_iOS_Simulator` value is wrong for Xcode 7

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed it at v10.9.15.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by puttin** [comment]
The works you do in https://github.com/tekezo/Karabiner/commit/3b71156f0f9099a7797fbe1c465dd2246424dbea may cause old remappings for Xcode not works correctly.

Is there any possible to keep both?

Or upgrade to newest Xcode version is preferred for most Karabiner users?

**Comment by tekezo** [comment]
> upgrade to newest Xcode version

Yes. We should use the latest Xcode.

If you want to keep both, override it in private.xml:

```xml
  <vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_APP_iOS_Simulator</name>
    <url type="shell">open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app || open /Applications/Xcode.app/Contents/Applications/iOS\ Simulator.app</url>
  </vkopenurldef>
```

**Comment by puttin** [comment]
Tested in v10.9.16.
