### ISSUE TITLE
Transfer modifier to prefix in tmux

### ISSUE THREAD

**Issue by hanjianwei** [tekezo/Karabiner#482]
I'm using tmux whose command key bindings are prefixed by `Ctrl-b`. It's annoying to input prefix key each time (e.g. `Ctrl-b c` to create a window). So I mapped COMMAND_R to the prefix:

``` xml
<windownamedef>
  <name>Tmux</name>
  <regex>tmux</regex>
</windownamedef>

<item>
  <name>Right ⌘ to ⌃B (prefix)</name>
  <identifier>private.right_cmd_to_ctrl_b</identifier>

  <only>TERMINAL</only>
  <windowname_only>Tmux</windowname_only>

  <autogen>
    __KeyToKey__
    KeyCode::COMMAND_R, 

    KeyCode::B, ModifierFlag::CONTROL_L
  </autogen>
</item>
``` 

I can type `COMMAND_R c` to create a window, feel good. However, when resizing a pane I should type these: press `COMMAND_R OPTION UP`, release `COMMAND_R` and type that sequence again.

Is it possible when `COMMAND_R` is pressed, each KEY transfers to Ctrl-b KEY? 

Sorry I can not find enough document about this.

**Comment by tekezo** [comment]
Change all keys is the only way to do it.

```xml
    <!-- send control-b when you press the right command key alone. -->
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::COMMAND_R,
      KeyCode::COMMAND_R,
      KeyCode::B, ModifierFlag::CONTROL_L,
    </autogen>

    <!-- send control-b before key. -->
    <autogen>
      __KeyToKey__
      KeyCode::C, ModifierFlag::COMMAND_R,
      KeyCode::B, ModifierFlag::CONTROL_L,
      KeyCode::C,
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::CURSOR_UP, ModifierFlag::COMMAND_R,
      KeyCode::B, ModifierFlag::CONTROL_L,
      KeyCode::CURSOR_UP,
    </autogen>
```

**Comment by hanjianwei** [comment]
It's good enough for me, Thanks!

I've updated my [private.xml](/hanjianwei/dotfiles/blob/master/roles/karabiner/files/Library/Application%20Support/Karabiner/private.xml).
