### ISSUE TITLE
Can two layers of mapping work? Trying to implement home row mode cmd-forwarddelete.

### ISSUE THREAD

**Issue by lastobelus** [tekezo/Karabiner#483]
I ask because I am stymied trying to get a homerow mode version of cmd-forwarddelete to work for me.

Some background to this: for some reason I have not been able to resolve, DefaultKeyBindings.dict does not work on my newest laptop.This is why I turned to Karabiner in the first place, and then got interested in home row mode.

I am using a modified version of homerow mode.

I made the following setting to enable Cmd-FN-Delete or Cmd-ForwardDelete, which replaces a `deleteToEndOfLine:` keybinding and works fine normally (ie, when not using homerow mode):

```xml
    <item>
      <name>[Option] Cmd-ForwardDelete</name>
      <identifier>option.dvorak_homerow_cmd_forward_delete</identifier>
      <autogen>
        __KeyToKey__
        KeyCode::FORWARD_DELETE, ModifierFlag::COMMAND_L,
        KeyCode::V, ModifierFlag::CONTROL_L,
        KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_dvorak_homerow_cmd_forward_delete
      </autogen>
      <autogen>
        __KeyToKey__
        KeyCode::DELETE, ModifierFlag::FN, ModifierFlag::COMMAND_L,
        KeyCode::V, ModifierFlag::CONTROL_L,
        KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_dvorak_homerow_cmd_forward_fn_delete
      </autogen>
    </item>
```

Then I added the following:
```xml
    <item>
      <name>[Option] U to Backspace, O to forward delete</name>
      <appendix>a simplification of the above setup</appendix>
      <identifier>option.dvorak_homerow_mode_u_to_backspace</identifier>
      <config_only>notsave.dvorak_homerow_mode</config_only>
      <autogen>__KeyToKey__ KeyCode::U, KeyCode::DELETE</autogen>
      <autogen>__KeyToKey__ KeyCode::O, KeyCode::DELETE, ModifierFlag::FN</autogen>
    </item>
```
NOTE: I also tried
```xml
      <autogen>__KeyToKey__ KeyCode::O, KeyCode::FORWARD_DELETE</autogen>
```

I also have `d` mapped to `[option]` and `f` to [cmd] as in the normal homerow mode

With this setting enabled the following works in home row mode:
* hitting `o` forward-deletes one character
* holding `d` and hitting `o` forward-deletes one word

**BUT** holding `f` and hitting `o` does nothing.

Is this because karabiner only makes one pass through its set of settings? Is there a way to make this work if I can't get `~/Library/KeyBindings/DefaultKeyBinding.dict` to work? (if I could I wouldn't have this problem as I have bindings for cmd-forwarddelete & cmd-fn-delete to `deleteToEndOfLine:`)

**Comment by tekezo** [comment]
You should send "command-shift-left arrow, delete".
Please use this autogens.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::O, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_COMMAND,
      KeyCode::CURSOR_RIGHT, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_COMMAND | ModifierFlag::SHIFT_L,
      KeyCode::DELETE,
    </autogen>
    <autogen>__KeyToKey__ KeyCode::O, KeyCode::FORWARD_DELETE</autogen>
```

Note:
The autogen order is important.
https://pqrs.org/osx/karabiner/xml.html.en#order

**Comment by lastobelus** [comment]
Yes! that worked, and it also worked to use to move my original `ctrl-v` map into the `o` map as well, like this:

```xml
    <item>
      <name>[Option] U to Backspace, O to forward delete</name>
      <appendix>a simplification of the above setup</appendix>
      <identifier>option.dvorak_homerow_mode_u_to_backspace</identifier>
      <config_only>notsave.dvorak_homerow_mode</config_only>
      <autogen>__KeyToKey__ KeyCode::U, KeyCode::DELETE</autogen>
      <autogen>
        __KeyToKey__
        KeyCode::O, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_COMMAND,
        KeyCode::V, ModifierFlag::CONTROL_L
      </autogen>
      <autogen>__KeyToKey__ KeyCode::O, KeyCode::FORWARD_DELETE</autogen>
    </item>
```

I'm slightly embarassed I didn't come up with that idea.

So, it is the case then that Karabiner makes one pass through? I had thought otherwise because of the ability to set a virtual key and then base other mappings off that, but I suppose those work because there are mulitple events involved?  or is there another reason the way I tried originally didn't work?

**Comment by tekezo** [comment]
Karabiner applies only the first matched <autogen>.
And Karabiner does not support recursive rules.

So you should change everything in one autogen.

**Comment by lastobelus** [comment]
Ok, thanks! And thank you very much for providing and maintaining Karabiner, I'm really enjoying learning how to use it.
