### ISSUE TITLE
Is it possible to remap one specific key?

### ISSUE THREAD

**Issue by synthview** [tekezo/Karabiner#484]
Hello,
Is it possible to remap one key on a wireless apple keyboard ?
Thanks

**Comment by tekezo** [comment]
Please describe detailed your desire.
What's key you want to change?

**Comment by synthview** [comment]
In the US  international keyboard, the section glyph § is displayed both tapping the § key as alt+§ key, that is quite useless.
At the same time, there is no way to get the multiplication glyph ×. 
![schermata 2015-09-29 alle 16 07 52](https://cloud.githubusercontent.com/assets/1451689/10166444/56b1dd30-66c4-11e5-9a28-cb4b6599c810.png)

So I would find more useful to remap alt+§ to display ×

**Comment by tekezo** [comment]
Please enable "Unicode Hex Input" input source by this way.
https://pqrs.org/osx/karabiner/faq.html.en#unicode-hex-input

Then, use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.unicode_input2/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by synthview** [comment]
hmm it’s not optimal as the US international has plenty of combos to write all possible Latin glyphs with diacritics. With the Uni Hex I lose them all.

**Comment by tekezo** [comment]
What's the concrete problem?

**Comment by synthview** [comment]
As said, with the US international layout I have access to plenty of other (and necessary) glyphs with the alt+key or shift+alt+key  combos. Uni Hex do not provide it so it seems quite useless in real life, at least for European languages.

**Comment by tekezo** [comment]
The new setting allows you to use US international input source.
Karabiner changes input source temporarily only when you pressed option-§.
(Karabiner restores input source automatically after × is entered.)

Does the new setting break your input environment?

**Comment by synthview** [comment]
oh I understand, I though I had to set the uni hex as defaulf layout.

I’m almost done with the private xml but I can’t find the keycode data for ×. I only see keypad_multiply but it outputs *

I see there is a string to set a custom key, something like  <symbol_map type="KeyCode" name="CLASSIC_MULTIPLY" value="0x10001" />

but I can’t find the hex value for × sign…

Wouldn’t it better for Karabinier to work with unicode rather than Hex mappings?

**Comment by synthview** [comment]
I found the hex for multiply at the end, but it does not seem to work…

<?xml version="1.0"?>
<root>
	<item>
    <name>alt + § = ×</name>
    <symbol_map type="KeyCode" name="CLASSIC_MULTIPLY" value="0xd7" />
    <identifier>private.alt_section_is_multiply</identifier>
    <autogen>__KeyToKey__ 
    	KeyCode::UK_SECTION, ModifierFlag::OPTION_L,
    	KeyCode::CLASSIC_MULTIPLY
    </autogen>
  </item>
</root>

**Comment by tekezo** [comment]
× is U+00D7.
So these lines sends 00D7.
https://github.com/tekezo/Files/blob/master/Karabiner/private.unicode_input2/private.xml#L17-L21

**Comment by synthview** [comment]
I’m sorry but I don’t understand…
I set  
```
<symbol_map type="KeyCode" name="CLASSIC_MULTIPLY" value="00D7" />
```
but I have 
```
Error in XML.
----------------------------------------
Invalid 'value' Attribute within <symbol_map>:

<symbol_map type="KeyCode" name="CLASSIC_MULTIPLY" value="00D7" />
```

**Comment by synthview** [comment]
if I try, as mentioned here https://pqrs.org/osx/karabiner/xml.html.en#rawvalue
```
    <autogen>__KeyToKey__ 
    	KeyCode::UK_SECTION, ModifierFlag::OPTION_L,
    	KeyCode::RawValue::0xd7
    </autogen>
```

I have no error but nothing happens when I type alt+§

**Comment by tekezo** [comment]
You should send key sequence "option+0,option+0,option+D,option+7" in unicode hex input source.
The way to send keys is this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.unicode_input2/private.xml

There is not a way to input "×" directly.

**Comment by synthview** [comment]
so I should type on my keyboard option+0+0+d+7? 
No good solution, sorry.
You really should make it work with unicode glyph references.

**Comment by tekezo** [comment]
> so I should type on my keyboard option+0+0+d+7? 

No.
Karabiner sends these keys by alt+§.

**Comment by synthview** [comment]
Oh sorry, I get it.
now where can I find a list of keyboards to change this?

      KeyCode::VK_CHANGE_INPUTSOURCE_US,

What I mean is I have a localised version of Mac Os and I don’t know which is the name of my VK_CHANGE_INPUTSOURCE_

I’ve tried VK_CHANGE_INPUTSOURCE_USEXTENDED and US_EXTENTED but din’t work

**Comment by tekezo** [comment]
Please read this section.
https://pqrs.org/osx/karabiner/xml.html.en#vkchangeinputsourcedef

**Comment by synthview** [comment]
my keyboard layout isn’t in your list
 https://github.com/tekezo/Karabiner/blob/version_10.9.0/src/core/server/Resources/vkchangeinputsourcedef.xml

**Comment by tekezo** [comment]
You can define your own KeyCode by `<vkchangeinputsourcedef>`.
https://pqrs.org/osx/karabiner/xml.html.en#vkchangeinputsourcedef

**Comment by synthview** [comment]
it works!
thank you for your help :) this was very technical.

**Comment by tekezo** [comment]
it's great!
