### ISSUE TITLE
How to achieve `select word` assigned to cmd+d, or even ctrl+d

### ISSUE THREAD

**Issue by rkpatel33** [tekezo/Karabiner#485]
I would like to achieve a word selection shortcut but not sure who to assign the key combo in the private XML to cmd+d, or even ctrl+d, so what it will work in MS Word on OSX. The cocoa command I am trying to trigger is `selectWord:`.

I have tried to do it manually in the DefaultKeyBinding.dict but it does not work in some apps, with cmd or ctrl.

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.select_word/private.xml

**Comment by rkpatel33** [comment]
Thanks that worked great!
