### ISSUE TITLE
How to change "behaviour" of a key combination but not binding?

### ISSUE THREAD

**Issue by utku1** [tekezo/Karabiner#486]
As far as I understand, Karabiner changes a binding to another binding. That is; if I change alt<- to cmd<- using Karabiner, the OS thinks that I have pressed alt<-, whenever I press cmd<-.

Problem is, this is not the behaviour I want. When I press cmd<-, I want the OS to still think that I have pressed cmd<- but instead of moving the cursor to the beginning of the line, I want it to move the cursor to the previous word. That is, I want to change just the "behaviour" of a key combination.

Do you know any way of doing this Mr. Fumihiko? Or could you direct me to some resources so that I will be able to do it myself?

Regards

**Comment by tekezo** [comment]
You should use DefaultKeyBinding.dict.
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/EventOverview/TextDefaultsBindings/TextDefaultsBindings.html

**Comment by utku1** [comment]
Thank you very much.
