### ISSUE TITLE
All backtick mappings map to <

### ISSUE THREAD

**Issue by ain** [tekezo/Karabiner#487]
__Steps to reproduce__:

1. Enable _Swap backtick and underscore_ Programmer setting

__What happens__: hitting underscore for backtick will produce less than sign (`<`).

__What should happen__:  backtick should appear instead of less than sign.

System: 
```
OS X El Capitan 10.11
Karabiner 10.9.0
Keyboard input: Estonian
```

**Comment by tekezo** [comment]
That setting depends on your input source.
Please tell me input source that you are using.

**Comment by tekezo** [comment]
The setting is designed for U.S. input source.

If you want to input backtick in Estonian input source,
please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.estonian_backtick/private.xml

*Note*
You should enable Estonian and U.S. input source together by System Preferences > Keyboard > Input Sources.

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml


*Alternative*
You might be able to input backtick by making your own keyboard layout with Ukelele.
http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele

**Comment by ain** [comment]
Thanks for your support @tekezo. I'll give it a run and come back with results to close the ticket :)

**Comment by ain** [comment]
Above suggestion works apart from Ukulele which clearly doesn't. Every app runs it's own input source, on some, the source can't be changed, _Cmd +_ keys get blocked. Extremely buggy as far as I can see.
