### ISSUE TITLE
No KeyCode mapping for caret?

### ISSUE THREAD

**Issue by ain** [tekezo/Karabiner#488]
I didn't find the caret (^) mapping in the keycodes, but on some inputs it is missing. Did I miss something or is there some ground for a new KeyCode to be supported?

**Comment by tekezo** [comment]
KeyCode is correspond to the physical key.

If you want to input ^, you should replace this line:
https://github.com/tekezo/Files/blob/master/Karabiner/private.estonian_backtick/private.xml#L27
with
```
KeyCode::KEY_6, ModifierFlag::SHIFT_L,
````
(shift+6 == ^ in U.S. input source.)

**Comment by ain** [comment]
Excellent! It works like a charm @tekezo my Estonian mappings are now complete with ain/.dotfiles@0e42c0826ea62ba8b4465f1eaa40763856a536e0

Thanks again for your prompt and very valuable support!
