### ISSUE TITLE
Scripting / Macro capabilities [feature request]

### ISSUE THREAD

**Issue by pinouchon** [tekezo/Karabiner#489]
I love karabiner so far.

What I am missing is the ability to write custom scripts/macro inside Karabiner.

My use case is the following: I want to experiment having deceleration in the key repetition rate (like the scroll has).
So I would like to be able to specify something like this: 

```
When this key is pressed, set the repetition rate to 1000. 
Each passing 3 milliseconds, decrease the rate by 50.
When that key is pressed, stop the repetition
...
```

The way I plan to do it is to have a `<vkopenurldef>` opening an shellscript or applescript with the right params, and then the script calculates the deceleration, and sends the right key at the right rate. But this feels hacky.

Any plan to introduce custom scripting/macros (via javascript for example) inside Karabiner ?

**Comment by tekezo** [comment]
There are no plan to imtroduce script into Karabiner.
Karabiner modifies input events in kernel to avoid key events leaks.
The script does not match with this architecture.

**Comment by pinouchon** [comment]
Fair enough
