### ISSUE TITLE
< and ² getting inverted on AZERTY USB keyboard

### ISSUE THREAD

**Issue by astorije** [tekezo/Karabiner#491]
When plugging an external USB AZERTY / French keyboard (Logitech K310), although the layout places the <kbd><</kbd> key near the left <kbd>shift</kbd> key, and the keyboard actually places the key accordingly, <kbd><</kbd> and <kbd>²</kbd> (just under <kbd>esc</kbd>) are being switched.

Could Karabiner add an option to switch those two?

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.french_fix_logitech_k310/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by astorije** [comment]
Waouh, works great, thanks!
I don't think I would have ever guessed that `BACKQUOTE` and `UK_SECTION` needed switching on a French keyboard...
