### ISSUE TITLE
Support for devices other than keyboards & mice?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tekezo/Karabiner#492]
I've got both a 6DoF (3Dconnexion SpaceMouse) for work, and a complex joystick / throttle setup (Thrustmaster Warthog) for gaming. I'd _really_ like to be able to configure / remap some of the controls / buttons / keys / axes on these to other tasks. I expected KeyRemap4MacBook to be able to do so, but neither of them are showing up in EventViewer at all; is this a task that's just completely unsupported?

**Comment by tekezo** [comment]
Karabiner supports only HID keyboards and mice.
If your devices are not listed in EventViewer > Devices tab, unfortunately, you cannot use these devices in Karabiner.
