### ISSUE TITLE
Add BBEdit to the list of apps in appdef.xml

### ISSUE THREAD

**Issue by pborenstein** [tekezo/Karabiner#493]
Some of us old-timers still use it :)

```xml
<appdef>
  <appname>BBEdit</appname>
  <equal>com.barebones.bbedit</equal>
  <equal>com.barebones.textwrangler</equal>
</appdef>
```

**Comment by tekezo** [comment]
Thank you for information.
I've added it at Karabiner-10.11.4. (the latest beta version)

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates
