### ISSUE TITLE
Don't repeat letters

### ISSUE THREAD

**Issue by kakulukia** [tekezo/Karabiner#496]
Hi!

i wonder if there kinda exists an option to have hight key repeat for like arrows, space, del, backspace but to have key repeat set to a much lower rate or even disable it completely for letters and numbers?

**Comment by tekezo** [comment]
There is not an option in prepared settings.

Increase "Delay Until Repeat" (eg. 10000).
https://pqrs.org/osx/karabiner/document.html.en#keyrepeat

And then use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.set_key_repeat/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by kakulukia** [comment]
AWESOME!!

**Comment by kakulukia** [comment]
:+1:

**Comment by kakulukia** [comment]
@tekezo with the kinda new paypal.me someone can also leave a short message, but now im doing it here .. works and made my day!
