### ISSUE TITLE
Any way to use thumbsense for homerow numbers overlay

### ISSUE THREAD

**Issue by nathanielescribano** [tekezo/Karabiner#497]
been trying out the home row numbers overlay, but have been running into issues when typing quickly.
is there anyway for the trigger to be thumbsense (leave finger on trackpad and press a homerow key for a number) instead of holding on to the spacebar?

**Comment by tekezo** [comment]
Please replace your private.xml with this:
https://github.com/tekezo/Files/blob/master/Karabiner/notsave.private_homerow/private.xml

Then, specify "notsave.private_homerow" in multitouch extension.
<img width="526" alt="screen shot 2015-10-22 at 12 24 05 pm" src="https://cloud.githubusercontent.com/assets/659178/10656266/104c9c58-78b8-11e5-80c4-84c3f634d6ed.png">


How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by nathanielescribano** [comment]
this is amazing!
btw do you have a way to donate to your project?

**Comment by tekezo** [comment]
Thank you.
I accept donations by PayPal.
https://pqrs.org/osx/karabiner/donation.html.en
