### ISSUE TITLE
Virtual keycodes do not repeat

### ISSUE THREAD

**Issue by sxmichaels** [tekezo/Karabiner#498]
I'm writing several shell-based keycodes, in the following form.

```
<!-- Previous song -->
<vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_SHELL_mpc_prev</name>
    <url type="shell">
        <![CDATA[ /usr/local/bin/mpc prev ]]>
    </url>
</vkopenurldef>

<!-- Rewind by 1 second -->
<vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_SHELL_mpc_rewind</name>
    <url type="shell">
        <![CDATA[ /usr/local/bin/mpc seek -00:00:01 ]]>
    </url>
</vkopenurldef>

...

    <!-- Previous song / rewind -->
    <autogen>
        __HoldingKeyToKey__
        ConsumerKeyCode::MUSIC_PREV, ModifierFlag::NONE

        @begin
        KeyCode::VK_OPEN_URL_SHELL_mpc_prev,
        @end

        @begin
        KeyCode::VK_OPEN_URL_SHELL_mpc_rewind,
        @end
    </autogen>

...
```

With this setup, the `VK_OPEN_URL_SHELL_mpc_rewind` command should repeat while I'm holding `MUSIC_PREV`. However, it only gets called once, holding it for longer has no effect. If I replace `VK_OPEN_URL_SHELL_mpc_rewind` with `DELETE`, it does repeat, as one would expect the delete key to. I cannot find any documentation on how to make these virtual keycodes repeat as other keys do; is this a bug?

**Comment by tekezo** [comment]
Karabiner does not repeat `KeyCode::VK_OPEN_URL_*`  in order to prevent running too many processes.

**Comment by hmc-cs-smichaels** [comment]
Is there a workaround for this through Karabiner  then?  I can think of one: have a script that starts rewinding on one trigger and stops on another, and call the first on key down after hold in detected, then call  and the second on keyup. Is that the way you'd recommend doing it or is there a better way? My idea seems like it could be error prone, and I want to do the same for several functions, brightness, volume, etc.

**Comment by tekezo** [comment]
You can call mpc_rewind by sending plural keys with KeyCode::VK_NONE.

```xml
    <autogen>
        __HoldingKeyToKey__
        ConsumerKeyCode::MUSIC_PREV, ModifierFlag::NONE

        @begin
        KeyCode::VK_OPEN_URL_SHELL_mpc_prev,
        @end

        @begin
        KeyCode::VK_OPEN_URL_SHELL_mpc_rewind,
        KeyCode::VK_NONE,
        @end
    </autogen>
```
