### ISSUE TITLE
Missing KeyUp events

### ISSUE THREAD

**Issue by paulfchristiano** [tekezo/Karabiner#499]
I have simple VI mode enabled, and the following custom mapping:

        <autogen>
            __SimultaneousKeyPresses__
            @begin
            KeyCode::SEMICOLON, KeyCode::O,
            @end
            @begin
            KeyCode::P,
            @end
        </autogen>

If I press s, then press p, then release s, then release p, the key up event is not triggered for p. The key down event will continue to repeat until I type another key (so that it will insert the text sppppppp...). If I use a `SYNC_KEYDOWNUP` as an output from the `__SimultaneousKeyPresses__`, it won't be turned off until I type P again (this is the largest problem for me).

This problem also occurs with mousekeysv2, where dp produces dppppp.... It also occurs with `__KeyOverlaidModifier__`, which I assume is doing the same thing as vimode/mousekeys behind the scenes. For example:
 
     <autogen>
        __KeyOverlaidModifier__
        KeyCode::A, ModifierFlag::NONE,

        @begin
        KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_left_modifiers
        @end

        @begin
        KeyCode::A,
        @end
      </autogen>

Causes adown, pdown, aup, pup, to insert apppppp...

The problem occurs with all `__SimultaneousKeyPresses__` mappings (including those whose input is only a single key). It does not occur with `__KeyToKey__` mappings.

For testing purposes I disabled all other mappings and the problem persists.

I noticed the problem after I upgraded to El Capitan and then upgraded to Karabiner 10.11. I think the problem started when I upgraded Karabiner, but it's possible that I just didn't notice it at first after upgrading to El Capitan (though I doubt it, since it causes problems for me every time I type "sp" or "sy").

**Comment by tekezo** [comment]
I cannot reproduce this issue.
Can you reproduce this issue in clean environment such as Guest User?

**Comment by paulfchristiano** [comment]
I was able to reproduce it as follows:

* Guest account on El Capitan. Karabiner 10.11. Builtin keyboard on MacBook Pro (Retina, 13-inch, Late 2012)

* Turn on "Simple Vi Mode v2"

* Turn on "Engelbart > OPTION." Only these two settings are on.

* Go to the Event Viewer.

* Press S. Wait 50ms. Press K+L. Wait 50ms. Release S. Wait 50ms. Release K+L. 

If I wait too long between pressing K+L and releasing S then it will drop the S. But as long as that doesn't happen I don't think the timing matters.

* The Event Viewer shows "KeyDown s, KeyUp s, FlagsChanged +OPT"

The result is that the option key is now held down, and I have to press the option key again to release it.

The desired behavior is "KeyDown s, KeyUp s, FlagsChanged +OPT, FlagsChanged -OPT."

**Comment by tekezo** [comment]
Thank you!
I have been able to reproduce this issue.
I'll fix this issue soon. Please wait for a while.

**Comment by tekezo** [comment]
I've fixed this issue at v10.11.13.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by paulfchristiano** [comment]
That fixed it, thanks!

**Comment by paulfchristiano** [comment]
I'm having a similar issue with `__KeyOverlaidModifier__` and `VK_CONFIG_SYNC_KEYDOWNUP`, this time when they are typed in the opposite order.

I have S set to enable vimode and the mapping:

`__KeyToKey__ KeyCode::E, @begin KeyCode::E, KeyCode::VK_CONFIG_KEYDOWNUP_edown`

If I type es, then eventviewer correctly registers "e down, e up, s down, s up." But the edown modifier isn't removed, and I have to type "e" again to reset it.

I think that this was introduced by updating just now, though it might have existed before and I just didn't notice it because the other issue is more common. Let me know if you can't reproduce the issue and I can poke around a bit more.

I was able to work around this by changing the order of KeyCode::E and VK_CONFIG. If I do that, everything is fine.

Sorry to give you so much trouble, I really appreciate all of your work on Karabiner!

**Comment by tekezo** [comment]
Thank you for feedback.
I reproduced new problem.
I'll fix this issue soon. Please wait.

**Comment by tekezo** [comment]
I've fixed this issue at v10.11.14.
Please confirm the latest beta version.

**Comment by paulfchristiano** [comment]
This seems to fix it. Thanks!
