### ISSUE TITLE
Karabiner will not share modifiers between Wireless Apple Keyboard and Belkin yourtype wireless keypad

### ISSUE THREAD

**Issue by gramirezjuan** [tekezo/Karabiner#500]
I'm running OSX 10.9.5 and want to share modifiers between my Apple wireless keyboard and Belkin yourtype keypad. The problem I'm having is that Osx recognizes the keypad as another keyboard so it won't allow shortcuts to be applied if I press the modifiers in the apple keyboard and other keys in the keypad. Since an implicit behavior of Karabiner is to share modifier keys with all connected keyboards, I thought installing it would solve the problem, but it hasn't worked. I verified that Karabiner was working by briefly enabling a change of key in the apple keyboard and that worked fine. I also verified that both keyboards appeared under "devices" in Event viewer. For the Belkin keypad the Vendor Id is 0x0411 & Product Id is 0x0244. I tried enabling "Allow devices which vendor Id and product Id are zero but this didn't work either.

 As of now I have nothing enabled in Karabiner.

Is there anything that you could recommend to make this work? Any help would be appreciated.

**Comment by tekezo** [comment]
The modifier sharing should work in OS X 10.9.5.

Are you using third vendor driver?
Could you show me your devices tab in EventViewer?

**Comment by gramirezjuan** [comment]
![screen shot 2015-10-27 at 6 21 01 pm](https://cloud.githubusercontent.com/assets/15336581/10774470/b015d0ce-7cd7-11e5-9c2b-5c91cf5245f6.png)

**Comment by gramirezjuan** [comment]
Details:
 
 YourType Wireless KeyPad:
  Address:	F0-65-DD-78-CD-91
  Major Type:	Keyboard
  Minor Type:	Peripheral
  Services:	Broadcom Bluetooth Wireless Keyboard SDP Server, Broadcom Bluetooth Wireless  Keyboard                        , Broadcom Bluetooth Wireless Keyboard PnP Server
  Paired:	Yes
  Configured:	Yes
  Connected:	Yes
  Manufacturer:	Broadcom (0x5, 0x2211)
  Firmware Version:	0x0108
  Vendor ID:	0x0411
  Product ID:	0x0244
  Class of Device:	0x05 0x10 0x2540
  AFH:	On
  AFH Map:	FFF00000E01F0
  RSSI:	-61
  Role:	Master
  Host Connectable:	Yes
  EDR Supported:	No
  eSCO Supported:	No
  SSP Supported:	Yes

**Comment by tekezo** [comment]
Thank you for information!

I cannot see any strange points in your information.
Could you show me the result of `ioreg -l` in Terminal?

**Comment by gramirezjuan** [comment]
Tank you for the quick response. I had to send results as an attachment to your email because  the ioreg -l response in Terminal is to large and will not be accepted as a  comment.
 


     On Wednesday, October 28, 2015 3:56 AM, Takayama Fumihiko <notifications@github.com> wrote:
   

 Thank you for information!I cannot see any strange points in your information.
Could you show me the result of ioreg -l in Terminal?—

**Comment by gramirezjuan** [comment]
Tank you for the quick response. I had to send results as an attachment to your email because  the ioreg -l response in Terminal is to large and will not be accepted as a  comment.

**Comment by tekezo** [comment]
The attachment file has been removed by github.
Could you send me directly? tekezo@pqrs.org

**Comment by gramirezjuan** [comment]
Please see attachment. Thanks! 


     On Thursday, October 29, 2015 3:41 AM, Takayama Fumihiko <notifications@github.com> wrote:
   

 The attachment file has been removed by github.
Could you send me directly? tekezo@pqrs.org—

**Comment by tekezo** [comment]
I cannot receive your mail...
Could you paste the result to https://gist.github.com/ ?

**Comment by gramirezjuan** [comment]
I must be doing something wrong. I copied ioreg -l in  terminal and pressed enter, but received a very long response. I tried to copy it to github, but  it said it was to long. So I saved it as a pdf and it amounted to 1099 pages. 
Also Github will not let me include the pdf as an attachment. 

Is there any other way to send you the ioreg -l result?

**Comment by tekezo** [comment]
Hmm, you can dump the result to text file by this command in Terminal.

```shell
ioreg -l > ~/Desktop/ioreg.txt
```

I guess you can open it by text editor and paste full text into gist.
But if you are rejected from github, please create separate gists.

**Comment by gramirezjuan** [comment]
I created a separate repository which accepted the ioreg. txt. Also, I included you as a collaborator. Sorry that it took so long, I am learning how to use Github. Please let me know if you are able to see the file. Thanks.

**Comment by tekezo** [comment]
Thank you for new repository.

There is almost empty file at the moment.
https://github.com/gramirezjuan/Karabiner-help/blob/master/ioreg.%20txt
Could you update the file?

**Comment by gramirezjuan** [comment]
Please verify: https://github.com/gramirezjuan/Karabiner-help/commit/78e3f4c2f91ec7671056e52c8ec634ef5aa16213

**Comment by tekezo** [comment]
Thank you for ioreg information!
Your Belkin yourtype wireless keypad is controled with ControllerMate.
Please detach ControllerMate from your device and then confirm this issue again.

**Comment by gramirezjuan** [comment]
Completely deleted ControllerMate from system but I still can't get modifiers to share between Keyboard and Belkin Keypad. Posted new ioreg.txt on repository. 
Please verify:
 https://github.com/gramirezjuan/Karabiner-help/files/25058/ioreg.txt

Thanks.

**Comment by tekezo** [comment]
Thank you for confirmation!
Your ControllerMate uninstallation is succeeded.
So, there is another cause of this issue.

Please let me know your environment.

I understand you are using 3 keyboards. Is it right?
* MacBook Pro built-in keyboard.
* Apple wireless keyboard.
* Belkin yourtype wireless keypad.

Are the built-in keyboard and Apple wireless keyboard sharing modifier keys?

**Comment by gramirezjuan** [comment]
Those are the 3 keyboards that I use. The modifier sharing works between the MacBook Pro built-in keyboard & the Apple wireless keyboard. Neither of them share modifiers with the Belkin yourtype wireless keypad.

**Comment by tekezo** [comment]
Thank you for information.

I doubt that Belkin yourtype wireless keypad does not send input events by standard way, or all non-Apple bluetooth keyboards has the issue.

I don't have Belkin yourtype wireless keypad, but I'll confirm this issue with generic bluetooth keyboard.
Please wait for a while.

**Comment by gramirezjuan** [comment]
Thanks for the response. I'll wait.

**Comment by gramirezjuan** [comment]
Hi! I just realized that after uninstalling ControllerMate, the modifiers are sharing. I'm able to use shortcuts that require modifier sharing in different applications. So your solution worked.

The error that I committed verifying this was that I used Screen Capture by pressing "Shift" and "Command"  in the Apple  wireless Keyboard and pressing "3" in the Belkin YourType Keypad but what I didn't realize is that this won't work since in the Belkin keypad the "3" does not have a shift function of "#" like it does on the Apple wireless keyboard. So logically it won't work. I failed to see the shortcut as (Command + #) instead of (Command +Shift +3).

Thank you for all your help.

**Comment by tekezo** [comment]
It's great!

The numpad numbers and normal numbers are different.
You can confirm them by EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer


Please use new setting by this private.xml if you want to use numpad as normal number:
https://github.com/tekezo/Files/blob/master/Karabiner/private.numpad_to_number/private.xml

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by Neku** [comment]
I've got the same issue on 10.12.1

**Comment by tekezo** [comment]
@Neku
Confirm your devices are not controlled under ControllerMate.
If you are using "Don't remap xxx" settings in Karabiner, the excluded devices do not share the modifiers.

**Comment by Neku** [comment]
I'm using controllermate to remap the foot switches to modifiers keys (they output "A" "B" "C"). Is that achievable through Karabiner? @tekezo

**Comment by tekezo** [comment]
You have to choose either controllermate or Karabiner.

You might be able to change the foot switches by Karabiner with private.xml.
https://pqrs.org/osx/karabiner/xml.html.en#devicedef

**Comment by Neku** [comment]
I uninstalled controllermate, but using the eventviewer I can't see the device list. The main tab shows the key pressed. I tried to use the values that I find in system report, but still doesn't work.
