### ISSUE TITLE
Increase mouse tilt event proc rate

### ISSUE THREAD

**Issue by ivancuric** [tekezo/Karabiner#502]
I have the scrollwheel tilt bound to middle click. However, successive clicks aren't registered properly, and neither is holding down the button.

```
eventType:MouseDown       code:0x2        name:middle          flags:                                   misc:{752, 119} 1
eventType:MouseUp         code:0x2        name:middle          flags:                                   misc:{752, 119} 1
eventType:MouseDown       code:0x2        name:middle          flags:                                   misc:{752, 119} 1
eventType:MouseUp         code:0x2        name:middle          flags:                                   misc:{752, 119} 1
```

The event pair ticks every 500ms or so, and successive clicks in a 500ms window aren't registered properly.

**Comment by tekezo** [comment]
These events are actually sent by your device.
So, our options are limited.

* Karabiner can ignore successive events. Only the first events will be sent to app.
* Karabiner can send mousedown and mouseup events with properly interval at physical MouseDown events.

Please use this setting.

```xml
    <block>
      <!-- ignore successive middle click -->
      <lastpressedphysicalkey_only>PointingButton::MIDDLE</lastpressedphysicalkey_only>
      <!-- elapsed time since last pressed less than 600ms -->
      <elapsedtimesincelastpressed_lessthan>Millisecond::RawValue::600</elapsedtimesincelastpressed_lessthan>
      <!-- drop event -->
      <autogen>__KeyToKey__ PointingButton::MIDDLE, KeyCode::VK_NONE</autogen>
    </block>
    <autogen>
      __KeyToKey__
      PointingButton::MIDDLE,

      <!-- send mousedown and mouseup event at the same time. -->
      PointingButton::MIDDLE,
      KeyCode::VK_NONE,
    </autogen>
```

If the middle click is not recognized in app, 
please increase "Wait before and after a pointing device click event" parameter.
(It is in "Key Repeat" tab in the stable release, "Parameters" tab in the beta version.)

![151029-0001](https://cloud.githubusercontent.com/assets/659178/10817809/d39e227c-7e7f-11e5-8499-e2bebadeb500.png)
