### ISSUE TITLE
Logitech Harmony Hub

### ISSUE THREAD

**Issue by generator85** [tekezo/Karabiner#503]
Hi, I'm trying to remap the keys my Logitech Harmony Hub sends, but it doesn't seem to work. The EventViewer shows the events exactly like my USB keyboard, but they aren't remapped.

The Harmony Hub shows up in the devices list as "Harmony Keyboard", but the Vendor ID and Product ID show up as 0x0000.

Is this device not supported?

**Comment by tekezo** [comment]
Karabiner ignores devices which their Vendor ID and Product ID are zero.
Please enable this setting.
![151031-0001](https://cloud.githubusercontent.com/assets/659178/10862271/44dae72a-7fe5-11e5-95c8-9f4124d77388.png)

**Comment by generator85** [comment]
Thanks, that did the trick! Is there a serious risk with system crashes?

**Comment by tekezo** [comment]
Some devices which does not valid vendor id and product id causes the system crash immediately after they are attached to Karabiner.
Thus, Karabiner ignores them in default.

If your Logitech Harmony Hub works fine, there is no problem.

**Comment by generator85** [comment]
Great, thanks!
