### ISSUE TITLE
Disable "Command_R to Option_R" on left click

### ISSUE THREAD

**Issue by jlgrall** [tekezo/Karabiner#504]
I am using KeyRemap4MacBook on an old MacBook Pro with Mac OS X 10.6.8
In `Resources/include/checkbox/languages/french.xml` there is a nice remapping: _Dvorak and bépo: Command_R to Option_R_
```xml
    <item>
      <name>Dvorak and bépo: Command_R to Option_R</name>
      <identifier>remap.french_inputmode_dvorak_bepo_command_r_to_option_r</identifier>
      <inputsource_only>DVORAK,BEPO</inputsource_only>
      <autogen>__KeyToKey__ KeyCode::COMMAND_R, KeyCode::OPTION_R</autogen>
    </item>
```
It is nice because it allows me to use the right Command as an Option key when typing bépo.
But I would like this behavior to be disabled when I click. So that a Command_R + Click would not be modified to Option_R + Click. That would allow me to use the right Command key to Command-click links in my browser to open them in new tabs, as it does by default.

Here is my attempt, but it doesn't work:
```xml
<item>
	<name>Dvorak and bépo: Disable "Command_R to Option_R" on click</name>
	<identifier>remap.inputmode_dvorak_bepo_command_r_to_option_r_except_click</identifier>
	<inputmode_only>DVORAK,BEPO</inputmode_only>
	<autogen>__PointingButtonToPointingButton__ PointingButton::LEFT, ModifierFlag:: COMMAND_R, PointingButton::LEFT, ModifierFlag::NONE</autogen>
</item>
```
Any tip or help would be welcome. I didn't find a proper way to do it in the documentation.

**Comment by tekezo** [comment]
You should restore option_r+click to command_r+click.

```xml
    <autogen>
      __PointingButtonToPointingButton__
      PointingButton::LEFT, ModifierFlag::OPTION_R,
      PointingButton::LEFT, ModifierFlag::COMMAND_R,
    </autogen>
```

The autogen also change physical right option key + click.
If you don't want it, use this autogen together.
```xml
<autogen>__KeyToKey__ KeyCode::OPTION_R, KeyCode::OPTION_L</autogen>
```

**Comment by jlgrall** [comment]
Thanks, the disadvantage is that it changes the OPTION_R to the OPTION_L. But it should be good enough in most cases, as I don't think I need to differentiate between those 2 keys in practice.

Thanks a lot, it is working !
