### ISSUE TITLE
"Use PC Style Lock Screen" (L character) not adjusted when "Use Dvorak Style Layout" is enabled

### ISSUE THREAD

**Issue by dhiltonp** [tekezo/Karabiner#506]
When "Use Dvorak Style Layout" is enabled, the lock key is not remapped as well, so an equivalent of "N" instead of "L" is used to lock, which is weird.

**Comment by tekezo** [comment]
The prepared setting is designed for qwerty.

Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.dvorak_pc_style_lock_screen/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by dhiltonp** [comment]
Installed.

I can see why the remapping is specific to one layout or another, but I found it a little confusing.

Thanks for the response!
