### ISSUE TITLE
Ubiquitous vim mode uses keycode, not character for vim mappings.

### ISSUE THREAD

**Issue by Grazfather** [tekezo/Karabiner#507]
I use colemak, built into the OS. When turn on ubiquitous vim mode, it uses 'hnei' which takes place of hjkl on colemak. I think this behaviour is incorrect.

I'm not sure how this is done in the OS (not sure how the event viewer still sees the real keycodes), because it seems that when I select colemak _from Karabiner_ the event viewer shows that I actually send the 'hnei' keycodes.

This might suggest that changing layout through Karabiner is the right solution, but I disagree, since then I will be stuck in qwerty when I first boot up the computer.

**Comment by tekezo** [comment]
Please use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.vi_hjkl/private.xml

(This private.xml does not add new setting. It is applied automatically.)

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by Grazfather** [comment]
Interesting. Thank you!
