### ISSUE TITLE
Add 'tarmak' steps as alternative layouts.

### ISSUE THREAD

**Issue by Grazfather** [tekezo/Karabiner#508]
You have included the CarpalxQ steps as separate layouts. I think it would be nice if you could do the same for [Tarmak](http://forum.colemak.com/viewtopic.php?id=1858) which is the same idea, but for colemak.

**Comment by tekezo** [comment]
I've added Tarmak at Karabiner-10.14.3. (The latest beta version)
![151107-0001](https://cloud.githubusercontent.com/assets/659178/11015411/6810c464-85a1-11e5-8121-b704b06ed0d6.png)

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by Grazfather** [comment]
You are fantastic!

**Comment by Grazfather** [comment]
FYI, they are linking to it in the Tarmak thread: http://forum.colemak.com/viewtopic.php?id=1858

Very much appreciated!

**Comment by garrettw** [comment]
How do I get Tarmak on the latest version? Importing Colemak from [your website](https://pqrs.org/osx/karabiner/complex_modifications/) doesn't add it, nor is Tarmak listed on that page.

**Comment by bretfunk** [comment]
I also would like to add Tarmak but don't see how to do it.
