### ISSUE TITLE
Button4 + __PointingRelativeToKey__

### ISSUE THREAD

**Issue by afterdesign** [tekezo/Karabiner#510]
Hi, Is there option to bind those 2 things together ? Logitech performance mx is doing this and I would love to get this functionality with microsoft sculpt ergonomic mouse. I can bind "windows key" with movement because it's sending the command_r and I can use it as modifier. But I had no luck with the other key which is sending the Button4 information.

**Comment by tekezo** [comment]
We might do that.
Please describe your desired behavior.

**Comment by afterdesign** [comment]
So I think this example is the best answer. Right now I'm using another button on the mouse and it's sending the ```COMMAND_R``` and with right/left I'm using next/prev in browsers and so, with up/down I'm switching spaces:

```xml
<autogen>
    __PointingRelativeToKey__ ModifierFlag::COMMAND_R,
    PointingRelative::LEFT, KeyCode::BRACKET_LEFT, ModifierFlag::COMMAND_L,
    PointingRelative::RIGHT, KeyCode::BRACKET_RIGHT, ModifierFlag::COMMAND_L,
    PointingRelative::UP, KeyCode::CURSOR_LEFT, ModifierFlag::CONTROL_L,
    PointingRelative::DOWN, KeyCode::CURSOR_RIGHT, ModifierFlag::CONTROL_L
</autogen>
```

I would love to get options for other buttons. For example on my performance mx I'm using scroll wheel + up/down to control volume and other buttons to skip to next/prev song in spotify (with some help of applescript and alfred).

**Comment by tekezo** [comment]
How about this private.xml?

```xml
    <autogen>
      __KeyToKey__
      PointingButton::BUTTON4,
      PointingButton::BUTTON4, ModifierFlag::BUTTON4,
    </autogen>

    <autogen>
      __PointingRelativeToKey__ ModifierFlag::BUTTON4,
      PointingRelative::LEFT, KeyCode::BRACKET_LEFT, ModifierFlag::COMMAND_L,
      PointingRelative::RIGHT, KeyCode::BRACKET_RIGHT, ModifierFlag::COMMAND_L,
      PointingRelative::UP, KeyCode::CURSOR_LEFT, ModifierFlag::CONTROL_L,
      PointingRelative::DOWN, KeyCode::CURSOR_RIGHT, ModifierFlag::CONTROL_L
    </autogen>
```

I might misunderstand your desire. If so, let me know.

**Comment by afterdesign** [comment]
@tekezo yeah, that was it. I didn't find info that I can register button as a modifier. Thanks !

**Comment by tekezo** [comment]
It's great.
If you don't want to send the button4 event to app, please this autogen instead.

```xml
    <autogen>
      __KeyToKey__
      PointingButton::BUTTON4,
      KeyCode::VK_MODIFIER_BUTTON4,
    </autogen>
```
