### ISSUE TITLE
Conflict between an application hotkey and option-backquote

### ISSUE THREAD

**Issue by solarsailer** [tekezo/Karabiner#511]
Hello,

I switched to a QWERTY keyboard a few days ago and I try to map accents to certain keys since then (I'm french and I still type French regularly).

From what I read, Karabiner cannot print special characters directly, so I execute a certain combination of keys to "trigger" a character instead (eg.. I trigger `option-E then E` to print an `é` when I press `option-o`). Is this the better way to do that or am I missing a more obvious and simpler solution?

My problem is that I bind Fantastical's menubar app to `option-backquote` (which is a combination that allows typing backquoted vowels like `ò` or `à`). If I try to print an `è`, I must do `option-backquote then E`. And then, Fantastical opens and search for an `e` instead of printing an `è`. I tried many things but I can't find a way to prevent this conflict.

For the moment, I disabled Fantastical hotkey but I would love to have a way to prevent Fantastical to open when I execute this specific sequence of keys. Is it possible? Can I set a priority or can I stop the hotkey propagation in this case? :)

Thanks!

**Comment by tekezo** [comment]
> Karabiner cannot print special characters directly, so I execute a certain combination of keys to "trigger" a character instead

You are right.
There is no workaround in Karabiner.

But there are some workarounds which are not related with Karabiner.

* Change Fantastical hotkey to another shortcut.
* Making your own keylayout by Ukelele.
  http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele

**Comment by solarsailer** [comment]
Okay. Thanks for the pointers.
