### ISSUE TITLE
Is there any possibility to remove the Alert when Karabiner not located in /Applications ?

### ISSUE THREAD

**Issue by chinanoahli** [tekezo/Karabiner#513]
I noticed that even though Karabiner not located in /Applications, it can still functional in the version of 10.14.0.
It better then the old version before Karabiner re-update.
But the Alert still popup when Karabiner not located in /Applications.

```
Karabiner Alert
Karabiner.app should be located in /Applications/Karabiner.app.
Do not move Karabiner.app into others folders.
```

Best Wishes

**Comment by tekezo** [comment]
The updater and uninstaller does not work if you moved Karabiner.app from /Applications.
Please do not change the location.
