### ISSUE TITLE
feature: disable slow mission control ctrl+up/down

### ISSUE THREAD

**Issue by tablatronix** [tekezo/Karabiner#514]
http://apple.stackexchange.com/questions/66433/remove-shift-key-augmentation-for-mission-control-animation/115698#115698

These do not seem to be included in the existing "slow" option.

**Comment by tekezo** [comment]
I think Karabiner does not satisfy your desire.

I understand that you want to use ctrl+shift+up/down in Sublime Text 2.
Is it right?

Karabiner cannot change the Mission Control behavior.
Therefore, we cannot pass ctrl+shift+up/down to other apps even if using Karabiner.

We can drop ctrl+shift+up/down events by Karabiner,
but you cannot use ctrl+shift+up/down in Sublime Text 2 with that setting.

**Comment by tablatronix** [comment]
I only linked that as it shows the plist keys to remap.
I thought it could be suppressed so it can be used in other apps as is done with the "slow" toggle.

<img width="773" alt="screen shot 2015-11-13 at 10 00 30 am" src="https://cloud.githubusercontent.com/assets/807787/11150463/c4cabca0-89ed-11e5-9120-2eda9d34c51b.png">

**Comment by tekezo** [comment]
OK.
I've updated the prepared setting at Karabiner 10.14.8.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates
