### ISSUE TITLE
ShowStatusMessage doesn't respect filters

### ISSUE THREAD

**Issue by undeadlegion** [tekezo/Karabiner#515]
When you have a status message inside a filter, it shows up anyways.

``` xml
<item>
	<block>
	<config_only>option.messages.hidden</config_only>
	<autogen>__KeyToKey__ KeyCode::KEY_1, KeyCode::P</autogen>
	<autogen>__ShowStatusMessage__ message still shows up</autogen>
	</block>
</item>
<item>
	<name>Hide Messages</name>
	<identifier vk_config="true">option.messages.hidden</identifier>
</item>
```

**Comment by tekezo** [comment]
Thank you for feedback.

`__ShowStatusMessage__` does not support filters at the moment.
And it's difficult to support.

Please move `__ShowStatusMessage__` into option.messages.hidden.

```xml
  <item>
    <name>Core</name>
    <identifier>private.core</identifier>
    <block>
      <config_only>option.messages.hidden</config_only>
      <autogen>__KeyToKey__ KeyCode::KEY_1, KeyCode::P</autogen>
    </block>
  </item>
  <item>
    <name>Hide Messages</name>
    <identifier vk_config="true">option.messages.hidden</identifier>
    <autogen>__ShowStatusMessage__ message still shows up</autogen>
  </item>
```

**Comment by undeadlegion** [comment]
Okay. Probably not worth the time compared to filling out the docs. 
Maybe just a note in the ShowStatusMessage, to save someone else a potential headache. (I was using messages to debug virtual modifiers and notsave configs)

**Comment by undeadlegion** [comment]
Is there a way right now to disable the modifier locked message for built in modifiers like virtual ones?
(e.g. notify="false" to hide only the Lock:shift message)

**Comment by tekezo** [comment]
OK. I'll update docs.

> Is there a way right now to disable the modifier locked message

There is no way to do for now.
But I can add the option.

Do you allow to hide the locked message anytime?
(I think that hiding the locked message will confuse you.)

**Comment by undeadlegion** [comment]
Looking at it again, that's probably an unnecessary change.
My original idea was to lock shift, then use a notsave.config to capitalize the next letter and then unlock it.

It seemed like it's not possible to unlock after ANY_KEY is pressed, so I ended up mapping every key. I could just add a shift modifier to each key instead of locking. Problem solved.
 
It looks something like this:
```
	<item hidden="true">
		<identifier vk_config="true">notsave.shift_toggle</identifier>
		<autogen>__ShowStatusMessage__ TOGGLE </autogen>
			<autogen>__KeyToKey__ KeyCode::Q, KeyCode::Q, {{SHIFT_TOGGLE_OFF}}</autogen>
			<autogen>__KeyToKey__ KeyCode::W, KeyCode::W, {{SHIFT_TOGGLE_OFF}}</autogen>
			<autogen>__KeyToKey__ KeyCode::E, KeyCode::E, {{SHIFT_TOGGLE_OFF}}</autogen>
			<autogen>__KeyToKey__ KeyCode::R, KeyCode::R, {{SHIFT_TOGGLE_OFF}}</autogen>
	</item>
```

**Comment by tekezo** [comment]
Your desire is very similar with sticky modifiers.
Please search "sticky shift" in prepared settings and try the sticky modifiers.

**Comment by undeadlegion** [comment]
Ah.. okay. Guess never really knew the effect of sticky keys. Thanks!
