### ISSUE TITLE
Setting key repeat smaller than 30 ms is ignored

### ISSUE THREAD

**Issue by danilcha** [tekezo/Karabiner#520]
El Capitan. I can set any key repeat delay, even 10 ms, but in fact when I press and hold a key I sill get ~30 keystrokes per minute.

**Comment by tekezo** [comment]
Please enable this setting.

![151123-0001](https://cloud.githubusercontent.com/assets/659178/11331296/27f963d8-91fc-11e5-8b3c-b88a307490d8.png)

**Comment by danilcha** [comment]
Thank you! It worked. You should write this on ‘Key Repeat’ page in small font.

**Comment by tekezo** [comment]
Thank you.

I decided to delete the limitation.

The setting has been added a long time ago.
The setting UI did not support mouse and we had to set key repeat rate by keyboard input.
So the limitation was necessary.

But I think this limitation is no more necessary and it confuses people.

**Comment by danilcha** [comment]
That will be funny. For a long time I had these settings set to 20 ms delay and 10 ms repeat and thought that this is how it feels like. Imagine a person with such settings getting the next update without the limit :)

**Comment by tekezo** [comment]
The limitation has been removed at Karabiner-10.14.16.
