### ISSUE TITLE
shortcut to close or hide specific application

### ISSUE THREAD

**Issue by nbara** [tekezo/Karabiner#521]
It would be very useful to be able to set a certain key combination to hide (or at least close) an application. 

For instance, that could be used to set a certain key combination to bring the application to the foreground, and if already in the foreground then the same key combination would hide it.

**Comment by tekezo** [comment]
Please use Apple Script:
http://brettterpstra.com/2011/01/22/quick-tip-applescript-application-toggle/

You can run Apple Script from shortcut by using `<vkopenurldef>`.
https://pqrs.org/osx/karabiner/xml.html.en#vkopenurldef

**Comment by nbara** [comment]
Thank you @tekezo 

Do I need to save the apple script as a .app in Automator for this to work? It seems a bit have-handed...

**Comment by tekezo** [comment]
You can run apple script via shell with osascript comment.

Example:
https://github.com/tekezo/Karabiner/blob/version_10.14.0/src/core/server/Resources/vkopenurldef.xml#L278

Of course, you can save your apple script to file and execute from the file.

**Comment by nbara** [comment]
Excellent, working now thanks!

For those who are wondering, here's how it looks:
```xml
<vkopenurldef>
     	<name>KeyCode::VK_OPEN_URL_TOGGLE_APP</name>
     	<url type="shell">
      	       <![CDATA[/usr/bin/osascript pathtoapplescript.scpt]]>
	</url>
        <background />
</vkopenurldef>
```
