### ISSUE TITLE
Karabiner causes ImageJ/Fiji plugin to freeze

### ISSUE THREAD

**Issue by skalarproduktraum** [tekezo/Karabiner#522]
When Karabiner with activated AXNotifier is used on El Capitan in conjunction with ImageJ or Fiji (http://fiji.sc), at least the ClearVolume viewer (github.com/clearvolume/clearvolume) freezes upon startup. I feel this issue is related to #259 and #255, even though the Event Viewer window tells all of Fiji's windows are already exempt:
![screen shot 2015-11-25 at 18 10 56](https://cloud.githubusercontent.com/assets/586495/11403986/fce51cbe-939f-11e5-97aa-af23b2702d4c.png)

If I disable AXNotifier, Fiji and ClearVolume work as expected.

OS X version is 10.11.1,
Karabiner version is 10.14.18,
Java JRE/JDK is 1.8.0_66

Edit: Fiji's process name is `ImageJ-macosx`, the bundle identifier is `org.fiji`.

**Comment by tekezo** [comment]
Thank you for feedback.
I've fixed this issue at Karabiner-10.14.19.

Please upgrade Karabiner to the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by skalarproduktraum** [comment]
Thanks for the quick fix, I just verified it works :)

Out of curiosity: Do you know what the root cause of these hangs is? When looking at the thread dump of our plugin - while it was hanging - I noticed an AWT thread being blocked.

**Comment by tekezo** [comment]
Thank you for confirmation!

This issue is caused by AXObserverCreate.
https://developer.apple.com/library/mac/documentation/ApplicationServices/Reference/AXUIElement_header_reference/

I believe it's an issue of Java.
Java apps will be hang when we observe java apps using the accessibility API.

**Comment by skalarproduktraum** [comment]
Interesting, thanks for the info! I'll close the issue now. Also thanks again for fixing it so fast :)
