### ISSUE TITLE
Remapped CapsLock not acting like a modifier

### ISSUE THREAD

**Issue by appsforartists** [tekezo/Karabiner#524]
I just installed Karabiner/Seil on a new machine running 10.11.1.  I imported my settings from an old Mountain Lion machine.

I'm trying to map Caps to Cmd+Opt+Shift+Ctrl.  In the Keyboard Viewer (accessible from the Keyboard menu), I can see that it's registering as an instant press/release of those buttons, even though I'm holding them down.  Did something change to cause this?  What's the workaround?

You can see my settings at the bottom of [this gist](https://gist.github.com/appsforartists/f63eb430eab72989072f).

**Comment by tekezo** [comment]
If you did not do "No Action" configuration, this issue might happen.

Please confirm "No Action" configuration.
https://pqrs.org/osx/karabiner/seil.html.en#noaction

**Comment by appsforartists** [comment]
D'oh!  Forgot to do that.

Thanks @tekezo!
