### ISSUE TITLE
How to make left-option key as meta key for emacs in osx yosemite

### ISSUE THREAD

**Issue by mozammilwy** [tekezo/Karabiner#525]

**Comment by tekezo** [comment]
If you are using standalone emacs, use mac-option-modifier.

`(setq mac-option-modifier 'meta)`

**Comment by samv** [comment]
You can also do this from the menus, but what I want is the right option to still select the alternate character group, but the left option to be meta (similar to the Sun Type 4 Unix keyboard layout).  Inside emacs, I can set the right option key to be Meta, but not just the left one.  In Karabina, the I see an "Option L to Option R" setting, but no corresponding reverse option.

**Comment by tekezo** [comment]
You can swap left and right options with new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.swap_options/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by samv** [comment]
This worked perfectly!  Thanks so much!  Now to complete the rest of my keyboard symbol mapping :-).

![keyboard](https://cloud.githubusercontent.com/assets/41057/11852125/281877a4-a3eb-11e5-8bc8-236989cad00f.jpg)
