### ISSUE TITLE
Option "Command-left/right arrow to option-left/right arrow" works inconsistently

### ISSUE THREAD

**Issue by IshmaelYavitz** [tekezo/Karabiner#527]
I'm using Karabiner 10.14.0.

I have the option "Command-left/right arrow to option-left/right arrow" turned on under "Change Arrow(Up/Down/Left/Right) Key".

It works sometimes (i.e. the keys are properly remapped) and doesn't work other times (i.e. the keys are not properly remapped and Command+Arrow does what Command+Arrow always does.)

When it works sometimes, during that time period it works in all programs.  Similarly, during the times it's not working, it doesn't work in all programs.

That's all I know so far.

**Comment by tekezo** [comment]
Thank you for feedback.

The setting checks the frontmost application and will be disabled when you are using virtual machine and remote desktop client.

I guess Karabiner fails to detect the frontmost application on your machine.

Please confirm the properly application will be shown in EventVIewer > App tab.
https://pqrs.org/osx/karabiner/xml.html.en#appdef-steps

**Comment by IshmaelYavitz** [comment]
I figured it out by disabling the custom mappings I've added.  This may be a case of user confusion.  :)

I use a PC keyboard.  I have a set of mappings I wrote to map the numeric keypad keys to their non-numeric equivalents - arrows, Home, Page Up, etc.

It turns out that whereas I thought Karabiner was acting inconsistently, it actually wasn't: it works when I use Command+InvertedTArrowKeys and doesn't work when I use Command+NumericKeypadArrowKeys.

Even though I map Left/4 to Left Arrow and Right/6 to Right Arrow, that doesn't appear to be sufficient for  "Command-left/right arrow to option-left/right arrow".

Is that the expected behavior?

I'm guessing the solution is to _not_ use  "Command-left/right arrow to option-left/right arrow" but rather to add custom mapping specifically for Command+Left/4 and Command+Right/6 to Option+Left and Option+Right respectively?

**Comment by tekezo** [comment]
> Is that the expected behavior?

Yes.
Karabiner does not allow you the recursive mappings.

Please add these autogens into the top of your custom settings.
```xml
    <autogen>
      __KeyToKey__
      KeyCode::KEYPAD_4, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_COMMAND,
      KeyCode::CURSOR_LEFT, ModifierFlag::OPTION_L,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::KEYPAD_6, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_COMMAND,
      KeyCode::CURSOR_RIGHT, ModifierFlag::OPTION_L,
    </autogen>
```

Note:
Karabiner applies only the first matched <autogen>.
So, you should put above autogens to the top of your custom settings.
https://pqrs.org/osx/karabiner/xml.html.en#order

**Comment by IshmaelYavitz** [comment]
Works great.  Thanks!
