### ISSUE TITLE
what is he keycode of those spanish letters (Ñ,Ç)

### ISSUE THREAD

**Issue by Cha72** [tekezo/Karabiner#528]
Hi,
I have a Spanish keyboard and would like to remap my t (key does not work anymore) to my Ñ or Ç symbole. I do not find the Keycode for those, and need help.
thanks
![capture d ecran 2015-12-10 a 11 00 24](https://cloud.githubusercontent.com/assets/16243042/11720486/78465d08-9f2d-11e5-9816-8eb63aad1fea.png)

**Comment by tekezo** [comment]
Please use new settings by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.broken_keyboard_8/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml


Note:
You can investigate your keycode by EventViewer:
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by Cha72** [comment]
Thank you so much!!!!
