### ISSUE TITLE
Fn to Control_L on Magic Keyboard on El Capitan does not work

### ISSUE THREAD

**Issue by tobsn** [tekezo/Karabiner#529]
tried everything... is there maybe a problem i couldn't find while trying to solve it myself?

**Comment by tekezo** [comment]
Thank you for feedback.

I don't have Magic Keyboard, so I can not reproduce this issue yet.

But there are similar known issue that OS X ignores fn key events from non Apple keyboards.
And Apple began using different vendor id for bluetooth keyboard from Magic Keyboard.
The change made this issue.

I don't have work arounds for this issue yet.
I'm trying to enable fn key on non Apple keyboard.
I'll share the work around for this issue if I found it.

**Comment by tobsn** [comment]
@tekezo just fyi, the doublecommand prefpane has the same issue for me - maybe you can team up? ;)

**Comment by diegodesouza** [comment]
I have a Matias Ergo Pro and have just accomplished this, could this be a keyboard specific issue?

**Comment by tekezo** [comment]
OS X kernel does not pass the fn key events to Karabiner if the keyboard vendor ID is not Apple (0x05ac).

Apple wireless keyboard is 0x05ac, so we can change the fn key.
But Magic Keyboard is 0x004c (New vendor ID for Apple Bluetooth devices.) and other keyboard has their own vendor ID, then we cannot detect the fn key events from these devices.

I'm searching the way to get the fn key events, but I don't find it at the moment.
