### ISSUE TITLE
Swap € and $ in German Layout

### ISSUE THREAD

**Issue by PaulePan** [tekezo/Karabiner#530]
There is a function like that for French Layout. Is it also possible to make this work for German Layout. Using Neo 2 German Layout.

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.german_swap_euro_and_dollar/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by PaulePan** [comment]
Wow, thank you for the fast support! I added the Code into private.xml and activated the Key Change by the Checkbox, but Keys didn't change. Maybe i did something wrong.

**Comment by tekezo** [comment]
That setting exchanges shift+4 and alt+e.

I assume these key combination input $ and € in your German Layout.
Is it right?
* shift+4 == $
* alt+e == €

**Comment by PaulePan** [comment]
I am using German Neo Layout2 :-)

The Key  combination is:

Modifier 3 + ö = $
OR Shift + 6 = $
(but want to use Modifier 3 + ö for €)

Shift + 7 = €

Thank you for the Support.

**Comment by tekezo** [comment]
OK.
I updated private.xml. Please replace your private.xml with it.

https://github.com/tekezo/Files/blob/master/Karabiner/private.german_swap_euro_and_dollar/private.xml

**Comment by tekezo** [comment]
I updated private.xml again.

**Comment by PaulePan** [comment]
Works perfect. thank you so much.
