### ISSUE TITLE
Sharing configuration between machines

### ISSUE THREAD

**Issue by jritsema** [tekezo/Karabiner#531]
Hey, I love the app!  This may be a dumb question but how do you share your settings between multiple machines?  I tried copying the org.pqrs.Karabiner.plist file but that didn't seem to work.  Thanks.

**Comment by tekezo** [comment]
You have to restart cfprefsd after you replaced plist file.
https://manytricks.com/blog/?p=3049

You can also use command line interface to export settings.
https://pqrs.org/osx/karabiner/document.html.en#export

**Comment by jritsema** [comment]
Perfect, thank you for the quick response!

**Comment by jritsema** [comment]
Hi Tekezo, unfortunately neither of these approaches seemed to work for me.  I must be missing something.

**Comment by jritsema** [comment]
Ok, I figured it out.  I didn't have the correct profile selected before exporting.  Thanks.
