### ISSUE TITLE
Mouse movement to scroll delay

### ISSUE THREAD

**Issue by naorunaoru** [tekezo/Karabiner#532]
I use Logitech M570 trackball and have RightClick+CursorMove to ScrollWheel and Disable inertial scroll enabled. Scrolling feels kinda laggy — there's a noticeable delay between moving the ball and page scrolling. Fine movements are ignored by Karabiner. How can I tweak the sensivity of CursorMove to ScrollWheel?

**Comment by tekezo** [comment]
Hmm, I cannot feel the delay.

You can adjust the scroll speed by Karabiner Preferences > Parameters tab > CursorMove to ScrollWheel > Rate.
Does it solve your issue?

If not, I want know more about this issue.
Does the delay happen in all apps?
And does the delay happen in clean environment such as Guest User?

**Comment by ethus3h** [comment]
FWIW, I'm not having any problems with my MiddleClick+CursorMove to ScrollWheel, with or with out Disable inertial scroll enabled, using OS X 10.11.1....

**Comment by naorunaoru** [comment]
Sorry it took too long to answer. Adjusting scroll speed did not help, delay happens in all apps and even in clean environment.

I've looked into other software providing this feature and found that [Smart Scroll](http://www.marcmoini.com/sx_en.html)'s Grab Scroll feature is much more sensitive. Looks like it polls cursor position and tries to place it back as soon as movement occured. That results in minor glitches (cursor wiggles around sometimes), but nothing too serious.
