### ISSUE TITLE
BlockUntilKeyUp with no timeout?

### ISSUE THREAD

**Issue by ethus3h** [tekezo/Karabiner#533]
Hi! Sorry to bother you, but I'm wondering what the correct setting would be for making BlockUntilKeyUp have no timeout? (Right now it seems to be sending the keydown event in under a second after it was pressed.) I'm basically looking for making it so that the keydown event is discarded, and the keyup event sends keydown, keyup in quick succession. Sorry, this is probably a dumb question... Thanks :)

(Here's what I tried that didn't do the trick:

   <item>
    <name>Block right mouse</name>
    <identifier>private.blockrightmouse</identifier>
    <autogen>
      __BlockUntilKeyUp__ PointingButton::RIGHT
    </autogen>
  </item>

)

(Moderately irrelevant information that may be relevant if this turns out to be an X-Y question: I'm doing it with the right mouse button trying to emulate the behavior that KDE had (?) where the context menu wouldn't pop up until the button was released. The different behavior is an annoyance for me in OS X because I tend to lean on the right mouse button with my thumb while I'm typing, which means I accidentally trigger context menu actions that have single-letter keyboard bindings in Firefox a lot. If you're wondering how I'm leaning on a mouse button with my thumb, it's because I use an IBM SpaceSaver II keyboard/trackpoint combo, which instead of a traditional mouse button has three extra keys below the space bar that let me mouse without taking my hands off of the keyboard. Which is a HUGE improvement over a traditional mouse or trackpad. Thanks again! :) )

**Comment by ethus3h** [comment]
Huh, the XML got mangled by Git Hub... hmm. Looking at the Markdown guide, it looks like I need to wrap it in triple backticks. Let's try this again, eh?

```xml
  <item>
    <name>Block right mouse</name>
    <identifier>private.blockrightmouse</identifier>
    <autogen>
      __BlockUntilKeyUp__ PointingButton::RIGHT
    </autogen>
  </item>
```

**Comment by tekezo** [comment]
You can adjust the timeout in Karabiner Preferences > Parameters tab.

But I think you should use __KeyOverlaidModifier__ instead of __BlockUntilKeyUp__.

```
    <autogen>
      __KeyOverlaidModifier__
      PointingButton::RIGHT,
      KeyCode::VK_NONE,
      PointingButton::RIGHT,
    </autogen>
```

**Comment by ethus3h** [comment]
Oh, glorious! The suggested config works like a charm. I'll have to read up about how to use the KeyOverlaidModifier parameter...

Thanks again! :D

**Comment by ethus3h** [comment]
I would like to note this here in case anyone else is wondering about this:

In the computer game "Sauerbraten", it is helpful to have bindings to the right mouse button that act on mousedown separately from mouseup.
For instance:
```
bind MOUSE2 [zoomfov 30; zoom 1; onrelease [zoom -1;]]
```
uses it to toggle zoom (zoomed in when right mouse is depressed).

My solution for allowing this in Sauerbraten but preserving the usual behavior in other apps is as follows:

```
  <appdef>
    <appname>SAUERBRATEN</appname>
    <equal>com.dot3labs.sauerbraten</equal>
  </appdef>
  <item>
    <name>Block right mouse, but not in Sauerbraten (edit from 2015dec27a28)</name>
    <identifier>private.blockrightmousens</identifier>
    <not>SAUERBRATEN</not>
	<autogen>
      __KeyOverlaidModifier__
      PointingButton::RIGHT,
      KeyCode::VK_NONE,
      PointingButton::RIGHT,
    </autogen>
```

The examples and documentation explain this method, but I figured I'd mention it in case anyone's doing a Google search for how to do this :)
