### ISSUE TITLE
How can I execute a shell script with the PATH in my normal shell

### ISSUE THREAD

**Issue by dsdshcym** [tekezo/Karabiner#536]
I found that the shell scripts executed in Karabiner is using a different shell
than my normal use.

I want to execute a ruby script and it needs rvm support to load external library.
Can I do this using Karabiner?

**Comment by tekezo** [comment]
You can execute via wrapper script.

wrapper.sh:

```shell
#!/bin/bash

# set up your environment

ruby your-file.rb
```

private.xml:

```xml
<url type="shell">
      <![CDATA[    your-directory/wrapper.sh    ]]>
</url>
```

**Comment by dsdshcym** [comment]
Thanks for your reply!

I found the problem. I was using `/usr/bin/env ruby` instead of `/usr/local/bin/ruby`.

And I think your answer is another solution too.

Thanks again!
