### ISSUE TITLE
Popup on 10.15.0

### ISSUE THREAD

**Issue by koob** [tekezo/Karabiner#537]
Im getting some new prompt popup while typing anywhere with newest Karabiner version. Cant find setting to disable it. Any ideas?

**Comment by tekezo** [comment]
You can disable here.
But I think you enabled some extra settings which uses pop up, and you should disable it.
Could you show me your enabled setting? (screen shot of Karabiner Preferences with "show enabled only" checkbox.)

![151222-0001](https://cloud.githubusercontent.com/assets/659178/11945047/cb611aae-a88e-11e5-9b6a-7aeae5f56057.png)

**Comment by trevordmiller** [comment]
I also started seeing a weird popup with character accents starting with 10.15.0 today that looks like this:
![screen shot 2015-12-21 at 8 05 38 pm](https://cloud.githubusercontent.com/assets/5497885/11947007/7b80376a-a81e-11e5-9c21-7e316465f124.png)

Certain characters are also starting to repeat 5-6 times (like spaces, `-` etc) like this:
![new_tab](https://cloud.githubusercontent.com/assets/5497885/11947017/916f4890-a81e-11e5-811e-756ef5b7f8f6.png)

I have the "Status Message" set to off.

**Comment by trevordmiller** [comment]
@tekezo ^

**Comment by tekezo** [comment]
@trevordmiller 
You can disable the popup by this way:
http://www.tekrevue.com/tip/how-to-disable-the-character-accent-menu-in-os-x-mountain-lion/

**Comment by trevordmiller** [comment]
My issue had to do with the changed settings for "Key Repeat". Setting the repeat delay to 200ms fixed both the popup and the weird repeating symbols. Related: https://github.com/tekezo/Karabiner/issues/539
