### ISSUE TITLE
Scrolling inverted with Mouse Keys Mode v2 

### ISSUE THREAD

**Issue by codeanpeace** [tekezo/Karabiner#538]
With mouse keys mode v2 turned on, d+s and j should scroll down and k should scroll up. They are inverted, I suspect it has to do with having tradition scrolling (two finger up on trackpad scrolls up) configured instead of natural scrolling (two fingers up on trackpad scrolls down).

**Comment by tekezo** [comment]
Please try this setting.
![151222-0002](https://cloud.githubusercontent.com/assets/659178/11946713/f5635a94-a8a0-11e5-85bf-a9ed54750264.png)

**Comment by codeanpeace** [comment]
Perfect! I did not know about that setting, thanks a bunch
