### ISSUE TITLE
key repeat broken 

### ISSUE THREAD

**Issue by hitima** [tekezo/Karabiner#540]
when i update 10.15.0,
kkkkkkkkkkkkeeeeeeeeeyyyyyyyy repeat is broken....

OSX 10.10.5（14F1509）

**Comment by tekezo** [comment]
The safety limit of key repeat rate has been removed at v10.15.0.

The limit was 200 ms and 5 ms in the previous versions of Karabiner.
Please increase the key repeat values to 200 ms and 5 ms if you feel new key repeat is too fast.

**Comment by bago2k4** [comment]
I'm running v10.15.0 on OS X 10.11.2. This is what happens for me when i type `SPACE` `a` `SPACE` `a`:
http://cl.ly/183m3Q3A2l39

I'm not sure this is happening for everybody right after the update, maybe it depends from the setup but it's very annoying.
After updating the Key Repeat values everything went back to normal.
Just FYI.

**Comment by hmalphettes** [comment]
This is also happening for me.

**Comment by fedragon** [comment]
thanks @tekezo, changing the key repeat settings solved the issue for me.

**Comment by hitima** [comment]
Resolved After change the settings. Thanks.

**Comment by FunTimeCoding** [comment]
I had it set to 0 for no good reason. I couldn't log in anymore after rebooting, so I had to log in using SSH to change the config file.

```sh
cd ~/Library/Preferences
plutil -convert plist -o org.pqrs.Karabiner.plist org.pqrs.Karabiner.xml
vim org.pqrs.Karabiner.xml
plutil -convert binary1 -o org.pqrs.Karabiner.plist org.pqrs.Karabiner.xml
rm org.pqrs.Karabiner.xml
```

**Comment by tekezo** [comment]
@FunTimeCoding 
Sorry for inconvenience.

You can also modify Karabiner Preferences in Safe Mode.
(We can launch Karabiner in Safe Mode, but the key repeat rate is not affected in Safe Mode.)

Mac OS X: Starting up in Safe Mode
http://support.apple.com/kb/ht1455
