### ISSUE TITLE
Is it possible to make SPACE a modifier key?

### ISSUE THREAD

**Issue by mmzeeman** [tekezo/Karabiner#541]
I would like to map SPACE + Q to P and just a SPACE to SPACE. In other words I like to make it a modifier when pressed together with another key. 

That would allow me to create a definition for a half querty keyboard.

Is that possible?

**Comment by tekezo** [comment]
Please try new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.space_as_modifier/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml


There are some options to adjust key behavior.
For example, you can use __BlockUntilKeyUp__ for fast typing.
https://github.com/tekezo/Karabiner/blob/version_10.15.0/src/core/server/Resources/include/checkbox/standards/space.xml#L174-L197

**Comment by mmzeeman** [comment]
Thanks, this works very well. Working on the definition of the half querty keyboard because I injured my right pinky and my right arm is now in a cast for 6 weeks.

Are you interested in a pull request of the half querty keyboard mapping? I will check for possible patent infringements first.

**Comment by tekezo** [comment]
Pull Request is welcome.

There are some half qwerty keyboard layout in prepared settings (eg. grenouille)
https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/grenouille/left.xml
It might be useful for you.

**Comment by mmzeeman** [comment]
That is a Dvorak like mapping. Half querty is very useful if you already know how to touch type with a normal querty keyboard.

http://www.matias.ca/halfkeyboard/index.php

It is pretty amazing how quickly one can adapt.
