### ISSUE TITLE
Issue with H and G

### ISSUE THREAD

**Issue by esfruga** [tekezo/Karabiner#542]
Hello guys i have this problem, 

Updated to the latest update like i saw advised in some threads but still doesn't work  

What is happening is my "H" key is giving me the "`" key (almost all of the time) and the "g" key often doens't work, as well as "S" key. 

Can someone help me? please?

i'm on a portuguese mac keyboard.
MBP 13 2015 - El Capitan

G key gives me this sometimes
![tecla g](https://cloud.githubusercontent.com/assets/16482824/12045143/1c944c08-ae8d-11e5-9e61-a81712c84fd7.png)

H key give me this
![tecla h](https://cloud.githubusercontent.com/assets/16482824/12045160/80603530-ae8d-11e5-99e0-9c00e7a5fb61.png)

PS: just noticed that after shut down and open karabiner again, its working perfect for some time, until it starts doing it again. Am i doing anything to change this behaviour?

**Comment by esfruga** [comment]
just noticed that after shut down and open karabiner again, its working perfect. Am i using any modifier t

**Comment by tekezo** [comment]
I guess thumbsense changes your keys.
Did you open multi-touch extension?

Please confirm the multi-touch extension settings.
https://pqrs.org/osx/karabiner/document.html.en#multitouchextension
