### ISSUE TITLE
Karabiner 10.15.0 does not automatically launch on login: OS X 10.11.2 (15C50)

### ISSUE THREAD

**Issue by Nonstopdrivel** [tekezo/Karabiner#544]
I have been using Karabiner 10.15.0 to disable my left shift key, which my MacBook Pro (15-inch, Mid 2010) seems to think is constantly firing. While Karabiner is running, it works perfectly. However, I cannot get it to load automatically on login and therefore must manually start it every time I log in. The documentation states that Karabiner should not appear in the Login Items list, so I have removed it from the list, but that makes no difference. 

Incidentally, since I installed Karabiner, my computer has started to do a complete shutdown instead of going into sleep mode every time I close the lid. I have not been able to find a workaround for this.

Following is a complete list of all Karabiner-related messages in my Console logs:

```
03/01/16 14:33:18,000 kernel[0]: org.pqrs.Karabiner --Info-- init
03/01/16 14:33:18,000 kernel[0]: org.pqrs.Karabiner --Info-- start
03/01/16 14:35:11,924 WindowServer[169]: disable_update_timeout: UI updates were forcibly disabled by application "Karabiner" for over 1.00 seconds. Server has re-enabled them.
03/01/16 14:35:18,072 Karabiner[457]: checkForUpdates https://pqrs.org/osx/karabiner/files/appcast.xml
03/01/16 14:35:18,306 WindowServer[169]: common_reenable_update: UI updates were finally reenabled by application "Karabiner" after 7.38 seconds [0.14fps] (server forcibly re-enabled them after 1.00 seconds [1.00fps])
03/01/16 14:35:18,310 Karabiner[457]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:35:18,310 Karabiner[457]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:35:18,311 Karabiner[457]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:35:18,322 Karabiner[457]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:35:18,322 Karabiner[457]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:35:18,326 Karabiner[457]: Session state has been changed. (active)
03/01/16 14:35:18,454 Karabiner[457]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:35:18,456 Karabiner[457]: observer_IONotification
03/01/16 14:35:18,456 Karabiner[457]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:35:18,000 kernel[0]: org.pqrs.Karabiner --Info-- RemapClass::allocation_count_ 417857/2097152 (memory usage: 19% of 8192KB)
03/01/16 14:35:19,126 Karabiner_AXNotifier[465]: AXNotifier Preferences: {
    kAXNotifierDisabledInJavaApps = 1;
    kAXNotifierDisabledInPreview = 1;
}
03/01/16 14:35:59,000 kernel[0]: org.pqrs.Karabiner --Info-- RemapClass::allocation_count_ 417857/2097152 (memory usage: 19% of 8192KB)
03/01/16 14:37:57,396 com.apple.xpc.launchd[1]: (org.pqrs.Karabiner.185952[457]) Service exited due to signal: Killed: 9
03/01/16 14:37:57,420 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000002.Karabiner_AXNotifier[465]) Service exited due to signal: Killed: 9
03/01/16 14:40:01,241 WindowServer[498]: disable_update_timeout: UI updates were forcibly disabled by application "Karabiner" for over 1.00 seconds. Server has re-enabled them.
03/01/16 14:40:04,266 Karabiner[641]: checkForUpdates https://pqrs.org/osx/karabiner/files/appcast.xml
03/01/16 14:40:04,529 WindowServer[498]: common_reenable_update: UI updates were finally reenabled by application "Karabiner" after 4.29 seconds [0.23fps] (server forcibly re-enabled them after 1.00 seconds [1.00fps])
03/01/16 14:40:04,595 Karabiner[641]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:40:04,595 Karabiner[641]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:40:04,596 Karabiner[641]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:40:04,613 Karabiner[641]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:40:04,613 Karabiner[641]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:40:04,613 Karabiner[641]: Session state has been changed. (active)
03/01/16 14:40:04,630 Karabiner[641]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:40:04,898 Karabiner[641]: observer_IONotification
03/01/16 14:40:04,898 Karabiner[641]: [INFO] BRIDGE_USERCLIENT_SYNCHRONIZED_COMMUNICATION connection is null
03/01/16 14:40:05,000 kernel[0]: org.pqrs.Karabiner --Info-- RemapClass::allocation_count_ 417857/2097152 (memory usage: 19% of 8192KB)
03/01/16 14:40:05,313 Karabiner_AXNotifier[649]: AXNotifier Preferences: {
    kAXNotifierDisabledInJavaApps = 1;
    kAXNotifierDisabledInPreview = 1;
}
03/01/16 14:40:07,000 kernel[0]: org.pqrs.Karabiner --Info-- RemapClass::allocation_count_ 417857/2097152 (memory usage: 19% of 8192KB)
```

Out of curiosity, Karabiner never appears in the Task Switcher, even when the window is open. Is that by design, or is that a bug?

**Comment by Nonstopdrivel** [comment]
In case it's helpful, here is the list of Diagnostic and Usage Messages that mention Karabiner:

    02/01/16 16:29:33,869 diagnostics_agent[284]: 
    com.apple.message.domain:
    com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 14072
    com.apple.message.value2: 0
    com.apple.message.value3: 1
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 16:29:33,869 diagnostics_agent[284]:
    com.apple.message.domain:
    com.apple.usage.app_activetime
    com.apple.message.signature: EventViewer
    com.apple.message.signature2: org.pqrs.Karabiner.EventViewer ||| 10.15.0 (10.15.0)
    com.apple.message.value: 17
    com.apple.message.value2: 17
    com.apple.message.value3: 1
    com.apple.message.value4: 0
    com.apple.message.value5: 1
    com.apple.message.value6: 1
    com.apple.message.value7: 17
    com.apple.message.result: YES
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 16:29:33,871 diagnostics_agent[284]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value: 14063
    com.apple.message.value2: 0
    com.apple.message.value3: 1
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 19:59:45,912 diagnostics_agent[284]: 
    OSActivityID: 0x0000000000000d07
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 12612
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 19:59:45,914 diagnostics_agent[284]: 
    OSActivityID: 0x0000000000000d07
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.value: 12612
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 20:25:33,470 diagnostics_agent[284]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 1548
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 20:25:33,471 diagnostics_agent[284]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value: 1548
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 23:58:05,280 diagnostics_agent[284]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 12751
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    02/01/16 23:58:05,283 diagnostics_agent[284]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value: 12751
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 00:15:06,339 systemstats[982]: 
    com.apple.message.domain: com.apple.telemetry.coalitions.daily
    com.apple.message.reason: daily
    com.apple.message.date: 20160101
    com.apple.message.os_build: 15C50
    com.apple.message.system_uptime: 28000
    com.apple.message.label: org.pqrs.Karabiner
    com.apple.message.ac-active.total.duration: 27000
    com.apple.message.ac-active.total.cpu_time: 210
    com.apple.message.ac-active.spin.count: 1
    com.apple.message.ac-active.total.run_time: 26000
    com.apple.message.ac-active.total.up_time: 27000
    com.apple.message.ac-active.total.energy_impact: 21000
    com.apple.message.ac-active.total.wakeups: 45000
    com.apple.message.ac-active.total.interrupts: 180000
    com.apple.message.ac-active.total.spawns: 14
    com.apple.message.ac-active.total.disk_bytes_read: 15000000
    com.apple.message.ac-active.total.disk_bytes_write: 240000
    com.apple.message.ac-active.spin.duration: 19000
    com.apple.message.ac-active.spin.hist: 0,16000,1,32000,0
    com.apple.message.ac-active.spin.avg: 18830
    com.apple.message.ac-active.spin.rank: 2
    SenderMachUUID: 11213C5D-3A89-3476-B749-7D8B9FA02C2A

    03/01/16 00:15:45,455 systemstats[982]: 
    com.apple.message.domain: com.apple.telemetry.coalitions.daily
    com.apple.message.reason: daily
    com.apple.message.date: 20160102
    com.apple.message.os_build: 15C50
    com.apple.message.system_uptime: 41000
    com.apple.message.label: org.pqrs.Karabiner
    com.apple.message.battery-active.total.duration: 9800
    com.apple.message.battery-active.total.cpu_time: 12
    com.apple.message.battery-active.total.run_time: 9600
    com.apple.message.battery-active.total.up_time: 30000
    com.apple.message.battery-active.total.energy_impact: 1500
    com.apple.message.battery-active.total.wakeups: 15000
    com.apple.message.battery-active.total.interrupts: 21000
    com.apple.message.battery-active.total.spawns: 7
    com.apple.message.battery-active.total.disk_bytes_read: 5400000
    com.apple.message.ac-active.spin.count: 1
    com.apple.message.battery-active.total.disk_bytes_write: 100000
    com.apple.message.battery-active.spin.duration: 27000
    com.apple.message.battery-active.spin.hist: 0,16000,1,32000,0
    com.apple.message.ac-active.total.spawns: 6
    com.apple.message.battery-active.spin.count: 1
    com.apple.message.battery-active.spin.avg: 27158
    com.apple.message.battery-active.spin.rank: 4
    com.apple.message.ac-active.total.duration: 32000
    com.apple.message.ac-active.total.cpu_time: 26
    com.apple.message.ac-active.total.run_time: 32000
    com.apple.message.ac-active.total.up_time: 41000
    com.apple.message.ac-active.total.energy_impact: 3500
    com.apple.message.ac-active.total.wakeups: 47000
    com.apple.message.ac-active.total.interrupts: 65000
    com.apple.message.ac-active.total.disk_bytes_read: 6100000
    com.apple.message.ac-active.total.disk_bytes_write: 94000
    com.apple.message.ac-active.spin.duration: 7600
    com.apple.message.ac-active.spin.hist: 0,4000,1,8000,0
    com.apple.message.ac-active.spin.avg: 7593
    com.apple.message.ac-active.spin.rank: 3
    SenderMachUUID: 11213C5D-3A89-3476-B749-7D8B9FA02C2A

    03/01/16 00:21:33,158 diagnostics_agent[284]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 1408
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 00:21:33,160 diagnostics_agent[284]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value: 1408
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 01:54:14,691 diagnostics_agent[284]: OSActivityID: 0x0000000000000d07
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 5562
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 01:54:14,694 diagnostics_agent[284]: OSActivityID: 0x0000000000000d07
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.value: 5562
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 14:37:44,868 diagnostics_agent[357]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 155
    com.apple.message.value2: 0
    com.apple.message.value3: 1
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 14:37:44,869 diagnostics_agent[357]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value: 146
    com.apple.message.value2: 0
    com.apple.message.value3: 1
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 14:37:54,017 diagnostics_agent[357]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 9
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 14:37:54,019 diagnostics_agent[357]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value: 9
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 14:37:57,357 diagnostics_agent[357]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner
    com.apple.message.signature2: org.pqrs.Karabiner ||| 10.15.0 (10.15.0)
    com.apple.message.value: 4
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

    03/01/16 14:37:57,358 diagnostics_agent[357]: 
    com.apple.message.domain: com.apple.usage.app_activetime
    com.apple.message.signature: Karabiner_AXNotifier
    com.apple.message.signature2: org.pqrs.Karabiner-AXNotifier ||| 10.15.0 (10.15.0)
    com.apple.message.value: 4
    com.apple.message.value2: 0
    com.apple.message.value3: 0
    com.apple.message.value4: 0
    com.apple.message.value5: 0
    com.apple.message.value6: 0
    com.apple.message.value7: 0
    com.apple.message.result: NO
    com.apple.message.summarize: YES
    SenderMachUUID: 3637A703-9E26-3964-BF0F-66E4F4E88C2D

**Comment by tekezo** [comment]
OS X does not launch application automatically when the shift key is pressed when you log in. 
You have to open Karabiner every time when you logged in due to this OS X restriction.
