### ISSUE TITLE
How to activate "XXX to Fn"

### ISSUE THREAD

**Issue by weiweihuanghuang** [tekezo/Karabiner#545]
I have a Microsoft Sculpt Ergonomic  and want to remap the Fn+F1...F12 to Functional Keys (Brightness Adjust, Music Control, Etc). It is not working, I looked in the manual and Q&A, and didn't find a solution. I did find this bit above the settings I'm trying to use that says, `Use these settings if you activated "XXX to Fn"`, where is this setting? I haven't found how to activate this.

My only settings
![screen shot 2016-01-04 at 1 01 07 pm](https://cloud.githubusercontent.com/assets/1271897/12082245/8689633c-b2e3-11e5-99c6-581186c56c01.png)

This keyboard doesn't have an Fn key but an Fn switch, in the event viewer, when I press for example F1..F12 buttons it shows the following where F1 = F1+Fn twice...:
![screen shot 2016-01-04 at 1 07 18 pm](https://cloud.githubusercontent.com/assets/1271897/12082277/3acd3242-b2e4-11e5-8606-9dd947619b06.png)

**Comment by tekezo** [comment]
If you want to use both normal f1-f12 keys and media controls, please make fn key and use such settings.

"Application Key to Fn" in prepared settings changes your menu key to fn key.
Then you can use brightness control by menu key + f1.

**Comment by weiweihuanghuang** [comment]
Thanks for your reply, I don't understand why I need to make an Fn key though? My current F1…F12 keys, when pressed are already pressing F1+Fn as you can see in the EventViewer screenshot above; the strange thing is that it returns F1+Fn twice when I press it once even when I press very quickly.

**Comment by tekezo** [comment]
> I just want to use them as Functional Keys 

OK. Please enable following settings.

![160105-0001](https://cloud.githubusercontent.com/assets/659178/12106583/64e362e8-b3a4-11e5-8014-97af79348c48.png)

> F1+Fn flag as you can see in the EventViewer 

EventViewer is affected by OS X behavior.
OS X adds the Fn flag automatically for F1-F12 keys even if the Fn key is not pressed.
So, EventViewer always shows the Fn flag for F1-F12 keys.

> The strange thing is that it returns F1+Fn twice when I press it once even when I press very quickly.

Are they KeyDown and KeyUp?
Or is KeyDown shown twice for each KeyUp?

**Comment by weiweihuanghuang** [comment]
>OK. Please enable following settings.
Thank you very much for your help! That fixed it. I didn't know that OS X adds the Fn flag.
