### ISSUE TITLE
F15/14 binding not work

### ISSUE THREAD

**Issue by voutcn** [tekezo/Karabiner#547]
```xml
<?xml version="1.0"?>
<root>
  <item>
    <name>F15/14 to Page Up/Down</name>
    <identifier>private.f_15_14_to_page_up_down</identifier>
    <autogen>__KeyToKey__ KeyCode::F15, KeyCode::HOME</autogen>
    <autogen>__KeyToKey__ KeyCode::F14, KeyCode::END</autogen>
  </item>

  <item>
    <name>shift+opt+L/R to HOME/END</name>
    <identifier>private.shift_opt_L_R_to_HOME_END</identifier>
    <autogen>__KeyToKey__ KeyCode::CURSOR_LEFT, ModifierFlag::SHIFT_L | ModifierFlag::OPTION_L, KeyCode::HOME</autogen>
    <autogen>__KeyToKey__ KeyCode::CURSOR_RIGHT, ModifierFlag::SHIFT_L | ModifierFlag::OPTION_L, KeyCode::END</autogen>
  </item>
</root>
```

Screen shot of EventViewer
![screen shot 2016-01-04 at 3 41 45 pm](https://cloud.githubusercontent.com/assets/6329785/12085315/ba16a60e-b2f9-11e5-9c68-195afdb91a8a.png)

**Comment by tekezo** [comment]
This setting works fine on my machine.
Did you enable the new setting?

**Comment by voutcn** [comment]
Yes, I've enabled the setting. Probably the problem exists with my keyboard (logitech K480), where the F15/14 is actually a combination of Fn+UpArrow/DownArrow. The Fn key alone is unrecognizable.

**Comment by tekezo** [comment]
OK. Please show me the raw input event of F15/F14 in debug mode.
https://pqrs.org/osx/karabiner/document.html.en#debugmode

**Comment by voutcn** [comment]
It is very strange that nothing captured by the debug mode when I press Fn+UpArrow/DownArrow (but the EventViewer captured the signal of F15/F14).

**Comment by tekezo** [comment]
I guess other keyboard driver is installed and it conflicts with Karabiner.
Did you install Logitech Control Center or other keyboard drivers?

**Comment by voutcn** [comment]
Yes, you are correct. I've installed Logitech options. Let me uninstall it
and test out Karabiner then. Thanks.

On Wed, Jan 6, 2016 at 10:30 AM, Takayama Fumihiko <notifications@github.com
> wrote:

> I guess other keyboard driver is installed and it conflicts with Karabiner.
> Did you install Logitech Control Center or other keyboard drivers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tekezo/Karabiner/issues/547#issuecomment-169201930>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com

**Comment by voutcn** [comment]
Without logitech options, Fn+UpArrow/DownArrow become opt_L+UpArrow/DownArrow instead of F15/F14. It seems that there are no perfect way to map Fn+UpArrow/DownArrow to PAGEUP/DOWN with K480. I am closing this issue.

**Comment by ethus3h** [comment]
could you leave the logitech thing out, and just map the OPTION_L+arrows to PgUp and PgDown? just an idea...

**Comment by tekezo** [comment]
K480 has a mode switch in keyboard.
You can use fn-arrow keys by using PC mode.

**Comment by voutcn** [comment]
@ethus3h thx but I have to use the driver for my logitech mouse. I am now using OPTION_L+arrows to replace Fn+arrows for PgUp and PgDown.

@tekezo By using PC mode the Fn+Up/Down arrow still map to F15/F14.

**Comment by tekezo** [comment]
@voutcn Thank you for confirmation.
The fn+up/down will be PageUp/Down with PC mode on my Logitech K480, but I understand it is model specific behavior.
