### ISSUE TITLE
How to set a key to toggle a Karabiner rule?

### ISSUE THREAD

**Issue by weiweihuanghuang** [tekezo/Karabiner#548]
I want to change my CAPSLOCK key to a toggle that turns on and off another Karabiner rule, is this possible (I know I have to use seil)? To be specific in a certain app I want to use CAPSLOCK to enable a rule that turns WSAD to Up Down Left Right (I know how to make this rule itself).

**Comment by tekezo** [comment]
This is an example.
https://github.com/tekezo/Files/blob/master/Karabiner/private.mode_example/private.xml

Add vk_config="true" in identifier.
https://github.com/tekezo/Files/blob/master/Karabiner/private.mode_example/private.xml#L15

Then you can use KeyCode::VK_CONFIG_TOGGLE_xxx.
(xxx is identifier with replacing `.` with `_`.)

**Comment by weiweihuanghuang** [comment]
Thank you for your help!
