### ISSUE TITLE
Use PC Home Style #2 End key sends Ctrl+. to GUI Emacs

### ISSUE THREAD

**Issue by spattersongt** [tekezo/Karabiner#549]
If I load Emacs.app with or without the -q option (no config) and press "End" Emacs is claiming "C-." is not defined.  

![screen shot 2016-01-05 at 12 26 10 pm](https://cloud.githubusercontent.com/assets/859176/12122223/b37101a6-b3a7-11e5-9639-f1c18152389f.png)

![screen shot 2016-01-05 at 12 26 58 pm](https://cloud.githubusercontent.com/assets/859176/12122226/b6e3c12a-b3a7-11e5-8e87-6e7d4abaa430.png)

This is pretty frustrating.  Home/End works *everywhere* else.  Any ideas?

**Comment by spattersongt** [comment]
Oh.  Important to note.  I'm using Dvorak.  The "e" key in Dvorak is "." 
Ctrl+A works just fine because "a" is the same on Qwerty and Dvorak

**Comment by spattersongt** [comment]
https://github.com/tekezo/Karabiner/pull/550

Should fix this issue for Dvorak users

**Comment by tekezo** [comment]
I merged #550.
