### ISSUE TITLE
Emacs mode key bindings does't work for Dvorak keyboard

### ISSUE THREAD

**Issue by tix209** [tekezo/Karabiner#552]
I am using karabiner 10.15.0 in OSX El Capitan under English Dvorak keyboard layout.

I enabled Option+BF to Option+Left/Right but it still outputs ∫ and ƒ. Any ideas?

**Comment by tekezo** [comment]
Thank you for feedback.
Emacs mode was designed for qwerty keyboard.

I support Dvorak in that setting at Karabiner-10.15.8.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates
