### ISSUE TITLE
Keys are pressed more than once

### ISSUE THREAD

**Issue by kbariotis** [tekezo/Karabiner#553]
On the latest build, 10.50.0, the keys are pressed more than once, completely random. I ended up quitting Karabiner cause I couldn't write.

![karabiner](https://cloud.githubusercontent.com/assets/605742/12241453/fa980b08-b89b-11e5-8d1e-b516ed54a962.gif)

**Comment by tekezo** [comment]
Sorry for inconvenience.

You have set very small key repeat rate in the previous version.

Please increase the key repeat values to 200 ms and 5 ms from Preferences:
https://pqrs.org/osx/karabiner/document.html.en#keyrepeat

The safety limit of key repeat rate has been removed at Karabiner-10.15.0.
Then, you can overwrite key repeat rate by extreme fast values.


Version History:
https://pqrs.org/osx/karabiner/history.html.en#history

**Comment by kbariotis** [comment]
Thank you @tekezo, no inconvenience at all. :)
