### ISSUE TITLE
Add com.p5sys.jump.mac.viewer.web to appdef.xml

### ISSUE THREAD

**Issue by pablomedok** [tekezo/Karabiner#554]
please, add  <equal>com.p5sys.jump.mac.viewer.web</equal>
to REMOTEDESKTOPCONNECTION section of appdef.xml

it's needed for non-AppStore verison of JumpDesktop for Mac. I add it manually after Karabiner updates.

Please, also add a string for Parallels 2X RDP client. I don't use it, but when I tried it I was also not working.

**Comment by tekezo** [comment]
I've added com.p5sys.jump.mac.viewer.web at Karabiner-10.15.9.
Please upgrade to the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

> Parallels 2X RDP client

Do you know the bundle identifier of Parallels 2X RDP client?

**Comment by pablomedok** [comment]
App Bundle: com.2X.Client.Mac

С уважением,
Супрунюк Павел


От: Takayama Fumihiko <notifications@github.com<mailto:notifications@github.com>>
Обратный адрес: tekezo/Karabiner <reply@reply.github.com<mailto:reply@reply.github.com>>
Дата: среда, 13 января 2016 г., 10:46
Кому: tekezo/Karabiner <Karabiner@noreply.github.com<mailto:Karabiner@noreply.github.com>>
Копия: Pavel Supruniuk <pablomedok@tut.by<mailto:pablomedok@tut.by>>
Тема: Re: [Karabiner] Add com.p5sys.jump.mac.viewer.web to appdef.xml (#554)


I've added com.p5sys.jump.mac.viewer.web at Karabiner-10.15.9.
Please upgrade to the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

Parallels 2X RDP client

Do you know the bundle identifier of Parallels 2X RDP client?

**Comment by tekezo** [comment]
Thank you!
I've added com.2X.Client.Mac at Karabiner-10.15.12.
