### ISSUE TITLE
Show Carabiner in Application Switcher (⌘⇥)

### ISSUE THREAD

**Issue by eugenesvk** [tekezo/Karabiner#555]
Currently Karabiner doesn't appear in the default __App Switcher__ list — the one fired up by `⌘⇥` (Command-Tab).
This is very inconvenient during testing different shortcuts as I can't use the default `⌘⇥` to quickly switch between Karabiner and other apps, in which I am testing those shortcuts. Every time I have to do something rather cumbersome — either enable menu icon, click on it and choose `Preferences` or use some other trick with hiding current windows until I see Karabiner or launch Karabiner from Spotlight or something.
Is it possible to have an option to show Karabiner in the __App Switcher__ list, please (btw., creating a shortcut to launch Karabiner would be rather inconvenient as well since then I'd have to memorize it just for those infrequent events when I test new shortcuts)?
Thank you!

**Comment by tekezo** [comment]
Please upgrade to the latest beta and enable this setting.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

![160113-0002](https://cloud.githubusercontent.com/assets/659178/12292400/2d0d56ca-ba30-11e5-9400-39c191f15108.png)

**Comment by eugenesvk** [comment]
Thank you very much for this additional feature and such a prompt response!
