### ISSUE TITLE
Mapping mouse buttons to scrolling

### ISSUE THREAD

**Issue by dclelland** [tekezo/Karabiner#558]
Hi there,

I'm using a [R.A.T. 7 mouse](http://store.madcatz.com/platforms/pc/Mad-Catz-RAT-7-Gaming-Mouse-for-PC-and-Mac.html) which has a sideways scroll wheel, which for some reason doesn't map to scroll events, left and right map to `PointingButton::BUTTON6` and `PointingButton::BUTTON7`.

I'm trying to map these back to scrolling but no luck: so far I've tried 

``` xml
<item>
  <name>Use Button6 and Button7 (the horizontal scroll wheel) as the horizontal scroll wheel</name>
  <identifier>private.pointing_button6_and_button7_to_scroll_left_and_right</identifier>
  <autogen>__KeyToKey__ PointingButton::BUTTON6, KeyCode::VK_MOUSEKEY_SCROLL_LEFT</autogen>
  <autogen>__KeyToKey__ PointingButton::BUTTON7, KeyCode::VK_MOUSEKEY_SCROLL_RIGHT</autogen>
</item>
```

and

``` xml
<item>
  <name>Use Button6 and Button7 (the horizontal scroll wheel) as the horizontal scroll wheel</name>
  <identifier>private.pointing_button6_and_button7_to_scroll_left_and_right</identifier>
  <autogen>__KeyToKey__ PointingButton::BUTTON6, ScrollWheel::LEFT</autogen>
  <autogen>__KeyToKey__ PointingButton::BUTTON7, ScrollWheel::RIGHT</autogen>
</item>
```

with no success. I see there is a `__KeyToKey__` flag in Karabiner as well as a `__ScrollWheelToKey__` but no `__KeyToScrollWheel__`... Am I on the right track?

**Comment by tekezo** [comment]
The first autogens should work.

Does PointingButton::RIGHT work on your machine?

```xml
  <autogen>__KeyToKey__ PointingButton::BUTTON6, KeyCode::VK_MOUSEKEY_SCROLL_LEFT</autogen>
```

If it does not work, the common cause is the third vendor driver confliction.
Did you install another mouse driver such as SmoothMouse?
