### ISSUE TITLE
How to create shortcut for the specific characters which can't be input from keyboard?

### ISSUE THREAD

**Issue by zlargon** [tekezo/Karabiner#560]
Hi,
I would like to create shortcuts for arrow symbol (e.g. ← ↑ → ↓), but those characters can't be input from keyboard. How can I create shortcuts for them?
Thanks.

**Comment by tekezo** [comment]
Please use Unicode Hex Input Hack.
https://pqrs.org/osx/karabiner/faq.html.en#unicode-hex-input

**Comment by zlargon** [comment]
Awesome!!
Thank you so much and have a nice day :smile:

**Comment by jmcruz** [comment]
Hello, I have the _exact_ same question, and the solution seems to not apply any longer. What's the correct way to do this now?
