### ISSUE TITLE
Add PC style "Change input source" #4 Command_L+Shift_L to Command+Space

### ISSUE THREAD

**Issue by aels** [tekezo/Karabiner#561]
Hi.
Maybe you found useful key set "Command_L+Shift_L" as optional pc-like input source changer,
because Command-key on Mac keyboards is in place of Alt-key on windows keyboards.
So, usage of regular "alt+shift" cause pain while often tapping command-key instead.
It is also very useful in combo with "Command_L"->Fn bindings, to bring back original "Ctrl+Shift" set, because Fn-key on Mac keyboards is swapped with Ctrl-key.
- It there a manual way to set "Command_L+Shift_L" as "Command+Space" ?
- Can "Command_L+Shift_L" to "Command+Space" be set as one of Karabiner options?

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.pc_command_shift_to_command_space/private.xml

If it works well on your environment, I'll add it into prepared settings.

**Comment by aels** [comment]
Works like a charm, huge thank!

**Comment by tekezo** [comment]
I've added this setting into prepared settings at v10.15.32.
https://github.com/tekezo/Karabiner/commit/ef6ff9aa9d32b6f5bfbd966b3433a1419a753389

You can confirm it in the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by 4vanger** [comment]
How could I make it work with Karabiner-Elements?
