### ISSUE TITLE
Link to FAQ from submit issue page?

### ISSUE THREAD

**Issue by ethus3h** [tekezo/Karabiner#563]
I've been watching this repo for a while, and I've noticed that a lot of people post issues that are answered in the FAQ page (https://pqrs.org/osx/karabiner/faq.html.en).

Maybe to help them find their answers faster, a link to the FAQ page could be added to the create issue page (https://github.com/tekezo/Karabiner/issues/new)?

Just a thought :)

**Comment by ethus3h** [comment]
(Well, I suppose it wouldn't necessarily be faster, since you often respond incredibly quickly, but it might cut down on the amount of chaff to sort through and respond to.)

**Comment by tekezo** [comment]
It sounds good!
But we seems no way to add extra information into the page in github.

**Comment by ethus3h** [comment]
Well, I think there is a way to do it. This repo does it https://github.com/gorhill/uBlock/issues/new

**Comment by ethus3h** [comment]
Ah! Here is some information about it. https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by tekezo** [comment]
Thank you!
I've added it.

**Comment by ethus3h** [comment]
Nice! I'll close this issue now :)
