### ISSUE TITLE
re-mapped keys confuses Microsoft Remote Desktop

### ISSUE THREAD

**Issue by moander** [tekezo/Karabiner#564]
I use "For Norwegian" rules like "Improve ISO Keyboard Layout" and "At sign fix". These mappings makes it impossible to write @ \ | in remote desktop.

Enabling "Disable all settings while you are using Remote Desktop or VNC" solves the key-mapping problem, but this setting also disables the "Enable at only Remote Desktop" settings.

Is this a bug, or am I doing something wrong? :)

**Comment by tekezo** [comment]
Thank you for feedback.
I've update these settings to be ignored in Remote Desktop at Karabiner-10.15.34.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by moander** [comment]
It works perfectly :+1:
