### ISSUE TITLE
Mouse button to mouse lock

### ISSUE THREAD

**Issue by dr-ewan** [tekezo/Karabiner#567]
Hi,

How can you make a mouse or key work as a toggle to hold the left mouse button? (click or drag lock)

Thank you

**Comment by tekezo** [comment]
You can use KeyCode::VK_MOUSEKEY_LOCK_BUTTON_LEFT like this setting:
https://github.com/tekezo/Files/blob/master/Karabiner/private.button5_to_left_button_lock/private.xml

**Comment by dr-ewan** [comment]
That's great thank you! Is there a way to modify it so that the click lock turns off after a mouse left click?

**Comment by tekezo** [comment]
I've updated private.xml.

This autogen turns off the lock.
https://github.com/tekezo/Files/blob/master/Karabiner/private.button5_to_left_button_lock/private.xml#L14-L21

**Comment by dr-ewan** [comment]
Perfect, thank you!
