### ISSUE TITLE
Issues with bluetooth keyboard and mouse scroll wheel.

### ISSUE THREAD

**Issue by smartepsh** [tekezo/Karabiner#568]
- Can't recognise my MADCATZ R.A.T 9 wireless mouse in EventViewer （In the Devices Page）
- Can't recognise my thinkpad bluetooth keyboard Fn Key

> There is nothing been shown when I press the Fn key on my thinkpad bluetooth keyboard In the EventViewer Main Page.
- Can't flip the mouse scroll wheel vertical（or horizontal）

The Devices Page:

``` xml
Keyboard
    Apple Internal Keyboard / Trackpad ()

    DeviceVendor::RawValue::0x05ac,
    DeviceProduct::RawValue::0x0273,

    DeviceLocation::RawValue::0x1000000,

Keyboard
    Bluetooth USB Host Controller (Broadcom Corp.)

    DeviceVendor::RawValue::0x05ac,
    DeviceProduct::RawValue::0x8290,

    DeviceLocation::RawValue::0x14300000,

Keyboard
    ThinkPad Compact Bluetooth Keyboard with TrackPoint (Unknown)

    DeviceVendor::RawValue::0x17ef,
    DeviceProduct::RawValue::0x6048,

    DeviceLocation::RawValue::0x6110d3e7,

Consumer
    Apple Internal Keyboard / Trackpad ()

    DeviceVendor::RawValue::0x05ac,
    DeviceProduct::RawValue::0x0273,

    DeviceLocation::RawValue::0x1000000,

Consumer
    ThinkPad Compact Bluetooth Keyboard with TrackPoint (Unknown)

    DeviceVendor::RawValue::0x17ef,
    DeviceProduct::RawValue::0x6048,

    DeviceLocation::RawValue::0x6110d3e7,


```

The private.xml

``` xml
    <item>
        <identifier>remap.samples_flipscrollwheel_vertical</identifier>
        <name>Flip Vertical ScrollWheel</name>
        <device_only>DeviceVendor::RawValue::0x17ef,DeviceProduct::RawValue::0x6048</device_only>
        <autogen>--FlipScrollWheel-- Option::FLIPSCROLLWHEEL_VERTICAL</autogen>
    </item>
```

Nothing happens even if I change RawValue or delete the <devcie_only>.

**Comment by tekezo** [comment]
> Can't recognise my MADCATZ R.A.T 9 wireless mouse in EventViewer （In the Devices Page）

Are you using non-Apple device driver for this mouse?
If so, the driver might be conflicting with Karabiner.
Please uninstall the driver.


> Can't recognise my thinkpad bluetooth keyboard Fn Key

Unfortunately, fn key in non-Apple keyboard is not recognizable.


> Can't flip the mouse scroll wheel vertical（or horizontal）

Are you change the TrackPoint to scroll wheel by Karabiner?
Please enable this setting.
![160205-0002](https://cloud.githubusercontent.com/assets/659178/12849187/a5642afc-cc61-11e5-9962-4155c1eaac81.png)

**Comment by smartepsh** [comment]
I cant uninstall my mouse driver...I need it to show the battery ...


![123](https://cloud.githubusercontent.com/assets/3273295/12864383/f39dd170-ccc3-11e5-8679-5b82a3ec486c.jpg)
It doesn't work...

**Comment by tekezo** [comment]
> I cant uninstall my mouse driver...I need it to show the battery ...

I understand your situation.
If so, please give up using Karabiner for MADCATZ R.A.T 9 wireless mouse.

> It doesn't work...

Hmm, I believe trackpoint does not has native scroll wheel.
I understand you change the trachkpoint to scroll wheel with `__PointingRelativeToScroll__`.
Is it right?

**Comment by ethus3h** [comment]
The setting shown in https://github.com/tekezo/Karabiner/issues/568#issuecomment-180383253 works fine for my trackpoint fine. As far as I know it doesn't affect the trackpad, which is controlled through the Natural Scrolling option in System Preferences.

**Comment by smartepsh** [comment]
@tekezo @ethus3h Sorry for waiting...
My trackpoint and trackpad always in same direction and controlled by System Preferences.
@tekezo NO. Thinkpad keyboard use mouse middle button + trackpoint to scroll. The event viewer display that just is the scroll wheel.
I've tried two ways and neither of these can work:
> Set __FlipScrollWheel__ Option::FLIPSCROLLWHEEL_VERTICAL in private.xml
> Enable 'Reverse scroll direction vertically'

Whatever I do, they even have nothing changed.
So what else can I do?

**Comment by tekezo** [comment]
@smartepsh I guess you are using another driver for trackpoint. (For example, SteerMouse)
Could you show me the result of `ioreg -l` in Terminal.

* Open Terminal.app
* Execute `ioreg -l > ~/Desktop/ioreg.txt` in Terminal.
* Put ioreg.txt in Desktop into this issue.

**Comment by smartepsh** [comment]
[ioreg.txt](https://github.com/tekezo/Karabiner/files/124233/ioreg.txt)
I use 'smoothmouse' to change mouse acceleration.

**Comment by tekezo** [comment]
I got it.
We cannot use Karabiner and SmoothMouse together.
Karabiner ignores all pointing devices if SmoothMouse is installed.

You might be able to flip scroll by another apps like this:
https://pilotmoon.com/scrollreverser/

**Comment by smartepsh** [comment]
Hmmm.....Yes, it works....
The SmoothMouse wastes a lot of time....
Thank you for your help!
