### ISSUE TITLE
"Swap left command key and left control key in Wineskin" No longer works in El Capitan

### ISSUE THREAD

**Issue by cbbflfjz** [tekezo/Karabiner#569]
Apparently somebody has already reported this issue here, https://groups.google.com/forum/#!topic/osx-karabiner/dQrvcRaCAnE
but for some reason that person never responded back when asked to provide private.xml and bundle identifier..

Well, here is [mine.zip](https://github.com/tekezo/Karabiner/files/115912/mine.zip), I really hope this can get fixed.

**Comment by tekezo** [comment]
The setting works well on my machine.
Please show me the App tab in EventViewer when you activate Wineskin app.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by ethus3h** [comment]
(Random thought: is it possible that it is an issue affecting only some Wineskin apps?)

**Comment by d-robin** [comment]
I am using Crossover. Is there a way I can make it work with apps on Crossover?

**Comment by tekezo** [comment]
Karabiner requires apps be an OS X bundle forms to detect the application switching.
If these apps are bare binaries, we should wrap them by properly way.
(eg. There are possibiliity to solve by making a wrapper app by Automator.)
