### ISSUE TITLE
Vim keybindings in Preview.app

### ISSUE THREAD

**Issue by framecurrent** [tekezo/Karabiner#571]
I have tried to set up vim keybindings in OSX Preview.app. Everything works fine, except that the keys don't work in the search box. I have the same settings as shown in #414, including the `<uielementrole_not>` tag, but it doesn't help.

Does the tag actually still work? Any workaround?
---

OS X 10.11.3 (same results for the previous version)
Karabiner 10.15.0 
MacBook Pro
Keyboard: Several, including the MBP one

**Comment by tekezo** [comment]
Please turn off the attached checkbox. 
![160206-0002](https://cloud.githubusercontent.com/assets/659178/12851769/05415384-cc6f-11e5-91b9-be48153c4415.png)
