### ISSUE TITLE
Supporting beta version of Microsoft Remote Desktop

### ISSUE THREAD

**Issue by supermomonga** [tekezo/Karabiner#572]
Karabiner has Microsoft Remote Desktop app configuration by default. I found there is the [beta version of Microsoft Remote Desktop](https://blogs.msdn.microsoft.com/rds/2015/08/11/introducing-the-new-microsoft-remote-desktop-preview-app-for-mac/), and we can download it [here](https://rink.hockeyapp.net/apps/5e0c144289a51fca2d3bfa39ce7f2b06/). I think it's nice if we can also use beta version configuration as default.

Could you consider to support not only stable version but also beta version as default?

**Comment by tekezo** [comment]
I've supported Microsoft Remote Desktop beta at Karabiner-10.15.43.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by supermomonga** [comment]
I tried Karabiner-10.15.43 and it works perfectly!
Thank you :smile:
