### ISSUE TITLE
Unknown symbol:  ModifierFlag::F15

### ISSUE THREAD

**Issue by weiweihuanghuang** [tekezo/Karabiner#575]
Is it not possible to use F15 as a modifier? I want to create a mapping that turns

W+F15, into Up:
```
	<item>
		<name>Glyphs App WSAD to D-Pad Using Mouse</name>
		<identifier vk_config = "true">private.glyphs_wsad_mouse</identifier>
		<only>GLYPHSAPP</only>
		<autogen>__KeyToKey__
			KeyCode::W, ModifierFlag::F15,
			KeyCode::CURSOR_UP
		</autogen>
	</item>
```

but I get the error
`Unknown symbol:  ModifierFlag::F15` 
I tried the __SimultaneousKeyPresses__ but it doesn't let me press and hold it.

**Comment by tekezo** [comment]
Please use modifierdef to make your f15 key as modifier.

```xml
    <modifierdef>F15</modifierdef>
    <autogen>__KeyToKey__ KeyCode::F15, KeyCode::VK_MODIFIER_F15</autogen>
    <autogen>
      __KeyToKey__
      KeyCode::W, ModifierFlag::F15,
      KeyCode::CURSOR_UP
    </autogen>
```

https://pqrs.org/osx/karabiner/xml.html.en#modifier

**Comment by weiweihuanghuang** [comment]
Worked thank you very much
