### ISSUE TITLE
activate all sub-items of an item

### ISSUE THREAD

**Issue by ksint** [tekezo/Karabiner#576]
Is is possible to add a checkbox to an item that activates all sub-items in the xml settings?
For me, this would be helpful so I can activate all my custom settings with one click.

**Comment by tekezo** [comment]
I think using command line interface (`enable` command) is suitable way for this purpose.

**Comment by ksint** [comment]
Thanks. The export feature is the perfect solution.

    /Applications/Karabiner.app/Contents/Library/bin/karabiner export > set_karabiner_settings.sh
