### ISSUE TITLE
swap previously swapped keys

### ISSUE THREAD

**Issue by ksint** [tekezo/Karabiner#578]
Is it possible to swap an already swapped key? Below, I swapped Cmd and Option and then swapped left Cmd and Option for VMware Fusion but the second swap doesn't seem to work. A workaround would be to swap using `<not>` but I wanted to check if it is possible this way. Thanks.

```
	<item>
		<name>swap cmd and opt for specified devices</name>
		<identifier>private.swap.cmd.option</identifier>
		<autogen>
			__KeyToKey__ 
			KeyCode::OPTION_L, 
			KeyCode::COMMAND_L
		</autogen>
		<autogen>
			__KeyToKey__ 
			KeyCode::COMMAND_L, 
			KeyCode::OPTION_L
		</autogen>
		<autogen>
			__KeyToKey__ 
			KeyCode::OPTION_R, 
			KeyCode::COMMAND_R
		</autogen>
		<autogen>
			__KeyToKey__ 
			KeyCode::COMMAND_R, 
			KeyCode::OPTION_R
		</autogen>
	</item>

	<appdef>
		<appname>VMWARE_FUSION</appname>
		<equal>com.vmware.fusion</equal>
	</appdef>
	
	<item>
		<name>vmware, swap left cmd and option</name>
		<identifier>private.vmware.leftcmd.leftoption</identifier>
		<only>VMWARE_FUSION</only>

		<autogen>
			__KeyToKey__ 
			KeyCode::COMMAND_L, 
			KeyCode::OPTION_L
		</autogen>
		<autogen>
			__KeyToKey__ 
			KeyCode::OPTION_L,
			KeyCode::COMMAND_L
		</autogen>
	</item>
```

**Comment by ksint** [comment]
The reason for this way instead of `<not>` was that the first item would swap keys for non-Mac keyboards but the swap for VMware would apply regardless of keyboard.

**Comment by tekezo** [comment]
> Is it possible to swap an already swapped key?

There is no way for recursive changes.
Please use <not> filter in private.swap.cmd.option.

**Comment by ksint** [comment]
That works. Thanks.
