### ISSUE TITLE
No keycode for event

### ISSUE THREAD

**Issue by rarens** [tekezo/Karabiner#579]
I'm trying to map my mouse's left and right scroll to vol up/down.  The events get fired but there is no key code to remap.  However, there is some data showing up in "misc."   My mouse shows up under devices as well.  Every other button event on the mouse has a keycode.  Is there some way to resolve this?

I have tried to remap it with:
<autogen>
**ScrollWheelToKey** ScrollWheel::LEFT,  ConsumerKeyCode::VOLUME_DOWN
</autogen>
<autogen>
**ScrollWheelToKey** ScrollWheel::RIGHT, ConsumerKeyCode::VOLUME_UP
</autogen>

but it did not work.  Is there anything else I should try?
<img width="777" alt="screen shot 2016-02-18 at 12 42 43 am" src="https://cloud.githubusercontent.com/assets/7475631/13135669/942679d6-d5d8-11e5-89bb-364446b0436b.png">
<img width="882" alt="screen shot 2016-02-18 at 12 43 32 am" src="https://cloud.githubusercontent.com/assets/7475631/13136006/507aa114-d5db-11e5-940d-6629e7950322.png">

**Comment by tekezo** [comment]
Your autogens should work.
Please decrease "ScrollWheel To Key > Key Repeat Wait" in Karabiner Preferences > Parameters tab.
![160218-0001](https://cloud.githubusercontent.com/assets/659178/13141956/51cb0390-d67d-11e5-8ada-6204116bc34e.png)

**Comment by rarens** [comment]
Thank you for your reply.  I tried that.  No change.

**Comment by tekezo** [comment]
Hmm, please confirm Karabiner can modify your mouse events.
For example, this autogen changes your right button to mission control.

```xml
    <autogen>__KeyToKey__ PointingButton::RIGHT, KeyCode::MISSION_CONTROL</autogen>
```

If the autogen works fine but `__ScrollWheelToKey__` does not work, did you change scroll wheel events by another setting (eg. `__FlipScrollWheel__`)?
Karabiner applies only the first matched <autogen>.
So you should put `__ScrollWheelToKey__` in the top of your private.xml.
