### ISSUE TITLE
Feature: Support remapping zoom button on Microsoft Ergonomic 4000

### ISSUE THREAD

**Issue by indradhanush** [tekezo/Karabiner#580]
Recently Karabiner added support for remapping keys in Microsoft Ergonomic 4000 Keyboard. But it does not have any option to remap the zoom key in the center of the keyboard. It would be great if we can add support for remapping this key to scroll up/down.

**Comment by indradhanush** [comment]
@tekezo I'd be happy to send in a patch for this, if you can help me on how to get started. :)

**Comment by tekezo** [comment]
Is there any output by the zoom button in debug mode?
https://pqrs.org/osx/karabiner/document.html.en#debugmode

If not, unfortunately, Karabiner can not change the zoom button.

**Comment by indradhanush** [comment]
@tekezo Cant see anything in debug mode. :(

**Comment by tekezo** [comment]
Thank you for confirmation.
If you want to use the zoom button, it is worth to try another drivers.

USB Overdrive:
http://www.usboverdrive.com/

ControllerMate:
http://www.orderedbytes.com/controllermate/

**Comment by indradhanush** [comment]
Thanks @tekezo. I used USB Overdrive. Works perfectly!
