### ISSUE TITLE
Change F1...F12 to Brightness Control...Not working in OS X 10.11.4

### ISSUE THREAD

**Issue by kluthage421** [tekezo/Karabiner#583]
I have box checked but settings not applied. External keyboard. Reinstalled. Tried beta version. Restarted computer. Plugged keyboard in again.

**Comment by tekezo** [comment]
What is your keyboard hardware?

**Comment by kluthage421** [comment]
My keyboard is a DBPower USB keyboard.

**Comment by tekezo** [comment]
Thank you for information.
I believe Karabiner can change the f1-f12 keys on your keyboard.

Please confirm the follows:

1. Is your keyboard shown in EventViewer > Devices tab?
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

2. Did you enabled this setting?
There are similar settings in prepared settings.
Be careful to select "F1,F2 to XXX". (not "XXX to F1,F2")

![160223-0002](https://cloud.githubusercontent.com/assets/659178/13247885/0fcc13e0-da5f-11e5-9438-fab389390df0.png)

**Comment by kluthage421** [comment]
Thank you very much for your support. I completely removed everything and then installed the latest beta and it appears to be working. I wish I knew why it wasn't, but it is now. :)
