### ISSUE TITLE
Use Control+Space as Markset enables Shift permanently

### ISSUE THREAD

**Issue by indradhanush** [tekezo/Karabiner#585]
Steps to reproduce:

1. Enable "Control+Space as Markset...
2. Hit `Control+Space` outside karabiner.
3. Now whatever you type, `shift` is enabled by default.
4. Go to `Karabiner` and look at the `show enabled items`. If you have `n` items, it will show `n+1`.
5. Click on `Reload XML` and everything is back to normal again.

I confirmed that it is the `shift` key by enabling debug mode.

**Comment by tekezo** [comment]
This is intended behavior.
Karabiner turn on the shift modifier to keep text selection.
Press control+space again or other markset commands (control+W,option+W,control+G) to turn off the shift modifier.

**Comment by indradhanush** [comment]
@tekezo Ah. Now I understand it. Thanks!
