### ISSUE TITLE
Wrongly identified devices

### ISSUE THREAD

**Issue by blueset** [tekezo/Karabiner#586]
* OS X version: 10.10.5
* Karabiner version: 10.15.0
  (You can confirm the version in "Misc & Uninstall" tab in Karabiner Preferences.)
* Your Mac hardware: rMBP
* Your ~~keyboard~~ hardware: Vortex POK3R; Microsoft Sculpt Touch Mouse

My Bluetooth mouse is identified as both a keyboard and a mouse, the same thing happens to my keyboard too.
This affects the "Disable an internal keyboard while external keyboards are connected" option when I only connect the mouse.

Screenshot from Event Viewer
![image](https://cloud.githubusercontent.com/assets/553831/13273681/3d0ca94c-dae0-11e5-9b49-8e38a191a38e.png)

**Comment by tekezo** [comment]
Thank you for feedback.
I've changed to ignore Microsoft Sculpt Touch Mouse from connected keyboard at Karabiner 10.15.65.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by blueset** [comment]
It works perfectly now. Thank you!
