### ISSUE TITLE
Question: Is it possible to remap hjkl to jkl; using the vim keybindings?

### ISSUE THREAD

**Issue by diegodesouza** [tekezo/Karabiner#587]
I looked around the documentation but didn't find it, I believe there's a way to add custom configuration, can someone point me to the right direction if this is possible. I normally use fn + jkl; to move around vim in insert mode if needed, since i don't have the arrow keys in my 60% keyboard.

**Comment by tekezo** [comment]
What vim bindings are you using?

Please show me your enabled settings.
(Screen shot of Karabiner Preferences with "show enabled only".)

**Comment by diegodesouza** [comment]
![screen shot 2016-03-02 at 3 30 57 pm](https://cloud.githubusercontent.com/assets/7575914/13474393/d817f88c-e08b-11e5-8732-0562d7a77501.png)

**Comment by tekezo** [comment]
Thank you for information.

Please upgrade Karabiner to the latest beta. (v10.15.74)

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

Then add the following replacementdef into your private.xml.

```xml
  <replacementdef>
    <replacementname>VI_H</replacementname>
    <replacementvalue>KeyCode::J</replacementvalue>
  </replacementdef>

  <replacementdef>
    <replacementname>VI_J</replacementname>
    <replacementvalue>KeyCode::K</replacementvalue>
  </replacementdef>

  <replacementdef>
    <replacementname>VI_K</replacementname>
    <replacementvalue>KeyCode::L</replacementvalue>
  </replacementdef>

  <replacementdef>
    <replacementname>VI_L</replacementname>
    <replacementvalue>KeyCode::SEMICOLON</replacementvalue>
  </replacementdef>
```

**Comment by diegodesouza** [comment]
Beautiful, Thank you very much for the help!
