### ISSUE TITLE
Adding a sticky modifier key.

### ISSUE THREAD

**Issue by kilbert134** [tekezo/Karabiner#588]
[private copy.txt](https://github.com/tekezo/Karabiner/files/148920/private.copy.txt)

hi, recently i broke my arrow keys on my computer so i was wondering how to remap them to WASD. I succeeded in that, but i need to hold down the shift key for them to work, so i was wondering how i would go about adding a sticky key so all i would need to do is click it once for it to switch between the arrow keys and the regular wasd. im completely new to  karabiner and have never remapped my keys before so im a little new to all of this. I put a txt file of what i currently have

**Comment by tekezo** [comment]
Please replace your private.xml with this:

```xml
<?xml version="1.0"?>
<root>

  <modifierdef>ARROW</modifierdef>

  <item>
    <name>Allow Shift+WASD keys to behave like arrow keys</name>
    <identifier>private.allow_esc_with_arrow_keys</identifier>

    <!-- first type -->
    <autogen>
      __KeyToKey__
      KeyCode::W, ModifierFlag::SHIFT_L,
      KeyCode::CURSOR_UP,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::A, ModifierFlag::SHIFT_L,
      KeyCode::CURSOR_LEFT,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::S, ModifierFlag::SHIFT_L,
      KeyCode::CURSOR_DOWN,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::D, ModifierFlag::SHIFT_L,
      KeyCode::CURSOR_RIGHT,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>

    <!-- second type -->
    <autogen>
      __KeyToKey__
      KeyCode::W, ModifierFlag::ARROW,
      KeyCode::CURSOR_UP,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::A, ModifierFlag::ARROW,
      KeyCode::CURSOR_LEFT,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::S, ModifierFlag::ARROW,
      KeyCode::CURSOR_DOWN,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::D, ModifierFlag::ARROW,
      KeyCode::CURSOR_RIGHT,
      KeyCode::VK_STICKY_ARROW_FORCE_ON,
    </autogen>

    <!-- cancel by escape key -->
    <autogen>
      __KeyToKey__
      KeyCode::ESCAPE, ModifierFlag::ARROW,
      KeyCode::VK_STICKY_ARROW_FORCE_OFF,
    </autogen>

  </item>
</root>
```

**Comment by jfumez** [comment]
is there a certain reason i can only use this on certain apps. on some computer games/ other clients it doesnt work when trying to walk or spin the camera? is it the client or did i do something wrong?

**Comment by tekezo** [comment]
The above setting send keydown and keyup at the same time in order to use sticky modifier.
I guess it is the cause of issue in games.

Please use new private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.allow_esc_with_arrow_keys/private.xml

**Comment by jfumez** [comment]
Finally got it working thanks so much Takezo

**Comment by tekezo** [comment]
Use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.allow_esc_with_arrow_keys2/private.xml

You can toggle mode by the left shift key.

**Comment by jfumez** [comment]
Perfect, thanks again
