### ISSUE TITLE
Question: Move to trash

### ISSUE THREAD

**Issue by xpert13** [tekezo/Karabiner#589]
Hello.

Is it any way to use Delete key for "Move to trash" action in Finder?

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.finder_delete_to_move_to_trash/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by xpert13** [comment]
It's doesn't work. But Cmd+Delete doesn't work too. And I don't know why :(

**Comment by tekezo** [comment]
Does you mention the forward delete key as "Delete key"?

What result of EventViewer when you pressed delete key?
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by xpert13** [comment]
Thank you for the help and super fast answers. It was not DELETE but FORWARD_DELETE key.

**Comment by tekezo** [comment]
Please use "Use Forward Delete key as Delete Files" in prepared settings.
![160229-0002](https://cloud.githubusercontent.com/assets/659178/13397145/fa1b3e68-df3b-11e5-8398-4f29ed8d495f.png)

**Comment by xpert13** [comment]
Perfect. Thank you again.
