### ISSUE TITLE
How can I change [] with () without interfering with anything else?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#590]
I am looking through Karabiner documentation and trying to figure out how to edit my XML file so I can do this but I don't quite know how to do it.

I want to be able to use round brackets with a single presses on where [ and ] keys are and be able to use shift + 9 and shift + 0 to get my [ and ] respectively.

Thank you for any help and I hope there is way to do it.

**Comment by ethus3h** [comment]
See https://pqrs.org/osx/karabiner/xml.html.en#keytokey-syntax — look into the first 3 headings in that section.

Use the Event Viewer https://pqrs.org/osx/karabiner/document.html.en#eventviewer to figure out the key names :)

**Comment by nikitavoloboev** [comment]
Thank you,

However I tried it now and I don't quite know how I can change it without losing the curly brackets. perhaps I am doing it wrong. Here is what I have done in my XML file, is this the right way to do it?
![1](https://cloud.githubusercontent.com/assets/6391776/13411095/8a4e5e26-df3b-11e5-921f-2aba898736f7.png)

**Comment by ethus3h** [comment]
Try adding `ModifierFlag::NONE` to the first two items, maybe? Then it'll only affect it with no modifier keys pressed.

**Comment by nikitavoloboev** [comment]
That worked. Thank you so much.

**Comment by nikitavoloboev** [comment]
However this brings the issue that when I press the key where the bracket is at whilst typing in russian, the bracket shows up instead of the letter 'х'.

I guess one way I can solve this is to make it so that these <item> things work only on what kind of keyboard i.e. 'British'. 

Do you by chance know a way to make this and whether it is even possible to do this. I am not even sure if that is the right way to go about it. 

Thank your any help.

**Comment by ethus3h** [comment]
Hmm, I'm not sure, sorry. :(

**Comment by tekezo** [comment]
Please use `< inputsource_only>` filter together.
https://pqrs.org/osx/karabiner/xml.html.en#inputsourcedef

**Comment by nikitavoloboev** [comment]
thank you tekezo, that worked perfectly :)
