### ISSUE TITLE
Karabiner just does nothing

### ISSUE THREAD

**Issue by cawoodm** [tekezo/Karabiner#592]
Spent around 2 hours trying to get Karabiner 10.15.0 to do something... anything but it seems to have zero effect. I've tried both the UI and private.xml but nothing has any effect. Yes, Karabiner has been allowed the privileges in Security and Privacy.

Example config:

```
<?xml version="1.0"?>
<root>
  <item>
    <name>Swap Space and Tab</name>
    <identifier>private.swap_space_and_tab</identifier>
    <autogen>__KeyToKey__ KeyCode::SPACE, KeyCode::TAB</autogen>
    <autogen>__KeyToKey__ KeyCode::TAB, KeyCode::SPACE</autogen>
  </item>
</root>
```

My assumption is when I save private.xml my space and tab keys should immediately be swapped. This is not the case so I guess I am missing something really basic.

Interestingly in the UI I have 2 changes active which are not in the XML. When I click reload the XML nothing happens: the space/tab swap above does not appear.

**Comment by tekezo** [comment]
The cause might be that your keyboard has own driver and it's not compatible with Karabiner.
Please tell me your hardware information.

* Your Mac hardware:
* Your keyboard hardware:

**Comment by cawoodm** [comment]
MacBookPro11,2 (Late 2013) - don't know much else. It's the built-in keyboard - Swiss layout.

**Comment by tekezo** [comment]
Hmm, Karabiner should work on your environment.

Did you follow this instruction?
https://pqrs.org/osx/karabiner/document.html.en#privatexml

> My assumption is when I save private.xml my space and tab keys should immediately be swapped. 

No, you have to enable new setting.
See step 7 in the above instruction.
