### ISSUE TITLE
The following build commands failed The following build commands failed: 	CompileXIB Resources/PreferencesWindow.xib 

### ISSUE THREAD

**Issue by boddumanohar** [tekezo/Karabiner#593]
I 've copied the 'boost' folder in the downloaded 'boost_1_60_0' to /opt/local/include/ and also done:**sudo gem install cocoapods && pod setup** 

then
cd Karabiner-master 
make

results in the 

*\* BUILD FAILED **

The following build commands failed:
    CompileXIB Resources/PreferencesWindow.xib
(1 failure)
make[4]: **\* [all] Error 65
make[3]: **\* [all] Error 2
make[2]: **\* [all] Error 2
make[1]: **\* [build] Error 2
make: **\* [all] Error 2

how to fix this failure

**Comment by tekezo** [comment]
What is your Xcode version?
Please use Xcode 7.2.

**Comment by bmanu199** [comment]
now I've installed Xcode 7.2.1. Now the build has succeeded but returned the same errors.

** BUILD SUCCEEDED **

xcodebuild \
		-workspace *.xcworkspace \
		-scheme Pods \
		-configuration Release \
		build \
		SYMROOT=`pwd`/build
Build settings from command line:
    SYMROOT = /Users/manoharreddy/Desktop/Karabiner-master

xcodebuild: error: Unknown build action 'copy/src/core/server/build'.
make[4]: *** [all] Error 65
make[3]: *** [all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2
make: *** [all] Error 2

**Comment by tekezo** [comment]
Please confirm you installed command line tools.

**Comment by bmanu199** [comment]
Yes command line tools have also been updated.
