### ISSUE TITLE
Karabiner 10.17.0 crashing in -[PreferencesManager clearNotSave]

### ISSUE THREAD

**Issue by nriley** [tekezo/Karabiner#594]
Twice so far today. I was not using my Mac at either time.

[Karabiner_2016-03-06-150337_mary.txt](https://github.com/tekezo/Karabiner/files/160538/Karabiner_2016-03-06-150337_mary.txt)
[Karabiner_2016-03-06-102708_mary.txt](https://github.com/tekezo/Karabiner/files/160537/Karabiner_2016-03-06-102708_mary.txt)

I've never had a crash with any previous version of Karabiner and my configuration hasn't changed.

**Comment by tekezo** [comment]
Thank you for feedback!

I've fixed this issue at v10.18.0.
Please upgrade Karabiner.
