### ISSUE TITLE
Karabiner 10.18.0 breaks Intellij keyboard shortcuts

### ISSUE THREAD

**Issue by petromir** [tekezo/Karabiner#595]
I set some of the settings in section "For PC Users". One of the selected option is 'User PC Stype Copy/Paste", which internally sets Control+C to Command+C. At the same time my Intellij keymap settings already have Control+C as a copy command, but pressing it actually passes Command+C, which breaks the IDE keymap functionallity.

I think that Intellij should be (or may be provided as option) excluded from this option just like other applications like Team Viewer, VNC etc.

Machine: MacBookPro11,4
OS: OS X 10.11.3 
Keyboard: Microsoft Comfort Curve Keyboard 3000

**Comment by tekezo** [comment]
Please override ignore apps by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.PC_STYLE_BINDINGS_IGNORE_APPS2/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by petromir** [comment]
Thanks. That fixed the issue :)

**Comment by b1102** [comment]
and how to do the same in the 11.5 version?
