### ISSUE TITLE
Can I map FN + Left Shift to act as some combination when pressed together?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#599]
I am trying to make it work right now and this is what I have so far :

![karabiner1](https://cloud.githubusercontent.com/assets/6391776/13781754/b6d01afe-eac4-11e5-96c4-b072e0ccbace.png)

This is wrong though as I believe that SHIFT_L is a ModifierFlag and not a KeyCode but then I am also not sure and I think you cannot have two ModifierFlag together without some KeyCode in there too.

I don't really know what I should do from here as I really want to make that combination work + if this works, this can open up the possibility to map other Modifier keys together like Right Command and left Opt key. 

I hope what I wrote is understandable and this can be done with Karabiner as it really will be quite nice, I don't get much use of the fn key right now and I want to change that.

Thank you for any help.

**Comment by tekezo** [comment]
Do you want this autogen?

```xml
    <autogen>
      __KeyToKey__
      KeyCode::SHIFT_L, ModifierFlag::FN,
      KeyCode::CONTROL_L, ModifierFlag::OPTION_L | ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Yes, this is exactly what I want. However it seems that the normal FN + Shift + {some other key}, don't work now. It treats that FN + Shift as that combination. I want it so that it makes that combination of keys only when FN + Shift is pressed alone and that is it, other times it will act as normal modifier keys.

This is quite close though.

**Comment by tekezo** [comment]
How about this?

```xml
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_L, ModifierFlag::FN,
      KeyCode::SHIFT_L, ModifierFlag::FN,
      KeyCode::X, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L, ModifierFlag::SHIFT_L
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Yess, thank you so much. 

I see what you did there too so I am confident I can use variations of this autogen for some other cool bindings I was thinking of.

**Comment by nikitavoloboev** [comment]
hey tekezo,

I want to use fn key as all four key modifier when pressed in combination and fn when pressed alone. This works great but is there a way I can also use the above mentioned autogen with it where it will also work and not interfere with the my big four modifier keys autogen?

Is there some way I can make it work? Here is what I have made, but that does not work and I don't really know how to make an exception for it.

![4](https://cloud.githubusercontent.com/assets/6391776/13784200/a4340518-eace-11e5-9a90-eb20d030d6ae.png)

**Comment by tekezo** [comment]
I think changing the physical left shift key to X key is simplest way.

The general way is using own modifier (MY_FN) to determine whether the physical fn key is pressed.

```xml
    <modifierdef>MY_FN</modifierdef>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_L, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L | ModifierFlag::MY_FN,
      KeyCode::SHIFT_L, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L | ModifierFlag::MY_FN,
      KeyCode::X, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L, ModifierFlag::SHIFT_L
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::FN,
      KeyCode::COMMAND_L, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L, ModifierFlag::SHIFT_L | ModifierFlag::MY_FN,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
I am not sure I fully understand what you did there with <modifierdef>.

Also is is <modifierdef> a global thing or should be declared in-between  <item> and </item>.

I just copied what you wrote there but that does not work. FN key works as a modifier of 4 but Shift + FN does not. 

![5](https://cloud.githubusercontent.com/assets/6391776/13784998/d1701b72-ead1-11e5-8c4b-7858d1785a94.png)

**Comment by tekezo** [comment]
Do you want to use fn+shift as fn+shift (not 4 modifers)?
If so, modify `__KeyOverlaidModifier__` like this.

```xml
    <modifierdef>MY_FN</modifierdef>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_L, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L | ModifierFlag::MY_FN,
      KeyCode::SHIFT_L, ModifierFlag::FN | ModifierFlag::MY_FN,
      KeyCode::X, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L, ModifierFlag::SHIFT_L
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::FN,
      KeyCode::COMMAND_L, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L, ModifierFlag::SHIFT_L | ModifierFlag::MY_FN,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Wow, that worked. That's exactly what I wanted. I am still not really sure what role `<modifierdef>` plays there but that worked. Will try to look at it again and try and understand everything.

Thank you a lot for your help. :)

**Comment by tekezo** [comment]
If you allow to change the physical command-control-option-shift to fn-shift, you do not need to use MY_FN.
It's used to distinglish the physical command-control-option-shift and the physical fn-shift.

```xml
  <item>
    <name>Fn Shift to combination</name>
    <identifier>private.fn_shift_to_combination</identifier>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_L, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L,
      KeyCode::SHIFT_L, ModifierFlag::FN,
      KeyCode::X, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L, ModifierFlag::SHIFT_L
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::FN,
      KeyCode::COMMAND_L, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L, ModifierFlag::SHIFT_L,
    </autogen>
  </item>
```

**Comment by nikitavoloboev** [comment]
I apologise for asking for your help again but I've been trying to do this for quite some time yesterday and am bit confused with how to map something to an actual physical delete key. 

I have this autogen that I use very often now : 

![2016-03-19 at 12 33](https://cloud.githubusercontent.com/assets/6391776/13898365/0fd739d6-edcf-11e5-9954-8a382175a4b1.png)

It's pretty straightforward, as it makes right shift act as shift + command and delete key when pressed alone. I also have my right option key binded to left control key with one of app's given autogens : 


![2016-03-19 at 12 37](https://cloud.githubusercontent.com/assets/6391776/13898377/6a83b1fc-edcf-11e5-9a0b-0ec4cf0510d7.png)

I then use my right opt key to open various applications, I binded it with bettertouchtool : 

![2016-03-19 at 12 40](https://cloud.githubusercontent.com/assets/6391776/13898388/d6d2570a-edcf-11e5-8324-4e19f986e6e5.png)

The thing is though that now that I have both shift and delete key as 'Delete' key i cannot bind two unique things to both my actual physical delete key and my binded shift key as they are literally the same key. 

I was thinking a lot yesterday and now how can I make a binding of physical 'OPTION_R' and physical 'DELETE' key to open a specific application I want, in my case I want OPTION_R + 'top DELETE' to open Mindnode and 'OPTION_R' + 'Right Shift' to open Sublime Text. 

I read through the documentation and this is what I came up with so far : 

![2016-03-19 at 12 58](https://cloud.githubusercontent.com/assets/6391776/13898481/8f7ebfd0-edd2-11e5-8c57-541d02f56af7.png)

and my KeyCode::VK is right : 

![2016-03-19 at 13 01](https://cloud.githubusercontent.com/assets/6391776/13898487/a90c3ec8-edd2-11e5-9061-98cf368ae979.png)


But that doesn't work and if I decide to change DELETE to KEYCODE instead of MODIFERKEY it works for that specify combination but messes up every other keybinding I had with my right option key :( 

I really wish I could make this work, reading through karabiner documentation is really great and its extensive but I couldn't make it work.

Essentially all I want is for my right option key + physical delete key to open one app and physical option key + right shift key to open another app without interfering with anything else. I hope I make this work.

Thank you for any help you can provide, tekezo :)

**Comment by tekezo** [comment]
To open app by the physical option + delete key,

```xml
    <autogen>
      __KeyToKey__
      KeyCode::DELETE, ModifierFlag::CONTROL_L,
      KeyCode::VK_OPEN_URL_APP_...,
    </autogen>

    <!-- right option + 
    <autogen>
      __KeyToKey__
      KeyCode::SHIFT_R, ModifierFlag::CONTROL_L,
      KeyCode::VK_OPEN_URL_APP_...,
    </autogen>
```

You have to put these autogen before private.right_shift_to_command_and_shif.
https://pqrs.org/osx/karabiner/xml.html.en#order

Note:
Please use fenced code blocks to describe XML in order to keep text form.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by nikitavoloboev** [comment]
Thank you a lot. This worked. 

I can see how I can bind things now with Karabiner. It's pretty powerful.

I changed the screenshots to 'code blocks' so it should be good.

Thank you a lot.
