### ISSUE TITLE
How to map 'option + PointingButton::LEFT' to another key?

### ISSUE THREAD

**Issue by loggerhead** [tekezo/Karabiner#600]
I want to execute an applescript when press `option + left tap on trackpad`, here is my configuration:

```xml
        <autogen> __KeyToKey__
          PointingButton::LEFT,
          ModifierFlag::OPTION_L, ModifierFlag::NONE,
          KeyCode::VK_OPEN_URL_SCRIPT_COPY_FINDER_PATH
        </autogen>
```

I tried map from other key combinations, they all works fine except `PointingButton::LEFT, ModifierFlag::OPTION_L`. So, is something wrong in my configuration?

**Comment by tekezo** [comment]
Your autogen should work.

There are some possibility.

* You should enable Tap to click in System Preferences > Trackpad.
![160316-0001](https://cloud.githubusercontent.com/assets/659178/13800317/7b68ddc8-eb6b-11e5-980d-54c703cf21d6.png)
* If you pressed other modifiers (command, control or shift), the autogen does not change left click.
* If you already changed left click in your private.xml, Karabiner uses only the first matched autogen.
    https://pqrs.org/osx/karabiner/xml.html.en#order

**Comment by loggerhead** [comment]
I have check all above possibility, and I am pretty sure none of them is the cause. I post my configuration to gist, you can check it [here](https://gist.github.com/loggerhead/c4eef484190b8d61fbda)

**Comment by loggerhead** [comment]
Sorry, I have found that I enable predefined configurations:

* `Don't remap any pointing devices`
* `Don't remap Apple's pointing devices`

That's the reason why it not work.
