### ISSUE TITLE
Single key -> two simultaneous keys?

### ISSUE THREAD

**Issue by MITGameLab** [tekezo/Karabiner#601]
Hi! I tried looking in the documentation for this: Is it possible to remap a single keypress to two simultaneous keypresses?

Specifically, we have an app that does something specific if you hold down two keys on the keyboard simultaneously. We are using Karabiner to make it work with an arcade stick, and we want to map one button on the the arcade stick to act as two buttons on the keyboard.

Holding "Shift_L" button down -> "A" and "D" held down simultaneously
Holding "W" button down -> "J" and "L" held down simultaneously 

We've tried:
__KeyToKey__ KeyCode::W, KeyCode::J, KeyCode::L

That just results in "jljljljljljl" when we hold down W in a text-input window, but is not recognized as J and L held down simultaneously.

Thanks for any insight you can bring to this, and for an incredibly useful tool!

OS X 10.9.5
Karabiner 10.18.0
Mac Mini 2.7GHz Intel Core i7
X-Arcade Tankstick

**Comment by tekezo** [comment]
You can use `KeyCode::VK_PARTIAL_KEYDOWN` and `KeyCode::VK_PARTIAL_KEYUP` like this:

```xml
    <autogen>
      __KeyToKey__
      KeyCode::SHIFT_L,
      KeyCode::VK_NONE,

      Option::KEYTOKEY_BEFORE_KEYDOWN,
      KeyCode::VK_PARTIAL_KEYDOWN, KeyCode::A,
      KeyCode::VK_PARTIAL_KEYDOWN, KeyCode::D,

      Option::KEYTOKEY_AFTER_KEYUP,
      KeyCode::VK_PARTIAL_KEYUP, KeyCode::A,
      KeyCode::VK_PARTIAL_KEYUP, KeyCode::D,
    </autogen>
```

**Comment by MITGameLab** [comment]
It works! Thank you very much!
