### ISSUE TITLE
[Question] Is it possible to map Control_L + R to Command_L + R

### ISSUE THREAD

**Issue by peteyy** [tekezo/Karabiner#602]
Do you think it is possible to make that work somehow? That's the only thing I'm missing from the awesome PC mode. :)

**Comment by nikitavoloboev** [comment]
here is an autogen you can try if I understood correctly what you wanted :) 

```XML
<autogen>
__KeyToKey__
KeyCode::R, ModifierKey::CONTROL_L,
KeyCode::R, ModifierKey::COMMAND_L,	
</autogen>	
```

**Comment by tekezo** [comment]
I've added "PC Style Reload" at Karabiner-10.18.8.
Please upgrade Karabiner to the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by peteyy** [comment]
Woah, that was fast, thanks a lot, it works like a charm :)
