### ISSUE TITLE
Is there a way to assign key to delete line before cursor and after the cursor?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#603]
I want to make it so that when I press shift + delete keys, it would delete the entire line before the cursor and preferably save what was deleted into my clipboard

here is an example 

I have this :

![2016-03-21 at 21 15](https://cloud.githubusercontent.com/assets/6391776/13932768/0cb29e12-efaa-11e5-90ed-d9e8e0102216.png)

I press shift + delete key and I get this :

![2016-03-21 at 21 17](https://cloud.githubusercontent.com/assets/6391776/13932822/5742aa4e-efaa-11e5-881b-63dc0deb6b56.png)

I searched through the documentation and couldn't find an example on how to do this, I am wondering if it is possible because if it is, that would make code editing and writing a joy. I also wish to make shift + return to do the same thing (ie delete the entire line) but do it forward. So in the case above, the line would become 

```
this is a sentence, my cursor is here
```

This is the autogens I have so far but I don't know how to go from here.

```XML
<autogen>
__KeyToKey__
KeyCode::DELETE, ModifierFlag::SHIFT_L,

</autogen>
```

```XML
<autogen>
__KeyToKey__
KeyCode::RETURN, ModifierFlag::SHIFT_L,

</autogen>
```

I really want to make this be a reality and I hope there is some way I can make this work with karabiner.

Thank you for any help.

**Comment by ethus3h** [comment]
If you can figure out how to get it to happen using AppleScript, you could use Karabiner to trigger via Hammerspoon an AppleScript that does that would probably work.

**Comment by tekezo** [comment]
You can do by this autogen:
```xml
    <autogen>
      __KeyToKey__
      KeyCode::DELETE, ModifierFlag::SHIFT_L | ModifierFlag::NONE,
      KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
      KeyCode::X, ModifierFlag::COMMAND_L,

      Option::NOREPEAT,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
this is the autogen I have now and it doesn't seem to do anything, it's also sitting at the top of the XML file so it shouldn't interfere with anything.

```XML
<item>
<name>shift + delete to delete line before cursor</name>
<identifier>private.shift_and_delete_to_delete_before_cursor</identifier>
 __KeyToKey__
KeyCode::DELETE, ModifierFlag::SHIFT_L | ModifierFlag::NONE,
KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
KeyCode::X, ModifierFlag::COMMAND_L,

Option::NOREPEAT,
</item>
```

**Comment by tekezo** [comment]
Did you activate the new setting?

What's result of shift-delete in EventViewer?
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

>  what this does it,

The autogen changes shift-delete to command-shift-left arrow, command-x.
The `Option::NOREPEAT` suppresses key repeat for shift-delete.

**Comment by nikitavoloboev** [comment]
this is what I get in EventViewer when I press left shift and delete together : 

![2016-03-22 at 15 25](https://cloud.githubusercontent.com/assets/6391776/13954758/7775d334-f042-11e5-93d6-0c252830536d.png)

I just checked and this autogen works with the right shift and delete but not with the left shift even though the autogen specifies for the SHIFT_L to be binded.

**Comment by tekezo** [comment]
Hmm, I guess extra modifier flags are pressed when you press the left shift.
Does removing ModifierFlag::NONE change the behavior?

```xml
    <autogen>
      __KeyToKey__
      KeyCode::DELETE, ModifierFlag::SHIFT_L,
      KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
      KeyCode::X, ModifierFlag::COMMAND_L,

      Option::NOREPEAT,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
I just checked it, it does not. This is quite strange.

**Comment by nikitavoloboev** [comment]
Just checked and this autogen you shared works with left command + left shift + delete and does what is intended. 

However does not work with just shift + delete.

**Comment by nikitavoloboev** [comment]
All right I have fixed it, it was my mistake with copying. Thank you a lot tekezo.

**Comment by nikitavoloboev** [comment]
I was wrong that it worked with left shift and delete key, it works with left shift and return, it also works with left shift and right shift together.

But for some reason it doesn't want to work with left shift and my delete key. I don't really know why. 

Here is my screenshot of the event viewer of when I press left shift and delete together : 

![2016-03-22 at 16 04](https://cloud.githubusercontent.com/assets/6391776/13956156/d747793e-f047-11e5-9b8a-c10cd3359b1a.png)

and the autogen that I got from you which in theory should be working : 

```XML
<autogen>
 __KeyToKey__
KeyCode::DELETE, ModifierFlag::SHIFT_L,
KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
KeyCode::X, ModifierFlag::COMMAND_L,
Option::NOREPEAT,
</autogen>
```

**Comment by tekezo** [comment]
Please show me debug logs when you press the delete key.
https://pqrs.org/osx/karabiner/document.html.en#debugmode

**Comment by nikitavoloboev** [comment]
I have delete key binded to right shift as well as a normal delete key with this autogen, don't know if it can interfere with something but here it is : 

```XML
<item>
<name>right shift to command and shift when together, delete when alone</name>
<identifier>private.right_shift_to_command_and_shift</identifier>
<autogen>
--KeyOverlaidModifier--
KeyCode::SHIFT_R,
KeyCode::SHIFT_L,
ModifierFlag::COMMAND_L,
KeyCode::DELETE
</autogen>
</item>
``` 

Nothing seems to happen in the console when I press either the physical delete key or right shift, the console is not changing, here is a screenshot of the top of the console log : 

![2016-03-22 at 16 38](https://cloud.githubusercontent.com/assets/6391776/13957375/893fe334-f04c-11e5-889f-dbf0c52ef192.png)

**Comment by tekezo** [comment]
OK, your private.xml is correct.
When you are using the right shift key as delete,
You should specify KeyCode::SHIFT_R as target key as you wrote.

> Is it possible to make it so that these combinations only work when these specific combinations are pressed and none other.

I think your settings are already do that. (right shift + return acts as right shift + return)
Please describe your problem more.

**Comment by nikitavoloboev** [comment]
everything is working well now, only this autogen doesn't want want to work : 

```XML
<autogen>
 __KeyToKey__
KeyCode::SHIFT_R, ModifierFlag::SHIFT_L,
KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
KeyCode::X, ModifierFlag::COMMAND_L,
Option::NOREPEAT,
</autogen>
``` 

I have changed it to this to test because I believe it should do the same thing but it too doesn't work : 

```XML
<autogen>
 __KeyToKey__
KeyCode::SHIFT_R, ModifierFlag::SHIFT_L,
KeyCode::CURSOR_LEFT, ModifierFlag::SHIFT_R,
KeyCode::X, ModifierFlag::COMMAND_L,
Option::NOREPEAT,
</autogen>
``` 

Neither of these autogens make the intended behaviour however the other two are working perfectly and do not interfere with anything so thank you for that. These are the three autogens that I have together, I'm not sure how the ordering of them matters but I tried rearranging it a few times : 


```XML
<!-- make left shift + right shift cut line before cursor -->
<item>
<name>left shift + right shift to delete line before cursor</name>
<identifier>private.left_shift_and_right_shift_to_cut_before_cursor</identifier>
<autogen>
 __KeyToKey__
KeyCode::SHIFT_R, ModifierFlag::SHIFT_L,
KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
KeyCode::X, ModifierFlag::COMMAND_L,
Option::NOREPEAT,
</autogen>
</item>



<item>
<name>right shift to command and shift when together, delete when alone</name>
<identifier>private.right_shift_to_command_and_shift</identifier>
<autogen>
--KeyOverlaidModifier--
KeyCode::SHIFT_R,
KeyCode::SHIFT_L,
ModifierFlag::COMMAND_L,
KeyCode::DELETE
</autogen>
</item>


<!-- make left shift + return cut line after cursor -->
<item>
<name>left shift + return to cut line after cursor</name>
<identifier>private.right_shift_and_return_to_cut_afer_cursor</identifier>
<autogen>
 __KeyToKey__
KeyCode::RETURN, ModifierFlag::SHIFT_L,
KeyCode::CURSOR_RIGHT, ModifierFlag::COMMAND_L | ModifierFlag::SHIFT_L,
KeyCode::X, ModifierFlag::COMMAND_L,
Option::NOREPEAT,
</autogen>
</item>
```
