### ISSUE TITLE
New Apple Wireless Keyboard FN_L to CONTROL_L not working

### ISSUE THREAD

**Issue by rdiogoo** [tekezo/Karabiner#604]
is anyone able to map the left function key to control? it seems like none of the apps can do it... doublecommand totally hit the wall a while ago and karabiner seems to also not being able to do it.

the only work around I have atm is reinstalling doublecommand after ever logout/restart.

Karabiner seems to not work with the new keyboard that apple recently released. it works with my old, not with the new one.

**Comment by tekezo** [comment]
#529
