### ISSUE TITLE
Excluding Xcode app does not work

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#606]
In the documentation it says that Xcode is one of the prepared application definitions that we can use and it doesn't need an appdef to be created. However that does not work. 

I want this two items to work everywhere but Xcode : 

```XML
<item>
<name>Change Colon to SemiColon</name>	
<identifier>private.colon_to_semicolon</identifier>
<not>XCODE</not>
<inputsource_only>British</inputsource_only>
<autogen>
__KeyToKey__
KeyCode::SEMICOLON, ModifierFlag::SHIFT_L,
KeyCode::SEMICOLON
</autogen>	
</item>

<item>
<name>Change SemiColon to Colon</name>	
<identifier>private.semicolon_to_colon</identifier>
<not>XCODE</not>
<inputsource_only>British</inputsource_only>
<autogen>
__KeyToKey__
KeyCode::SEMICOLON,
KeyCode::SEMICOLON, ModifierFlag::SHIFT_L
</autogen>	
</item>
``` 

Perhaps I made a mistake somewhere but that doesn't do anything. I still can use these autogens everywhere, including Xcode. I also tried changing 'not' for 'only' to test and that too did not work, it seems to not register Xcode as an app to exclude. 

I also went to event viewer and got the definition of the app there and then I tried to make my own definition for the app and try it like this : 

```XML
<appdef>
<appname>XCODE</appname>
<equal>com.apple.dt.Xcode</equal>
</appdef>

<item>
<name>Change Colon to SemiColon</name>	
<identifier>private.colon_to_semicolon</identifier>
<inputsource_only>British</inputsource_only>
<not>XCODE</not>
<autogen>
__KeyToKey__
KeyCode::SEMICOLON, ModifierFlag::SHIFT_L,
KeyCode::SEMICOLON
</autogen>	
</item>

<item>
<name>Change SemiColon to Colon</name>	
<identifier>private.semicolon_to_colon</identifier>
<not>XCODE</not>
<inputsource_only>British</inputsource_only>
<autogen>
__KeyToKey__
KeyCode::SEMICOLON,
KeyCode::SEMICOLON, ModifierFlag::SHIFT_L
</autogen>	
</item>
``` 

This too did not work sadly. I don't really know where I am making a mistake here.

Thank you for any help.

**Comment by tekezo** [comment]
Your private.xml should work.

You have to run AXNotifier in order to use `<not>` filter.
https://pqrs.org/osx/karabiner/document.html.en#axnotifier

Please confirm the AXNotifier is enabled.

**Comment by nikitavoloboev** [comment]
Yes, you're right. That was the problem. Thank you.
