### ISSUE TITLE
Compiling and loading kext under El Capitan

### ISSUE THREAD

**Issue by alxppp** [tekezo/Karabiner#607]
I want to make some modifications to the kext. I was able to compile it using the make file, however I cannot kextload the created kext file:

```
$ sudo kextload pkgroot/Library/Application\ Support/org.pqrs/Karabiner/Karabiner.signed.kext
/Users/ap/Desktop/kar/Karabiner-master/pkgroot/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8).
```

The system log contains the following errors:

```
27.3.16 23:44:52.636 com.apple.kextd[54]: kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/Users/ap/Desktop/kar/Karabiner-master/pkgroot/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext"
27.3.16 23:44:52.864 com.apple.kextd[54]: kext signature failure override allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/Users/ap/Desktop/kar/Karabiner-master/pkgroot/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext"
27.3.16 23:44:52.865 com.apple.kextd[54]: Can't load /Users/ap/Desktop/kar/Karabiner-master/pkgroot/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext - authentication problems.
```

My computer has System Integrity Protection turned off, so I should be able to run unsigend kexts, even on El Capitan.

Do you have an idea how to load the kext?

Thanks!

**Comment by ethus3h** [comment]
I thought unsigned kexts were entirely disallowed, even with SIP disabled? (and that disabling SIP simply allows signed kexts to run)

I could be wrong, though.

**Comment by tekezo** [comment]
> authentication failure (file ownership/permissions)

That's why. The kext file have to be owned by root user.
There are two ways to load kext properly.

* In development:
Run `make reload` in src/core/kext.
* In production:
Install Karabiner package. The kext will be installed with properly owner.

**Comment by alxppp** [comment]
@tekezo Thanks a lot! That was it.
