### ISSUE TITLE
Cursor movement by holding arrow key feels unnatural

### ISSUE THREAD

**Issue by rahmatawaludin** [tekezo/Karabiner#609]
I use only setttings to map left ctrl to esc when tapped. My cursor movement by holding arrow key become weird when Karabiner is activated. Eq. I hold up, the cursor skipped some line (using vim). I'm not having this when Karabiner is off. How to fix this?

System: OSX 10.11.4

**Comment by tekezo** [comment]
I guess you have set too small key repeat rate value in Karabiner.
Please confirm the key repeat setting.
https://pqrs.org/osx/karabiner/document.html.en#keyrepeat

**Comment by rahmatawaludin** [comment]
Thanks, changing key repeat to 33 ms fixed this.. :)
