### ISSUE TITLE
 [Question] Is it possible to override specific option of section

### ISSUE THREAD

**Issue by petromir** [tekezo/Karabiner#611]
I've added Intellij to ignored apps for specific section (e.g. "For PC Users"), but now I want to exlude it only from specific option (e.g. "Change Input Source").

Karabiner version: 10.18.0 
Machine: MacBookPro11,4
OS: OS X 10.11.3
Keyboard: Microsoft Comfort Curve Keyboard 3000

**Comment by tekezo** [comment]
Making similar settings by private.xml is the easiest way.

https://github.com/tekezo/Karabiner/blob/version_10.18.0/src/core/server/Resources/include/checkbox/for_pc_users.xml#L791

**Comment by petromir** [comment]
I'm afraid that I don't understand what should be done.
This is the content of my ```private.xml```
```xml
<root>
  <replacementdef>
    <replacementname>PC_STYLE_BINDINGS_IGNORE_APPS</replacementname>
    <replacementvalue>
      <!-- default value -->
      VIRTUALMACHINE,
      REMOTEDESKTOPCONNECTION,
      VNC,
      TEAMVIEWER,
      EMACS,
      TERMINAL,
      X11,
      CITRIX_XEN_APP_VIEWER,

      <!-- extra -->
      IntelliJ,
    </replacementvalue>
  </replacementdef>
</root>
```
I would like to use "Change Input Source" for Intellij, but at the same time to ignore it for the rest of choosen option under  "For PC Users" section.

**Comment by tekezo** [comment]
For example, use this private.xml and enable new "Change Input Source" instead of prepared one.

```xml
<?xml version="1.0"?>
<root>

  <replacementdef>
    <replacementname>PC_STYLE_BINDINGS_IGNORE_APPS</replacementname>
    <replacementvalue>
      <!-- default value -->
      VIRTUALMACHINE,
      REMOTEDESKTOPCONNECTION,
      VNC,
      TEAMVIEWER,
      EMACS,
      TERMINAL,
      X11,
      CITRIX_XEN_APP_VIEWER,

      <!-- extra -->
      IntelliJ,
    </replacementvalue>
  </replacementdef>

  <item>
    <name>Use PC Style "Change Input Source" #1</name>
    <identifier>private.pcstyle_changeinputmethod1</identifier>
    <autogen>__KeyToKey__ KeyCode::SHIFT_L, ModifierFlag::OPTION_L, KeyCode::SPACE, ModifierFlag::COMMAND_L</autogen>
  </item>

</root>
```

**Comment by petromir** [comment]
Thanks. It did the trick :)
