### ISSUE TITLE
can't figure out how to bind opt+caps+tab only to some specific hotkey without conflicts

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#612]
I have been experimenting quite a lot of times with this but can't get it to work. 

My current caps lock key acts like an escape key when pressed alone and as control + option when in combination with something. The caps lock was at first binded to be F19 with Seil app. I want to make it so that 'left option + physical caps lock key + tab' would make some specific hotkey combination. 

However I am not rally sure how I can do that. I would assume that something like this would work : 

```XML
<item>
<name>left alt + caps + tab to search snippets lab</name>
<identifier>private.left_alt_caps_tab_search_snippets</identifier>
<autogen>
__KeyToKey__
KeyCode::F19, ModifierFlag::OPTION_L, ModifierFlag::TAB,
KeyCode::T, ModifierFlag::COMMAND_L, ModifierFlag::OPTION_L,
</autogen>
</item>


<item>
<name>F19 to F19</name>
<appendix>(F19 to Hyper (ctrl+opt) + F19 Only, send escape)
</appendix>
<identifier>private.f192f19_escape</identifier>
<autogen>
--KeyOverlaidModifier--
KeyCode::F19,
KeyCode::OPTION_L,
ModifierFlag::CONTROL_L,
KeyCode::ESCAPE
</autogen>
</item> 
``` 

However it does seem that TAB is not a modifier key and should be a physical KeyCode but that messes up quite a lot of other things. i.e. left option and caps lock key makes a tab key.

In short I just want to have opt+caps+tab to make some combination whilst having everything else work that uses those keys. 

I have caps + tab = open sublime like so (done in bettertouchtool) :

![2016-04-06 at 16 41](https://cloud.githubusercontent.com/assets/6391776/14320715/669fcb70-fc16-11e5-8078-b872b26e09ed.png)
 
I also have opt key + escape (i.e. where my caps lock key is) to open up dash with Alfred : 

![2016-04-06 at 16 42](https://cloud.githubusercontent.com/assets/6391776/14320757/8d12c1fe-fc16-11e5-9f0d-4147f063b468.png)

Is it possible to make this alt+caps+tab to work. The thing is that I know how to make it if it would of been some other key like command but since my caps lock is my control and opt key, I don't really know how to make it work. 

Thank you a lot for any help.

**Comment by nikitavoloboev** [comment]
Perhaps I also can make it so that I can open sublime with caps lock + tab from Karabiner and that just set alt+caps+tab in bettertouchtool like so : 

![2016-04-06 at 16 52](https://cloud.githubusercontent.com/assets/6391776/14321104/1d5e57ae-fc18-11e5-9308-0a5ca996b36b.png)

I just can't figure out how to bind caps lock and tab together as both are physical keys and if I do something like : 

```XML
<autogen>
__KeyToKey__
KeyCode::F19, KeyCode::TAB,
KeyCode::T, ModifierFlag::COMMAND_L, ModifierFlag::OPTION_L,
</autogen>
```  

This makes a lot of conflicts as is expected. :(

**Comment by tekezo** [comment]
If you allow to change physical control+option+tab, use this autogen.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::TAB, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L,
      KeyCode::T, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L,
    </autogen>

```

**Comment by nikitavoloboev** [comment]
That doesn't really work in my case. :( 

I have caps lock act as CONTROL_L and OPTION_L when pressed together with something. This autogen you linked will make my caps + tab do what is needed but I want alt + caps + tab to do it without changing anything in the other autogens that are linked to these buttons. 

Perhaps it is not possible to do.

**Comment by tekezo** [comment]
You can do it by using `ModifierFlag::NONE` and extra modifiers.

```xml
    <modifierdef>MY_CAPSLOCK</modifierdef>
    <modifierdef>MY_OPTION_L</modifierdef>
    <modifierdef>MY_CONTROL_L</modifierdef>

    <autogen>
      __KeyToKey__
      KeyCode::TAB, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::MY_CAPSLOCK | ModifierFlag::NONE,
      KeyCode::T, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L,
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::CONTROL_L,
      KeyCode::CONTROL_L, ModifierFlag::MY_CONTROL_L,
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::OPTION_L,
      KeyCode::OPTION_L, ModifierFlag::MY_OPTION_L,
    </autogen>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::F19,
      KeyCode::OPTION_L, ModifierFlag::CONTROL_L | ModifierFlag::MY_CAPSLOCK,
      KeyCode::ESCAPE,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Thank you so much tekezo,

Here is the final XML I left to use : 

```XML
<autogen>
__KeyToKey__
KeyCode::TAB, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::MY_CAPSLOCK | ModifierFlag::NONE,
KeyCode::VK_OPEN_URL_APP_Sublime Text,
</autogen>
<autogen>
__KeyToKey__
KeyCode::CONTROL_L,
KeyCode::CONTROL_L, ModifierFlag::MY_CONTROL_L,
</autogen>
<autogen>
__KeyToKey__
KeyCode::OPTION_L,
KeyCode::OPTION_L, ModifierFlag::MY_OPTION_L,
</autogen>
<autogen>
__KeyOverlaidModifier__
KeyCode::F19,
KeyCode::OPTION_L, ModifierFlag::CONTROL_L | ModifierFlag::MY_CAPSLOCK,
KeyCode::ESCAPE,
</autogen>
``` 

This is really amazing. I have a question though. I just want to understand better the difference between a ',' and '|' as separation of modifier keys. 

In the documentation it says that '|' is used 'to specify multiple modifiers' but I thought that you can also use comma for that. So I have to use the pipe character when I want to specify more than one modifier, if I understand it right.

Thank you so much again and I think I understood the reason you used custom modifiers there although to be honest I am still a bit confused as to why that worked.

**Comment by tekezo** [comment]
> the difference between a ',' and '|' as separation of modifier keys.

They are same since Karabiner-10.0.0.
Karabiner supports only `|` to join modifiers In the prior versions.

> the reason you used custom modifiers

`ModifierFlag::NONE` allows you to change the tab key only when pressed modifier flags are `ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::MY_CAPSLOCK`.

If the physical left control key is pressed, the pressed modifiers is `ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::MY_CAPSLOCK | ModifierFlag::MY_CONTROL_L`, then the tab key will not be changed.
We are using the extra modifiers to determine whether other modifiers are pressed.

(Note: These extra modifiers are ignored in other apps. It works only in Karabiner rules.)
