### ISSUE TITLE
PC style Ctrl+Shift+(Left or Right Arrow) to highlight words

### ISSUE THREAD

**Issue by andriy-m** [tekezo/Karabiner#614]
Just like in this [previous issue](https://github.com/tekezo/Karabiner/issues/349) , this particular setting still doesn't work for me for highlighting individual workds.

In every app (text editor, browser, Finder, etc), **Shift+Ctrl+Left** or **Ctrl+Shift+Left** selects to the start/end of the line instead of just one word.

If it helps, I'm on OSX 10.11.4 with Karabiner 10.18.0 and here are the only things I have turned on:

![screen shot 2016-04-12 at 5 30 35 pm](https://cloud.githubusercontent.com/assets/2603195/14479515/51c1365e-00d4-11e6-949c-bcb8eb02025e.png)

**Comment by tekezo** [comment]
Your settings works well on my machine.
I guess you are using Shift+Command+Left.
Please confirm your input in EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by andriy-m** [comment]
@tekezo you're right - it is Command+Shift+Left, according to EventViewer. so then is there any way to remap this behavior to Command+Shift+Left/Right? or remap Alt+Shift+Left/Right (which right now works for that behavior) to Command+Shift+Left/Right?

![image](https://cloud.githubusercontent.com/assets/2603195/14508261/7cac3b3c-017b-11e6-87e2-223a6a449c29.png)

Ctrl = Command due to this system setting in Keyboard > Modifier Keys (which i needed to enable to get the majority of other pc style shortcuts working properly, before i set up Karabiner for some of the final tweaks).

![image](https://cloud.githubusercontent.com/assets/2603195/14508306/a6cc5636-017b-11e6-8dbf-635c091cb21c.png)

**Comment by tekezo** [comment]
OK.
Please use new setting by this private.xml:
(And disable prepared one)
https://github.com/tekezo/Files/blob/master/Karabiner/private.pclikecontrolarrow_except_vm/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml
