### ISSUE TITLE
Reducing modifier key clutter...?

### ISSUE THREAD

**Issue by joonaspaakko** [tekezo/Karabiner#615]
So currently what I'm doing is changing numbers from `1-9` to point to: `Cmd + Alt + Ctrl + Shift + {number}` ...and also many other buttons to all of these modifier keys + the button ( or some other button ). 

**This is the way I'm doing it now:**
```
<autogen>__KeyToKey__ KeyCode::1, KeyCode::1, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L | ModifierFlag::CONTROL_L | ModifierFlag::SHIFT_L </autogen>
<autogen>__KeyToKey__ KeyCode::2, KeyCode::2, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L | ModifierFlag::CONTROL_L | ModifierFlag::SHIFT_L </autogen>
...
```

Since I keep using the same set of modifier keys, is there away I could do that with less clutter?

**For example something like this?:**
```
<ModifierGroup>
   <all>
      COMMAND_L, OPTION_L, CONTROL_L, SHIFT_L
   </all>
</ModifierGroup>

<autogen>__KeyToKey__ KeyCode::1, KeyCode::1, ModifierGroup: all </autogen>
<autogen>__KeyToKey__ KeyCode::2, KeyCode::2, ModifierGroup: all </autogen>
...
```

**Comment by tekezo** [comment]
You can use string replacement.
https://pqrs.org/osx/karabiner/xml.html.en#replacementdef

**Comment by joonaspaakko** [comment]
I knew there had to be away. Thanks @tekezo.
