### ISSUE TITLE
Tap Drag with Karabiner

### ISSUE THREAD

**Issue by hochem** [tekezo/Karabiner#616]
Hello!
I am trying to use Karabiner to get a better 'tap drag' experience than the one available in OSX (which is useless because it introduces a delay before taps and after the tap drag; see discussions on the net). Basically I just want to be able to double-tap an item and drag it without lifting the finger after the second tap and without any delays. I already tried some configs with `lastpressedphysicalkey_only`, `elapsedtimesincelastpressed_lessthan` and `lastsentevent_only` but I am not able to get the wanted behavior. Currently I have the following config, but it only starts after a full double tap and also just ends on a full double tap and only works for selecting text.
```
<item>
  <name>Double Tap Drag</name>
  <identifier>private.doubletapdrap</identifier>
  <lastpressedphysicalkey_only>PointingButton::LEFT</lastpressedphysicalkey_only>
  <elapsedtimesincelastpressed_lessthan>Millisecond::RawValue::200</elapsedtimesincelastpressed_lessthan>
  <autogen>
    __KeyToKey__
    PointingButton::LEFT,
    KeyCode::VK_MOUSEKEY_LOCK_BUTTON_LEFT
  </autogen>
</item>
```
I would appreciate it if you could give me some hints or help me to make it work as described. 
Thank You.

**Comment by tekezo** [comment]
Karabiner does not support tap, so you should enable "Tap to Click" in System Preferences > Trackpad.
Then, use this autogen.

```xml
    <autogen>
      __KeyToKey__
      PointingButton::LEFT,
      KeyCode::VK_MOUSEKEY_LOCK_BUTTON_LEFT,

      Option::KEYTOKEY_AFTER_KEYUP,
      KeyCode::VK_MOUSEKEY_LOCK_BUTTON_ALL_FORCE_OFF,
    </autogen>
```

**Comment by hochem** [comment]
Thanks. I just tried your autogen, this seems to be the correct one, but on my system osx 10.11.4, it will only trigger the `KeyCode::VK_MOUSEKEY_LOCK_BUTTON_LEFT` together with `KeyCode::VK_MOUSEKEY_LOCK_BUTTON_ALL_FORCE_OFF` when I do a fast double tap (also the notification window just shortly flashes). When I click instead of tapping, it seems to show the correct behavior (the notification window shows up on the second BUTTON_LEFT down event and disappears on the second BUTTON_LEFT up event). I don't know exactly how Karabiner handles taps and clicks, but somehow taps will only trigger on the up event, ThumbSense seems to work fine though.

**Comment by hochem** [comment]
I just tried ThumbSense with a custom config and realized how powerful this feature is. So I will probably don't need / no longer work on the tap drag config. I leave it up to you to close this issue, maybe you want to have a look on the behavior described in my previous comment. There are also quite a lot of people on the internet complaining about the tap drag feature available in osx and it's delay and I think it's possible to get rid of it using Karabiner (BetterTouchTool also has an experimental tap drag, but it's not perfect as BTT isn't using a kext afaik). Anyway, thanks for your response!

**Comment by tekezo** [comment]
Thank you for confirmation.
Excuse me, you are right. The OS X "Tap to Click" sends both button down and up events at the finger is lifted. So, we have to use the physical click for this purpose.
