### ISSUE TITLE
Brightness control does not change brightness on PC Keyboard

### ISSUE THREAD

**Issue by dmlo** [tekezo/Karabiner#617]
OS X: 10.11.4
Karabiner: 10.18.0
Mac: Mac Mini Late 2012, Apple Thunderbolt Display x 2
Keyboard: Logitech K120

Enabled Karabiner settings:
- Change Control_R to Fn
- Change F1..F19 Key -> For PC Keyboards -> Change f1..f12 to brightness, music, volume

With these settings enabled, I can change the volume and playback, but the brightness controls do not have an effect. If I connect an apple keyboard simultaneously, it can adjust the brightness.

The event viewer will show ConsumerKeyCode::BRIGHTNESS_DOWN/UP from the K120, but not adjust the brightness.

Using the Apple keyboard, the Event Viewer does not record the brightness keystrokes, but the brightness is adjusted.

For both the Apple keyboard and the K120, the Event Viewer shows the volume but not the playback codes Both change the system as desired.

The results are reproducible using either a single or dual monitors and are not affected by a system restart.

Event Viewer keystroke test sequence:
1. K120 volume up (F12) [volume up ok]
2. Apple volume down (F12) [volume down ok]
3. K120 brightness up (F2) [no effect]
4. Apple brightness down (F2) [brightness down ok]
5. K120 Play/Pause (F8) [music paused ok]
6. Apple Play/Pause (F8) [music starts ok]

eventType:SysKeyDown      code:0x0        name:                flags:                                   misc:ConsumerKeyCode::VOLUME_UP
eventType:SysKeyUp        code:0x0        name:                flags:                                   misc:ConsumerKeyCode::VOLUME_UP
eventType:SysKeyDown      code:0x1        name:                flags:                                   misc:ConsumerKeyCode::VOLUME_DOWN
eventType:SysKeyUp        code:0x1        name:                flags:                                   misc:ConsumerKeyCode::VOLUME_DOWN
eventType:SysKeyDown      code:0x2        name:                flags:                                   misc:ConsumerKeyCode::BRIGHTNESS_UP
eventType:SysKeyUp        code:0x2        name:                flags:                                   misc:ConsumerKeyCode::BRIGHTNESS_UP

Thank you for your time. I can perform additional tests if requested.

**Comment by tekezo** [comment]
The brightness control is one of the most complex OS X function.

There are two physical brightness control keys and one virtual key.
They have different behavior in the built-in and the external monitor.

----------

At first, please confirm that your K120 sends normal F1 key without Karabiner settings.

And then, if the F1 key events are sent, please try three settings by this private.xml.
Please enable either the new settings.
(Disable other two settings when one setting is enabled.)

https://github.com/tekezo/Files/blob/master/Karabiner/private.f1_to_iohidpostevent_brightness_down/private.xml


How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by dmlo** [comment]
F1 & F2 Events with Karabiner settings disabled:

eventType:KeyDown         code:0x7a       name:F1              flags:Fn                                 misc:KeyCode::F1	 characters:    
eventType:KeyUp           code:0x7a       name:F1              flags:Fn                                 misc:KeyCode::F1	 characters:    
eventType:KeyDown         code:0x78       name:F2              flags:Fn                                 misc:KeyCode::F2	 characters:    
eventType:KeyUp           code:0x78       name:F2              flags:Fn                                 misc:KeyCode::F2	 characters:    


Success! The second custom setting you provided works, and with the usual ctrl modifier changes the brightness on the second monitor as well.

  <item>
    <name>Change f1,f2 to brightness control.</name>
    <appendix>(Using KeyCode::BRIGHTNESS_UP.)</appendix>
    <identifier>private.f1_to_keycode_brightness_down</identifier>
    <autogen>
      __KeyToKey__
      KeyCode::F1,
      KeyCode::BRIGHTNESS_DOWN,
    </autogen>
    <autogen>
      __KeyToKey__
      KeyCode::F2,
      KeyCode::BRIGHTNESS_UP,
    </autogen>
  </item>

**Comment by dmlo** [comment]
Further testing update:

The above fix works when an Apple keyboard is connected, and stops working when the apple keyboard is disconnected.  

Tested with Apple Wireless Keyboard (bluetooth) and Apple Keyboard with Numeric Keypad (USB)

**Comment by tekezo** [comment]
Thank you for feedback.

Are the brightness control keys recognized as f14 and f15 key in EventViewer when Apple keyboards are not connected?
If so, please confirm System Preferences > Keyboard > Shortcuts.
![160423-0001](https://cloud.githubusercontent.com/assets/659178/14759988/58903dd6-0971-11e6-808c-d5045a075b17.png)
