### ISSUE TITLE
How to change the input source / language of a specific device?

### ISSUE THREAD

**Issue by joonaspaakko** [tekezo/Karabiner#618]
I know how to [filter a specific device](https://pqrs.org/osx/karabiner/xml.html.en#devicedef) , but I just can't figure out how to change the input source of the device. I was trying to use [this sample](https://pqrs.org/osx/karabiner/xml.html.en#vkchangeinputsourcedef) to do that, but I can't figure out how to trigger the input source change without the key combination.

**Comment by tekezo** [comment]
Do you want to change the input source automatically when you type the specific keyboard?

If so, there are no simple way.
We have to change all keys to trigger input source switching like follows.

```xml
    <block>
      <inputsource_not>ENGLISH</inputsource_not>
      <autogen>
        __KeyToKey__
        KeyCode::A, KeyCode::A,

        Option::KEYTOKEY_BEFORE_KEYDOWN,
        KeyCode::VK_CHANGE_INPUTSOURCE_US, KeyCode::VK_WAIT_100MS,
      </autogen>
      <autogen>
        __KeyToKey__
        KeyCode::B, KeyCode::B,

        Option::KEYTOKEY_BEFORE_KEYDOWN,
        KeyCode::VK_CHANGE_INPUTSOURCE_US, KeyCode::VK_WAIT_100MS,
      </autogen>
      <!-- similar autogen for C-Z -->
    </block>
```

**Comment by joonaspaakko** [comment]
Yes. That is exactly what I was trying to do. Luckily, what I'm doing is not dependent on this. This just would've made some things easier.

Thanks.
