### ISSUE TITLE
Any way to tell if focus is on an <input /> or <textarea /> in Chrome?

### ISSUE THREAD

**Issue by eamodio** [tekezo/Karabiner#619]
I have a custom re-mapping of the Home/End keys (for PC behavior), but I can't get that behavior to be disabled when focused on a HTML input/textarea in Chrome. The event viewer just reports AXWindow, though if I focus on the Chrome address bar it reports AXTextField (as expected). Is there anything Karabiner can do here?

Thanks and love the app!

**Comment by tekezo** [comment]
Unfortunately, there is not a way in Karabiner.
Google Chrome should change the UIElementRole for each HTML elements like Safari.

**Comment by eamodio** [comment]
@tekezo damn :( thanks for the response tho!
