### ISSUE TITLE
Timing issue with Control_L + escape

### ISSUE THREAD

**Issue by karptonite** [tekezo/Karabiner#620]
I'm using the setting Control_L to Control_L (+ when you type Control_L only, send escape).

Unfortunately, similar to what is described in issue #226, I'm having a timing issue,where if I hit Ctrl-L then another key in fast succession, it does not register the escape. I don't have this problem with the actual escape key, and I'm certain that I am releasing the Ctrl-L before hitting the next key. 
My only changes from the default settings are:
Key overlaid modifier timeout to 300 ms
Timeout of delayed action to 100 ms

Is there some setting that will allow the escape to be sent from Ctrl-L (only) immediately on keyup?

**Comment by tekezo** [comment]
This private.xml adds a setting that allows you to send escape key event when you release the left control key before another key is released.
https://github.com/tekezo/Files/blob/master/Karabiner/private.control_to_control_escape/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by karptonite** [comment]
Thanks, I added that to my private.xml and tried it out, but it did not fix the timing problem. It is still the case that I can press and release the Control key, then hit the next key, without escape being sent first. In contrast, it always works properly if I hit the esc key directly, or map CTRL-L to just esc. Is there some timing setting I should be changing?

**Comment by tekezo** [comment]
Hmm, really?
If it is easy to reproduce, could you show me the result of EventViewer?
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

Anyway, increasing "Key Overlaid Modifier > Initial Modifier Wait" might help you.
(But the setting requires you to hold the control key to specified milli seconds to use control key as modifier.)

**Comment by karptonite** [comment]
OK, I tried the EventViewer, and it showed the desired behavior, so I investigated whether it may be an issue with my other software. It may be an issue with vim/neovim.

Here is what I found: In both programs, if I am in insert mode and hit the real escape key, followed by, say, "p", they leave insert mode, then paste the contents of the buffer, as expected.

By contrast, when I use the L-ctrl key + escape, i get the following behavior:
In Neovim, which I had been using, it remains in insert mode, and inserts a "p".
In Vim, it briefly displays a p, as if it had been in insert mode, then immediately deletes it, and pastes the content of the buffer, with the final result being "correct", but obviously something odd is going on behind the scenes.

It seems likely to me that this is not a Karabiner issue--if you agree, go ahead and close it. Sorry for the trouble!

**Comment by karptonite** [comment]
This appears to be a known issue in Neovim--
https://github.com/neovim/neovim/issues/2454. Apparently, the alt key is simulated by sending the escape followed by a key, and differentiated from the actual escape key by timing. (Although it isn't clear why the problem is showing up for me with the ctrl-esc key, but not just the regular escape key.)

Interestingly, there is a potential solution, but I'm not sure what other implications that would have:
https://github.com/neovim/neovim/issues/2454#issuecomment-94900764
It appears that if the escape byte is followed by the nul byte, that will distinguish it from the alt key sequence. If it it possible to simulate that by adding something to my private.xml file, I'd love to give it a try.

**Comment by tekezo** [comment]
Thank you for information.

If releasing the escape key immediately after press causes this issue,
how about put wait between key down and key up by this private.xml?
https://github.com/tekezo/Files/blob/master/Karabiner/private.control_to_control_escape/private.xml
