### ISSUE TITLE
Any way to launch or hide apps by press several keys in sequence?

### ISSUE THREAD

**Issue by xream** [tekezo/Karabiner#622]
What I want to achieve: 

Press `cmd space` to enter this mode. 
Type `fa` to launch `FaceTime.app`. If `FaceTime.app` is already in front, hide it. 
Then exit this mode.

**Comment by tekezo** [comment]
You can do it but the 2 stroke shortcut definition is too complex.

Please consider one key shortcut like `command-space, f`.
You can do it by this private.xml:
https://github.com/tekezo/Files/tree/master/Karabiner/private.launcher_mode_3

**Comment by xream** [comment]
I see. Thanks!
