### ISSUE TITLE
Swap left & right mouse buttons

### ISSUE THREAD

**Issue by mtissington** [tekezo/Karabiner#623]
I have OSX in a VMWare guest and need to create an item to swap left and right mouse buttons. (it seems the system mouse settings are being ignored). Any ideas please?

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.swap_mouse_buttons/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by mtissington** [comment]
Hi, 

 

thanks but unfortunately this does not work.

The event viewer still shows left as left and right as right (maybe this is expected).

Right click still shows the context menu.

 

I’m wondering if this is because it’s a VMWare guest and the mouse driver is from VMWare.

 

Any ideas please?

 

Michael

**Comment by ethus3h** [comment]
I don't think the event viewer is supposed to change what it shows. I could be wrong, but...

**Comment by tekezo** [comment]
Thank you for confirmation.

> I’m wondering if this is because it’s a VMWare guest and the mouse driver is from VMWare.

I don't know about VMware well, but I think your assumption is right.
Please consider swapping buttons in Host OS.
