### ISSUE TITLE
Ignore Vim, but not in iTerm2?

### ISSUE THREAD

**Issue by yifanchen** [tekezo/Karabiner#624]
I am running Vim in iTerm2? I'd like to disable karabiner in Vim but not in iTerm2. Is this possible?

**Comment by tekezo** [comment]
Karabiner cannot distinglish the running app in Terminal.

But Karabiner provides the command line interface.
https://pqrs.org/osx/karabiner/document.html.en#commandlineinterface

You can do that by the following procedure if you can execute shell commands from Vim:

* Add new setting by this private.xml:
   https://github.com/tekezo/Files/blob/master/Karabiner/private.passthrough_terminal/private.xml
* Execute `karabiner enable private.passthrough_terminal` when Vim is opened.
* Execute `karabiner disable private.passthrough_terminal` when Vim is terminated.

**Comment by yifanchen** [comment]
I actually don't know how to do this, let me do some research. 
Thanks, man.
