### ISSUE TITLE
Kernel panic under Yosemite 10.10

### ISSUE THREAD

**Issue by ptram** [tekezo/Karabiner#626]
Dear Tekezo,

I'm not sure this issue is caused by Karabiner, but I'm experimenting with various software configurations. The kernel parnic happens often, but not always, so it is still a bit difficult to track the culprit.

I have frequent kernel panics when my Mac goes to sleep, either automatically or manually invoked (throught a key sequence programmed in Karabiner). Attached is a typical crash log after this happen. Karabiner is always on top of the list of the loaded kext, together with VirtualBox (that I had excluded after a few tests).

Maybe you can see something useful in my log?

Paolo

[Kernel_2016-05-04-122119_Mac-mini-di-PaoloT.panic.zip](https://github.com/tekezo/Karabiner/files/248593/Kernel_2016-05-04-122119_Mac-mini-di-PaoloT.panic.zip)

**Comment by tekezo** [comment]
I guess the panic is caused by GPU error or AppleUSBCDC error.
Disable USB support in VirtualBox might suppress the panic if you can.

**Comment by ptram** [comment]
Dear Tekezo-san, thank you very much for the hint! I'll try with that setting change.

Paolo
