### ISSUE TITLE
Alfred 3 beta

### ISSUE THREAD

**Issue by RRomaric** [tekezo/Karabiner#627]
Hello,
Karabiner does not work with Alfred 3 beta in standard mode.

[http://www.alfredforum.com/topic/7080-alfred-272-beta-build-mid-development-testing/?p=38525](http://www.alfredforum.com/topic/7080-alfred-272-beta-build-mid-development-testing/?p=38525)

thank you very much
Romaric

**Comment by tekezo** [comment]
Thank you for feedback.
I'll confirm it after I got Alfred 3 beta.

**Comment by RRomaric** [comment]
Simply "Bundle identifier" increased from com.runningwithcrayons.Alfred-2 to com.runningwithcrayons.Alfred-3

On another Mac, I have compiled Karabiner adding com.runningwithcrayons.Alfred-3 in the  Karabiner/src/core/server/Resources/appdef.xml and it's good.

**Comment by tekezo** [comment]
Thank you!
I've supported Alfred 3 at v10.18.34.
Please upgrade Karabiner to the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by RRomaric** [comment]
Wonderful!
It works perfectly!
