### ISSUE TITLE
Alter alt+f, alt+b, and alt+d in emacs mode to respect underscores (_) as word boundaries

### ISSUE THREAD

**Issue by excetara2** [tekezo/Karabiner#630]
Is this possible so when you use forward word, etc... so it will respect these as word boundaries? Right now it only respects dashes (-) but it be a lot better if it could also respect underscores. I couldn't find a setting for this or if it would be easily possible.

**Comment by tekezo** [comment]
Karabiner just changes alt+f key to option-right arrow.
Then OS X interprets the option-right arrow shortcut.

Therefore, the behavior depends OS X text area cursor movements.
And, unfortunately, I think we cannot change it.

**Comment by excetara2** [comment]
Thanks for the help.
