### ISSUE TITLE
Karabiner cannot connect with kernel extension. Please restart your system in order to solve the problem.

### ISSUE THREAD

**Issue by accorde** [tekezo/Karabiner#631]
Karabiner cannot connect with kernel extension.
Please restart your system in order to solve the problem.

Suddenly I faced with this question. When I restart my mac, the problem occurred again.  And key binding is failure. 
What should I do to solve this problem?
My computer: 
Darwin Aces-Mac-mini.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

Os X 10.11.4

**Comment by vors** [comment]
I seen the same error, when I installed a dev version from my own build.

**Comment by tekezo** [comment]
Please try loading the Karabiner kext manually.

1. Open Terminal.app.
2. Execute this command. (This command requires administrator privillege. You have to enter your password after execute this command.)
```
sudo kextload '/Library/Application Support/org.pqrs/Karabiner/Karabiner.signed.kext'
```

@vors 
You should change SIP configuration to load your own kext.
```
csrutil enable --without kext
```
http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11
