### ISSUE TITLE
Microsoft Remote Desktop remapping ehancement

### ISSUE THREAD

**Issue by vors** [tekezo/Karabiner#632]
I start use Karabiner a couple weeks ago for `Microsoft Remote Desktop` to rdp to windows machines.
It's super cool already, but I'd like to make it even better.
### Problem

When I didn't connect to a remote session yet, just opened the app, I already use remapped binding.
It's confusing, because `Cmd+Tab` suddenly doesn't work.

On the picture: main window

![image](https://cloud.githubusercontent.com/assets/816680/15265872/1899337e-1946-11e6-8e40-5ed4368cd574.png)

It's natural to use remapping, when you are in the **actual remote window**. Currently there is no filtering, based on window name. 
### Solution

The main window name is `Microsoft Remote Desktop`.
So adding

``` xml
    <windownamedef>
        <name>Microsoft_Remote_Desktop</name>
        <regex>Microsoft Remote Desktop</regex>
     </windownamedef>
....
    <only>REMOTEDESKTOPCONNECTION</only>
      <windowname_not>Microsoft_Remote_Desktop</windowname_not>
```

Make remapping effective everywhere, except the main window. 
I hope it would be useful for others and perhaps it could be the default option.

The only problem that I see is AXNotifier additional privileges. Is it a requirement to avoid AXNotifier in default options?

**Comment by tekezo** [comment]
Thank you for feedback!

This issue already solved in the latest beta version by `<bundleidentifieroverridedef>`.
https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/bundleidentifieroverridedef.xml#L39-L53

Please confirm the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by vors** [comment]
Sorry for the long reply time, just got a chance to try it out.

It indeed **solves** problem for the released RDP version.
I personally switched to [RDP beta version](https://rink.hockeyapp.net/apps/5e0c144289a51fca2d3bfa39ce7f2b06/) because it has much better support for multi-monitor connections.

Beta version has different pattern for windows names. [That](https://github.com/vors/karabiner-fu/blob/master/private.xml#L7-L9) works for me with beta. I suspect that it could be added to https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/bundleidentifieroverridedef.xml#L39-L53 

Something along the lines:

```xml
...
<equal></equal>
<equal>User Accounts</equal>
...
```

Also, I start publishing my customizations to a [repo](https://github.com/vors/karabiner-fu). I'd like to contribute them to the upstream at some point, when I test them enough. They focused on RDP and Terminal. Do you think it's valuable?

**Comment by tekezo** [comment]
Thank you for information!

I've added such lines into bundleidentifieroverridedef.xml:
https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/bundleidentifieroverridedef.xml#L48-L49

> I'd like to contribute them to the upstream at some point, when I test them enough.

Thank you! welcome.

**Comment by e-gaulue** [comment]
I use the last version of Karabiner and I still observe fishes falling through the net regarding Microsoft Remote Desktop.

Looking at /src/core/server/Resources/bundleidentifieroverridedef.xml, could we imagine 2 overrides:
1. One with all the windows whose names are:
      <equal>Microsoft Remote Desktop</equal>
      <equal>Verify Certificate</equal>
      <equal></equal>
      <equal>User Accounts</equal>
      <equal>Preferences</equal>
      <equal>Remote Resources</equal>
      <equal>Azure RemoteApp</equal>
      <prefix>Edit Remote Desktops -</prefix>
2. One with the rest

Most of the time you don't want to have the keyboard change apply in the first case but in the second.

According to me, we just have to put the first rules first and to put the other next, as the first will get the bundleidentifier.

By the way, I insist on the fact the keyboard is held really differently with this app compared with classical Remote Desktop application.

I'll propose a new pull.

Regards,

**Comment by tekezo** [comment]
@e-gaulue I might misunderstand your desire, but I describe the purpose of bundleidentifieroverridedef.

The main purpose of bundleidentifieroverridedef is to be able to ignore RDC settings in the remote desktop preferences.
So, ideally, we want to define only `karabiner.remotedesktop-preferences` in the following lines and keep the bundle identifer (`com.microsoft.rdc.mac`) in the remote machine window.
https://github.com/tekezo/Karabiner/blob/version_10.20.0/src/core/server/Resources/bundleidentifieroverridedef.xml#L88-L106

The approach works well in the most case.
But, when we are using RDC with the multi monitor, the window name is always the empty string in the remote machine window.

To distingulish the remote machine window in this case, we uses `karabiner.remotedesktop`.
https://github.com/tekezo/Karabiner/blob/version_10.20.0/src/core/server/Resources/bundleidentifieroverridedef.xml#L75-L86

**Comment by e-gaulue** [comment]
OK I understand better. I'm not able to test multi-screen right now.

The trouble is the first time I open the remote connection window I get in karabiner.remotedesktop. By the way, "Verify Certificate" is also in karabiner.remotedesktop while it should be in karabiner.remotedesktop-preferences. It's due to the karabiner.remotedesktop being the first to be verified.

Don't you think moving karabiner.remotedesktop after karabiner.remotedesktop-preferences would handle it better or adding a window name empty condition to karabiner.remotedesktop?

I'm really sorry I can't test with multiscreen (I'll try later). Another idea, if you remove the empty window name condition in the remotedesktop-preferences and remove karabiner.remotedesktop bundle won't it do the trick: All the management in karabiner.remotedesktop-preferences and the rest as is?

Regards,

**Comment by tekezo** [comment]
I think too, but the RDC window name and ui element role handling is not enough reliable.
It keeps old values in the some case. (eg https://github.com/tekezo/Karabiner/blob/version_10.20.0/src/core/server/Resources/bundleidentifieroverridedef.xml#L27-L39 )

The disadvantage is larger when we miss the remote machine window.
(eg. PC style remappings do not work in RDC.)

So, I want to set the higher priority to `karabiner.remotedesktop` than `karabiner.remotedesktop-preferences` until the RDC behavior has been improved.

**Comment by e-gaulue** [comment]
@tekezo I've tried dual screen mode and modified /Applications/Karabiner.app/Contents/Resources/bundleidentifieroverridedef.xml as I suggested yesterday. I've been testing it hard and I can't see any case when it's not working.

Windows Name is empty only when using a second screen, if not it has always a name. The rules you provide in `karabiner.remotedesktop-preferences` are perfect and I can't see other ones (I've tried RemoteApp as well). The only one I've removed is the one for empty application name. Then I've totally remove the `karabiner.remotedesktop`.

This way, if you're in one of the management screen, `karabiner.remotedesktop-preferences` get the lead due to the windows name. If you're in a window with an empty name or in a window with the remote machine name, you get the classical application name `com.microsoft.rdc.mac` or `com.microsoft.rdc.osx.beta`. I agree if somebody call is remote machine:
- "Microsoft Remote Desktop"
- "Verify Certificate"
- "User Accounts"
- "Preferences"
- "Remote Resources"
- "Azure RemoteApp"
- "Edit Remote Desktops -" (prefix)

he will run into troubles. But it won't come to my mind to give such names for remote machine.

This simplify a lot of things.

**Comment by tekezo** [comment]
@e-gaulue The empty window name is needed for RDC beta.
https://github.com/tekezo/Karabiner/issues/632#issuecomment-223737024

**Comment by e-gaulue** [comment]
I'm a stubborn. With RDC beta, remote window name is always set, even in the second "multi-screen". As soon as you are "local" window doesn't have a name, or if in preferences specific ones. So I propose to dissociate `rdc.mac` and `rdc.osx.beta`:
```
<bundleidentifieroverridedef>
    <newbundleidentifier>karabiner.remotedesktop-preferences.microsoft</newbundleidentifier>

    <bundleidentifiers>
      <equal>com.microsoft.rdc.mac</equal>
    </bundleidentifiers>

    <windownames>
      <equal>Microsoft Remote Desktop</equal>
      <equal>Verify Certificate</equal>
      <equal>User Accounts</equal>
      <equal>Preferences</equal>
      <equal>Remote Resources</equal>
      <equal>Azure RemoteApp</equal>
      <prefix>Edit Remote Desktops -</prefix>
    </windownames>
  </bundleidentifieroverridedef>

<bundleidentifieroverridedef>
    <newbundleidentifier>karabiner.remotedesktop-preferences.microsoft</newbundleidentifier>

    <bundleidentifiers>
      <equal>com.microsoft.rdc.osx.beta</equal>
    </bundleidentifiers>

    <windownames>
      <equal>General</equal>
      <equal>User Accounts</equal>
      <equal>Gateways</equal>
      <equal>Groups</equal>
      <equal></equal>
    </windownames>
  </bundleidentifieroverridedef>
```

This works like a charm for me with both beta and not. All the remote interactions stay in `com.microsoft.rdc.mac` and `com.microsoft.rdc.mac`.

Regards,

**Comment by tekezo** [comment]
Thank you for feedback!

I'm afraid that this setting might be broken when the beta version of RDC becomes the stable release.
I think we should replace the bundleidentifieroverridedef with your definition of `com.microsoft.rdc.osx.beta` after the new RDC has been shipped.

**Comment by e-gaulue** [comment]
All right. I'll wait until then to pull the french translated keyboard you need to set when using this application. I've put a post a while ago on my blog explaining how to solve this trouble using private.xml, but lost find it to hard to implement. It's sure a checkbox is always simpler.

By the way, I'm interested by any information about the future of `com.microsoft.rdc.osx.beta`. It has been said to me it was more a beta solution to answer people complaints faster than with the production release. They still have a lot to do before final release (RemoteApp, Azure, multi server). As far as I understand, every real improvement tested in the beta that can be port to the production release moves to it. Maybe, in the future, windows without name will get some, but I don't think they will remove the ones with the remote machine name. I use those applications almost every day. I can test any new version if you want.

I did the exercice and found 2 more named window:
`
<bundleidentifieroverridedef>
    <newbundleidentifier>karabiner.remotedesktop-preferences.microsoft</newbundleidentifier>

    <bundleidentifiers>
      <equal>com.microsoft.rdc.osx.beta</equal>
    </bundleidentifiers>

    <windownames>
      <equal>General</equal>
      <equal>User Accounts</equal>
      <equal>Gateways</equal>
      <equal>Groups</equal>
      <equal>About</equal>
      <equal>Updating Microsoft Remote Desktop Beta</equal>
      <equal></equal>
    </windownames>
  </bundleidentifieroverridedef>
`
