### ISSUE TITLE
Karabiner fails to build from source

### ISSUE THREAD

**Issue by jacobwhitten** [tekezo/Karabiner#635]
The following is the error that I get when I try to build from scratch. Any advice on how to get this working? The error is not coming up in google. Any advice would be appreciated.
- OS X version: 10.11.4
- Karabiner version: 10.18.0
  (You can confirm the version in "Misc & Uninstall" tab in Karabiner Preferences.)
- Your Mac hardware: MacBook Pro
- Your keyboard hardware: Razer BlackWidow (Probably not relevant)

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C server

pod install --no-repo-update

Re-creating CocoaPods due to major version update.

Analyzing dependencies

[!] The dependency `Sparkle` is not used in any concrete target.

make[4]: *** [all] Error 1

make[3]: *** [all] Error 2

make[2]: *** [all] Error 2

make[1]: *** [build] Error 2

make: *** [all] Error 2
```

**Comment by tekezo** [comment]
The master branch does not depend on CocoaPods.
Please clone master branch.
