### ISSUE TITLE
Scroll reverse turning off when clicking on certain icons in the menu bar

### ISSUE THREAD

**Issue by ksrb** [tekezo/Karabiner#637]
When I click something like the date in the menubar:
![screen shot 2016-05-18 at 5 16 01 pm](https://cloud.githubusercontent.com/assets/3750409/15378892/4f6e8d3e-1d1c-11e6-914e-98b997263e5f.png)
The reverse scrolling stops working as in scrolling up on the mouse wheel goes up and scrolling down goes up.

Here is the relevant setting:
![screen shot 2016-05-18 at 5 17 14 pm](https://cloud.githubusercontent.com/assets/3750409/15378902/69f285a2-1d1c-11e6-9678-5c2160fb3786.png)

The setting gets 'restored' if I right click somewhere on the desktop.
![screen shot 2016-05-18 at 5 19 26 pm](https://cloud.githubusercontent.com/assets/3750409/15378934/bf962676-1d1c-11e6-8fbb-b96e6b16b695.png)

**Comment by tekezo** [comment]
Thank you for feedback.
This issue has been fixed at Karabiner 10.18.7.
Please upgrade Karabiner to the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by ksrb** [comment]
Thanks for the response, the beta does fix the issue but the scroll reverse activates after a slight delay of about 0.5s. Is this expected behavior?

**Comment by tekezo** [comment]
> Is this expected behavior?

Unfortunately, yes.
OS X does not send notification for it. We have to observe the menu state on timer.
The delay is interval of that timer.

**Comment by ksrb** [comment]
Well it's better than nothing, thanks!
