### ISSUE TITLE
I am not really sure how vim emulation work, I wish to make left cmd as toggle for it

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#638]
I activated these settings in the karabiner window :

![2016-05-19 at 09 28](https://cloud.githubusercontent.com/assets/6391776/15385764/0b631708-1da4-11e6-925a-f5cc449cb0e0.png)

I would assume this would allow me to press left command alone to enter normal mode and then I could  press it alone (if I was in normal mode) to enter insert mode whilst still being able to use left command as normal when pressed in combination with other keys. Is this the case and if not how and can I achieve this behaviour.

Thank you a lot for such a great open source project.

**Comment by tekezo** [comment]
You are right.
It allows you to toggle vim emulation mode by left command key.

I guess other settings are conflicted with it.
If you already changed the physical command key, please disable that setting.

**Comment by nikitavoloboev** [comment]
Oh wow, thank everything is working now, I guess I didn't really test it fully.

One remark I have albeit a small, it would really great if the 'status message' would centre the text : 

![2016-05-19 at 11 57](https://cloud.githubusercontent.com/assets/6391776/15389830/193f5606-1db9-11e6-9cd9-aa6a4c273492.png)

And perhaps even adjust the size of the 'black overlay' to the size of the text to make it less intrusive and still noticeable. But centring the text would be really great, I think.

**Comment by nikitavoloboev** [comment]
Thank you, that worked perfectly.
