### ISSUE TITLE
Doesn't Recognize Keyboard

### ISSUE THREAD

**Issue by gbonk** [tekezo/Karabiner#639]
I have a Lenovo KU-0225 Keyboard.

I have created the device mappings in my private xml

```
<!— Vendor Definitions —->

  <devicevendordef>
    <vendorname>CHICONY</vendorname>
    <vendorid>0x04B3</vendorid>
  </devicevendordef>

  <deviceproductdef>
    <productname>LENOVO_KEYBOARD</productname>
    <productid>0x3025</productid>
  </deviceproductdef>

```

None of my device specific mappings work.  I have a macbook 11.3

Keyboard
    USB NetVista Full Width Keyboard (CHICONY)

```
DeviceVendor::RawValue::0x04b3,
DeviceProduct::RawValue::0x3025,

DeviceLocation::RawValue::0x14100000,
```

**Comment by tekezo** [comment]
Please show me your private.xml.

**Comment by gbonk** [comment]
I've posted my private.xml, but it seems to have started working mysteriously.  Maybe some of these shortcuts could be integrated into the provided configurations ?


[private.xml.zip](https://github.com/tekezo/Karabiner/files/278011/private.xml.zip)

**Comment by tekezo** [comment]
> it seems to have started working mysteriously.

It's great!
I confirmed your private.xml. It seems correct.

If you are using other keyboard driver together (eg. USB overdrive), Karabiner might be affected.
Or there are some device specific limitations, for example, the device notifies  another device vendor id at the first device connection from boot.
