### ISSUE TITLE
Is it possible to modify vim keybindings in Karabiner?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#640]
I want to make - key act as shift+4 ($ sign) while in vim mode to go to the end of line. It is located to the right of 0 key which goes to the beginning of the line and it would make using both of these vim commands much better. I find pressing shift + 4 every time I want to move to the end of line very cumbersome.

Is such a thing possible to do?

**Comment by tekezo** [comment]
I think there are not modification points at the moment.

The vim emulation is developed here.
Please create new issue in the project.
https://github.com/rcmdnk/vim_emu

**Comment by nikitavoloboev** [comment]
Oh all right, thank you.
