### ISSUE TITLE
Karabiner crashed my mac couple of times

### ISSUE THREAD

**Issue by chandradeepak** [tekezo/Karabiner#644]
Anonymous UUID:       9739E8A3-FDE6-FC17-539E-79FC1B98EEA3

Tue May 24 11:54:07 2016

*** Panic Report ***
panic(cpu 2 caller 0xffffff800c76aad5): "zalloc: zone map exhausted while allocating from zone kalloc.8192, likely due to memory leak in zone kalloc.1024 (5391306752 total bytes, 5264945 elements allocated)"@/SourceCache/xnu/xnu-2782.40.9/osfmk/kern/zalloc.c:2521
Backtrace (CPU 2), Frame : Return Address
0xffffff81f8af3c00 : 0xffffff800c72ad21 
0xffffff81f8af3c80 : 0xffffff800c76aad5 
0xffffff81f8af3db0 : 0xffffff800c733581 
0xffffff81f8af3de0 : 0xffffff800c712ed0 
0xffffff81f8af3e10 : 0xffffff800c72ef27 
0xffffff81f8af3e40 : 0xffffff800c7139f3 
0xffffff81f8af3e90 : 0xffffff800c72429d 
0xffffff81f8af3f10 : 0xffffff800c80231a 
0xffffff81f8af3fb0 : 0xffffff800c8344c6 

BSD process name corresponding to current thread: WindowServer

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
Kernel slide:     0x000000000c400000
Kernel text base: 0xffffff800c600000
__HIB  text base: 0xffffff800c500000
System model name: MacBookPro11,5 (Mac-06F11F11946D27C5)

System uptime in nanoseconds: 25429084922007
vm objects:35695920
vm object hash entri:5264120
VM map entries:9506960
pagetable anchors:1085440
pv_list:70090752
vm pages:261957248
kalloc.16:174990992
kalloc.32:1677312
kalloc.64:339155712
kalloc.128:10465280
kalloc.256:15446016
kalloc.512:128274432
kalloc.1024:5391306752
kalloc.2048:3088384
kalloc.4096:4927488
kalloc.8192:8945664
mem_obj_control:2104960
sched groups:1415232
ipc ports:4218560
threads:2593576
x86 fpsave state:1713920
uthreads:1556352
vnodes:40367520
namecache:16083360
HFS node:54419136
HFS fork:12185600
cluster_write:3492584
decmpfs_cnode:1257984
buf.4096:1658880
buf.8192:54222848
ubc_info zone:8208552
vnode pager structur:3732960
compressor_pager:2752512
compressor_segment:2528496
Kernel Stacks:4079616
PageTables:249008128
Kalloc.Large:67775817

Backtrace suspected of leaking: (outstanding bytes: 423936)
0xffffff800c76aed6 
0xffffff800c733581 
0xffffff800c733e88 
0xffffff7f8fcdd553 
0xffffff7f8fce402b 
0xffffff7f8fce22da 
0xffffff7f8fce23ac 
0xffffff7f8fce9eb5 
0xffffff81f98b66a0 
0xffffff800cc4b376 
      Kernel Extensions in backtrace:
         com.verdasys.dgagent(2029.12.7)[463B2568-AE9E-326E-A912-A94516AC5300]@0xffffff7f8fcdc000->0xffffff7f8fd15fff
            dependency: com.apple.security.sandbox(300.0)[DD112B48-71D8-3A60-8309-47200488CD40]@0xffffff7f8d1bb000

last loaded kext at 16682296932044: com.apple.driver.AppleUSBOHCI	656.4.1 (addr 0xffffff7f8fe8a000, size 69632)
last unloaded kext at 16772775831131: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7f8fe12000, size 16384)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	5.0.16
org.virtualbox.kext.VBoxNetFlt	5.0.16
com.verdasys.dgagent	2029.12.7
org.virtualbox.kext.VBoxUSB	5.0.16
org.virtualbox.kext.VBoxDrv	5.0.16
org.pqrs.driver.Karabiner	10.18.0
com.apple.driver.AppleUSBDisplays	372.1
com.apple.iokit.AppleBCM5701Ethernet	10.1.3
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.AGPM	110.19.6
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleHDA	272.18.1
com.apple.driver.AppleGraphicsDevicePolicy	3.7.7
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.kext.AMDFramebuffer	1.3.2
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.AMDRadeonX4000	1.3.2
com.apple.kext.AMD7000Controller	1.3.2
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleCameraInterface	5.36.0
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleIntelHD5000Graphics	10.0.6
com.apple.driver.AppleIntelFramebufferAzul	10.0.6
com.apple.driver.AppleMuxControl	3.10.25
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.AppleTopCaseHIDEventDriver	67
com.apple.driver.AppleUSBTopCaseDriver	67
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleUSBAudio	295.23
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.iokit.IOFireWireFamily	4.5.8
com.apple.driver.AppleThunderboltPCIUpAdapter	2.0.2
com.apple.driver.AppleThunderboltDPOutAdapter	4.0.6
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	272.18.1
com.apple.kext.OSvKernDSPLib	1.15
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.kext.AMDSupport	1.3.2
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOSurface	97.4
com.apple.AppleGraphicsDeviceControl	3.10.25
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.driver.AppleGraphicsControl	3.10.25
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.iokit.IOUSBHIDDriverPM	710.4.7
com.apple.driver.CoreStorage	471.30.1
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.iokit.IO80211Family	730.60
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1
Model: MacBookPro11,5, BootROM MBP114.0172.B04, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe, 2048 MB
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@189,0,0
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@188,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@187,0,1
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@187,0,0
PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@194,0,0
PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@187,0,2
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@193,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@199,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@199,0,1
PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@199,0,2
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: USB Optical Mouse
USB Device: Apple Thunderbolt Display
USB Device: Display Audio
USB Device: FaceTime HD Camera (Display)
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: USB Optical Mouse
USB Device: Display Audio
USB Device: Apple Thunderbolt Display
USB Device: FaceTime HD Camera (Display)
USB Device: Internal Memory Card Reader
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
Thunderbolt Device: Thunderbolt Display, Apple Inc., 1, 26.2

**Comment by tekezo** [comment]
This panic is caused by `com.verdasys.dgagent (Digital Guardian Agents)`.
Please post the issue to that product support.

**Comment by chandradeepak** [comment]
but this crash didnt happen before i installed karabiner. Even i delete karabiner this crash still happens. is there any solution to this.  I dont know who are those Digital Guardian Agents.

**Comment by tekezo** [comment]
The Digital Guardian Agents might be this.
https://digitalguardian.com/products/digital-guardian-agents/mac

If this issue happen after uninstalling Karabiner, Karabiner is not related with this issue completely.
https://pqrs.org/osx/karabiner/document.html.en#uninstall

It's worth booting Safe Mode once for clean up your environment.
The Safe Mode will delete cache files at boot. It might be solve this issue.
https://support.apple.com/en-us/HT201262

**Comment by chandradeepak** [comment]
thanks. once i uninstalled karabiner and then did safe boot. that cleaned up the drives i guess. i no longer see the issue.

Thanks for letting me know that we can do safe boot. i will let you know if it repeats again.

Thanks for helping out with your answers.

**Comment by cuteeyesj** [comment]
Dear I am getting this error..
I just want to swap left command with fn..


Exception Name: NSInvalidArgumentException
Description: *** -[NSTextView replaceCharactersInRange:withString:]: nil NSString given.
User Info: (null)

0   CoreFoundation                      0x00000001090107bb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x000000010741aa2a objc_exception_throw + 48
2   CoreFoundation                      0x000000010908da65 +[NSException raise:format:] + 197
3   AppKit                              0x0000000107aa71e2 -[NSTextView replaceCharactersInRange:withString:] + 211
4   Karabiner-Elements                  0x0000000106c8a7f8 __37-[LogFileTextViewController monitor:]_block_invoke + 562
5   libdispatch.dylib                   0x0000000109770128 _dispatch_client_callout + 8
6   libdispatch.dylib                   0x0000000109785c10 _dispatch_continuation_pop + 533
7   libdispatch.dylib                   0x000000010977bad2 _dispatch_source_latch_and_call + 192
8   libdispatch.dylib                   0x0000000109772966 _dispatch_source_invoke + 1248
9   libdispatch.dylib                   0x000000010977da0f _dispatch_main_queue_callback_4CF + 505
10  CoreFoundation                      0x0000000108fc6df9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  CoreFoundation                      0x0000000108f8837d __CFRunLoopRun + 2221
12  CoreFoundation                      0x0000000108f87874 CFRunLoopRunSpecific + 420
13  HIToolbox                           0x000000010f96cf6c RunCurrentEventLoopInMode + 240
14  HIToolbox                           0x000000010f96cda1 ReceiveNextEventCommon + 432
15  HIToolbox                           0x000000010f96cbd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
16  AppKit                              0x00000001079085f5 _DPSNextEvent + 1093
17  AppKit                              0x00000001080188eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
18  AppKit                              0x00000001078fcfbd -[NSApplication run] + 926
19  AppKit                              0x00000001078c7a8a NSApplicationMain + 1237
20  libdyld.dylib                       0x00000001097e3255 start + 1
