### ISSUE TITLE
Change Key bindings for mouse keys mode v2?

### ISSUE THREAD

**Issue by excetara2** [tekezo/Karabiner#647]
I am having problems with sometimes typing text and the d key is taken over or skipped typing because of this setting. Also i think the d keys is one of the fastest keys to type so that doesn't help. I want to keep this setting on but change it to using the `z,x,c` keys instead of `s,d,f`. This will map the `d` to the `x` which is a lot less used key as well as typically typed slower I think so shouldn't be affected while typing. What is the best way to  this? Is the function for mouse keys somewhere and I can copy the version I want into the priviate.xml?

**Comment by tekezo** [comment]
For example, this private.xml allows you to use the right option key as the trigger key.
https://github.com/tekezo/Files/blob/master/Karabiner/private.mouse_keys_mode_v2_option/private.xml

**Comment by excetara2** [comment]
okay thanks that helps!
