### ISSUE TITLE
Mouse Over does not work sometimes

### ISSUE THREAD

**Issue by azngeek** [tekezo/Karabiner#648]
If i have Karabiner running, sometimes the Mouse Over does not work any more. For example if i hover over one of the items then they should be highlighted but instead of that nothing happens.

![image](https://cloud.githubusercontent.com/assets/213429/15646545/7c96bf8e-265e-11e6-8aa7-0a4b146221d0.png)

A side effect is that drag and drop operations also seems to lag the system. I do not know how to replicate it but maybe someone has a similar issue.

**Comment by tekezo** [comment]
It's known that some mice does not work well with Karabiner.
Does this setting solve this issue?
You can find the setting by searching `core don't`.

![160530-0001](https://cloud.githubusercontent.com/assets/659178/15652130/ee0df172-26be-11e6-8f7a-5cfbb16c80d4.png)

**Comment by azngeek** [comment]
I will try it. Thanks for the fast response. If the problems are solved within the next days i will close the ticket.
