### ISSUE TITLE
problem with faulty keyboard

### ISSUE THREAD

**Issue by Pain1666** [tekezo/Karabiner#650]
Hi i'm very new to Karabiner, i'm actually using KeyRemap 8.4.0 ver in an old 2006 Macbook.

The keyboard is somehow faulty and the H key not properly working, so instead of typing correctly it types this: ˙
Same goes for Opt Key: ˙ 

Now, i created a basic profile where I manage to make both work again but only alternatively switching from one profile to the other, here's the script:

```
<?xml version="1.0"?>
<root>
<item>
    <name>h</name>
    <identifier>private.swap_h</identifier>
    <autogen>__KeyToKey__ KeyCode::H, ModifierFlag::OPTION_L, KeyCode::H</autogen>
  </item>
<item>
    <name>Option_L</name>
    <identifier>private.swap_option_l</identifier>
    <autogen>__KeyToKey__ KeyCode::H, ModifierFlag::OPTION_L, KeyCode::OPTION_L</autogen>
  </item>
</root>
```

Now my questions are:

1. Is it possible to make them work both at the same time instead of having to switch between profiles?
2. is it possible to add a delay when I press the H key as it seems to trigger something else when i type too fast H followed by A, E, I, O, U get respectively: hå h´hˆ hø h¨

Thanks in advance

Diego

**Comment by tekezo** [comment]
I guess we cannot distinguish the physical h and option keys.

I think dropping the left option key event is the most robust way:

```
    <autogen>__KeyToKey__ KeyCode::OPTION_L, KeyCode::VK_NONE</autogen>
```

(Please use the right option key to use option modifier.)

**Comment by Pain1666** [comment]
It worked perfectly! 
Thanks
