### ISSUE TITLE
Is there some way to group items 

### ISSUE THREAD

**Issue by hgiesel** [tekezo/Karabiner#652]
Is there some way to *group* the `<autogen>` items in the private.xml file? So that they appear ordered in some fashion. When you add more and more at some point you lose the overview...

OS X 10.11.5; Karabiner 10.18.0; MacBook Air 2014; Built-in keyboard

**Comment by tekezo** [comment]
Separating XML by `<include>` tag is one of the ways.
https://pqrs.org/osx/karabiner/xml.html.en#include

------------------------------

If you are writing complex private.xml, you can also use XML generator.

Easy-Karabiner
    https://github.com/loggerhead/Easy-Karabiner

Karabiner DSL
    https://github.com/k0kubun/karabiner-dsl

**Comment by hgiesel** [comment]
Okay things, that is sufficient for me. I don't really like applications that obscure what I'm doing by adding another laying of abstraction, but thanks anyway!
