### ISSUE TITLE
Conditional remapping based on UI input context

### ISSUE THREAD

**Issue by Neo-Desktop** [tekezo/Karabiner#656]
New Feature idea:

Conditional key remapping based on what UI element is currently focused.

For instance - if an input box is currently focused, then allow certain remappings to take place (such as the PC Style Home/End). This should apply en tandem with the conditional application remappings.

Just a thought. I'm not well versed on the OS X API, but this will certainly make my OS X experiance way more windows-like.

Thanks!

**Comment by tekezo** [comment]
This function is already exists.
https://pqrs.org/osx/karabiner/xml.html.en#uielementroledef

Settings that uses this function:
https://pqrs.org/osx/karabiner/gallery.html.en#operate-finder-by-hjkl-keys

However, I guess you want to use it in the web browsers, the web browsers do not notify UI element role changes properly.
You can confirm the UI element role changes in EventViewer > App tab.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

Google Chrome and Firefox keep AXWindow for any elements.
Safari is much better but it is not perfect.
