### ISSUE TITLE
replacementdef seems not working in replacementvalue

### ISSUE THREAD

**Issue by puttin** [tekezo/Karabiner#657]
I have a `replacementdef` `CONFIG_FOLDER`
and `CONFIG_FOLDER` have a subfolder `A`

then I want to def a `replacementdef` called `FOLDER_A`

```
<replacementdef>
  <replacementname>FOLDER_A</replacementname>
  <replacementvalue>{{ CONFIG_FOLDER }}/A</replacementvalue>
</replacementdef>
```

**Comment by tekezo** [comment]
Unfortunately, the recursive replacement in the same level is not supported.
(Sorry for inconvenience)

Please use <include> together.
https://pqrs.org/osx/karabiner/xml.html.en#include-with-replacementdef

Example:
https://github.com/tekezo/Files/tree/master/Karabiner/recursive-replacement-example

**Comment by puttin** [comment]
Workaround better than nothing
