### ISSUE TITLE
Key remap just unchecks itself...

### ISSUE THREAD

**Issue by ipepe** [tekezo/Karabiner#658]
Key remap just unchecks itself...
![Gif](http://i.imgur.com/zoFjlQx.gif)
My specs:
Karabiner: 10.19.2
Mac: 10.11.5
Hardware: MacBook Pro (13-inch, Early 2011)

DoubleCommand worked before updating to 10.11 but now I tried Karabiner and it won't work like DoubleCommand... :(

**Comment by tekezo** [comment]
I guess that your system is refusing to save Karabiner configuration by some reason.
Does restart your system and reinstall Karabiner solve this issue?

**Comment by ipepe** [comment]
Nope

**Comment by tekezo** [comment]
Hmm, is the following command in Terminal able to change the setting?
(Open Terminal.app and paste this command and then press return key.)

```xml
/Applications/Karabiner.app/Contents/Library/bin/karabiner toggle remap.fn2controlL
```

And I want to know whether you can add new profile in Karabiner?
Could you try to add profile and confirm this issue with new profile?
https://pqrs.org/osx/karabiner/document.html.en#profiles

**Comment by ipepe** [comment]
Command didn't work. I created a profile, but something was interrupting renaming that profile. On new profile I was able to remap that key successfully from GUI.

**Comment by tekezo** [comment]
Thank you for confirmation!
I've improved the profile handling in Karabiner-10.20.0 by your feedback.
