### ISSUE TITLE
Is it possible to automatically disable Karabiner in certain applications?

### ISSUE THREAD

**Issue by ghost** [tekezo/Karabiner#661]
There is a specific application that I need the standard function keys for (F1, F2, etc), however I have all the function keys assigned to media/custom keys normally. Is there a way for Karabiner to automatically disable it self within certain applications?

**Comment by tekezo** [comment]
You can do it by making your own setting by private.xml.
What app do you want to disable Karabiner?

------

Reference links if you can make private.xml:

Use `__PassThrough__` with `<only>` filter.
https://pqrs.org/osx/karabiner/xml.html.en#syntax-__PassThrough__
https://pqrs.org/osx/karabiner/xml.html.en#appdef

An example:
https://github.com/tekezo/Karabiner/blob/version_10.20.0/src/core/server/Resources/include/checkbox/ignore_apps_and_devices.xml#L9-L14

**Comment by dem466** [comment]
The app is specifically called 'Cubase 8.5'

**Comment by tekezo** [comment]
OK.
Please tell me the bundle identifier of Cubase 8.5.
You can confirm it in EventViewer > App tab.
https://pqrs.org/osx/karabiner/xml.html.en#appdef-steps

**Comment by dem466** [comment]
Figured it out! Grabbed the identifier and used <appdef>

**Comment by brianroach** [comment]
@tekezo I tried using the format in the example you posted here: https://github.com/tekezo/Karabiner/blob/version_10.20.0/src/core/server/Resources/include/checkbox/ignore_apps_and_devices.xml#L9-L14 and it successfully works while the apps window is in focus, but is it possible to do something simlar, but for apps that don't have windows (i.e. menubar apps)?

Essentially, I am trying to simply disable the app from receiving a shortcut regardless of what app I am currently using. Is this possible?
