### ISSUE TITLE
Is it possible to automatically switch the Input Source between application ?

### ISSUE THREAD

**Issue by Thanyth** [tekezo/Karabiner#662]
Is it possible to automatically switch the Input Source of my keyboard only in specific application, without  the need of a key press? Usage: In Photoshop I'm using a French Canadian (QC) keyboard. I have try to remap all of them, but some won't work. ( Example: Alt+[ or Alt+] ) I added a custom code (to switch the input source) in the private.xml but it's not the best option I think.

 OS X El Capitan 10.11.5
 Karabiner: 10.20.0
 Mac hardware: Mac Mini
 Keyboard hardware: Logitech access keyboard 600

**Comment by tekezo** [comment]
Other applications is more suitable for this purpose.

Hammerspoon:
http://www.hammerspoon.org/

AutoKeyboard:
https://itunes.apple.com/jp/app/autokeyboard/id908553210
