### ISSUE TITLE
help with mapping command + shift without conflicts

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#664]
I want to make a mapping that when command + shift is pressed over a selected text, it will perform a hotkey. I am not sure whether Karabiner can know whether I have selected text or not but that doesn't matter as much I think.

I just want to make it so that I can press command + shift and it will perform a hotkey press whist I can still use my command + shift to do things and also use shift. I have tried to make it work with this code : 

```XML
<!-- command + left shift for google text selection -->
<item>
<name>command plus left shift to google selected text</name>
<identifier>private.command_plus_left_shift_to_hotkey</identifie>
<autogen>
__KeyToKey__
KeyCode::SHIFT_L, ModifierFlag::COMMAND_L,
KeyCode::9, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L, ModifierFlag::SHIFT_L, ModifierFlag::COMMAND_L,
</autogen>
<autogen>
__KeyOverlaidModifier__
KeyCode::SHIFT_L,
KeyCode::SHIFT_L,
</autogen>
</item>

<!-- left option plus left shift for dash text selection -->
<item>
<name>left option plus left shift to search documentation for selected text</name>
<identifier>private.left_option_plus_left_shift_to_hotkey</identifie>
<autogen>
__KeyToKey__
KeyCode::SHIFT_L, ModifierFlag::OPTION_L,
KeyCode::O, ModifierFlag::CONTROL_L, ModifierFlag::SHIFT_L, ModifierFlag::COMMAND_L,
</autogen>
<autogen>
__KeyOverlaidModifier__
KeyCode::SHIFT_L,
KeyCode::SHIFT_L,
</autogen>
</item>
```

However this throws a lot of conflicts. I am also not sure if I need the KeyOverlaidModifier there. 

Can you help me please make these two mappings work please. It seems that command + shift seems to trigger my binded hotkey instantly when pressed and not on release thus I can't normally use command + shift normal but I may be wrong.

Thank you for any help. An absolutely phenomenal application. ♥

**Comment by tekezo** [comment]
I think this XML satisfies your desire. Please try it.

```xml
  <!-- command + left shift for google text selection -->
  <item>
    <name>command plus left shift to google selected text</name>
    <identifier>private.command_plus_left_shift_to_hotkey</identifier>
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_L, ModifierFlag::COMMAND_L,
      KeyCode::SHIFT_L, ModifierFlag::COMMAND_L,
      KeyCode::9, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
    </autogen>
  </item>
```

**Comment by nikitavoloboev** [comment]
Thank you, that worked beautifully.
