### ISSUE TITLE
Could karabiner.remotedesktop be more specific?

### ISSUE THREAD

**Issue by e-gaulue** [tekezo/Karabiner#666]
Dear developper,

I want to provide contributions specific to Microsoft Remote Desktop for Mac when on the remote login screen (if credentials have not been set in the preference) and in the remote window. This application handle foreign keyboard really strangely.

Presently, you offer the newbundleidentifier karabiner.remotedesktop. Could it be specific to Microsoft Remote Desktop for Mac and not include "Chrome Remote Desktop" or "RoyalTSX"? Changed to microsoft.rdc.remotedesktop?

Or what is the priority for bundleIdentifier? I mean if I build a new one looking for the same as karabiner.remotedesktop, the winner is always karabiner.remotedesktop and not mine. Is there a way to force priority?

Regards,

**Comment by tekezo** [comment]
OK.
I've changed the bundle identifier to karabiner.remotedesktop.microsoft.

```xml
  <appdef>
    <appname>Microsoft_Remote_Desktop</appname>
    <equal>com.microsoft.rdc</equal>
    <equal>com.microsoft.rdc.mac</equal>
    <equal>com.microsoft.rdc.osx.beta</equal>
    <equal>karabiner.remotedesktop.microsoft</equal>
  </appdef>

  <item>
    <name>Example</name>
    <identifier>private.example</identifier>

    <only>Microsoft_Remote_Desktop</only>

    <autogen>...</autogen>
  </item>
```

**Comment by e-gaulue** [comment]
I know it's strange but the way keyboard is handle by com.microsoft.rdc is totally different than with com.microsoft.rdc.mac (one is at the window manager level and the other one at the driver level). Both can use Karabiner but for some keys like '6' need to be handle differently. So, I would recommend to remove com.microsoft.rdc from this list.

Regards,

**Comment by tekezo** [comment]
OK.
You should use this appdef.

```xml
  <appdef>
    <appname>Microsoft_Remote_Desktop</appname>
    <equal>com.microsoft.rdc.mac</equal>
    <equal>com.microsoft.rdc.osx.beta</equal>
    <equal>karabiner.remotedesktop.microsoft</equal>
  </appdef>
```

**Comment by twilly86** [comment]
I am on a mac mini, using a windows keyboard, and then remote dekstop'ing into a windows machine.

Below is a screen shot of my settings.  "Except in "RDC" is not working when I am using Microsoft Remote Desktop app.  The commands are still filtered.

![image](https://cloud.githubusercontent.com/assets/3496838/18836212/2faa4aa4-83bc-11e6-9adf-b3a2c051f0bc.png)
