### ISSUE TITLE
Can I increase key repeat on a key binding I made?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#668]
I have this simple autogen I made and it works well : 

```XML
<item>
<name>right shift to command and shift when together, delete when alone</name>
<identifier>private.right_shift_to_command_and_shift</identifier>
<autogen>
--KeyOverlaidModifier--
KeyCode::SHIFT_R,
KeyCode::SHIFT_R, ModifierFlag::COMMAND_L,
KeyCode::DELETE
</autogen>
</item>
```

However I wish I can increase key repeat on it, like what I have on my original delete key, that is pressing and holding will be deleting things faster. Can I do that?

Also there is a weird issue, perhaps my logic is wrong. I want to have right command and right shift when held together be OPTION_L and COMMAND_L  so I made this : 

```XML
<item>
<name>right shift and right command to option and command</name>
<identifier>private.right_shift_and_command_to_option_command</identifier>
<autogen>
--KeyOverlaidModifier--
KeyCode::SHIFT_R, ModifierFlag::COMMAND_R,
KeyCode::OPTION_L, ModifierFlag::COMMAND_L,
KeyCode::DELETE, ModifierFlag::COMMAND_L
</autogen>
</item>
```

This however doesn't seem to work. What is wrong with it?

By the way, I always wondered what keybindings you yourself use, I think it would be quite interesting to see. :)

Thank you a lot for your help with this and for the great application.

**Comment by tekezo** [comment]
Please use `Option::KEYOVERLAIDMODIFIER_REPEAT` like this:

```xml
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::SHIFT_R,
      KeyCode::SHIFT_R, ModifierFlag::COMMAND_L,
      KeyCode::DELETE,

      Option::KEYOVERLAIDMODIFIER_REPEAT,
    </autogen>
```

> By the way, I always wondered what keybindings you yourself use, I think it would be quite interesting to see. :)

I'm usually using 100+ settings, mainly the follows.
* emacs mode
* simple vi mode v2
* mouse keys mode v2
* hjkl cursor
* launcher mode v2
* disable built-in keyboard

These settings are described here:
https://pqrs.org/osx/karabiner/gallery.html.en

**Comment by nikitavoloboev** [comment]
Thank you this worked
