### ISSUE TITLE
Help with sticky keys

### ISSUE THREAD

**Issue by AdamKing0126** [tekezo/Karabiner#669]
Hello.  
I've looked at some of the examples but cannot figure out how to add sticky keys.  Can anyone help?

Specifically here's what I'm trying to do:
I want to remap some keys on my homerow so that when I press and release L-shift, and then press 'd', I get '{', 'f' would give '[', 'g' would give '(', 'h' would give ')', 'j' would give ']', 'k' would give '}', etc.

Can anybody help me out with this mapping?

Thanks a lot!
Adam

**Comment by tekezo** [comment]
Please use new setting by this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/private.homerow_sticky/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by AdamKing0126** [comment]
Wow! Thanks so much for your help.  Much appreciated!
