### ISSUE TITLE
Use PC Style Lock Screen - Go to sleep instead of lock screen

### ISSUE THREAD

**Issue by remia** [tekezo/Karabiner#673]
Just noticed that when using the 'Use PC Style Lock Screen' option, the system is put to sleep.
I'm sure I used this before and it was as expected, I reinstalled OS X though and might have missed something.

Is this the intended behavior now ?

(OS X 10.11.5, Karabiner 10.20.0)

**Comment by tekezo** [comment]
Thank you for feedback!

I've adjusted that setting in Karabiner-10.21.1.
Please upgrade to the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by remia** [comment]
Thanks for the quick fix !

Checked the new beta version, it works as intended :)

**Comment by chazlegrand** [comment]
Noticed the same issue and came across this searching for a solution. I think it's still not *quite* fixed as ctrl-shift-power allows my music to remain running in the background (like windows lock-screen does). Rather, ctrl-L seems to log me out. Loving this program though.

**Comment by percontation** [comment]
```
    <vkopenurldef>
      <name>KeyCode::VK_OPEN_URL_SHELL_lock_screen</name>
      <url type="shell">
        <![CDATA[    python -c 'exit(__import__("ctypes").cdll.LoadLibrary("/System/Library/PrivateFrameworks/login.framework/login").SACLockScreenImmediate())' || '/System/Library/CoreServices/Menu Extras/User.menu/Contents/Resources/CGSession' -suspend    ]]>
      </url>
    </vkopenurldef>
```

@chazlegrand You can have the behavior you want by adding this to your private.xml

@tekezo Perhaps this should be the default command for locking the screen?

(The fallback to `CGSession -suspend` is mostly to stay compatible with older OS X versions; AFAIK SACLockScreenImmediate doesn't fail under normal conditions. I'm on El Cap, I'm assuming this works for Sierra)
