### ISSUE TITLE
How can I use f to search in Vim mode? e.g. "abc" fc

### ISSUE THREAD

**Issue by YongHaoWu** [tekezo/Karabiner#674]
I have searched all the vim keywords on Karabiner, however, there is no f key.
Could you tell me how to solve this? It is useful to use f to move the cursor.
Thank you very much.

**Comment by tekezo** [comment]
Karabiner does not extend the text area behavior.
Karabiner simulates vim behavior by sending shortcuts.
(eg. sending arrow keys by hjkl keys.)

The `f` key is one of the vim function which is difficult to imitate.

**Comment by YongHaoWu** [comment]
@tekezo Thank you for your reply. I understand now.
But if can simulates vim behavior by sending shortcuts, why it can not support 3e, 4w as it can use a loop to send shortcuts?

**Comment by tekezo** [comment]
It's due to the limitation of Karabiner private.xml expression.
Karabiner does not provide counter at the moment for some reason.
Therefore, such repeat function will be very complex private.xml.

The `vim emu` settings provide strong functions, but the definition is huge.

**Comment by YongHaoWu** [comment]
OK， thank you very much!
