### ISSUE TITLE
Remap horizontal scroll to shift + vertical scroll?

### ISSUE THREAD

**Issue by thalesmello** [tekezo/Karabiner#675]
I was wondering if it's possible to remap Horizontal Scroll to Vertical Scroll + key modifier.

I wish to use this to achieve horizontal scrolling on the terminal and other applications that do not support horizontal scrolling by default.

I've tried the ScrollWheelToScrollWheel keybindings, but apparently it only works for changing modifiers. Is there any way of putting this together?

**Comment by tekezo** [comment]
Unfortunately, there is not such a function at the moment.
However, you can change the horizontal scrolling to key by `__ScrollWheelToKey__ `.

**Comment by thalesmello** [comment]
I have indeed tried that, however, I find it to be inconsistent when I use it with a TrackPad.

It only activates the key remapping when I start the scroll movement.

It, however, fails to repeat the key command when I continuously move my fingers across the trackpad.

I've used EventViewer and noticed it indeed captures ScrollWheel events in a sufficient frame rate, but somehow those are not converted to key repeats.

![image](https://cloud.githubusercontent.com/assets/1127394/16939644/e3d21316-4d59-11e6-8a9b-e7dc36ebd919.png)

Is there, maybe, any setting I'm missing?

**Comment by tekezo** [comment]
unfortunately, the __ScrollWheelToKey__ does not support smooth key repeating, but you can adjust the interval of key events in Parameter tab.

![160720-0002](https://cloud.githubusercontent.com/assets/659178/16973158/2b194b1e-4e6c-11e6-97b5-e18f438163f3.png)

**Comment by thalesmello** [comment]
Thanks, but I'm actually interested in the smooth scrolling functionality.

I'm considering submitting a pull request, as it bothers me enough.

@tekezo Would you be kind to give me direction on what would be necessary to do in order to implement wither the "smooth scroll to key repeat" or maybe the "map horizontal as vertical scroll wheel"?

**Comment by tekezo** [comment]
It's not a simple way.
I think the easiest way is hard code this behavior in `__FlipScrollWheel__` for prototyping.
https://github.com/tekezo/Karabiner/blob/master/src/core/kext/RemapFunc/FlipScrollWheel.cpp

I guess we should ignore slight horizontal scroll to prevent accidental event at normal vertical scrolling.
The similar code is in __ScrollWheelToKey__.
https://github.com/tekezo/Karabiner/blob/master/src/core/kext/RemapFunc/ScrollWheelToKey.cpp#L72-L99
