### ISSUE TITLE
How can I add a key to switch applications in Simple Vi Mode v2?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#678]
I really love using Simple Vi Mode v2, it is really great.

I very often read books whilst scrolling using this mode and take notes in another application. I would really love if I could add a new function to it where if I press M whist holding S, it will switch to previous application I was in. This would really save me quite a bit of time and if I will understand how to make it work I can add features of my own. 

Thank you so much for the work you have put into this software, it really does change the way you use your computer. I hope you can help me with this. I have looked into private.xml reference manual but couldn't really figure out how to make it work. 

Also, is it possible to reload xml from some command line command? I think it would really be a great option to have especially if you want to quickly test if the xml you entered is correct. What do you think?

**Comment by tekezo** [comment]
Please use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.SIMPLE_VI_MODE_EXTRA/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by nikitavoloboev** [comment]
Wow, this is really powerful. Thank you. I can also add new autogens to it by copying the replacement value and changing autogen to what you want.

I want to make a new key f, that when held will allow me to map different keys to it to do things. I found this : 

```XML
<?xml version="1.0"?>
<root>

  <vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_APP_Maps</name>
    <url type="file">/Applications/Maps.app</url>
  </vkopenurldef>

  <vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_APP_FaceTime</name>
    <url type="file">/Applications/FaceTime.app</url>
  </vkopenurldef>

  <replacementdef>
    <replacementname>LAUNCHER_MODE_V2_EXTRA</replacementname>
    <replacementvalue>
      <![CDATA[
        <autogen>
          __KeyDownUpToKey__
          KeyCode::C,
          KeyCode::VK_OPEN_URL_APP_Maps,
        </autogen>

        <autogen>
          __KeyDownUpToKey__
          KeyCode::V,
          KeyCode::VK_OPEN_URL_APP_FaceTime,
        </autogen>
      ]]>
    </replacementvalue>
  </replacementdef>

</root>
```

Which allows me to add actions to existing c held command. However what do I need to write If I want to make a new key, 'a' that when held, I can add new keys to it like I do here? I couldn't find it in the private.xml. I guess I should look in the code and see where Simple Vi Mode v2 was declared but again I am not sure where to look exactly. Thank you for your help on this.

**Comment by tekezo** [comment]
Put this xml and use Launcher Mode v2 is the easiest way.

```xml
  <replacementdef>
    <replacementname>LAUNCHER_MODE_V2_KEY</replacementname>
    <!-- You can change the start key. -->
    <replacementvalue>KeyCode::A</replacementvalue>
  </replacementdef>
```

**Comment by nikitavoloboev** [comment]
But this replaces the Launcher mode key. I already use it to open some of my applications. I wanted to create a new key 'a' that I can use as my modifier key press. For example, I hold down a, press t, it will trigger cmd+t. Can I do that?

**Comment by tekezo** [comment]
It's example:
https://github.com/tekezo/Files/blob/master/Karabiner/private.launcher_mode_example/private.xml

(This example was copied from the prepared launcher mode.)
https://github.com/tekezo/Karabiner/blob/version_10.21.0/src/core/server/Resources/include/checkbox/launcher_mode.xml

**Comment by nikitavoloboev** [comment]
This is exactly what I wanted. Thank you so much. However I am not really sure why this autogen : 

```XML

  <item>
    <name>launcher mode example</name>
    <identifier>private.launcher_mode_example</identifier>

    <!-- condition: turn on launcher mode only when the trigger key is pressed without other keys. -->
    <pressingphysicalkeys_lessthan>2</pressingphysicalkeys_lessthan>
    <modifier_not>
      ModifierFlag::COMMAND_L,
      ModifierFlag::COMMAND_R,
      ModifierFlag::CONTROL_L,
      ModifierFlag::CONTROL_R,
      ModifierFlag::FN,
      ModifierFlag::OPTION_L,
      ModifierFlag::OPTION_R,
      ModifierFlag::SHIFT_L,
      ModifierFlag::SHIFT_R,
    </modifier_not>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::A,

      <!--
          Use notsave.launcher_mode_v2 in order to be higher priority.
          Use ModifierFlag::MY_LAUNCHER_MODE for __DropAllKeys__.
      -->
      @begin
      KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_private_launcher_mode, ModifierFlag::MY_LAUNCHER_MODE,
      @end

      @begin
      KeyCode::A,
      @end
    </autogen>
  </item>

  <item hidden="true">
    <identifier vk_config="true">notsave.private_launcher_mode</identifier>

    <autogen>
      __BlockUntilKeyUp__ KeyCode::A,
    </autogen>

    <autogen>
      __KeyDownUpToKey__
      KeyCode::L,
      KeyCode::L, ModifierFlag::CONTROL_L
    </autogen>

    <autogen>
      __KeyDownUpToKey__
      KeyCode::W,
      KeyCode::KeyCode::W, ModifierFlag::CONTROL_L
    </autogen>
  </item>
```

Gives me the following error : 

![2016-07-23 at 15 57](https://cloud.githubusercontent.com/assets/6391776/17078257/35b18e18-50ee-11e6-9dcd-cae75e831af6.png)

**Comment by tekezo** [comment]
Replace `KeyCode::KeyCode::W` with `KeyCode::W`.

**Comment by nikitavoloboev** [comment]
Yeah, was a silly mistake :)

This is perfect. Thank you.

**Comment by nikitavoloboev** [comment]
I am curious are using using these sticky keys for other keys as well aside from O for 'open' and S for vim movement? The way this is implemented is really superb.

**Comment by nikitavoloboev** [comment]
I have tried to add another key the same way that you have added a 'sticky' key. I have to tried to add 'f' as a new sticky key. Copying and replacing things like so : 

```XML

  <modifierdef>MY_LAUNCHER_MODE</modifierdef>


  <item>
    <name>a key hold as control modifier</name>
    <identifier>private.launcher_mode_example</identifier>

    <!-- condition: turn on launcher mode only when the trigger key is pressed without other keys. -->
    <pressingphysicalkeys_lessthan>2</pressingphysicalkeys_lessthan>
    <modifier_not>
      ModifierFlag::COMMAND_L,
      ModifierFlag::COMMAND_R,
      ModifierFlag::CONTROL_L,
      ModifierFlag::CONTROL_R,
      ModifierFlag::FN,
      ModifierFlag::OPTION_L,
      ModifierFlag::OPTION_R,
      ModifierFlag::SHIFT_L,
      ModifierFlag::SHIFT_R,
    </modifier_not>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::A,

      <!--
          Use notsave.launcher_mode_v2 in order to be higher priority.
          Use ModifierFlag::MY_LAUNCHER_MODE for __DropAllKeys__.
      -->
      @begin
      KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_private_launcher_mode, ModifierFlag::MY_LAUNCHER_MODE,
      @end

      @begin
      KeyCode::A,
      @end
    </autogen>
  </item>

  <item hidden="true">
    <identifier vk_config="true">notsave.private_launcher_mode</identifier>

    <autogen>
      __BlockUntilKeyUp__ KeyCode::A,
    </autogen>

    <autogen>
      __KeyDownUpToKey__
      KeyCode::L,
      KeyCode::L, ModifierFlag::CONTROL_L
	
    </autogen>

    <autogen>
      __KeyDownUpToKey__
      KeyCode::J,
      KeyCode::J, ModifierFlag::CONTROL_L,
    </autogen>


    <autogen>
      __KeyDownUpToKey__
      KeyCode::K,
      KeyCode::K, ModifierFlag::CONTROL_L,
    </autogen>

    <autogen>
      __KeyDownUpToKey__
      KeyCode::W,
      KeyCode::W, ModifierFlag::CONTROL_L
    </autogen>
  </item>

  <vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_APP_Maps</name>
    <url type="file">/Applications/Maps.app</url>
  </vkopenurldef>

  <vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_APP_FaceTime</name>
    <url type="file">/Applications/FaceTime.app</url>
  </vkopenurldef>

  <item>
    <name>f on hold to open apps</name>
    <identifier>private.launcher_mode_open_apps</identifier>

    <!-- condition: turn on launcher mode only when the trigger key is pressed without other keys. -->
    <pressingphysicalkeys_lessthan>2</pressingphysicalkeys_lessthan>
    <modifier_not>
      ModifierFlag::COMMAND_L,
      ModifierFlag::COMMAND_R,
      ModifierFlag::CONTROL_L,
      ModifierFlag::CONTROL_R,
      ModifierFlag::FN,
      ModifierFlag::OPTION_L,
      ModifierFlag::OPTION_R,
      ModifierFlag::SHIFT_L,
      ModifierFlag::SHIFT_R,
    </modifier_not>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::F,

      <!--
          Use notsave.launcher_mode_v2 in order to be higher priority.
          Use ModifierFlag::MY_LAUNCHER_MODE for __DropAllKeys__.
      -->
      @begin
      KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_private_launcher_mode, ModifierFlag::MY_LAUNCHER_MODE,
      @end

      @begin
      KeyCode::A,
      @end
    </autogen>
  </item>

  <item hidden="true">
    <identifier vk_config="true">notsave.private_launcher_mode</identifier>

    <autogen>
      __BlockUntilKeyUp__ KeyCode::F,
    </autogen>

    <autogen>
      __KeyDownUpToKey__
      KeyCode::C,
      KeyCode::VK_OPEN_URL_APP_Maps,
    </autogen>

    <autogen>
      __KeyDownUpToKey__
      KeyCode::V,
      KeyCode::VK_OPEN_URL_APP_FaceTime,
    </autogen>
  </item>
```

Does not work. One thing I find confusing is that I cannot seem to change the identifier name, like so : 

```XML
    <identifier>private.launcher_mode_open_apps</identifier>
```

Can you help me pinpoint where I have made the mistake in the xml code please? I want to essentially make f key sticky and given its usefulness I would also love to be able to have a systematic way to add new keys and making them 'sticky'. Right now I am not quite sure how to do it. I have tried copying the xml you have showed through the example and change values accordingly but as I said, it seems that identifier for it is fixed and causes errors. 

I would really love to have that working. Thank you for any help.

**Comment by nikitavoloboev** [comment]
Also I am wondering, would it be possible to have repeat key functionality when a 'sticky' key and a key is held together? For example I have [this autogen](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L102) in my private.xml and it works great but I would like to have it so that if I press down and hold on j, it will keep deleting. 

I thought that adding this option : 

```XML
    <autogen>
      __KeyDownUpToKey__
      KeyCode::J,
      KeyCode::DELETE,
      Option::NOREPEAT,
    </autogen>
```

Would achieve this effect but it doesn't. Perhaps it is not possible. But if it is it would really be great to have. 

Also I still didn't quite get whether it is possible to live reload xml from some cli command as it would really speed up the 'testing' of new autogens and actions. I have looked into /Applications/Karabiner.app/Contents/Library/bin/karabiner but didn't find such option there. :( 

Thank you so much for your help, the things you can do with this app are quite overwhelming. :D

**Comment by tekezo** [comment]
I don't understand your sticky behavior.
Please describe more detail.

About the private.launcher_mode_open_apps error, you should change identifier to avoid conflict.

For example, replace `launcher_mode_open_apps` with `launcher_mode_open_apps2`.

```xml
...
  <item>
    <name>f on hold to open apps</name>

     ...
    <autogen>
      ...

      KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_private_launcher_mode2, ModifierFlag::MY_LAUNCHER_MODE,
      ...
    </autogen>
  </item>

  <item hidden="true">
    <identifier vk_config="true">notsave.private_launcher_mode2</identifier>
     ...
  </item>
```

**Comment by nikitavoloboev** [comment]
For example in Simple Mode Vi 2, the 'S' key can be considered sticky in that if I hold it, pressing other keys will do different actions. I want to make a new key have this behaviour. For example I want to have f open various applications when f is held. This  [private xml](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L269) does not work. I have changed open_apps to open_aps_v2.

**Comment by tekezo** [comment]
Please read the error message.
You have to change this line:
https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L306
And this line:
https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L296

Also you should change this line to `KeyCode::F`.
https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L300

**Comment by nikitavoloboev** [comment]
Oh my bad. Sorry about this. It makes sense now.

What about having key repeat on key when two keys are held down together. What I proposed here : 

![2016-07-25 at 16 20](https://cloud.githubusercontent.com/assets/6391776/17104598/e25ede9a-5283-11e6-9083-a35ec190fac2.png)

SimpleViMode does it so I suppose it should be possible. Although I am not quite sure how. 
[This](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L371) is an autgen I want to add this functionality to if it is possible. It would be incredible if it is.

Thank you again for your help.

**Comment by tekezo** [comment]
You can change j key to delete by putting this autogen at https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L106
(Or other places in notsave.private_launcher_mode_v3)

```xml
    <autogen>
      __KeyToKey__
      KeyCode::J,
      KeyCode::DELETE,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Wow, thank you. This worked. Didn't think about KeyToKey.
