### ISSUE TITLE
Chrome and Firefox - Reopen Closed Tab - New Incognito Window

### ISSUE THREAD

**Issue by Z3n3K** [tekezo/Karabiner#680]
Please can you add the shortcuts for 

- Reopen Closed Tab
- New Incognito Window

For the Chrome and Firefox browsers ? That hotkeys are populars.

Thanks

**Comment by tekezo** [comment]
What key bind do you want to use?

**Comment by Zen3K** [comment]
Reopen Closed Tab : ctrl+shift+T
New Incognito Window : ctrl+shift+N


Thanks.

**Comment by tekezo** [comment]
I've added these settings in v10.21.5.
Please enable them.
![160730-0002](https://cloud.githubusercontent.com/assets/659178/17254742/050364c8-55f1-11e6-95c8-8f940f9a44dc.png)

(You can find firefox version by searching "PC Style Firefox".)

**Comment by Zen3K** [comment]
Thanks for the answer Tekezo!

Only a few details:

- "New Incognito Window" is a different action of "New Window" you can see for yourself in the browser -> File (menu)

- "Reopen Closed Tab" is a different action of "New Tab".
