### ISSUE TITLE
Add WebStorm as register application.

### ISSUE THREAD

**Issue by Zen3K** [tekezo/Karabiner#681]
Can you please add WebStorm as a register application in the next release?

   <appdef>
        <appname>WebStorm</appname>
        <prefix>com.jetbrains.WebStorm</prefix>
    </appdef>

Thanks.

**Comment by tekezo** [comment]
I've added WebStorm at v10.21.4.
https://github.com/tekezo/Karabiner/commit/85267a672b887f4e5c431f510cc48a2ed78cc5e5

You can confirm the change in the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates
