### ISSUE TITLE
Add all JetBrains ides as PC_STYLE_BINDINGS_IGNORE_APPS.

### ISSUE THREAD

**Issue by Zen3K** [tekezo/Karabiner#682]
Can you please add all JetBrains ides as PC_STYLE_BINDINGS_IGNORE_APPS by default in you next release. 

That will be very helpfull for all the JetBrain users ;)

<replacementdef>
        <replacementname>PC_STYLE_BINDINGS_IGNORE_APPS</replacementname>
        <replacementvalue>

            
            VIRTUALMACHINE,
            REMOTEDESKTOPCONNECTION,
            VNC,
            TEAMVIEWER,
            EMACS,
            TERMINAL,
            X11,
            CITRIX_XEN_APP_VIEWER,
            Wine,

            
            IntelliJ,
            PhpStorm,
            WebStorm,
            RubyMine,
            ANDROID_STUDIO,
            JetBrainsApps,
        </replacementvalue>
    </replacementdef>

**Comment by tekezo** [comment]
I think JetBrains apps follow the mac shortcuts (eg. command-zxcv).

Please override PC_STYLE_BINDINGS_IGNORE_APPS in your private.xml like this:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.PC_STYLE_BINDINGS_IGNORE_APPS/private.xml

**Comment by Zen3K** [comment]
Yes my problem was because I just import my keymap from windows and that create problems, but I understand that cannot be the default. 

Thanks for the answer.
