### ISSUE TITLE
Asus GX900

### ISSUE THREAD

**Issue by RedSoxFan04** [tekezo/Karabiner#683]
Which device vendor name do you put in the private XML file for an Asus mouse? Would you use ASUSTEK, ASUS_Computer_Inc, etc?

**Comment by tekezo** [comment]
For Asus devices, please add <devicevendordef> and <deviceproductdef> into private.xml by yourself.
(You can use any string ASUSTEK, ASUS_Computer_Inc, etc in <vendorname>.)

You can do it by this instruction.
https://pqrs.org/osx/karabiner/xml.html.en#devicedef
