### ISSUE TITLE
Better Grouping of "Change Key" options.

### ISSUE THREAD

**Issue by Z3n3K** [tekezo/Karabiner#685]
Should be great if you Name the groups of options and give the possibility of open/close these groups. That will improve a LOT the navigability!

Examples:

+ Specific Key
   +Change Arrow
   +Change Delete Key
   ...

+  Languages
   +For Belgian
   +For Spanish
   ...

+ Programming
   +Emacs Mode
   +Programmer Settings
   ...

+ PC(Windows) Users
   +Use PC Style Home/End
   +Use PC Style Copy/Paste
   ...
  

+ Apps
   + For Finder
   + For Chrome
   ...

+ Devices
   + Broken keys
   + Device Specific Mixed Settings
   ...

Thanks You.

**Comment by tekezo** [comment]
Thank you!

The next release of Karabiner will be a big change in order to support macOS Sierra.
I'm planning cleaning up the settings at that release.
I will use this issue as reference.

**Comment by Zen3K** [comment]
Thanks for the answer !

When do you plan to release the next version of the App!? I am exited about that !!
