### ISSUE TITLE
Refresh with "F5" hotkey for PC Users

### ISSUE THREAD

**Issue by Z3n3K** [tekezo/Karabiner#687]
Can you please add in the next version:

Refresh with "F5" hotkey for PC Users.

Thanks

**Comment by dunkarooftop** [comment]
```
<item>
  <name>Refresh with F5</name>
  <identifier>private.refresh.with.f5</identifier>
    
    <autogen>
        --KeyToKey--
        KeyCode::F5,

        KeyCode::R, ModifierFlag::COMMAND_L,
    </autogen>

</item>

**Comment by waldyrious** [comment]
I tried both

    <autogen>--KeyToKey-- KeyCode::F5, KeyCode::R, ModifierFlag::COMMAND_L</autogen>

and

    <autogen>--KeyToKey-- KeyCode::BRIGHTNESS_DOWN, KeyCode::R, ModifierFlag::COMMAND_L</autogen>

but neither worked :/ any tips?
