### ISSUE TITLE
"Get Info" whit Alt+Return in Finder

### ISSUE THREAD

**Issue by Z3n3K** [tekezo/Karabiner#688]
Can you please add in the next release:

- The "Get Info" action with Alt+Return in the Finder app.

Thanks

**Comment by nikitavoloboev** [comment]
You can rebind that action with BetterTouchTool or even in System Preferences I believe. 

I find BettertouchTool a better tool for hotkey rebinding tasks.

**Comment by Z3n3K** [comment]
Thanks for the answer Nikita.

BettertouchTool looks like a nice app and is easier to configure the hotkey rebinding, but you need to do all the work from scratch, in other side Karabiner already have a lot of good rebindings actions and you only need to check the ones you like.

Using the System Preferences - Keyboard is possible to do that but is the same, you need to do it for yourself and you dont have the possibility of export the configurations for the future.

**Comment by dunkarooftop** [comment]
This will do. a simple keytokey swap

```
<item>
    <name>Get info in Finder</name>
    <identifier>private.get.info.in.Finder</identifier>
    <only>FINDER</only>
    
    <autogen>
        --KeyToKey--
        KeyCode::RETURN, ModifierFlag::OPTION_L,

        KeyCode::I, ModifierFlag::COMMAND_L,
    </autogen>
</item>
