### ISSUE TITLE
Would it be possible to highlight text like in 'Visual Model' whilst in Simple Vi Mode v2 holding both s and v keys?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#689]
For example right now I can go through text with holding s and moving with hjkl. 

I would really love if I could hold both s and v together and move with hjkl to highlight text in 'visual mode'. This would save me quite a bit of keystrokes and would be an absolute joy to use. I hope you could understand what I mean and such thing would be possible to do.

Thank you so much for the work you have done on this app.

**Comment by tekezo** [comment]
Please try this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.SIMPLE_VI_MODE_EXTRA2/private.xml

It changes the v key to the shift key in Simple Vi Mode v2.
(This setting will be applied automatically after you reloaded XML.)

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by nikitavoloboev** [comment]
Wow, this is perfect. Thank you.
