### ISSUE TITLE
double click with PointingButton::LEFT?

### ISSUE THREAD

**Issue by moon0326** [tekezo/Karabiner#690]
Hello,

It looks like I should ask questions in issues...? If not please delete.

I'm using extra keys on my keyboard for mouse clicking. I'm using the following config for left click.

```
<autogen>
    __KeyToKey__ KeyCode::BRACKET_LEFT, ModifierFlag::CONTROL_L, PointingButton::LEFT
</autogen>
```

This works just fine for single click. When I double press the key though, it does not double click. I first tried to change key repeat setting, but no luck so far.

I'm aware of adding two PointingButton::LEFT, but I want this particular key works as a single click and double click.

Is there a way to use the above config for double click?

**Comment by tekezo** [comment]
This setting should be work.
You have to hold the left control key while you press { key twice.

If you release control key and press it again in double press of { key, the control key event is fired between left click event.

You can confirm the behavior in EventViewer.
(Please place your mouse pointer in Mouse Area of EventViewer.)
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by moon0326** [comment]
Hi @tekezo

Thank you for the reply. I don't think I'm following.

What should I do exactly...?

The setting obviously does not work for me.

**Comment by moon0326** [comment]
@tekezo  I got it. Is there a way to avoid holding left control?

**Comment by tekezo** [comment]
There are some ways to avoid it.
I think the most suitable way is changing holding control-{ to double click.

This autogen changes short press of control-{ to single click and long press is double click.

```xml
    <autogen>
      __HoldingKeyToKey__
      KeyCode::BRACKET_LEFT, ModifierFlag::CONTROL_L,

      <!-- short press -->
      @begin
      PointingButton::LEFT,
      @end

      <!-- hold -->
      @begin
      PointingButton::LEFT,
      PointingButton::LEFT,
      KeyCode::VK_NONE,
      @end

      Option::NOREPEAT,
    </autogen>
```

**Comment by moon0326** [comment]
@tekezo  Thank you so much. That works!

It looks like I have to hold in any cases. I assume that there is no way to make a single button acts as a single and double click at the same time..unless I hold it. Am I correct?

**Comment by tekezo** [comment]
You can do it, too.

But you want to release control key between double press.
Changing "control-{, {" to double click causes a problem that you cannot enter normal `{` after control-{.
To avoid such limitation or misoperation, I think the `__HoldingKeyToKey__` is the best way.

**Comment by moon0326** [comment]
@tekezo  Thank you. I guess there is no way to do what I initially wanted to do (use a single key to simulate mouse click without holding or pressing an extra key). I think I'm okay without double click.
