### ISSUE TITLE
I've run into a small problem with running out of hotkeys I can bind

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#691]
From what I understand, I can bind keys to four modifiers : command, option, control and shift. 

I tried binding keys to FN but that doesn't seem to work. For example I thought this would work : 

```XML
<autogen>
__KeyToKey__
KeyCode::W,
KeyCode::FN, ModifierFlag::COMMAND_L
</autogen>
```

However this doesn't seem to work. I would really love if I could use FN and all its modifiers hotkeys to which I can bind to as that will open a lot of freedom.

Thank you a lot for any help on this.

**Comment by tekezo** [comment]
Please use this autogen if you want to change the fn key to command+control+option+shift.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::FN,
      KeyCode::COMMAND_L, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Hey tekezo,

I don't think you understood me right. My problem is that I can't find keybindings to which I can bind to as I have taken space of most of my  command+control+option+shift, command+option, control+option keys and so on. I have a pretty length [private.xml](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml).

My issue is that I can't seem to bind things to FN keys themselves. It doesn't seem to work. I have tried making use of your autogen [here](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L202). You can also see that I tried using it above as well. I essentially just want to bind to FN and FN + some modifier. 

Can I do that?

**Comment by tekezo** [comment]
I might be not understand your issue, yet.

Karabiner does not support recursive modifications.
You have to extract the keys in autogen like this:
```xml
    <autogen>
      __KeyToKey__
      KeyCode::A,
      KeyCode::COMMAND_L, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Yeah, I understand. However this is not what I am looking for. I am looking to bind some key to FN so that when I press these keys, FN will activate. This : 

```XML
    <autogen>
      __KeyToKey__
      KeyCode::F, ModifierFlag::COMMAND_L,
      KeyCode::FN
    </autogen>
```

Does not work for some reason.

**Comment by tekezo** [comment]
What is the result of command-f in EventViewer?
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

**Comment by nikitavoloboev** [comment]
Here is the result : 

eventType:FlagsChanged    code:0x37       name:Command_L       flags:Cmd                                misc:KeyCode::COMMAND_L	 characters:    
eventType:FlagsChanged    code:0x37       name:Command_L       flags:                                   misc:KeyCode::COMMAND_L	 characters:    
eventType:FlagsChanged    code:0x3f       name:Fn              flags:Fn                                 misc:KeyCode::FN	 characters:    
eventType:FlagsChanged    code:0x3f       name:Fn              flags:                                   misc:KeyCode::FN	 characters:    

And in screenshot : 

![2016-08-01 at 11 29](https://cloud.githubusercontent.com/assets/6391776/17289736/4c7f9c22-57db-11e6-87cf-57cbaba7448c.png)

**Comment by tekezo** [comment]
It seems the fn key is fired.

If you want to change command-f to command-control-option-shift-f, please use this autogen:

```xml
    <autogen>
      __KeyToKey__
      KeyCode::F, ModifierFlag::COMMAND_L,
      KeyCode::F, ModifierFlag::COMMAND_L | ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
I want to bind it to FN key and have it show. This however doesn't seem to register as FN key. When I press physical FN and F1 keys together it registers as 'FN1' key. 

Here is a small screencast to perhaps show better what I mean : http://quick.as/QWAZhnL0Z

**Comment by tekezo** [comment]
For that purpose, please enable settings in this section:
https://pqrs.org/osx/karabiner/faq.html.en#fn

Or use this autogen together.

```xml
<autogen>__KeyToKey__ ConsumerKeyCode::BRIGHTNESS_DOWN, ModifierFlag::FN, KeyCode::F1</autogen>
<autogen>__KeyToKey__ ConsumerKeyCode::BRIGHTNESS_UP,   ModifierFlag::FN, KeyCode::F2</autogen>
```

Detail:
The brightness control key `ConsumerKeyCode::BRIGHTNESS_DOWN`  and fn+f1 key `KeyCode::F1` are different physical keys in Karabiner.
The command+f+f1 sends `ConsumerKeyCode::BRIGHTNESS_DOWN, ModifierFlag::FN`, so we should change it manually.

**Comment by nikitavoloboev** [comment]
I am not quite sure what you mean. 

I have activated these settings in Karabiner : 

![2016-08-01 at 12 53](https://cloud.githubusercontent.com/assets/6391776/17291923/f9d8c19a-57e6-11e6-9bfd-bf3d4e6a2656.png)

However I could not find the 'XXX to fn' setting in there wit does not come up from the search.

How do I then get something like this to work : 

```XML
     <autogen>
      __KeyToKey__
      KeyCode::F, ModifierFlag::COMMAND_L,
      KeyCode::F1, ModifierFlag::FN
     </autogen>
```

I am not really sure how to proceed.

**Comment by nikitavoloboev** [comment]
Also will running this command `open -a -g /Applications/Karabiner.app/Contents/Applications/Utilities/ReloadXML.app` reload the config? 

It doesn't seem to work for me.

**Comment by tekezo** [comment]
Do you want to send command-control-option-shift-f1 by command-f?
If so, please use this autogen.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::F, ModifierFlag::COMMAND_L,
      KeyCode::F1, ModifierFlag::COMMAND_L | ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L,
    </autogen>
```

You can reload xml from command line by either:

```
open /Applications/Karabiner.app/Contents/Applications/Utilities/ReloadXML.app
```
or 
```
/Applications/Karabiner.app/Contents/Library/bin/karabiner reloadxml
```

**Comment by nikitavoloboev** [comment]
Thank you, this is exactly what I wanted.
