### ISSUE TITLE
Getting caps lock key back as tapping fn/application key after setting it to key code 80 with seil

### ISSUE THREAD

**Issue by excetara2** [tekezo/Karabiner#692]
I want to get back the function of the caps lock key. I am fine as having it work now as `shift+escape` but I thought of two good options for the caps lock key: 

One is to map it to tapping of the fn key. I also have this set to the application key for non-mac keyboards so will cover both, but `fn` I currently have mapped to act as a normal fn when pressed with the `F1-12` keys and as `hyper` otherwise (`Control_L` is set to `79` with Seil to act as the `hyper` key). Is there a way I could get it to make `capslock` work with this when tapping `FN` and still maintain all the other functions as they are now.

The other option is keep it as `shift+escape` but make it work with caps lock set as `escape`. This is a lot easier to work with on pc keyboards as the escape key is far from shift. Basically if you press `shift_R` then tap `capslock` it will trigger `Capslock` (`Capslock` is set in Seil to key `80` and the corresponding setting in karabiner that a tap is escape and holding is control).

**Comment by tekezo** [comment]
Please use this setting.

![160801-0003](https://cloud.githubusercontent.com/assets/659178/17288576/d0b14d6c-5810-11e6-8acc-74e1544183ab.png)

**Comment by excetara2** [comment]
So there is no way to do something like the content pasted below and have both of them work properly? Or the same with the fn key. I had left shift set to `~` so prefer not to change that is why I am curious.

```
<item>
      <name>Ctrl_l to Ctrl_l and Capslock TAP (Doesn't work)</name>
      <appendix>(+ When you type Ctrl_l only, send CapsLock)</appendix>
      <identifier>remap.ctrlL2ctrlL_capslock</identifier>
      <autogen>__KeyOverlaidModifier__ KeyCode::F18, KeyCode::F18, KeyCode::CAPSLOCK</autogen>
</item>

 <item>
    <name>Remap Left Control to Hyper</name>
    <appendix>OS X doesn't have a Hyper. This maps Left Control to Control + Shift + Option + Command.</appendix>

    <identifier>space_cadet.left_control_to_hyper</identifier>

    <autogen>
        --KeyToKey--
        KeyCode::F18,

        KeyCode::COMMAND_L,
        ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L
    </autogen>
</item>
```

**Comment by tekezo** [comment]
You should join them into one autogen:

```xml
    <autogen>
      __KeyOverlaidModifier__
      KeyCode::F18,

      KeyCode::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L

      KeyCode::CAPSLOCK
    </autogen>
```

**Comment by excetara2** [comment]
Okay thanks that worked!
