### ISSUE TITLE
How would I add 'goto new line' to SimpleVIModev2?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#693]
I am talking about this little feature : 
![2016-08-01 at 21 11](https://cloud.githubusercontent.com/assets/6391776/17305786/82f1144c-582c-11e6-916b-386e9a047b6d.png)

I would love it if I could press s and hold, then press 'o' and it will goto new line. 

Thank you for any help on this.

**Comment by tekezo** [comment]
Please use this private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.SIMPLE_VI_MODE_EXTRA3/private.xml


(This setting will be applied automatically after you reloaded XML.)

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by nikitavoloboev** [comment]
Thank you, this works great. ♥
