### ISSUE TITLE
Shift+Option+<Right> no regonized

### ISSUE THREAD

**Issue by blacknosugar** [tekezo/Karabiner#694]
Even on a fresh install with no keys changed **Shift+Option+Right** is not recognised. Not system-wide nor in EventViewer.

Shift+Right works, Option+Right works. Shift+Option+Left works.

Is it just me?

**Comment by tekezo** [comment]
I guess that this issue is a hardware limitation "2-key rollover".
https://pqrs.org/osx/karabiner/faq.html.en#rollover

What physical keys did you assign shift and option?

**Comment by blacknosugar** [comment]
I switched Command and Option. But doesn't make a difference. Same with no keys changed.

The moment I quit Karabiner, Shift+Option+Right does what it is supposed to do. Re-opened  Karabiner, the same keys are not even recognised in Karabiner's EventViewer.

**Comment by tekezo** [comment]
I cannot reproduce your issue.
Please confirm no keys changed in Karabiner.
(Check Karabiner Preferences with "show enabled only" checkbox.)

And could you show me the debug log when you press shift+option+right?
https://pqrs.org/osx/karabiner/document.html.en#debugmode
