### ISSUE TITLE
I want to add autogens for MOUSE_MODE

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#695]
I thought this syntax would work : 

```XML
  <replacementdef>
    <replacementname>MOUSE_MODE_EXTRA</replacementname>
    <replacementvalue>
      <![CDATA[

               <autogen>
                   __KeyToKey__
                   KeyCode::A,
                   KeyCode::T, ModifierFlag::COMMAND_L
                </autogen>

               ]]>
               ]]>
    </replacementvalue>
  </replacementdef>
```

Perhaps MOUSE_MODE_EXTRA should be something different.

**Comment by nikitavoloboev** [comment]
Also would it be possible to move my cursor to a certain location on screen from one of these auto gents. For example I would like to hold 'd' key and press 'a' and my mouse pointer will move to centre of the screen. 

Something like this would be really incredible to have. Thank you.

**Comment by tekezo** [comment]
Please use `MOUSE_KEYS_MODE_2_EXTRA`.

```xml
  <replacementdef>
    <replacementname>MOUSE_KEYS_MODE_2_EXTRA</replacementname>
    <replacementvalue>
      ....
    </replacementvalue>
  </replacementdef>
```

You can warp cursor from a command line utility.
```
/Applications/Karabiner.app/Contents/Library/utilities/bin/warp-mouse-cursor-position screen 0 middle +0 center +0
```

So, you can use `KeyCode::VK_OPEN_URL_SHELL_warp_mouse_cursor_position_screen_center_0`.
https://github.com/tekezo/Karabiner/blob/version_10.21.0/src/core/server/Resources/vkopenurldef.xml#L420

```xml
  <replacementdef>
    <replacementname>MOUSE_KEYS_MODE_2_EXTRA</replacementname>
    <replacementvalue>
      <![CDATA[
               <autogen>
                 __KeyToKey__
                 KeyCode::A,
                 KeyCode::VK_OPEN_URL_SHELL_warp_mouse_cursor_position_screen_center_0,
               </autogen>
               ]]>
    </replacementvalue>
  </replacementdef>
```

**Comment by nikitavoloboev** [comment]
Thank you. This works really great. 

I just noticed that if you hold s while holding d you can move scrollbar up and down. However for some reason, j moves scrollbar up and k moves scrollbar down which is very unintuitive. Is it possible to change it and swap this around?

**Comment by tekezo** [comment]
The scroll direction is affected System Preferences > Mouse or Trackpad > Scroll direction.
Please enable this setting in Karabiner.
![160803-0001](https://cloud.githubusercontent.com/assets/659178/17369022/7e63f06a-59d1-11e6-85f9-92378bbd6c0a.png)

**Comment by nikitavoloboev** [comment]
Thank you. This works.
