### ISSUE TITLE
Bug: Hold "o" key does not work (ôöòóœøōõ) if Launcher Mode v2 (Open apps by shortcut keys) is enable.

### ISSUE THREAD

**Issue by Z3n3K** [tekezo/Karabiner#697]
Bug: if Launcher Mode v2 (Open apps by shortcut keys) is enable then when you hold the "o" key the menu with the differents "o" types (ôöòóœøōõ) does not appear.

**Comment by tekezo** [comment]
It's an intended behavior.
Please change the trigger key by private.xml:
https://github.com/tekezo/Files/blob/master/Karabiner/replacementdef.LAUNCHER_MODE_V2_KEY_2/private.xml
