### ISSUE TITLE
question about binding consumer keys

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#700]
I want to bind a key to one of the top keys, in my case (play next song). I found this [page](https://github.com/tekezo/Karabiner/blob/version_10.21.0/src/bridge/generator/keycode/data/ConsumerKeyCode.data). Then I tried this : 

```XML
        <autogen>
      __KeyToKey__
      KeyCode::K,
      KeyCode::MUSIC_NEXT
      </autogen>
```

This however doesn't work. Perhaps this is not the way you have to use this.

**Comment by tekezo** [comment]
The media control keys are `ConsumerKeyCode`.
Please use this autogen.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::K,
      ConsumerKeyCode::MUSIC_NEXT
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Thank you, a lot. Just one more question, I could not find it in the documentation. How do you assign something to turn on and off caps lock key?

I suppose since I have changed it with Seil : 

[](http://i.imgur.com/GT52fQm.png)


I would need to then bind it to that key code. It's just that I use that key [here](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L2675) so I am not sure.

Perhaps I should use something like this?

```XML
        <autogen>
      __KeyToKey__
      KeyCode::R,
      KeyCode::80
      </autogen>
```

**Comment by tekezo** [comment]
The Seil setting are applied before Karabiner.
https://pqrs.org/osx/karabiner/document.html.en#event-modification-chaining

You have to change key to KeyCode::CAPSLOCK in Karabiner like this.

```xml
    <autogen>
      __DoublePressModifier__
      KeyCode::SHIFT_L,
      KeyCode::SHIFT_L,
      KeyCode::CAPSLOCK,
    </autogen>
```

**Comment by nikitavoloboev** [comment]
Thank you a lot, this works perfectly.
