### ISSUE TITLE
Assigning "enter" to "ù" key

### ISSUE THREAD

**Issue by gioialorusso** [tekezo/Karabiner#701]
Hi,
I'm trying to remap the ù key in enter key, because they are near in my new keyboard and I always press the ù key insetad of the enter key. I just cannot figure out what KEYCODE has the ù key, in order to write a custom rule in the private.xml files. Could you help me out? I attach a pic of the keyboard, highlighting what key I'd like to change. Thank you!
![img_20160808_143439](https://cloud.githubusercontent.com/assets/1935078/17479921/a3fb93d0-5d75-11e6-91aa-78d3d5793901.jpg)

**Comment by tekezo** [comment]
I guess it KeyCode::BACKSLASH.

Please try this setting.
![160810-0001](https://cloud.githubusercontent.com/assets/659178/17541808/3cd14df0-5efe-11e6-839d-a044d4314297.png)


If it does not work, you can investigate this key code in EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer

Please open OS X's Keyboard Viewer and type ù key in EventViewer.
https://support.apple.com/kb/PH21565

**Comment by gioialorusso** [comment]
Thank you, backslash to return worked perfectly.
Have a good day,
Gioia
