### ISSUE TITLE
way to have key that does warp mouse pointer to the current cursor position?

### ISSUE THREAD

**Issue by LynnWalton** [tekezo/Karabiner#705]
Is there a way to have key that does warp mouse pointer to the current cursor position?
I'm using both TouchCursor settings and MouseKeys 2 settings and I find this would help me a lot. 

Thanks,
Lynn

**Comment by tekezo** [comment]
Unfortunately, there is not a way to do.
(We can warp the mouse cursor, but we cannot detect the current cursor position.)
