### ISSUE TITLE
Simulate modifier key press autogen?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#706]
I would like to add few autogens to Mouse Keys Mode v2 if I can.

I want to make it so that when I hold 'd' key together with 'b' key, it would simulate a mouse click with 'control' modifier. This would be very useful for me especially in program like Xcode where I have to drag things while holding the control modifier. There was no place in the documentation where I could find how to do such a thing.

I would really appreciate any help on this. Thank you a lot once again for such a wonderful piece of software.

**Comment by dunkarooftop** [comment]
open file "/Applications/Karabiner.app/Contents/Resources/include/checkbox/mouse_keys.xml"

add below to line around 103 seems like a good spot ( any where between line 97 to 216 will do. )

change all the <identifier> name with prifix "private." and save it to where your private.xml file folder. Then add <include> in private.xml file to point to the new mouse xml file. This way when ever the software update you won't lose your setting. key "B" is taken for "middle mouse click", I use "A" here for your "control" key. You can edit to fit your need maybe swap the "A" and "B" key.  

`      
      <autogen>__KeyToKey__
        KeyCode::A,

        KeyCode::CONTROL_R, ModifierFlag::MOUSE_KEYS_MODE_2
      </autogen>`

**Comment by tekezo** [comment]
You can use MOUSE_KEYS_MODE_2_EXTRA to add key binds.
Example:
https://github.com/tekezo/Files/blob/master/Karabiner/private.mouse_keys_mode_v2_ijkl/private.xml
