### ISSUE TITLE
tilde

### ISSUE THREAD

**Issue by GrouchyGaijin** [tekezo/Karabiner#707]
My Swedish keyboard does not have a tilde key.  What is the keycode for a tilde which is usually triggered by shift+esc on a PC with a US English layout?

**Comment by dunkarooftop** [comment]
"BACKQUOTE" ?

full keycode can be found here
https://github.com/tekezo/Karabiner/blob/master/src/bridge/generator/keycode/data/KeyCode.data

**Comment by ProbonoBonobo** [comment]
BACKQUOTE =>  ` 

Which isn't a tilde (~), and there's no tilde in the KeyCode.data file you referenced. 

After a bunch of fruitless searching, and feeling utterly confused at the previous comment, the answer suddenly came to me when I saw a picture of a standard 82-key US Keyboard. And then it hit me: _backtick and tilde are on the same key!_.  So the missing piece of information in the previous comment is that Shift + Backquote = Tilde, which isn't obvious if you don't have the tilde/backquote key. Sure enough this does the trick on my tiny 61-key:

```
<item>
    <name> [ user ] Make: Tilde           From: [ Opt [ . ] ] </name>
    <identifier>private.tildeFromOptDot</identifier>
    <autogen>
        __KeyToKey__ KeyCode::DOT, ModifierFlag::OPTION_L, KeyCode::BACKQUOTE, ModifierFlag::SHIFT_L
    </autogen>
</item>
```

Is there something about the tilde character itself that would make it challenging to add to the symbol table? Someone with a standard US keyboard might be able to deduce the answer on her own, but keep in mind that a lot of the people who need a custom tilde rule are trying to extend the capabilities of a keyboard that doesn't have one. This person will have no idea that tilde is a shifted backquote.

**Comment by tekezo** [comment]
You can confirm the KeyCode in EventViewer.
https://pqrs.org/osx/karabiner/document.html.en#eventviewer
