### ISSUE TITLE
Mouse Keys Mode v2 Down+Left

### ISSUE THREAD

**Issue by jsilve24** [tekezo/Karabiner#709]
First off, thank you for the work on this package it is really fantastic. 

I have come to really like Mouse Keys Mode v2 but have noticed that holding d+h+j does not make the cursor move down and to the left. Other diagonals work (e.g., d+k+l moves up and to the right) but down and left for some reason is not working. 

I would very much appreciate advice as to how to fix this. 

Thank you,
Justin

**Comment by nikitavoloboev** [comment]
This is strange, I have it working for me.

**Comment by jsilve24** [comment]
Strange, I just noticed that its only a problem with my external keyboard and not my internal keyboard.
