### ISSUE TITLE
Karabiner is not working on sierra!!!  Changed delete key to forward delete and assigned '`' key for forward delete 

### ISSUE THREAD

**Issue by manojfedx** [tekezo/Karabiner#711]
I changed delete key to forward delete and assigned ` key for forward delete. This is like single stroke delete key. And I used Karabiner to set forward delete to move to trash.
Now Karabiner is not working on  sierra and i couldnt move my file to trash. Please i need help! Is there any other alternative! Right now I gave Fn+` as forward delete which will move my files to trash.
But i want single stroke delete back again! When will karabiner be updated for sierra!

**Comment by pzuraq** [comment]
See #660, he's working on it, there have been some major changes in Sierra so it's going to take a while.

**Comment by tekezo** [comment]
#660

You can use Karabiner-Elements for this purpose.
https://github.com/tekezo/Karabiner-Elements

**Comment by manojfedx** [comment]
Ah! Thanks a lot lot tekezo for all your effort!
