### ISSUE TITLE
ScrollWheelToScrollWheel and FlipScrollWheel didn't works together in one item.

### ISSUE THREAD

**Issue by quaritexa** [tekezo/Karabiner#712]
I need change alt-wheel vertical to command-wheel vertical and flip wheel direction at once.

```
<only>SKETCH</only>
<modifier_only>ModifierFlag::OPTION_L</modifier_only>
<autogen>__ScrollWheelToScrollWheel__ ModifierFlag::OPTION_L, ModifierFlag::COMMAND_L</autogen>
<autogen>__FlipScrollWheel__ Option::FLIPSCROLLWHEEL_VERTICAL</autogen>
```

**Comment by tekezo** [comment]
Unfortunately, you cannot combine multiple autogens at the same time.

**Comment by quaritexa** [comment]
Will it be possible in the future?

**Comment by tekezo** [comment]
I would like to do in the future.
However it is not soon since there are other high priority tasks (Sierra support).
