### ISSUE TITLE
Fn to center of display only works with HW key

### ISSUE THREAD

**Issue by Grazfather** [tekezo/Karabiner#714]
On my MBP I use a normal keyboard which doesn't have `Fn`. I enabled the option to turn `Command_R` to `Fn`, which works according to the event viewer, but I guess this 'center' feature checks before the conversion.

**Comment by tekezo** [comment]
The prepared setting is designed for built-in fn key.

Please make a custom setting by private.xml:
https://github.com/tekezo/Karabiner/blob/version_10.21.0/src/core/server/Resources/include/checkbox/custom_shortcuts.xml#L170-L185
(Replace FN with COMMAND_R)
