### ISSUE TITLE
Feature request: More buttons that can be used to center the cursor

### ISSUE THREAD

**Issue by Grazfather** [tekezo/Karabiner#715]
The options are all on the mouse (where all my buttons are used) or on the right side of the keyboard. I would like a key I can hold on the left side of the keyboard (like maybe shift_l) that I can hold, that way I don't have to move my right hand from the mouse.

**Comment by dunkarooftop** [comment]
which default setting are you talking about

**Comment by tekezo** [comment]
You can add it by private.xml.
#714
