### ISSUE TITLE
Switching number keys with the symbols

### ISSUE THREAD

**Issue by onselakin** [tekezo/Karabiner#716]
In Karabiner settings we can set up the number row for the symbols, in Programmer's Keyboard if I recall correctly. If we do this we can't use the numbers anymore. Is there a way to use the top row for symbols and at the same time access to numbers when typed with shift? 

Basically what I want to achieve is:
When I type 1, I get !,
When I type Shift + 1, I get 1.

**Comment by dunkarooftop** [comment]
<autogen>
  __KeyToKey__
  KeyCode::1, ModifierFlag::NONE,
  KeyCode::1, ModifierFlag::SHIFT_L
</autogen>

<autogen>
  __KeyToKey__
  KeyCode::1, ModifierFlag::SHIFT_L, 
  KeyCode::1,
</autogen>

more detail doc at
https://pqrs.org/osx/karabiner/xml.html.en
scroll down to "Modifier+Key to Key"  : )

**Comment by dunkarooftop** [comment]
<autogen>
  __KeyToKey__
  KeyCode::1, ModifierFlag::NONE,
  KeyCode::1, ModifierFlag::SHIFT_L
</autogen>

<autogen>
  __KeyToKey__
  KeyCode::1, ModifierFlag::SHIFT_L, 
  KeyCode::1,
</autogen>

more detail doc at
https://pqrs.org/osx/karabiner/xml.html.en
scroll down to "Modifier+Key to Key"  : )

actually I went take a look at the prepared setting "the ones that come with Karabiner by default" with what you want to archive. its under "Change num keys", "Swap numbers and symbols"

If you gonna change to that way search "home row number overlay" too when you hold space bar your home row become 1, 2, 3...... save you travel all the way up for numbers.

**Comment by onselakin** [comment]
Thanks @dunkarooftop.
I missed the "Swap numbers and symbols" setting. It did the trick!

Actually the home row with space + numbers is a very nice idea but while typing quickly I put numbers all over the place :-)
