### ISSUE TITLE
Is it possible to write out short and long presses in launcher mode?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#719]
For example I hold w and press k briefly, this does one action, I press it longer, it does another. 

Can I do that?

**Comment by dunkarooftop** [comment]
I would suggest that you set it up as tap "k" (1st action) and tap "k", "k" (2nd action) for both actions. In this sticky key mode setup you only feel slight delay if you want to activate the 1st action (with single "k" tap, because its waiting to see if there is any more following key command) and the 2nd action will spring right into action when you release the 2nd "k" which feel super snappy.  It's just a better user experience. Having to hold down a key and wait it not that fun in practice.

**Comment by dunkarooftop** [comment]
If you really wanna do tap and holding key do different thing there is a easier way with **__HoldingKeyToKey__** You actually bypass the sticky mod, one less key to press and hold on.

Doc here.
https://pqrs.org/osx/karabiner/xml.html.en#syntax-__HoldingKeyToKey__

You can also use with <only> app </only> to map for different apps, but I still think it's not as good a experience. The delay to wait for a key to do thing. that 200ms really feels like forever : )

**Comment by nikitavoloboev** [comment]
Thank you,

Can you give me an example of 'k' k' as two actions. I am not quite sure I get how to write it out properly.

**Comment by dunkarooftop** [comment]
Just finish writing you the email for your request tweak, the example in side has what you ask for here with "sticky key mod" :)

**Comment by nikitavoloboev** [comment]
Hey Dunk,

I still am not quite sure how to make this short / long press work within a sticky key. Can you give me an example please?

I would love to do it for my i key [here](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L2685). If I press and hold space, it would send cmd + a. 

Thank you.

**Comment by dunkarooftop** [comment]
to be clear that you want to set your "i" as sticky key and while holding down "i" and holding "space" to be cmd+a ? or holding down "i" tap "space" to be cmd+a

right now you have holding "i" tap "space" to be "ctrl+option+space" and you want holding "i" and space together to do "cmd+a" on top of it?

you can try "SimultaneousKeyPresses"
https://pqrs.org/osx/karabiner/xml.html.en#syntax-__SimultaneousKeyPresses__

```
<autogen>
  __SimultaneousKeyPresses__
  KeyCode::I, KeyCode::SPACE,

  KeyCode::A, ModifierFlag::COMMAND_L,
</autogen>
```

I am not sure if it would conflict with your sticky "i" mode. You might wanna try place it before or after the sticky "i". "cmd+a" is a very simple keystroke and easier to do than holding both "i" and "space" not sure why you would do this replacement. Also breaking down your XML and use `<include>` in private.xml would make it easier to manage the mods. :)

**Comment by dunkarooftop** [comment]
actually just test it turn out you can also use "HoldingKeyToKey" in side sticky mode. Replace your space setting with 

```
<autogen>
  __HoldingKeyToKey__
  KeyCode::SPACE,

  <!-- short press -->
  @begin
  KeyCode::SPACE, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L
  @end

  <!-- hold -->
  @begin
  KeyCode::A, ModifierFlag::COMMAND_L
  @end

  Option::NOREPEAT,
</autogen>
&&&

**Comment by dunkarooftop** [comment]
skimming thru your XML, I am guessing you are assign a lots of hotkey to trigger "Keyboard Maestro" and "Alfred" workflow or opening apps, there is better way to do it without using a single hotkey too

**to launch apps**
https://pqrs.org/osx/karabiner/xml.html.en#vkopenurldef

**to trigger "Keyboard Maestro" via applescript**
https://www.keyboardmaestro.com/documentation/6/triggers.html
at the end of the page
```
tell application "Keyboard Maestro Engine"
  do script "[Name or UID of Your Macro]"
end tell
```

**to trigger "Alfred" via applescript**
https://www.alfredapp.com/help/workflows/triggers/external/

**Comment by nikitavoloboev** [comment]
Oh this is actually really great. I've been thinking of what I would do when I will run out of hotkeys to bind. Calling externally these scripts would solve this. Thank you.
