### ISSUE TITLE
Help remapping volume keys to M, <, > via Karabiner

### ISSUE THREAD

**Issue by Dakine234** [tekezo/Karabiner#720]
Aloha,

If anyone has help and input it would be greatly appreciated!  New to remapping and using karabiner.  My goal here is to remap my mute, volume down and volume up keys to M, < and > respectively.  My modifier keys would be Shift left + Command left + ______ (remapped key).

Heres what my coding looks like in my private doc

`</item>
	<name> Volume Key Adjust: Cmd + Shift + M<> </name>
        <identifier>private.coolaj86_cmd_shift_volume</identifier>
        <autogen>
            __KeyToKey__ 
            KeyCode::M,
            ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
            KeyCode::VOLUME_MUTE
        </autogen>
        <autogen>
            __KeyToKey__ 
            KeyCode::COMMA,
            ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
            KeyCode::VOLUME_DOWN
        </autogen>
        <autogen>
            __KeyToKey__ 
            KeyCode::DOT,
            ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
            KeyCode::VOLUME_UP
        </autogen>
</item>
`
![image](https://cloud.githubusercontent.com/assets/21992202/18234532/f53ca75e-72a4-11e6-862f-fb82fff6e592.png)

**Comment by dunkarooftop** [comment]
You mix up the order of the key, full doc can be found here about keytokey
https://pqrs.org/osx/karabiner/xml.html.en#keytokey-syntax

The following code should work :)

```
</item> 
<name> Volume Key Adjust: Cmd + Shift + M<> </name> 
<identifier>private.coolaj86_cmd_shift_volume</identifier> 

<autogen> 
__KeyToKey__ 
<!-- from -->
KeyCode::VOLUME_MUTE,
<!-- to -->
KeyCode::M, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L, 
</autogen> 

<autogen> 
__KeyToKey__ 
KeyCode::VOLUME_DOWN, 
KeyCode::COMMA, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
</autogen> 

<autogen> 
__KeyToKey__ 
KeyCode::VOLUME_UP,
KeyCode::DOT, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,  
</autogen> 
</item>

**Comment by Dakine234** [comment]
@dunkarooftop Mahalo!  Unfortunately iʻm getting an error indicating: that there is an error in the XML.  </Users/JustinB/Library/Application Support/Karabiner/private.xml>(1): expected <

Also, I have another code that iʻm using to change the JKLI to arrow keys, could this be conflicting?   I tried running each separately, and the code for the arrow keys work fine, but once the volume keys are added, it gives the error above.  Any advice?  Iʻll attach my entire code below.  Thank you very much!!!

`<item>
        <name>Home Row Arrow Keys: Cmd + Shift + IJKL to ^&lt;&gt;v</name>
        <identifier>private.coolaj86_cmd_shift_homerowarrows</identifier>
        <autogen>
            __KeyToKey__ 
            KeyCode::I,
            ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
            KeyCode::CURSOR_UP
        </autogen>
        <autogen>
            __KeyToKey__ 
            KeyCode::J,
            ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
            KeyCode::CURSOR_LEFT
        </autogen>
        <autogen>
            __KeyToKey__ 
            KeyCode::K,
            ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
            KeyCode::CURSOR_DOWN
        </autogen>
        <autogen>
            __KeyToKey__ 
            KeyCode::L,
            ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
            KeyCode::CURSOR_RIGHT
        </autogen>
</item>

</item> 
	<name> Volume Key Adjust: Cmd + Shift + M<> </name> 
	<identifier>private.coolaj86_cmd_shift_volume</identifier> 
	<autogen> 
		__KeyToKey__ 
		
		KeyCode::VOLUME_MUTE,
		
		KeyCode::M, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L, 
	</autogen> 
	<autogen> 
		__KeyToKey__ 
		KeyCode::VOLUME_DOWN, 
		KeyCode::COMMA, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
	</autogen> 
	<autogen> 
		__KeyToKey__ 
		KeyCode::VOLUME_UP,
		KeyCode::DOT, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,  
	</autogen> 
</item> `

<img width="477" alt="screen shot 2016-09-07 at 9 30 58 pm" src="https://cloud.githubusercontent.com/assets/21992202/18340771/8ce76acc-7542-11e6-99b7-66fc9a2addac.png">

**Comment by dunkarooftop** [comment]
a few typo from my earlier code. Here is a tested working one.

```
<item> 
<name> Volume Key Adjust: Cmd + Shift + M</name> 
<identifier>private.coolaj86_cmd_shift_volume</identifier> 

<autogen> 
__KeyToKey__ 
<!-- from -->
ConsumerKeyCode::VOLUME_MUTE,
<!-- to -->
KeyCode::M, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L, 
</autogen> 

<autogen> 
__KeyToKey__ 
ConsumerKeyCode::VOLUME_DOWN, 
KeyCode::COMMA, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,
</autogen> 

<autogen> 
__KeyToKey__ 
ConsumerKeyCode::VOLUME_UP,
KeyCode::DOT, ModifierFlag::SHIFT_L | ModifierFlag::COMMAND_L,  
</autogen> 
</item>

**Comment by Dakine234** [comment]
Mahalo @dunkarooftop but it still does not seem to work, i may have some conflicting code thats preventing it from working.  Thank you very much for your help though!

**Comment by dunkarooftop** [comment]
Do you get error while reloading XML or it load ok but not work as expected ? If XML load ok. Open Karaniner go to last page and open Event Viewer try it there see what keycode get out put
