### ISSUE TITLE
Karabiner completely disables my keyboard

### ISSUE THREAD

**Issue by Phyks** [tekezo/Karabiner#722]
Hi,

I wanted to swap Ctrl_L and Fn keys and Karabiner seems to be able to do the job just fine.

Though, whenever I start it, I cannot type anything, my keyboard simply looks disabled. As soon as I quit Karabiner, it works again. I use the default config (no options modified at the moment).

I am running OSX El Capitan on a Macbook Pro Retina.

Thanks!

**Comment by tekezo** [comment]
I guess you are using another keyboard driver which is conflicted with Karabiner.
Please check apps and drviers you are installed.

**Comment by Phyks** [comment]
I do not use any other keyboard driver or app, actually my Mac is quite out of the box. I do not see anything which could potentially conflict with Karabiner :/

**Comment by tekezo** [comment]
There are some implicit drivers such as antivirus softwares.
You can confirm the installed kernel extension (drivers) by executing this command in Terminal.

```
kextstat | grep -v com.apple
```

**Comment by Phyks** [comment]
I get 

```
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  144    0 0xffffff7f831d9000 0x29000    0x29000    org.pqrs.driver.Karabiner (10.21.0) 0857A9A2-EC66-3C69-8403-2C21B732C140 <31 5 4 3 1>
  147    3 0xffffff7f83202000 0x61000    0x61000    org.virtualbox.kext.VBoxDrv (5.1.6) 2432AE53-EC50-36E5-B33B-799910A80FB2 <7 5 4 3 1>
  149    0 0xffffff7f83263000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (5.1.6) 4F861754-8C13-3623-BE58-893A2303341D <148 147 40 7 5 4 3 1>
  150    0 0xffffff7f8326b000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (5.1.6) 89A8D50A-DB9F-34B7-B1D0-20E305507610 <147 7 5 4 3 1>
  151    0 0xffffff7f83270000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (5.1.6) C1DDA422-665A-316D-AD52-FA64268ADA2C <147 5 4 1>
```

Looks like it can be conflicting with Virtualbox? Even no virtual machine are running?

**Comment by tekezo** [comment]
Thank you.
Virtualbox works well with Karabiner, so there is another cause.
However, I have no idea for another possible cause.

Unfortunately, please uninstall Karabiner from uninstaller.
https://pqrs.org/osx/karabiner/document.html.en#uninstall

Karabiner-Elements also allows you to swap fn and control.
It uses another approach to modify input events.
Thus, it might work on your machine.
https://github.com/tekezo/Karabiner-Elements
