### ISSUE TITLE
Key code for HHK Eject

### ISSUE THREAD

**Issue by tchajed** [tekezo/Karabiner#725]
It seems like there's no KeyCode or ConsumerKeyCode listed for `0x5a`, which is what the Happy Hacking Keyboard sends for Eject when in Macintosh mode. Could it be added as another ConsumerKeyCode? Alternately, is there a way to list a literal key code in an `<autogen>`?

* OS X version: 10.10.5 (Yosemite)
* Karabiner version: 10.21.0
* Hardware: MacBook Pro 2014
* Keyboard: Happy Hacking Keyboard Professional 2, with mode Macintosh (sw1+sw2 set to off+on)

**Comment by dunkarooftop** [comment]
Yes, you can use raw value

https://pqrs.org/osx/karabiner/xml.html.en#rawvalue

example from the doc.

```
<?xml version="1.0"?>
<root>
  <item>
    <name>Change right option key to tab key</name>
    <identifier>private.right_option_key_to_tab_key</identifier>
    <!-- change right option key (0x3d) to tab key (0x30) -->
    <autogen>__KeyToKey__ KeyCode::RawValue::0x3d, KeyCode::RawValue::0x30</autogen>
  </item>
</root>
```

**Comment by tchajed** [comment]
Awesome - sorry for not noticing that in the documentation!
