### ISSUE TITLE
Private.xml not working

### ISSUE THREAD

**Issue by marcinlbl** [tekezo/Karabiner#727]
Hello,
I have a japanese keyboard and did a custom private.xml file, like this:

`<?xml version="1.0"?>
<root>
  <item>
    <name>backquote</name>
    <identifier>private.eisuu_to_backquote</identifier>
    <autogen>__KeyToKey__ KeyCode::JIS_EISUU, KeyCode::BACKQUOTE</autogen>
  </item>
</root>`

Unfortunately this code not working. Do you have any idea why?

**Comment by dunkarooftop** [comment]
the XML do looks right.. can you go to last page of Karabiner and open "event viewer" and see what out put it do when you click the JIS_EISUU key
