### ISSUE TITLE
[Question]Is it posible to remap trackpad pinch and vertical scroll gestures while they are performed?

### ISSUE THREAD

**Issue by rraallvv** [tekezo/Karabiner#728]
I got here because of [this question](http://apple.stackexchange.com/q/252710/36642), where they suggest that Karabiner could be used to remap the trackpad gestures like so:

> ...on Photoshop take a two finder swapping gesture (vertical scroll) as if it where a pinching gesture, otherwise take it as is. Also change the two finger drag gesture while clicking by the two finger drag without clicking.

**Comment by dunkarooftop** [comment]
Better Touch Tool can do it

https://www.boastr.net/

It's amazing app working with trackpad

**Comment by tekezo** [comment]
Karabiner does not support Trackpad gestures.
Please use Better Touch Tool.
