### ISSUE TITLE
Help Mapping a Mouse Key That Shows up as CMD

### ISSUE THREAD

**Issue by Sav0ia** [tekezo/Karabiner#730]
Hello :)
Thanks for reading!

I have a Logitech M557 Mouse that I'm using on my Mac.  I uninstalled the Logitech software and am using BTT for my mapping.  

But there's one specific button it cannot map or even detect. Thankfully Karabiner detected it.
It is the square button underneath the scroll wheel.

When using the event viewer it shows up as  
eventType:FlagsChanged    code:0x37       name:Command_L       flags:Cmd                                misc:KeyCode::COMMAND_L	 characters:    
eventType:FlagsChanged    code:0x37       name:Command_L       flags:                                   misc:KeyCode::COMMAND_L	 characters:    

From what I read this means it's sending a windows signal that mac maps as CMD?

I would like to make this button map to **Launchpad**.  I'm on 10.9.5
The mouse is listed as

Pointing
    Bluetooth Mouse M557 (Unknown)

    DeviceVendor::RawValue::0x046d,
    DeviceProduct::RawValue::0xb010,

I tried writing to the xml using a Logitech mouse script I found but it did not work ^-^''

Some help would be great!

Thank you again for reading!

**Comment by dunkarooftop** [comment]
fallow the doc here to find out your mouse id and replace line 4

https://pqrs.org/osx/karabiner/xml.html.en#inputsourceid

```
  <inputsourcedef>
    <name>Logitech_M557_Mouse</name>
    <!-- Read the doc to find out the input source id from Eventviewer and replace the line below -->
    <inputsourceid_prefix>YOUR DEVICE ID HERE</inputsourceid_prefix>
  </inputsourcedef>

  <item>
    <name>Swap Space and Tab</name>
    <identifier>private.mouse.cmd.to.launchpad</identifier>

    <inputsource_only>Logitech_M557_Mouse</inputsource_only>

    <autogen>
    	__KeyToKey__
    	KeyCode::Command_L,

    	KeyCode::LAUNCHPAD,
    </autogen>
  </item>
```

**Comment by Sav0ia** [comment]
Thanks for your reply :)
I tried your script but it seemed to change my actual CMD left button on my keyboard as well.

So after some playing around I wrote this:


<?xml version="1.0"?>
<root>
  <devicevendordef>
    <vendorname>Unknown</vendorname>
    <vendorid>0x046d</vendorid>
  </devicevendordef>
  <item>
    <name>Mouse CMD to LAUNCHPAD</name>
    <identifier>private.mouse.cmd.to.launchpad</identifier>
    <device_only>DeviceVendor::Unknown</device_only>
    <autogen>
        __KeyToKey__
        KeyCode::COMMAND_L,
        KeyCode::LAUNCHPAD,
    </autogen>
  </item>
</root>


It's fixed :D Thanks
