### ISSUE TITLE
Is it possible to remap holding of right + left mouse buttons?

### ISSUE THREAD

**Issue by muhaos** [tekezo/Karabiner#731]
I have tried to accomplish it by using of __SimultaneousKeyPresses__
But in this case remapping works only if both buttons pressed at the same time. But what about if right button was pressed first and then after some time left button was pressed also?

**Comment by tekezo** [comment]
Please use this autogens:

```xml
    <autogen>
      __KeyOverlaidModifier__
      PointingButton::RIGHT,
      KeyCode::VK_MODIFIER_BUTTON2,
      PointingButton::RIGHT,
    </autogen>
    <autogen>
      __KeyToKey__
      PointingButton::LEFT, ModifierFlag::BUTTON2,
      KeyCode::MISSION_CONTROL,
    </autogen>
```
