### ISSUE TITLE
trackman marble setup?

### ISSUE THREAD

**Issue by filipgoc** [tekezo/Karabiner#735]
Hi, 
sorry if this is obvious, but I can't get the trackman marble to work on El Capitan. 
My wrist pain appreciates your help!
---

The scrolling does not work. I presume it's something to do with the Logitech Control Center setup.
What should the buttons be assigned as under Logitech Control Center?

here're my Logitech AND karabiner prefs: 

<img width="628" alt="screen shot 2016-09-26 at 4 13 28 pm" src="https://cloud.githubusercontent.com/assets/16858474/18850147/316761a4-8404-11e6-8a9b-6dca7d6e4178.png">

**Comment by tekezo** [comment]
You have to pass the button4 and button5 events to Karabiner, but LCC changes these events before Karabiner.

Please do either of the follows.

1. Uninstall LCC.
2. Configure `Mini Left Button` to `Button4` and `Mini Right Button` to `Button5` in LCC.
