### ISSUE TITLE
Please add documentation on Sierra uninstall

### ISSUE THREAD

**Issue by jtara** [tekezo/Karabiner#736]
Can you please add documentation on how to uninstall on MacOS Sierra?

The uninstall is normally done from inside the app. If I had known it would not work on Sierra, I would have uninstalled before upgrading. But I didn't know, and so now don't know how to uninstall.

I'd imagine it's more than simply moving the application to the trash.

MANY people will be in the same boat, so can you please add some prominent documentation on how to remove after Sierra update?

**Comment by Caf** [comment]
I agree it could be useful (if needed, dunno if next one will patch or replace this version).

**Comment by mhumeSF** [comment]
![screen_shot_2016-10-03_at_10_07_04_pm](https://cloud.githubusercontent.com/assets/1088457/19063295/510de7a0-89b6-11e6-9fd2-c86e2468d5a6.png)

Isn't this done from inside that app, with said [documentation available via the site](https://pqrs.org/osx/karabiner/document.html.en)? Are you saying the uninstall does not work for you?

**Comment by jtara** [comment]
The app doesn't run on Sierra. Catch-22!

If I had known it won't run on Sierra, I would have uninstalled it before upgrading to Sierra...

**Comment by mhumeSF** [comment]
Have you tried updating the app via brew? I have the app running in macOS Sierra. Just that the keyboard shortcuts do not work.
