### ISSUE TITLE
Why do KeyCodes after 'KeyCode::ESCAPE' do not work?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#737]
I have this xml in the config file : 

```XML
               <autogen>
                 __KeyToKey__
                 KeyCode::O,
                 KeyCode::ESCAPE,
                 KeyCode::O
               </autogen>
```
I want to simulate vim's 'O' in insert mode but for some reason it doesn't work. I know karabiner elements is being worked on now but if someone can help me make this work, it would be really great.

Thank you for any help.

**Comment by nkgm** [comment]
Not sure about your setup, but your mapping works fine on my system (`Escape` event sent normally as `Shift+Escape` as expected, but vim doesn't seem to mind).
