### ISSUE TITLE
[Feature] Ability to reverse full-screen app swipe on touchpad

### ISSUE THREAD

**Issue by RavenDT** [tekezo/Karabiner#738]
I am not sure if it's possible to accomplish with Karabiner and Multi-touch Extension currently, but I would like to reverse the "Swipe between full-screen apps" gesture so it acts more like a touch-screen.

If this is currently possible, then perhaps maybe adding a 'notsave.' entry in the default thumbsense.xml would be nice.

Thank you!  :D

**Comment by tekezo** [comment]
Karabiner does not support Trackpad gesture (eg. Swipe)
Please consider to use Better Touch Tool for this purpose.
