### ISSUE TITLE
doesn't work in the new MAC system "sierra".

### ISSUE THREAD

**Issue by paperayo** [tekezo/Karabiner#744]
when I install this new update, karabiner doesn't work even I reinstall it.What happened ?

**Comment by amureki** [comment]
Please, check already created issues instead of creating new ones:
https://github.com/tekezo/Karabiner/issues/739
https://github.com/tekezo/Karabiner/issues/732

**Comment by paperayo** [comment]
sorry for inattention ...

**Comment by BK-Choi** [comment]
@paperayo could you close this issue? people clicking this issue are wasting their clicks.
