### ISSUE TITLE
Karabiner seems to send a key signal every second without me doing or pressing anything.

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#745]
Here is the console, these messages keep appearing and I am not pressing anything : 

<img width="1440" alt="screen shot 2016-10-13 at 12 35 08" src="https://cloud.githubusercontent.com/assets/6391776/19346068/cac0b536-9141-11e6-94f5-b23abd2577d1.png">

**Comment by tekezo** [comment]
The log is event caught log.
Please check your devices state.
