### ISSUE TITLE
Hold Command+Q to Quit Application in Karabiner Elements

### ISSUE THREAD

**Issue by edwardjiang7** [tekezo/Karabiner#750]
I was wondering how I could activate Hold Command+Q to Quit Application? I know the old Karabiner had it but I don't see it in Karabiner Elements. Can someone point me in the right direction?

**Comment by baurmatt** [comment]
What was the solution?

**Comment by edwardjiang7** [comment]
@baurmatt I use another app for that. https://github.com/dteoh/SlowQuitApps

**Comment by baurmatt** [comment]
Thanks! :) But i would prefer to not have another tool running on my system. Lets see if tekezo replys to https://github.com/tekezo/Karabiner-Elements/issues/1020

**Comment by edwardjiang7** [comment]
@baurmatt Glad to help! :) I agree that it would be better to have all the keyboard modifications in one program. But to tell you from experience, I've been using this SlowQuitApps since Karabiner Elements came out and it works perfectly. Hopefully @tekezo replies.
