### ISSUE TITLE
Karabiner inside Virtualbox

### ISSUE THREAD

**Issue by epegzz** [tekezo/Karabiner#751]
First of all, thank you so much for this awesome software @tekezo! ❤️ 

Question: My current macbook is about to die, therefore I'm forced to buy a new one soon, which will come pre-installed with macOS Sierra. Since Karabiner won't work there yet, I thought about having a Virtualbox instance with El Capitan running in fullscreen inside macOS Sierra and have Karabiner installed inside there.

Any idea if running Karabiner inside Virtualbox is possible?

Cheers 😃

**Comment by tekezo** [comment]
I've once confirmed Karabiner works in VirtualBox guest.
(OS X 10.9 guest on OS X 10.11 host)

But I have not confirmed in the recent environment.
It's worth to try.

**Comment by epegzz** [comment]
Sounds good, I will give it a try and report here if it worked 👍
