### ISSUE TITLE
Sparkle Updater: Script authorization denied.

### ISSUE THREAD

**Issue by PDoakORNL** [tekezo/Karabiner#752]
OSX-10.10.5
MacBookPro
Keyboards many but not relevant here.
Karabiner-10.22.0 update fails with the following popup error message
Sparkle Updater: Script authorization denied

Syslog output:
```
Nov  4 10:43:35 macXXXXX Karabiner[587]: Sparkle: ===== Karabiner.app =====
Nov  4 10:43:35 macXXXXX Karabiner[587]: Sparkle: Extracting /Users/epd/Library/Caches/org.pqrs.Karabiner.updater/Sparkle/Karabi
ner 10.22.0/Karabiner-10.22.0.dmg as a DMG
Nov  4 10:43:38 macXXXXX kernel[0]: hfs: mounted Karabiner-10.22.0 on device disk2s1
Nov  4 10:43:43 macXXXXX Autoupdate[1457]: Sparkle: Installation Error: Error Domain=SUSparkleErrorDomain Code=4005 "Sparkle Updater: Script authorization denied." UserInfo=0xXXXXXXXXXXX {NSLocalizedDescription=Sparkle Updater: Script authorization denied.}
```

**Comment by tekezo** [comment]
You failed to enter administrator password during upgrading.
Please try again or upgrade from package. https://pqrs.org/osx/karabiner/index.html.en

**Comment by PDoakORNL** [comment]
It does not ask for the administrator password

**Comment by PDoakORNL** [comment]
It also fails from the package even when the package is invoked via
sudo open sudo open ./Karabiner.sparkle_guided.pkg
It does not invoke a administration password dialog.

additional information:
this macbook uses Safenet token login
My user has admin privledges
I have not had issues with any other program that requires admin rights (yet)

**Comment by PDoakORNL** [comment]
Safenet token on Yosemite causes this issue.
If the token is removed after login the proper admin dialogue will appear.
