### ISSUE TITLE
Karabiner don't work after MacOS Update Beta 10.12.2 version 1

### ISSUE THREAD

**Issue by krychlator** [tekezo/Karabiner#753]
Hi,

after update system (today - Beta 10.12.2 version 1) Karabiner elements disable apple keyboard. I cant type anything, no volume, no letter, nothing...I must login to system over Apple Watch. When I in Karabiner > Devices un-check Apple internal keyboard, i can type but Karabiner don't work. Touchpad working.

Why ? thank you very much!

**Comment by tekezo** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/383
