### ISSUE TITLE
question about my private.xml

### ISSUE THREAD

**Issue by lanox** [tekezo/Karabiner#758]
Hi I have leopold fc660C and I am trying to allocate keys for music.
Here is my private.xml

```
<?xml version="1.0"?>
<root>
  <item>
    <name>Change Inser to FN</name>
    <item>
      <name>Help to FN</name>
      <identifier>private.help2fn</identifier>
      <autogen>__KeyToKey__ KeyCode::HELP, KeyCode::FN</autogen>
    </item>
  </item>
  <item>
    <name>Functional Keys F1...F12</name>
    <item>
      <name>Music Controls</name>
      <item>
        <name>Music Controls F7...F9</name>
        <appendix>F7 Music Previous</appendix>
        <appendix>F8 Play/Pause Music</appendix>
        <appendix>F9 Music Next</appendix>
        <identifier>private.insert_fn_fkey_to_music_controls</identifier>
        <autogen>__KeyToKey__ KeyCode::F7, ModifierFlag::FN, ConsumerKeyCode::MUSIC_PREV</autogen>
        <autogen>__KeyToKey__ KeyCode::F8, ModifierFlag::FN, ConsumerKeyCode::MUSIC_PLAY</autogen>
        <autogen>__KeyToKey__ KeyCode::F9, ModifierFlag::FN, ConsumerKeyCode::MUSIC_NEXT</autogen>
      </item>
    </item>
    <item>
      <name>Speaker Controls</name>
      <item>
        <name>Volume Up/Down/Mute</name>
        <appendix>F10 to Mute</appendix>
        <appendix>F11 to Volume Down</appendix>
        <appendix>F12 to Volume Up</appendix>
        <identifier>private.insert_fn_fkey_to_volume_adjust</identifier>
        <autogen>__KeyToKey__ KeyCode::F10, ModifierFlag::FN, ConsumerKeyCode::VOLUME_MUTE</autogen>
        <autogen>__KeyToKey__ KeyCode::F11, ModifierFlag::FN, ConsumerKeyCode::VOLUME_DOWN</autogen>
        <autogen>__KeyToKey__ KeyCode::F12, ModifierFlag::FN, ConsumerKeyCode::VOLUME_UP</autogen>
      </item>
    </item>
  </item>
</root>
```

Above config works when I press F8 it will play/pause music. However since my leopold fc660c doesn't have F1...F12 keys by default I need to press FN+8 so it acts as F8. 

If I use my configuration above I would loose the functionality for F8 keys if I ever need to use it.

So I am asking is it possible to have INSERT + 8 act as F8 ??

Hope this make sense...

thanks

**Comment by lanox** [comment]
Update: Only way I got it to work, sort of is to press Insert+FN+F8 to make it act as F8, which is sort of what I want, I would just like to cut out FN step.

**Comment by lanox** [comment]
anyone. ??

**Comment by lanox** [comment]
@dunkarooftop  thanks for the tip, I want to have insert +7, however if I change it to this 

<autogen>__KeyToKey__ KeyCode::7, ConsumerKeyCode::MUSIC_PREV</autogen>
it actually doesn't work nothing happens when I press Insert+7

If i have it like this.
<autogen>__KeyToKey__ KeyCode::F7, ConsumerKeyCode::MUSIC_PREV</autogen>
then just by pressing F7 it goes to previous song.

But I also loose the functionality of F7 which is little annoying I would prefer if by pressing F7 does nothing, but when I press Insert +7 to change to previous song.

Thanks

**Comment by dunkarooftop** [comment]
This will be a hack but should work, by use `__KeyOverlaidModifier__` for it which you will turn "Insert" to act as when combine with other key act as "hyper key (cmd+shift+opt+ctrl)" but when press alone will act as "Insert" and then define "hyper + 7" to trigger "previous track".  This way we don't need to use F7 key.

Doc here https://pqrs.org/osx/karabiner/xml.html.en#syntax-__KeyOverlaidModifier__

```
<!--
 "Insert" to act as when combine with other key act as "hyper key (cmd+shift+opt+ctrl)" but when press alone will act as "Insert" 
-->
<autogen>
  __KeyOverlaidModifier__
  KeyCode::A,
  KeyCode::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L, 
  <!-- Change next line to "FN" if you want it to trigger for all the function key from "Insert" -->
    KeyCode::PC_INSERT,
</autogen>

<autogen>
	__KeyToKey__
	KeyCode::7, ModifierFlag::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,
	ConsumerKeyCode::MUSIC_PREV
</autogen>
```

Just tested and work fine :)

**Comment by lanox** [comment]
@dunkarooftop thanks, ugh dunno how I missed that one.

**Comment by lanox** [comment]
@dunkarooftop sorry to bother you again, I am not sure what a hell I am doing wrong.
so this is my config.

```
<?xml version="1.0"?>
<root>
  <item>
    <name>Functional Keys F1...F12</name>
    <item>
      <name>Music Controls</name>
      <item>
        <name>Music Controls F7...F9</name>
        <appendix>F7 Music Previous</appendix>
        <appendix>F8 Play/Pause Music</appendix>
        <appendix>F9 Music Next</appendix>
        <identifier>private.insert_fn_fkey_to_music_controls</identifier>
        <autogen>__KeyToKey__ KeyCode::F7, KeyCode::HELP, ConsumerKeyCode::MUSIC_PREV</autogen>
        <autogen>__KeyToKey__ KeyCode::F8, KeyCode::HELP, ConsumerKeyCode::MUSIC_PLAY</autogen>
        <autogen>__KeyToKey__ KeyCode::F9, KeyCode::HELP, ConsumerKeyCode::MUSIC_NEXT</autogen>
      </item>
    </item>
    <item>
      <name>Speaker Controls</name>
      <item>
        <name>Volume Up/Down/Mute</name>
        <appendix>F10 to Mute</appendix>
        <appendix>F11 to Volume Down</appendix>
        <appendix>F12 to Volume Up</appendix>
        <identifier>private.insert_fn_fkey_to_volume_adjust</identifier>
        <autogen>__KeyToKey__ KeyCode::F10, KeyCode::HELP, ConsumerKeyCode::VOLUME_MUTE</autogen>
        <autogen>__KeyToKey__ KeyCode::F11, KeyCode::HELP, ConsumerKeyCode::VOLUME_DOWN</autogen>
        <autogen>__KeyToKey__ KeyCode::F12, KeyCode::HELP, ConsumerKeyCode::VOLUME_UP</autogen>
      </item>
    </item>
  </item>
</root>
```

and it works fine. However when I press F8 alone with out Insert it also acts as MUSIC_PLAY.
How can I make it so it only works when I press Insert +F8  to act as MUSIC_PLAY and when I press F8 to act as F8.

thanks

**Comment by dunkarooftop** [comment]
All notes in code comment

What I did is turn "Insert" to become "Hyper (cmd+shift+opt+ctrl)" when pressed with other key, but act as "Insert" when press alone. Then turn "Hyper + Num_x" to all the music function. We do not use any "Function" key here.

The benefit of this is you can now also assign "Hyper (Insert)" + "key" to any of your app to use like "Keyboard Maestro" or "Alfred" like launcher...etc

More on Hyper key you can read the classic blog post from "Steve Losh"
https://stevelosh.com/blog/2012/10/a-modern-space-cadet/#hyper

Let me know if it work out for you. cheers
```

<?xml version="1.0"?>
<root>

<!--
 "Insert" when combine with other key act as "hyper key (cmd+shift+opt+ctrl)" but when press alone will act as "Insert" 
-->

<!-- Now you can assign even more hotkeys with "Insert" + "keys" in other app, this don't just limited to use here -->
 <item>
    <name>Change "Insert" to "Hyper" key</name>
    <identifier>private.change.intert.to.hyper</identifier>
		<autogen>
		  __KeyOverlaidModifier__
		<!-- Go to event viewer see the code for your "insert key", replace next line and 3 line below to match it -->
		  KeyCode::PC_INSERT,
		  KeyCode::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L, 
		  KeyCode::PC_INSERT,
		</autogen>
  </item>

	<!-- Set up a variable for our "Hyper key combo" for furture use, just save time to type and make code cleaner. HYPER = "ModifierFlag::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L"-->
	<replacementdef>
	  <replacementname>HYPER</replacementname>
	  <replacementvalue>
	    ModifierFlag::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L 
	  </replacementvalue>
	</replacementdef>

<!-- Note here I replace with all your F_x key to Num_x, We are not using any Functino key -->
  <item>
    <name>Functional Keys Num1...Num12</name>
    <item>
      <name>Music Controls</name>
      <item>
        <name>Music Controls Num7...Num9</name>
        <appendix>Num7 Music Previous</appendix>
        <appendix>Num8 Play/Pause Music</appendix>
        <appendix>Num9 Music Next</appendix>
        <identifier>private.insert_fn_fkey_to_music_controls</identifier>
        <autogen>
        	__KeyToKey__ 
        	KeyCode::KEY_7, {{ HYPER }}, 
        	ConsumerKeyCode::MUSIC_PREV
        </autogen>
        <autogen>
        	__KeyToKey__ 
        	KeyCode::KEY_8, {{ HYPER }}, 
        	ConsumerKeyCode::MUSIC_PLAY
        </autogen>
        <autogen>
        	__KeyToKey__ 
        	KeyCode::KEY_9, {{ HYPER }}, 
        	ConsumerKeyCode::MUSIC_NEXT
        </autogen>
      </item>
    </item>

    <item>
      <name>Speaker Controls</name>
      <item>
        <name>Volume Up/Down/Mute</name>
        <appendix>Num10 to Mute</appendix>
        <appendix>Num11 to Volume Down</appendix>
        <appendix>Num12 to Volume Up</appendix>
        <identifier>private.insert_fn_fkey_to_volume_adjust</identifier>
        <autogen>
        	__KeyToKey__ 
        	KeyCode::KEY_0, {{ HYPER }}, 
        	ConsumerKeyCode::VOLUME_MUTE
        </autogen>
        <autogen>
        	__KeyToKey__ 
        	KeyCode::MINUS, {{ HYPER }}, 
        	ConsumerKeyCode::VOLUME_DOWN
        </autogen>
        <autogen>
        	__KeyToKey__ 
        	KeyCode::EQUAL, {{ HYPER }} , 
        	ConsumerKeyCode::VOLUME_UP
        </autogen>
      </item>
    </item>
  </item>
</root>
```

**Comment by lanox** [comment]
Thanks so much @dunkarooftop I just got around changing this... I am not going to lie and say I understand how it works, but I am looking in to it now.

**Comment by lanox** [comment]
@dunkarooftop sorry to bother you again, I just updated my macos to sierra and the config above stoped working?
thanks so much.

**Comment by dunkarooftop** [comment]
God, I feel so bad that I am the one breaking this news to you..... Karabiner doesn't work in Sierra.
Apple rewrote the keyboard and mouse driver this OS update due to the touch bar support maybe...

There is Karabiner-Element which is very limited, but should be able to do what you want.
You will need to convert the mod to jason formate which is Karabiner-Element use.

https://github.com/tekezo/Karabiner-Elements

**Comment by lanox** [comment]
Hey @dunkarooftop I am sorry to be bothering you all the time. 

At this stage to be honest is the only thing I use on external keyboard.

**Comment by dunkarooftop** [comment]
What are the list of your media player ? It's a bit tricky but can be done with "Hammerspoon"

http://www.hammerspoon.org/

Give me the list I should be able to cook something up for you.

**Comment by lanox** [comment]
@dunkarooftop thanks in advance, I use Alfred. I am not sure what you mean by "What are the list of your media player ?" , for music I use Spotify.

**Comment by dunkarooftop** [comment]
fallow instruction on this page to turn your "insert" to "hyper" (CMD+OPT+SHIFT+CTRL)
He listed a couple ways see which one fit you better

Then down load this Alfred workflow and assign all the hotkeys to your liking.
https://github.com/dvjones89/alfred-media-keys
