### ISSUE TITLE
import not working.

### ISSUE THREAD

**Issue by lanox** [tekezo/Karabiner#759]
Hi
I was trying to export my config and then import it, however export works fine and I can see the content in the file  `karabiner-import.sh` but import didn't seem to do anything.

Steps are below.

`/Applications/Karabiner.app/Contents/Library/bin/karabiner export > ./karabiner-import.sh`

then to import I have cleared all first as per document instructions

`/Applications/Karabiner.app/Contents/Library/bin/karabiner \
     be_careful_to_use__clear_all_values_by_name \
     YOUR_PROFILE_NAME`
then
 `sh karabiner-import.sh`

However when I start karabiner I don't see anything in there ?

I am using mac os El Capitan 11.11.6

**Comment by tekezo** [comment]
Karabiner must be running when you execute `karabiner-import.sh`.

**Comment by lanox** [comment]
@tekezo it was running

**Comment by tekezo** [comment]
Could you show me the contents of `karabiner-import.sh`?

**Comment by lanox** [comment]
```#!/bin/sh

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set private.help2fn 1
/bin/echo -n .
$cli set private.insert_fn_fkey_to_music_controls 1
/bin/echo -n .
$cli set private.insert_fn_fkey_to_volume_adjust 1
/bin/echo -n .
/bin/echo
```

**Comment by tekezo** [comment]
Thank you!
You have to copy the private.xml to another machine.
(The `export` command does not support private.xml file itself.)

**Comment by lanox** [comment]
so you saying I have to place private.xml in karabiner directory then run the import ?

**Comment by tekezo** [comment]
> I have to place private.xml in karabiner directory

Yes. Place the private.xml and then reload XML, you can use your settings.

**Comment by lanox** [comment]
so what is the point of export import feature ?

**Comment by lanox** [comment]
? @tekezo
