### ISSUE TITLE
KeyboardEventCallback is not getting called in mac 10.12

### ISSUE THREAD

**Issue by nitin981** [tekezo/Karabiner#760]
Dear Mac developers

KeyboardEventCallback . is not getting called in mac 10.12 
its callback , which used to get called by os 10.10 
please let me know if any new way to registered it

**Comment by tekezo** [comment]
You have to use other methods.
https://github.com/tekezo/Karabiner-Elements/blob/master/DEVELOPMENT.md#the-difference-of-event-grabbing-methods
