### ISSUE TITLE
Mappings stepping over each other

### ISSUE THREAD

**Issue by iamsellek** [tekezo/Karabiner#769]
I would like to have two separate mappings that seem to be stepping over each other. There may be a way to fix this that I haven't been able to find, but I've Googled as much as I can about this and have found no answers to my question.

I have Control-T set to send Command-T. That works just fine. However, I'm trying to use Control-Alt-T with Apptivate to launch my terminal window and it's not allowing me because whenever I try to set the keyboard shortcut to Control-Alt-T, it tells me that Command-Alt-T can't be set to a shortcut because it's a system shortcut already. Is there a way to stop Karabiner from changing that Control press to a Command press when I'm also pressing Alt? I've tried the following:

`<item>
        <name>Do nothing on Control+Alt+T</name>
        <identifier>private.do_nothing_on_control_alt_t</identifier>
        <autogen>
          __KeyToKey__
          KeyCode::T, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L,
          KeyCode::T, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L
        </autogen>
    </item>`

I've also tried the none operator:

`<item>
        <name>Do nothing on Control+Alt+T</name>
        <identifier>private.do_nothing_on_control_alt_t</identifier>
        <autogen>
          __KeyToKey__
          KeyCode::T, ModifierFlag::CONTROL_L, ModifierFlag::OPTION_L,
          KeyCode::VK_NONE
        </autogen>
    </item>`

**Comment by dunkarooftop** [comment]
Add ```ModifierFlag::NONE,``` to your 1st keytokey mod will limited it only apply to "control" in your case.

doc. https://pqrs.org/osx/karabiner/xml.html.en
search "ModifierFlag::NONE" for more detials

```
	<autogen> 
	__KeyToKey__ 
	KeyCode::T, ModifierFlag::MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL | ModifierFlag::NONE, 
	KeyCode::T, ModifierFlag::MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_COMMAND
	</autogen>
```

**Comment by iamsellek** [comment]
Thanks so much! That did it!
