### ISSUE TITLE
cmd+option+esc for force quite menu

### ISSUE THREAD

**Issue by winglian** [tekezo/Karabiner#773]
I have cmd+esc mapped to cmd+` to switch windows, but this breaks cmd+option+esc to bring up the force quit menu. disabling the cmd+esc mapping and looking in the event viewer, I can see that karabiner is unable to capture that key sequence. Are there any known workarounds?

**Comment by dunkarooftop** [comment]
```
      <autogen>
        __KeyToKey__
        KeyCode::ESCAPE, ModifierFlag::COMMAND_L | ModifierFlag::NONE,
        KeyCode::BACKQUOTE, ModifierFlag::COMMAND_L,
      </autogen>
```

The magic here is ```ModifierFlag::NONE``` It limited the scope to apply only ```CMD``` is the only modifier.

doc
https://pqrs.org/osx/karabiner/xml.html.en#keytokey-syntax

it's a little way down you will see

**Comment by winglian** [comment]
Thanks @dunkarooftop! Works perfectly.
