### ISSUE TITLE
Cmd + tab + E to open editor

### ISSUE THREAD

**Issue by erwingaitano** [tekezo/Karabiner#775]
Is it possible change to my editor by pressing <kbd>cmd</kbd> + <kbd>tab</kbd> + <kbd>e</kbd>, without losing the original <kbd>cmd</kbd> + <kbd>tab</kbd> functionality? that is, if i hold that shortcut, it will navigate all the apps sequentially.

Basically it would be like a shortcut that has 2 keys (tab, e) and one modifier (cmd).

```xml
<root>
  <vkopenurldef>
    <name>KeyCode::VK_OPEN_URL_APP_Calculator</name>
    <url type="file">/Applications/Sublime Text.app</url>
  </vkopenurldef>

  <item>
    <name>Cmd + tab + e to open sublime</name>
    <identifier>private.openSublime</identifier>

    <autogen>
      __KeyToKey__
      KeyCode::TAB,
      KeyCode::E,
      ModifierFlag:: COMMAND_L,
      KeyCode::VK_OPEN_URL_APP_Sublime
    </autogen>
  </item>
</root>
```

**Comment by dunkarooftop** [comment]
I am afraid it won't be able to do so also your <autogen> is not valid. ```KeyToKey``` only take 2 events but you have 3 there. (each KeyCode:: is 1 event)

doc here
https://pqrs.org/osx/karabiner/xml.html.en#syntax-__KeyToKey__

a better way for launch often use app would be **Launcher Mode** you can search **Launcher Mode** in Karabiner to see example, if you have more question post here again or tell me what you want after you see the Launcher mode example,  I can help you out

**Comment by erwingaitano** [comment]
@dunkarooftop Yeah, I know that it doesn't work like that but was trying to explain my point with an example.

Thanks for pointing out the Launcher mode. Didn't know about that!

Anyway I think it won't work for me since what I want is to only use my left hand to perform this action. That's why I thought the convenience of cmd + tab + another key.

**Comment by dunkarooftop** [comment]
I have couple solutions for you, one with ```__SimultaneousKeyPresses__``` and one with ```Launcher Mode```

This one launch Sublime Text when "D" and "F" press at the same time. (You can change to any other keys to fit your need also can be more then 2 keys)

doc here: https://pqrs.org/osx/karabiner/xml.html.en#syntax-__SimultaneousKeyPresses__

```
<!-- Here we define a special key to open Sublime Text -->
<vkopenurldef>
  <name>KeyCode::VK_OPEN_URL_APP_SUBLIMETEXT</name>
  <url type="file">/Applications/Sublime Text.app</url>
</vkopenurldef>

<item>
  <name>Open Sublime Text when press "D" and "F" together</name>
  <identifier>private.open.sublime.text.with.d.f</identifier>
	<autogen>
	  __SimultaneousKeyPresses__
	  KeyCode::KEY_9, KeyCode::KEY_0,

	  KeyCode::VK_OPEN_URL_APP_SUBLIMETEXT,
	</autogen>
</item>
```

Launcher mode, say "Z" is the launcher mode trigger key. When press "Z" and

tap "E" to Sublime Text. 
tap "F" for Finder
tap "R" for Browser (I use Firefox as example here)

I am keeping it simple here, you can also have action 2 layer deep like

tap "F" do 1 thing
tap "F", "F" do a different thing, 

It looks scary at 1st but most of the code is just boiler plate, only need to focus on my comment part.


```
<!-- I have different xml to host all my "vkopenurldef" I have to include here to show the example below, "vkopenurldef" is like a variable which can store "file url", "web url", "bash script", "apple script"...etc  -->

<vkopenurldef>
  <name>KeyCode::VK_OPEN_URL_APP_FINDER</name>
  <url type="file">/System/Library/CoreServices/Finder.app</url>
</vkopenurldef>

<vkopenurldef>
  <name>KeyCode::VK_OPEN_URL_APP_SUBLIMETEXT</name>
  <url type="file">/Applications/Sublime Text.app</url>
</vkopenurldef>

<vkopenurldef>
  <name>KeyCode::VK_OPEN_URL_APP_FIREFOX</name>
  <url type="file">/Applications/firefox.app</url>
</vkopenurldef>

<!-- Launcher Mode begin -->
<!-- Change the key code to any key you like, I recommend "Z" on the left side because it's a rare use key -->
<replacementdef>
  <replacementname>LAUNCHER_MODE_KEY</replacementname>
  <replacementvalue>
    KeyCode::Z
  </replacementvalue>
</replacementdef>

<!-- Ignore from here -->
<item>
  <name>"Z" for Launcher Mode</name>
  <identifier>private.launcher.mode</identifier>

  <pressingphysicalkeys_lessthan>2</pressingphysicalkeys_lessthan>
  <modifier_not>
    ModifierFlag::COMMAND_L,
    ModifierFlag::COMMAND_R,
    ModifierFlag::CONTROL_L,
    ModifierFlag::CONTROL_R,
    ModifierFlag::FN,
    ModifierFlag::OPTION_L,
    ModifierFlag::OPTION_R, 
    ModifierFlag::SHIFT_L,
    ModifierFlag::SHIFT_R,
  </modifier_not>

  <autogen>
    __KeyOverlaidModifier__
    KeyCode::{{ LAUNCHER_MODE_KEY }},

    @begin
      KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_private_launcher_mode_v23, ModifierFlag::MY_LAUNCHER_MODE,
    @end

    @begin
      KeyCode::{{ LAUNCHER_MODE_KEY }},
    @end
  </autogen>
</item>
<!-- End ignore -->

<item hidden="true">
  <identifier vk_config="true">notsave.private_launcher_mode_v23</identifier>

  <autogen>
    __BlockUntilKeyUp__
    KeyCode::{{ LAUNCHER_MODE_KEY }},
  </autogen>

<!-- Only need to focus on from this line and below, it is where you put all your <autogen> -->

  <autogen>
    __KeyDownUpToKey__
    KeyCode::E,
    KeyCode::VK_OPEN_URL_APP_SUBLIMETEXT,
  </autogen>

  <autogen>
    __KeyDownUpToKey__
    KeyCode::F,
    KeyCode::VK_OPEN_URL_APP_FINDER,
  </autogen>

  <autogen>
    __KeyDownUpToKey__
    KeyCode::R,
    KeyCode::VK_OPEN_URL_APP_FIREFOX,
  </autogen>

</item>
```

Let me know if you need any more help :)
recommend to read thru doc once to have a better idea what's possible
https://pqrs.org/osx/karabiner/xml.html.en

**Comment by erwingaitano** [comment]
@dunkarooftop wow, actually I went for the route of launcher mode with the z key. It works pretty good!

Really appreciated, thanks man!
