### ISSUE TITLE
How to define if application is not open?

### ISSUE THREAD

**Issue by schoenwaldnils** [tekezo/Karabiner#780]
Hi there,

I tryed to change the action for the play-key (F8).
I changed it to open spotify. But now I have to focus spotify (manual or using the play-key) and have to press again to play/pause the music.

is there an option to detect, if an application is opened?
So that the play-key open spotify only if it isn't open?

My `private.xml` so far:
```
<?xml version="1.0"?>
<root>
    <!-- Spotify Path -->
    <vkopenurldef>
        <name>KeyCode::VK_OPEN_URL_APP_Spotify</name>
        <url type="file">/Applications/Spotify.app</url>
    </vkopenurldef>

    <!-- Set Spotify definition -->
    <appdef>
        <appname>SPOTIFY</appname>
        <equal>com.spotify.client</equal>
    </appdef>

    <!-- Use 'Music Play' key to launch Spotify if not ever in the application -->
    <!-- else, act as normal play/pause button in Spotify, Itunes -->
    <item>
        <name>Change Play key to launch Spotify</name>
        <identifier>private.play_launch_spotify</identifier>
        <not>SPOTIFY, ITUNES</not>
        <autogen>
            __KeyToKey__,
            ConsumerKeyCode::MUSIC_PLAY,
            KeyCode::VK_OPEN_URL_APP_Spotify,
        </autogen>
    </item>
</root>
```

**Comment by dunkarooftop** [comment]
Don't think it can do what you want but looking at it at a different view, what about when you holding down "play-key" open Spotify and when tap work as "Play/Pause"

```
<autogen>
  __HoldingKeyToKey__
  ConsumerKeyCode::MUSIC_PLAY,, ModifierFlag::NONE,

  <!-- short press -->
  @begin
  ConsumerKeyCode::MUSIC_PLAY,,
  @end

  <!-- hold -->
  @begin
  KeyCode::VK_OPEN_URL_APP_Spotify,
  @end

  Option::NOREPEAT,
</autogen>
```

or simply change ```__HoldingKeyToKey__``` to ```__DoublePressModifier__``` to have it act as, When single tap work as "Play/Pause" and double tap to open Spotify

doc: https://pqrs.org/osx/karabiner/xml.html.en#syntax-__HoldingKeyToKey__
