### ISSUE TITLE
How to find Key Code for Emojis?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#787]
For example I want to map cmd + t to this emoji (🐕). How do I find key code for it?

**Comment by dunkarooftop** [comment]
doc: https://pqrs.org/osx/karabiner/xml.html.en

scroll down to the end or search "Tips: Unicode hex input"

I recommend read the whole doc at least once

**Comment by nikitavoloboev** [comment]
Thank you @dunkarooftop :)
