### ISSUE TITLE
Not activating on 10.12.1 (Control_L <-> Fn)?

### ISSUE THREAD

**Issue by ylluminate** [tekezo/Karabiner#790]
I have a standard "Magic Keyboard" and have attempted to flip the Left Control and Fn keys, yet the changes do not take effect.

Any idea as to what may be going on here that's preventing this key swap?

**Comment by dunkarooftop** [comment]
Can you post your mod here I will take a look

**Comment by ylluminate** [comment]
Can you explain what you need precisely as I simply used the defaults in the system:
![screenshot](https://cl.ly/2n2u2p2e0T2i/Image%202017-01-01%20at%2011.00.17%20PM.png)

**Comment by EndangeredMassa** [comment]
This also just started happening to me. It was working for a long time, but stopped a few days ago. I'm not sure if I updated Karabiner then or not. Here's my config for remapping `Control_L <-> FN` on the system keyboard of a (Early 2015) macbook pro.

<img width="272" alt="screen shot 2017-01-02 at 1 32 03 pm" src="https://cloud.githubusercontent.com/assets/41545/21595105/e083b02e-d0ef-11e6-9848-2b9b6af72bd5.png">

Toggling options and restarting the machine did not change anything.

**Comment by dunkarooftop** [comment]
That's very strange, can you both open Karabiner and go to last page "misc and uninstall"

Open "Launch EventViewer" and see what keycode get send to system with and without the mod.

**Comment by dunkarooftop** [comment]
BTW, What OS are you 2 using, Karabiner DOES NOT work with mac Serria 

for mac Serria use Karabiner-Element
https://github.com/tekezo/Karabiner-Elements

**Comment by ylluminate** [comment]
Oh really? I'm on Sierra...

**Comment by EndangeredMassa** [comment]
Same for me. I forgot that Karabiner didn't work on Sierra. Thanks!
