### ISSUE TITLE
wrong mapping

### ISSUE THREAD

**Issue by Andreeaaas** [tekezo/Karabiner#802]
I tried to changed the output of the GERMAN-U-UMLAUT to BACKSLASH. Using BACKSLASH as KeyCode I get a $ as output, using the raw value 0x5C I get a 9 as output for the umlaut. Please tell me how to solve this mapping problem!

here is the xml:
<?xml version="1.0"?>
<root>

<item>
	<name>change ü to \</name>
	<identifier>Private.backslash</identifier>
	<autogen>__KeyToKey__ KeyCode::GERMAN_U_UMLAUT , KeyCode::RawValue::0x5C</autogen>
</item>
</root>

**Comment by dunkarooftop** [comment]
rawvalue for BACKSLASH is 0x2a
https://github.com/tekezo/Karabiner/blob/master/src/bridge/generator/keycode/data/KeyCode.data

give it a try

**Comment by Andreeaaas** [comment]
Thanks, doesn't work! 0x2a gives a $, same as BACKSLASH
