### ISSUE TITLE
Modifier Key Sharing For Multiple Keyboards Broke In macOS Sierra (10.12.2)

### ISSUE THREAD

**Issue by kininja** [tekezo/Karabiner#805]
Just upgraded to macOS Sierra 10.12.2. Modifier keys on one keyboard are no longer shared with the other keyboard. This is one of my favorite features--absolutely happy to help troubleshoot and resolve if there's anything I can do! :-)

**Comment by dunkarooftop** [comment]
Karabiner does not support Sierra, please check out "Karabiner-Element" which is for Sierra

**Comment by kininja** [comment]
Ah! I didn't even know about element. Thank you for the response!
