### ISSUE TITLE
Can you do a pause in Karabiner?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner#806]
For example I want to wait for 0.5 seconds before issuing next command, something like this : 

```XML
               <autogen>
                 __KeyToKey__
                 KeyCode::O,
                 KeyCode::ESCAPE,
                 KeyCode::WAIT_0.5S,
                 KeyCode::O
               </autogen>
```

**Comment by dunkarooftop** [comment]
try ```KeyCode::VK_WAIT_100MS,``` change 100MS to your desire time.

**Comment by dunkarooftop** [comment]
another way is to use applescript refer to doc
https://pqrs.org/osx/karabiner/xml.html.en
search for ```Using AppleScript via <vkopenurldef>```

**Comment by nikitavoloboev** [comment]
Thank you a lot @dunkarooftop.

This worked. :)
