### ISSUE TITLE
Any plans for diamond cursor? (ctrl + jkli)

### ISSUE THREAD

**Issue by jackbrannen** [tekezo/Karabiner#811]
One feature I loved from Karabiner on macOS 10.11 was using ⌃jkli as arrow keys. Any plans to bring this back?

**Comment by dunkarooftop** [comment]
It is still there for the default pre-set, search "Option_L+IKJL to Up/Down/Left/Right"

**Comment by dunkarooftop** [comment]
Unless you move on to Sierra, Karabiner is NOT support for Sierra. You need to look into Karabiner-Element. (which is VERY bear bone tweak)

**Comment by jackbrannen** [comment]
Yes, I'm on Sierra. I'm hoping this feature can be brought in to Karabiner Elements.

**Comment by jackbrannen** [comment]
Whoops, sorry, didn't realize Karabiner Elements was separate!
