### ISSUE TITLE
Any plans for fn + num to keypad num?

### ISSUE THREAD

**Issue by jackbrannen** [tekezo/Karabiner#812]
One feature I loved from Karabiner on macOS 10.11 was using fn + number keys to emulate the keypad keys on extended keyboards. Any plans to bring this back?

**Comment by dunkarooftop** [comment]
https://github.com/tekezo/Karabiner-Elements

Karabiner-Element is a better place to ask :)

**Comment by jackbrannen** [comment]
Whoops! Didn't realize it was separate. Thank you!
