### ISSUE TITLE
Change keys in number pad to arrows

### ISSUE THREAD

**Issue by i-schuetz** [tekezo/Karabiner#827]
My right arrow and down arrow keys are broken and I wanted to repurpose the 6 and 2 keys in the number pad as replacement. How do I do this? The mappings seem to be very specific, it doesn't seem possible to just say "make key A do B".

**Comment by dunkarooftop** [comment]
```
<item>
  <name>Change Num to Arrow</name>
  <appendix>Change NumPad 6 and 2 to Up and Down</appendix>
  <identifier>private.change.num.pad.to.up.and.down</identifier>
  <autogen>
    __KeyToKey__
    KeyCode::KEYPAD_6
    KeyCode::CURSOR_UP
  </autogen>
  <autogen>
    __KeyToKey__
    KeyCode::KEYPAD_2
    KeyCode::CURSOR_DOWN
  </autogen>
</item>
```

It's very easy to do, if you have any more question you can check out the doc.
https://pqrs.org/osx/karabiner/xml.html.en
Scroll down to "autogen syntax" section and take a look at the ```__KeyToKey__``` section.

Here is an example that Num 6 and 2 only turn to arrow when "Left CMD" is held down too.

```
<item>
  <name>Change Num to Arrow</name>
  <appendix>Change NumPad 6 and 2 to Up and Down</appendix>
  <identifier>private.change.num.pad.plus.left.cmd.to.up.and.down</identifier>
  <autogen>
    __KeyToKey__
    KeyCode::KEYPAD_6,  ModifierFlag::COMMAND_L | ModifierFlag::NONE,
    KeyCode::CURSOR_UP
  </autogen>
  <autogen>
    __KeyToKey__
    KeyCode::KEYPAD_2, ModifierFlag::COMMAND_L | ModifierFlag::NONE,
    KeyCode::CURSOR_DOWN
  </autogen>
</item>
```

If you have any more question let me know.

**Comment by dunkarooftop** [comment]
There are also many option when it come to arrow key function.
You can have ```Fn```or any of the modifier like ```CMD``` plus ```A, W, S, D``` for the arrow

or
When tap left ```CMD``` for ```UP``` and tap right ```CMD``` for ```DOWN``` (They still act as ```CMD``` when hold with other keys.

or
```Shift``` + ```Left``` = ```UP``` and ```SHIFT``` + ```RIGHT``` = ```DOWN```

or even
When ```F, D``` pressed at the same time = ```DOWN``` and ```S, D``` pressed at the same time = ```UP``` (This way your finger won't even need to move away from home row)

Take a look at the doc see what's possible

**Comment by i-schuetz** [comment]
You have some very nice documentation. Thanks for the examples! I only need the first one. I added and enabled it, however it doesn't seem to be working, I still get 6 and 2. What am I missing?

![screen shot 2017-03-28 at 11 36 02](https://cloud.githubusercontent.com/assets/1381744/24398780/095b1868-13ab-11e7-9fd5-e0a58108164f.png)

**Comment by dunkarooftop** [comment]
Go to the last page of Karabiner and open "Launch Event Viewer". Press the ```6 and 2``` to see what keycode they send to the OS and replace the autogen. I though they would be ```KEYPAD_6,``` and ```KEYPAD_2,``` but looks like not.

also I am just a volunteer, the doc is written by @tekezo

**Comment by i-schuetz** [comment]
I actually did that before but couldn't find the problem:

![screen shot 2017-03-28 at 20 42 56](https://cloud.githubusercontent.com/assets/1381744/24421732/774a2cd2-13f7-11e7-8221-91d4e563d977.png)

**Comment by dunkarooftop** [comment]
I guess you are using macOS Seirra. Which is not support by Karabiner. Check out Karabiner-Element that one is for Sierra. Limited function but can do what you needed.

**Comment by i-schuetz** [comment]
Thanks! With Karabiner-Element it works. I also was able to do that using only the UI there.
