### ISSUE TITLE
Share state of modifier keys with multiple keyboards not working for Sierra 10.12.4

### ISSUE THREAD

**Issue by cgoudie** [tekezo/Karabiner#828]
After upgrading to Sierra 10.12.4, the multiple keyboard functionality no longer works.

**Comment by cgoudie** [comment]
Uninstall, reboot, reinstall doesn't resolve the issue. Verified that Karabiner_AXNotifier is in the list of approved apps for accessibility.

**Comment by cgoudie** [comment]
Attempting to enable debug and tailing the system log, I don't see any entries for Karabiner coming through.

**Comment by cgoudie** [comment]
ah unsupported on sierra at the moment.

**Comment by cgoudie** [comment]
If you're here, because it's also not working for you, the Karabiner-Elements project does work.

**Comment by anotheredward** [comment]
[Karabiner Elements](https://github.com/tekezo/Karabiner-Elements)
