### ISSUE TITLE
how to config action of double click mouse with two fingers

### ISSUE THREAD

**Issue by hotdust** [tekezo/Karabiner#831]
Hello, 
I want to change the action of double click mouse with two fingers.
(current action opens mission control, I want to change it to open Application window)
I found mouse left/right/middle keycode in KeyCode.data. But I didn't find keycode about double click mouse with two fingers. How can I change the action of double click mouse with two fingers.
thank you

**Comment by dunkarooftop** [comment]
Karabiner is mostly for key customize, doesn't have deep mouse customize.
You can look into "Better Touch Tool" for gesture customize.

**Comment by hotdust** [comment]
thx for reply. I found MagicPrefs for my requirement
