### ISSUE TITLE
Why karabiner does not work in my case 

### ISSUE THREAD

**Issue by sharikovvladislav** [tekezo/Karabiner#836]
Hi!

I downloaded this utility by `curl` command from README.md.  Everything is fine. I checked current key mapping in Event listener. Ctrl L is Ctrl L and Fn is Fn.

Now I remapped this two buttons. I have this: 

<img src="https://cloud.githubusercontent.com/assets/5622526/25973307/3444b77c-36ac-11e7-98a5-bad8d7efe69d.png" width="400">

What I have in event viewer? I pressed FN then CTRL buttons.

```
eventType:FlagsChanged    code:0x3f       name:Fn              flags:Fn                                 misc:KeyCode::FN	 characters:    
eventType:FlagsChanged    code:0x3f       name:Fn              flags:                                   misc:KeyCode::FN	 characters:    
eventType:FlagsChanged    code:0x3b       name:Control_L       flags:Ctrl                               misc:KeyCode::CONTROL_L	 characters:    
eventType:FlagsChanged    code:0x3b       name:Control_L       flags:                                   misc:KeyCode::CONTROL_L	 characters:    
```

I have exactly what I pressed. But since I have this buttons swapped when I pressed Fn, message about ctrl must be and vice versa.

What I am doing wrong?

PS: I didn't find any "Submit" button. Maybe this is the problem?
PPS: I also tried to restart mbp and I have same result.

**Comment by dunkarooftop** [comment]
to debug this problem can you only enable one of the tweak at a time and see if they act as what you expected? post the result :)

**Comment by sharikovvladislav** [comment]
Ops! I have Sierra. That is the problem!!!

**Comment by sharikovvladislav** [comment]
Karabiner-Elements works perfectly! Thank you!
