### ISSUE TITLE
Map to "alt codes"?

### ISSUE THREAD

**Issue by lebigot** [tekezo/Karabiner#869]
Some alt code Windows sequences are useful for proper typography, like the long dash (— = alt-0151) and the ellipsis (… = alt-0133).

Can Karabiner map to such sequences? I can't find any example either in the documentation or on the web.

**Comment by lebigot** [comment]
Solved (in Karabiner Elements): this can be done by providing a *list* of left_option + Keypad_0, etc. keys in the "to" part of the Karabiner configuration file.

**Comment by asmeurer** [comment]
On Mac the common characters are provided by Option-letter, like Option-Shift-- (Option-Shift-DASH) for — and Option-; for …
