### ISSUE TITLE
HELP (PC_INSERT) key only generating keyUp event

### ISSUE THREAD

**Issue by kaelef** [tekezo/Karabiner#87]
I'm trying to map a key on my MacBook Pro (2012) to the missing HELP (PC_INSERT) key for use with PC applications.  If I map KeyCode::BRACKET_LEFT to KeyCode::PC_INSERT, then pressing the "[" key only generates a keyUp event for HELP - a keyDown event is never generated.  Only the KeyCode::PC_INSERT (or KeyCode::HELP) behaves this way - if I change it to a different key, for example KeyCode::HOME, then both the keyDown and keyUp events are generated.

Is this behavior expected?  

Here's a screenshot of KeyDump showing the results of the "[" key pressed 3 times, followed by the "]" key pressed 3 times.  The BRACKET_LEFT has been mapped to KeyCode::PC_INSERT and the BRACKET_RIGHT has been mapped to KeyCode::HOME.

![KeyDump Screen](http://i.imgur.com/Sv7FS.png)

**Comment by jmuheim** [comment]
I'm using [NVDA](http://www.nvaccess.org/) screen reader software to test websites for accessibility.

Because NVDA is a Windows application, I need to run a virtual machine with Windows in it using [VMWare Fusion](http://www.vmware.com/ch/products/fusion), or I have to connect to a running Windows PC using [TeamViewer](http://www.teamviewer.com/).

And while VMWare Fusion has features to emulate Windows keys like INSERT (which is NVDA's main key), TeamViewer doesn't. And finally, after months of casually looking for a solution, I stumbled over Karabiner! :heart: 

So, here's my custom script which allows me to use NVDA's keyboard shortcuts easily:

```xml
  <item>
    <name>Fn + Ctrl-Left to Insert</name>
    <identifier>private.fn_ctrl_to_insert</identifier>
    <autogen>
      __KeyToKey__KeyCode::CONTROL_L, ModifierFlag::FN,
      KeyCode::PC_INSERT
    </autogen>
  </item>
```

With this activated, I can e.g. press `Fn+Ctrl+N` to display the NVDA menu, regardless of whether I'm using VMWare Fusion, TeamViewer, or any other tunnel to a Windows OS.

Thank you! :+1:

**Comment by JoinGitHubNow** [comment]
**OS X version:** 10.6.8
**Hardware:** MacBook3,1
**Keyboard Hardware:** Logitech Pro 2400 Cordless Desktop (http://support.logitech.com/en_us/product/pro-2400-cordless-desktop)
 
**Software:**
1 - KeyRemap4Macbook 8.4.0
2 - Wineskin, Crossover, WineBottler
3 - VirtualBox
 
**Symptoms:** My intention is to send a PC_INSERT to a Windows software via hardware "Insert" key on the cordless keyboard described above to Windows software running on my Mac on Wine.

- 1 - Pressing the Insert Key aka "Help Key"only produces a KeyUp event (as described in the comments above by kaelef) Type on the EventViewer but not a KeyDown

- 2 - I can reassign the insert key (aka as "help key")  via KeyRemap4Macbook to TAB and my Windows software running in wine responds to the keypress as if I was pressing the TAB key with the code below in the Private.XML file: 
```
<autogen>
__KeyToKey__
KeyCode::HELP,
KeyCode::TAB
</item>
</autogen>

```

But when I try to reassign the same key to PC_INSERT (see the code below) then the software inside of wine doesn't even seem to tell that a key is being pressed. It doesn't respond. It does nothing.

```
<autogen>
__KeyToKey__
KeyCode::HELP,
KeyCode::PC_INSERT
</item>
</autogen>

```
- 3 - If I run the same Windows software in the same computer but now within VirtualBox the insert key (aka as the "Help key) does send PC_INSERT to my Windows app even without the need of using any remapping whatsoever

- 4 - I cannot send PC_INSERT to my software running in wine not even when I try other key combinations (i.e. mapping any other key to produce a PC_INSERT -see jmuheim  comment above mine)

**KERNEL LOG BELOW:**
**NOTE:** The following items were deleted from the log output for easy reading purposes and for space: Date, ComputerName, KeyRemap4MacBook,  -- --Debug--,   repeat = 0, kbdType  40

6:45:01 **UpdateEventFlagsCallback**[ caught]: ______..______ , **flags** _0x00400000_
6:45:01 **Keyboard Event Call back** [ caught]: **eventType** 10, **flags** _0x00400000_, **key** 0x0072
6:45:01 **Keyboard Event Call back** [_sending_]: **eventType** 10, **flags** 0x00000000, **key** 0x0072

6:45:02 **Keyboard Event Call back** [ caught]: **eventType** 11, **flags** _0x00400000_, **key** 0x0072
6:45:02 **UpdateEventFlagsCallback**[ caught]:  ______..______ , **flags** 0x00000000
6:45:02 **Keyboard Event Call back** [_sending_]: **eventType** 11, **flags** 0x00000000, **key** 0x0072

A "solution"would be running the software in VirtualBox but there are reasons I want to run it in Wine though

Thank you in advance for your reply/ies

Regards!
