### ISSUE TITLE
Inserting arbitrary text?

### ISSUE THREAD

**Issue by sjl** [tekezo/Karabiner#91]
I'd like to bind a key to insert arbitrary (unicode) text.  For example: `ctrl-shift-s` might insert `σ` (my actual configuration is a lot more complicated than this, but that's the idea).

The only way I've found to do this is to change my keyboard layout to Unicode Hex Input and tell KeyRemap4MacBook to type out the hex code.  This is tedious, and Unicode Hex Input breaks a lot of other functionality (like `Option-Left`, `Option-Delete`, etc).

It would be really helpful if KeyRemap4Macbook could insert arbitrary text (perhaps by sticking it in the clipboard, pasting, and then restoring the clipboard).  Keyboard Maestro can do this, but won't work with the other KeyRemap4MacBook stuff like the `ExtraN` modifiers.

**Comment by jbshirk** [comment]
I would like to know if there is a way to convert a digraph into an extAscii: <> to lozenge &#9674; which is unfortunately chosen for Pollen functions.

**Comment by bland328** [comment]
In case it helps anyone, my fairly-tidy solution for typing any character string with Karabiner is this:

1. I used Xcode to build the handy code provided at https://apple.stackexchange.com/a/289046/173446 and installed it as `/usr/local/bin/typechars`.

2. Whenever I need Karabiner to type an oddball character or characters, I do something like this:
`{`
`  "shell_command": "/usr/local/bin/typechars ⌘"`
`}`

The first time you use `typechars` in this way, you may need to give Accessibility permissions to `karabiner_console_user_server` in System Preferences. Hopefully, you'll be prompted for it; in my experience, Mojave seemed somewhat flaky about prompting for such things, but Catalina seems fairly reliable.

**Comment by veegee** [comment]
> In case it helps anyone, my fairly-tidy solution for typing any character string with Karabiner is this:
> 
> 1. I used Xcode to build the handy code provided at https://apple.stackexchange.com/a/289046/173446 and installed it as `/usr/local/bin/typechars`.
> 2. Whenever I need Karabiner to type an oddball character or characters, I do something like this:
>    `{`
>    `  "shell_command": "/usr/local/bin/typechars ⌘"`
>    `}`
> 
> The first time you use `typechars` in this way, you may need to give Accessibility permissions to `karabiner_console_user_server` in System Preferences. Hopefully, you'll be prompted for it; in my experience, Mojave seemed somewhat flaky about prompting for such things, but Catalina seems fairly reliable.

Thanks. Looks like this is the best solution right now. When did they add the shell_command ability? Is there any documentation for this?

**Comment by nkgm** [comment]
`shell_command` is available in Karabiner-Elements ([repo here](https://github.com/pqrs-org/Karabiner-Elements)), which is the rewrite of Karabiner for macOS 10.12 and later.

If you're on an older version of macOS using good old Karabiner classic (this repo), the equivalent would be:

```xml
<vkopenurldef>
	<name>KeyCode::VK_MY_COMMAND</name>
	<url type="shell">/usr/local/bin/typechars ⌘</url>
</vkopenurldef>

<autogen>
	__KeyToKey__ KeyCode::F10, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L, KeyCode::VK_MY_COMMAND
</autogen>
```
